#!/usr/bin/env python3
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
COMPONENT = ROOT / "src/pages/dashboard/RacePreparation.tsx"
LOCALES = ["en", "sr-Latn", "de", "hr", "es", "it", "fr", "ru"]

NEW_SCREEN_COPY = {
    "en": {
        "loadPageFailed": "Failed to load Race Preparation.",
        "loadSelectedRaceFailed": "Failed to load selected race.",
        "choosePlannerDeveloping": "Choose either a Sport Director or a U23 Head Coach.",
        "selectSportDirector": "Select a Sport Director.",
        "maxRidersWarning": "Maximum riders allowed: {{max}}. You selected: {{selected}}.",
        "maxStaffWarning": "Maximum race staff slots: {{max}}. You selected: {{selected}}.",
        "maxAssetsWarning": "Maximum race asset slots: {{max}}. You selected: {{selected}}.",
        "raceCanceledWeather": "This race was canceled due to weather.",
        "stageCanceledWeather": "This stage was canceled due to weather.",
        "developingManagedByU23": "This Developing Team race is managed by the U23 Head Coach.",
        "assignSportDirectorFirst": "Assign a Sport Director in the Race Plan first.",
        "u23HeadCoach": "U23 Head Coach",
        "existingManualViewOnly": "Existing manual plan · view only",
        "coachPlan": "Coach plan",
        "scheduled": "Scheduled",
        "manualPlan": "Manual plan",
        "manualPlanViewOnlyHint": "This older manual plan remains visible, but it cannot be changed while U23 automation is active.",
        "generatedSavedByCoach": "{{name}} generated and saved this Stage Plan automatically.",
        "coachWillGenerateAfterStage": "The U23 Head Coach will generate this plan after Stage {{stage}} finishes.",
        "coachWillGenerateStage1": "The U23 Head Coach will generate Stage 1 immediately after automation is activated.",
        "managedViewOnlySwitch": "This Stage Plan is managed by the U23 Head Coach and is view-only. Switch the Tactical Planner to Sport Director in the Race Plan before making manual changes.",
        "u23Schedule": "U23 Head Coach Stage Plan schedule",
        "checkingStagePlans": "Checking Stage Plans…",
        "stagePlanReadiness": "Stage Plan readiness",
        "u23ReadinessIntro": "Stage 1 is generated immediately when automation is activated. Each later stage is generated after the previous stage finishes, using the latest results, fatigue, health, weather and race situation.",
        "stagePlanReadinessPending": "Stage Plan readiness will appear after the Race Plan is submitted.",
        "generatedStages": "Generated {{generated}}/{{total}} stages",
        "scheduledCount": "Scheduled {{count}}",
        "existingManualCount": "Existing manual {{count}}",
        "loadingU23Status": "Loading U23 Head Coach status…",
        "existingManualPlan": "Existing manual plan",
        "managedByU23": "Managed by U23 Head Coach",
        "u23AutomationActiveTitle": "U23 Head Coach automation active",
        "manualPlanViewOnlyBody": "This older manual plan remains visible but is now view-only. The U23 Head Coach continues with the next eligible stage.",
        "generatedThisPlan": "{{name}} generated this plan automatically.",
        "adaptedAfterStage": "It was adapted after Stage {{stage}}.",
        "manualViewOnlyPeriod": "Existing manual plan · view only.",
        "generatedAutomatically": "Generated automatically by the U23 Head Coach.",
        "generatedAfterStage": "Generated after Stage {{stage}} finishes.",
        "generatedImmediately": "Generated immediately when U23 automation is activated.",
    },
    "sr-Latn": {
        "loadPageFailed": "Priprema trke nije mogla da se učita.",
        "loadSelectedRaceFailed": "Izabrana trka nije mogla da se učita.",
        "choosePlannerDeveloping": "Izaberite Sportskog direktora ili U23 glavnog trenera.",
        "selectSportDirector": "Izaberite Sportskog direktora.",
        "maxRidersWarning": "Maksimalno vozača: {{max}}. Izabrano: {{selected}}.",
        "maxStaffWarning": "Maksimalno mesta za osoblje trke: {{max}}. Izabrano: {{selected}}.",
        "maxAssetsWarning": "Maksimalno mesta za vozila trke: {{max}}. Izabrano: {{selected}}.",
        "raceCanceledWeather": "Ova trka je otkazana zbog vremenskih uslova.",
        "stageCanceledWeather": "Ova etapa je otkazana zbog vremenskih uslova.",
        "developingManagedByU23": "Ovom trkom Razvojnog tima upravlja U23 glavni trener.",
        "assignSportDirectorFirst": "Prvo izaberite Sportskog direktora u Race Plan-u.",
        "u23HeadCoach": "U23 glavni trener",
        "existingManualViewOnly": "Postojeći ručni plan · samo pregled",
        "coachPlan": "Plan trenera",
        "scheduled": "Zakazano",
        "manualPlan": "Ručni plan",
        "manualPlanViewOnlyHint": "Ovaj stariji ručni plan ostaje vidljiv, ali se ne može menjati dok je U23 automatizacija aktivna.",
        "generatedSavedByCoach": "{{name}} je automatski napravio i sačuvao ovaj Stage Plan.",
        "coachWillGenerateAfterStage": "U23 glavni trener će napraviti ovaj plan nakon završetka etape {{stage}}.",
        "coachWillGenerateStage1": "U23 glavni trener će napraviti Stage Plan za etapu 1 odmah nakon aktiviranja automatizacije.",
        "managedViewOnlySwitch": "Ovim Stage Plan-om upravlja U23 glavni trener i dostupan je samo za pregled. Prebacite Tactical Planner na Sportskog direktora u Race Plan-u da biste ga ručno menjali.",
        "u23Schedule": "Raspored Stage Plan-ova U23 glavnog trenera",
        "checkingStagePlans": "Provera Stage Plan-ova…",
        "stagePlanReadiness": "Spremnost Stage Plan-ova",
        "u23ReadinessIntro": "Etapa 1 se generiše odmah po aktiviranju automatizacije. Svaka naredna etapa se generiše nakon završetka prethodne, koristeći najnovije rezultate, umor, zdravlje, vreme i situaciju u trci.",
        "stagePlanReadinessPending": "Spremnost Stage Plan-ova biće prikazana nakon slanja Race Plan-a.",
        "generatedStages": "Generisano {{generated}}/{{total}} etapa",
        "scheduledCount": "Zakazano {{count}}",
        "existingManualCount": "Postojećih ručnih {{count}}",
        "loadingU23Status": "Učitavanje statusa U23 glavnog trenera…",
        "existingManualPlan": "Postojeći ručni plan",
        "managedByU23": "Upravlja U23 glavni trener",
        "u23AutomationActiveTitle": "U23 automatizacija glavnog trenera je aktivna",
        "manualPlanViewOnlyBody": "Ovaj stariji ručni plan ostaje vidljiv, ali je sada samo za pregled. U23 glavni trener nastavlja sa sledećom odgovarajućom etapom.",
        "generatedThisPlan": "{{name}} je automatski napravio ovaj plan.",
        "adaptedAfterStage": "Plan je prilagođen nakon etape {{stage}}.",
        "manualViewOnlyPeriod": "Postojeći ručni plan · samo pregled.",
        "generatedAutomatically": "Automatski generisao U23 glavni trener.",
        "generatedAfterStage": "Generiše se nakon završetka etape {{stage}}.",
        "generatedImmediately": "Generiše se odmah kada se aktivira U23 automatizacija.",
    },
    "de": {
        "loadPageFailed": "Die Rennvorbereitung konnte nicht geladen werden.",
        "loadSelectedRaceFailed": "Das ausgewählte Rennen konnte nicht geladen werden.",
        "choosePlannerDeveloping": "Wähle entweder einen Sportdirektor oder einen U23-Cheftrainer.",
        "selectSportDirector": "Wähle einen Sportdirektor.",
        "maxRidersWarning": "Maximal erlaubte Fahrer: {{max}}. Ausgewählt: {{selected}}.",
        "maxStaffWarning": "Maximale Plätze für Rennpersonal: {{max}}. Ausgewählt: {{selected}}.",
        "maxAssetsWarning": "Maximale Plätze für Rennfahrzeuge: {{max}}. Ausgewählt: {{selected}}.",
        "raceCanceledWeather": "Dieses Rennen wurde wetterbedingt abgesagt.",
        "stageCanceledWeather": "Diese Etappe wurde wetterbedingt abgesagt.",
        "developingManagedByU23": "Dieses Rennen des Entwicklungsteams wird vom U23-Cheftrainer verwaltet.",
        "assignSportDirectorFirst": "Weise zuerst im Race Plan einen Sportdirektor zu.",
        "u23HeadCoach": "U23-Cheftrainer",
        "existingManualViewOnly": "Vorhandener manueller Plan · nur Ansicht",
        "coachPlan": "Trainerplan",
        "scheduled": "Geplant",
        "manualPlan": "Manueller Plan",
        "manualPlanViewOnlyHint": "Dieser ältere manuelle Plan bleibt sichtbar, kann aber bei aktiver U23-Automatisierung nicht geändert werden.",
        "generatedSavedByCoach": "{{name}} hat diesen Stage Plan automatisch erstellt und gespeichert.",
        "coachWillGenerateAfterStage": "Der U23-Cheftrainer erstellt diesen Plan nach dem Ende von Etappe {{stage}}.",
        "coachWillGenerateStage1": "Der U23-Cheftrainer erstellt den Stage Plan für Etappe 1 sofort nach Aktivierung der Automatisierung.",
        "managedViewOnlySwitch": "Dieser Stage Plan wird vom U23-Cheftrainer verwaltet und ist schreibgeschützt. Wechsle im Race Plan den Tactical Planner zum Sportdirektor, um manuelle Änderungen vorzunehmen.",
        "u23Schedule": "Stage-Plan-Zeitplan des U23-Cheftrainers",
        "checkingStagePlans": "Stage Plans werden geprüft…",
        "stagePlanReadiness": "Bereitschaft der Stage Plans",
        "u23ReadinessIntro": "Etappe 1 wird sofort nach Aktivierung der Automatisierung erstellt. Jede weitere Etappe wird nach dem Ende der vorherigen Etappe anhand der neuesten Ergebnisse, Ermüdung, Gesundheit, Wetterlage und Rennsituation erstellt.",
        "stagePlanReadinessPending": "Die Bereitschaft der Stage Plans wird nach dem Einreichen des Race Plan angezeigt.",
        "generatedStages": "{{generated}}/{{total}} Etappen erstellt",
        "scheduledCount": "Geplant {{count}}",
        "existingManualCount": "Vorhanden manuell {{count}}",
        "loadingU23Status": "Status des U23-Cheftrainers wird geladen…",
        "existingManualPlan": "Vorhandener manueller Plan",
        "managedByU23": "Vom U23-Cheftrainer verwaltet",
        "u23AutomationActiveTitle": "U23-Cheftrainer-Automatisierung aktiv",
        "manualPlanViewOnlyBody": "Dieser ältere manuelle Plan bleibt sichtbar, ist jetzt aber schreibgeschützt. Der U23-Cheftrainer fährt mit der nächsten geeigneten Etappe fort.",
        "generatedThisPlan": "{{name}} hat diesen Plan automatisch erstellt.",
        "adaptedAfterStage": "Er wurde nach Etappe {{stage}} angepasst.",
        "manualViewOnlyPeriod": "Vorhandener manueller Plan · nur Ansicht.",
        "generatedAutomatically": "Automatisch vom U23-Cheftrainer erstellt.",
        "generatedAfterStage": "Wird nach dem Ende von Etappe {{stage}} erstellt.",
        "generatedImmediately": "Wird sofort bei Aktivierung der U23-Automatisierung erstellt.",
    },
    "hr": {
        "loadPageFailed": "Priprema utrke nije se mogla učitati.",
        "loadSelectedRaceFailed": "Odabrana utrka nije se mogla učitati.",
        "choosePlannerDeveloping": "Odaberite sportskog direktora ili U23 glavnog trenera.",
        "selectSportDirector": "Odaberite sportskog direktora.",
        "maxRidersWarning": "Najviše dopuštenih vozača: {{max}}. Odabrano: {{selected}}.",
        "maxStaffWarning": "Najviše mjesta za osoblje utrke: {{max}}. Odabrano: {{selected}}.",
        "maxAssetsWarning": "Najviše mjesta za vozila utrke: {{max}}. Odabrano: {{selected}}.",
        "raceCanceledWeather": "Ova utrka otkazana je zbog vremenskih uvjeta.",
        "stageCanceledWeather": "Ova etapa otkazana je zbog vremenskih uvjeta.",
        "developingManagedByU23": "Ovom utrkom razvojnog tima upravlja U23 glavni trener.",
        "assignSportDirectorFirst": "Najprije odaberite sportskog direktora u Race Plan-u.",
        "u23HeadCoach": "U23 glavni trener",
        "existingManualViewOnly": "Postojeći ručni plan · samo pregled",
        "coachPlan": "Plan trenera",
        "scheduled": "Zakazano",
        "manualPlan": "Ručni plan",
        "manualPlanViewOnlyHint": "Ovaj stariji ručni plan ostaje vidljiv, ali se ne može mijenjati dok je U23 automatizacija aktivna.",
        "generatedSavedByCoach": "{{name}} je automatski izradio i spremio ovaj Stage Plan.",
        "coachWillGenerateAfterStage": "U23 glavni trener izradit će ovaj plan nakon završetka etape {{stage}}.",
        "coachWillGenerateStage1": "U23 glavni trener izradit će Stage Plan za etapu 1 odmah nakon aktiviranja automatizacije.",
        "managedViewOnlySwitch": "Ovim Stage Plan-om upravlja U23 glavni trener i dostupan je samo za pregled. U Race Plan-u prebacite Tactical Planner na sportskog direktora za ručne izmjene.",
        "u23Schedule": "Raspored Stage Plan-ova U23 glavnog trenera",
        "checkingStagePlans": "Provjera Stage Plan-ova…",
        "stagePlanReadiness": "Spremnost Stage Plan-ova",
        "u23ReadinessIntro": "Etapa 1 generira se odmah nakon aktiviranja automatizacije. Svaka sljedeća etapa generira se nakon završetka prethodne koristeći najnovije rezultate, umor, zdravlje, vrijeme i situaciju u utrci.",
        "stagePlanReadinessPending": "Spremnost Stage Plan-ova prikazat će se nakon slanja Race Plan-a.",
        "generatedStages": "Generirano {{generated}}/{{total}} etapa",
        "scheduledCount": "Zakazano {{count}}",
        "existingManualCount": "Postojećih ručnih {{count}}",
        "loadingU23Status": "Učitavanje statusa U23 glavnog trenera…",
        "existingManualPlan": "Postojeći ručni plan",
        "managedByU23": "Upravlja U23 glavni trener",
        "u23AutomationActiveTitle": "U23 automatizacija glavnog trenera je aktivna",
        "manualPlanViewOnlyBody": "Ovaj stariji ručni plan ostaje vidljiv, ali je sada samo za pregled. U23 glavni trener nastavlja sa sljedećom odgovarajućom etapom.",
        "generatedThisPlan": "{{name}} je automatski izradio ovaj plan.",
        "adaptedAfterStage": "Plan je prilagođen nakon etape {{stage}}.",
        "manualViewOnlyPeriod": "Postojeći ručni plan · samo pregled.",
        "generatedAutomatically": "Automatski ga je izradio U23 glavni trener.",
        "generatedAfterStage": "Generira se nakon završetka etape {{stage}}.",
        "generatedImmediately": "Generira se odmah nakon aktiviranja U23 automatizacije.",
    },
    "es": {
        "loadPageFailed": "No se pudo cargar la preparación de carrera.",
        "loadSelectedRaceFailed": "No se pudo cargar la carrera seleccionada.",
        "choosePlannerDeveloping": "Elige un director deportivo o un entrenador principal U23.",
        "selectSportDirector": "Elige un director deportivo.",
        "maxRidersWarning": "Máximo de ciclistas permitido: {{max}}. Seleccionados: {{selected}}.",
        "maxStaffWarning": "Máximo de plazas de personal de carrera: {{max}}. Seleccionadas: {{selected}}.",
        "maxAssetsWarning": "Máximo de plazas para vehículos de carrera: {{max}}. Seleccionadas: {{selected}}.",
        "raceCanceledWeather": "Esta carrera fue cancelada por las condiciones meteorológicas.",
        "stageCanceledWeather": "Esta etapa fue cancelada por las condiciones meteorológicas.",
        "developingManagedByU23": "Esta carrera del equipo de desarrollo está gestionada por el entrenador principal U23.",
        "assignSportDirectorFirst": "Asigna primero un director deportivo en el Race Plan.",
        "u23HeadCoach": "entrenador principal U23",
        "existingManualViewOnly": "Plan manual existente · solo lectura",
        "coachPlan": "Plan del entrenador",
        "scheduled": "Programado",
        "manualPlan": "Plan manual",
        "manualPlanViewOnlyHint": "Este plan manual anterior sigue visible, pero no puede modificarse mientras la automatización U23 esté activa.",
        "generatedSavedByCoach": "{{name}} generó y guardó automáticamente este Stage Plan.",
        "coachWillGenerateAfterStage": "El entrenador principal U23 generará este plan cuando termine la etapa {{stage}}.",
        "coachWillGenerateStage1": "El entrenador principal U23 generará el Stage Plan de la etapa 1 inmediatamente después de activar la automatización.",
        "managedViewOnlySwitch": "Este Stage Plan está gestionado por el entrenador principal U23 y es de solo lectura. Cambia el Tactical Planner al director deportivo en el Race Plan para realizar cambios manuales.",
        "u23Schedule": "Calendario de Stage Plans del entrenador principal U23",
        "checkingStagePlans": "Comprobando Stage Plans…",
        "stagePlanReadiness": "Preparación de los Stage Plans",
        "u23ReadinessIntro": "La etapa 1 se genera inmediatamente al activar la automatización. Cada etapa posterior se genera al terminar la anterior usando los últimos resultados, fatiga, salud, tiempo y situación de carrera.",
        "stagePlanReadinessPending": "La preparación de los Stage Plans aparecerá después de enviar el Race Plan.",
        "generatedStages": "Generadas {{generated}}/{{total}} etapas",
        "scheduledCount": "Programadas {{count}}",
        "existingManualCount": "Manuales existentes {{count}}",
        "loadingU23Status": "Cargando estado del entrenador principal U23…",
        "existingManualPlan": "Plan manual existente",
        "managedByU23": "Gestionado por el entrenador principal U23",
        "u23AutomationActiveTitle": "Automatización del entrenador principal U23 activa",
        "manualPlanViewOnlyBody": "Este plan manual anterior sigue visible, pero ahora es de solo lectura. El entrenador principal U23 continúa con la siguiente etapa elegible.",
        "generatedThisPlan": "{{name}} generó este plan automáticamente.",
        "adaptedAfterStage": "Se adaptó después de la etapa {{stage}}.",
        "manualViewOnlyPeriod": "Plan manual existente · solo lectura.",
        "generatedAutomatically": "Generado automáticamente por el entrenador principal U23.",
        "generatedAfterStage": "Se genera cuando termina la etapa {{stage}}.",
        "generatedImmediately": "Se genera inmediatamente al activar la automatización U23.",
    },
    "it": {
        "loadPageFailed": "Impossibile caricare la preparazione gara.",
        "loadSelectedRaceFailed": "Impossibile caricare la gara selezionata.",
        "choosePlannerDeveloping": "Scegli un direttore sportivo oppure un allenatore capo U23.",
        "selectSportDirector": "Scegli un direttore sportivo.",
        "maxRidersWarning": "Numero massimo di ciclisti consentiti: {{max}}. Selezionati: {{selected}}.",
        "maxStaffWarning": "Numero massimo di posti per lo staff gara: {{max}}. Selezionati: {{selected}}.",
        "maxAssetsWarning": "Numero massimo di posti per i veicoli gara: {{max}}. Selezionati: {{selected}}.",
        "raceCanceledWeather": "Questa gara è stata annullata per le condizioni meteo.",
        "stageCanceledWeather": "Questa tappa è stata annullata per le condizioni meteo.",
        "developingManagedByU23": "Questa gara della squadra di sviluppo è gestita dall'allenatore capo U23.",
        "assignSportDirectorFirst": "Assegna prima un direttore sportivo nel Race Plan.",
        "u23HeadCoach": "allenatore capo U23",
        "existingManualViewOnly": "Piano manuale esistente · sola lettura",
        "coachPlan": "Piano dell'allenatore",
        "scheduled": "Programmato",
        "manualPlan": "Piano manuale",
        "manualPlanViewOnlyHint": "Questo vecchio piano manuale resta visibile, ma non può essere modificato mentre l'automazione U23 è attiva.",
        "generatedSavedByCoach": "{{name}} ha generato e salvato automaticamente questo Stage Plan.",
        "coachWillGenerateAfterStage": "L'allenatore capo U23 genererà questo piano al termine della tappa {{stage}}.",
        "coachWillGenerateStage1": "L'allenatore capo U23 genererà lo Stage Plan della tappa 1 subito dopo l'attivazione dell'automazione.",
        "managedViewOnlySwitch": "Questo Stage Plan è gestito dall'allenatore capo U23 ed è in sola lettura. Nel Race Plan passa il Tactical Planner al direttore sportivo per apportare modifiche manuali.",
        "u23Schedule": "Programma degli Stage Plans dell'allenatore capo U23",
        "checkingStagePlans": "Controllo degli Stage Plans…",
        "stagePlanReadiness": "Stato di preparazione degli Stage Plans",
        "u23ReadinessIntro": "La tappa 1 viene generata subito quando si attiva l'automazione. Ogni tappa successiva viene generata al termine della precedente usando gli ultimi risultati, fatica, salute, meteo e situazione di gara.",
        "stagePlanReadinessPending": "Lo stato di preparazione degli Stage Plans apparirà dopo l'invio del Race Plan.",
        "generatedStages": "Generate {{generated}}/{{total}} tappe",
        "scheduledCount": "Programmate {{count}}",
        "existingManualCount": "Manuali esistenti {{count}}",
        "loadingU23Status": "Caricamento stato dell'allenatore capo U23…",
        "existingManualPlan": "Piano manuale esistente",
        "managedByU23": "Gestito dall'allenatore capo U23",
        "u23AutomationActiveTitle": "Automazione dell'allenatore capo U23 attiva",
        "manualPlanViewOnlyBody": "Questo vecchio piano manuale resta visibile, ma ora è in sola lettura. L'allenatore capo U23 prosegue con la prossima tappa idonea.",
        "generatedThisPlan": "{{name}} ha generato automaticamente questo piano.",
        "adaptedAfterStage": "È stato adattato dopo la tappa {{stage}}.",
        "manualViewOnlyPeriod": "Piano manuale esistente · sola lettura.",
        "generatedAutomatically": "Generato automaticamente dall'allenatore capo U23.",
        "generatedAfterStage": "Viene generato al termine della tappa {{stage}}.",
        "generatedImmediately": "Viene generato subito quando si attiva l'automazione U23.",
    },
    "fr": {
        "loadPageFailed": "Impossible de charger la préparation de course.",
        "loadSelectedRaceFailed": "Impossible de charger la course sélectionnée.",
        "choosePlannerDeveloping": "Choisissez un directeur sportif ou un entraîneur principal U23.",
        "selectSportDirector": "Choisissez un directeur sportif.",
        "maxRidersWarning": "Nombre maximal de coureurs autorisés : {{max}}. Sélectionnés : {{selected}}.",
        "maxStaffWarning": "Nombre maximal de places pour le staff de course : {{max}}. Sélectionnées : {{selected}}.",
        "maxAssetsWarning": "Nombre maximal de places pour les véhicules de course : {{max}}. Sélectionnées : {{selected}}.",
        "raceCanceledWeather": "Cette course a été annulée en raison des conditions météo.",
        "stageCanceledWeather": "Cette étape a été annulée en raison des conditions météo.",
        "developingManagedByU23": "Cette course de l'équipe de développement est gérée par l'entraîneur principal U23.",
        "assignSportDirectorFirst": "Affectez d'abord un directeur sportif dans le Race Plan.",
        "u23HeadCoach": "entraîneur principal U23",
        "existingManualViewOnly": "Plan manuel existant · lecture seule",
        "coachPlan": "Plan de l'entraîneur",
        "scheduled": "Programmé",
        "manualPlan": "Plan manuel",
        "manualPlanViewOnlyHint": "Cet ancien plan manuel reste visible, mais il ne peut pas être modifié tant que l'automatisation U23 est active.",
        "generatedSavedByCoach": "{{name}} a généré et enregistré automatiquement ce Stage Plan.",
        "coachWillGenerateAfterStage": "L'entraîneur principal U23 générera ce plan après la fin de l'étape {{stage}}.",
        "coachWillGenerateStage1": "L'entraîneur principal U23 générera le Stage Plan de l'étape 1 immédiatement après l'activation de l'automatisation.",
        "managedViewOnlySwitch": "Ce Stage Plan est géré par l'entraîneur principal U23 et est en lecture seule. Dans le Race Plan, passez le Tactical Planner au directeur sportif pour effectuer des modifications manuelles.",
        "u23Schedule": "Calendrier des Stage Plans de l'entraîneur principal U23",
        "checkingStagePlans": "Vérification des Stage Plans…",
        "stagePlanReadiness": "État de préparation des Stage Plans",
        "u23ReadinessIntro": "L'étape 1 est générée immédiatement lorsque l'automatisation est activée. Chaque étape suivante est générée après la fin de la précédente à partir des derniers résultats, de la fatigue, de la santé, de la météo et de la situation de course.",
        "stagePlanReadinessPending": "L'état de préparation des Stage Plans apparaîtra après l'envoi du Race Plan.",
        "generatedStages": "{{generated}}/{{total}} étapes générées",
        "scheduledCount": "Programmées {{count}}",
        "existingManualCount": "Manuels existants {{count}}",
        "loadingU23Status": "Chargement du statut de l'entraîneur principal U23…",
        "existingManualPlan": "Plan manuel existant",
        "managedByU23": "Géré par l'entraîneur principal U23",
        "u23AutomationActiveTitle": "Automatisation de l'entraîneur principal U23 active",
        "manualPlanViewOnlyBody": "Cet ancien plan manuel reste visible, mais il est désormais en lecture seule. L'entraîneur principal U23 poursuit avec la prochaine étape éligible.",
        "generatedThisPlan": "{{name}} a généré automatiquement ce plan.",
        "adaptedAfterStage": "Il a été adapté après l'étape {{stage}}.",
        "manualViewOnlyPeriod": "Plan manuel existant · lecture seule.",
        "generatedAutomatically": "Généré automatiquement par l'entraîneur principal U23.",
        "generatedAfterStage": "Généré après la fin de l'étape {{stage}}.",
        "generatedImmediately": "Généré immédiatement lorsque l'automatisation U23 est activée.",
    },
    "ru": {
        "loadPageFailed": "Не удалось загрузить подготовку к гонке.",
        "loadSelectedRaceFailed": "Не удалось загрузить выбранную гонку.",
        "choosePlannerDeveloping": "Выберите спортивного директора или главного тренера U23.",
        "selectSportDirector": "Выберите спортивного директора.",
        "maxRidersWarning": "Максимально допустимое число гонщиков: {{max}}. Выбрано: {{selected}}.",
        "maxStaffWarning": "Максимум мест для персонала гонки: {{max}}. Выбрано: {{selected}}.",
        "maxAssetsWarning": "Максимум мест для гоночных автомобилей: {{max}}. Выбрано: {{selected}}.",
        "raceCanceledWeather": "Эта гонка отменена из-за погодных условий.",
        "stageCanceledWeather": "Этот этап отменён из-за погодных условий.",
        "developingManagedByU23": "Этой гонкой развивающей команды управляет главный тренер U23.",
        "assignSportDirectorFirst": "Сначала назначьте спортивного директора в Race Plan.",
        "u23HeadCoach": "главный тренер U23",
        "existingManualViewOnly": "Существующий ручной план · только просмотр",
        "coachPlan": "План тренера",
        "scheduled": "Запланировано",
        "manualPlan": "Ручной план",
        "manualPlanViewOnlyHint": "Этот старый ручной план остаётся видимым, но его нельзя изменять, пока активна автоматизация U23.",
        "generatedSavedByCoach": "{{name}} автоматически создал и сохранил этот Stage Plan.",
        "coachWillGenerateAfterStage": "Главный тренер U23 создаст этот план после завершения этапа {{stage}}.",
        "coachWillGenerateStage1": "Главный тренер U23 создаст Stage Plan для этапа 1 сразу после активации автоматизации.",
        "managedViewOnlySwitch": "Этим Stage Plan управляет главный тренер U23, поэтому он доступен только для просмотра. В Race Plan переключите Tactical Planner на спортивного директора, чтобы вносить изменения вручную.",
        "u23Schedule": "Расписание Stage Plans главного тренера U23",
        "checkingStagePlans": "Проверка Stage Plans…",
        "stagePlanReadiness": "Готовность Stage Plans",
        "u23ReadinessIntro": "Этап 1 создаётся сразу после активации автоматизации. Каждый следующий этап создаётся после завершения предыдущего с учётом последних результатов, усталости, здоровья, погоды и ситуации в гонке.",
        "stagePlanReadinessPending": "Готовность Stage Plans появится после отправки Race Plan.",
        "generatedStages": "Создано этапов: {{generated}}/{{total}}",
        "scheduledCount": "Запланировано {{count}}",
        "existingManualCount": "Существующих ручных: {{count}}",
        "loadingU23Status": "Загрузка статуса главного тренера U23…",
        "existingManualPlan": "Существующий ручной план",
        "managedByU23": "Управляет главный тренер U23",
        "u23AutomationActiveTitle": "Автоматизация главного тренера U23 активна",
        "manualPlanViewOnlyBody": "Этот старый ручной план остаётся видимым, но теперь доступен только для просмотра. Главный тренер U23 продолжает со следующим подходящим этапом.",
        "generatedThisPlan": "{{name}} автоматически создал этот план.",
        "adaptedAfterStage": "Он был адаптирован после этапа {{stage}}.",
        "manualViewOnlyPeriod": "Существующий ручной план · только просмотр.",
        "generatedAutomatically": "Автоматически создан главным тренером U23.",
        "generatedAfterStage": "Создаётся после завершения этапа {{stage}}.",
        "generatedImmediately": "Создаётся сразу после активации автоматизации U23.",
    },
}


def replace_required(text: str, old: str, new: str, label: str) -> str:
    if old not in text:
        raise SystemExit(f"Missing expected source fragment: {label}")
    return text.replace(old, new)


def main() -> None:
    src = COMPONENT.read_text(encoding="utf-8")

    replacements = [
        ('title="Race Plan Bonus Preview"', 'title={racePrepText("screen.bonusTitle")}', 'bonus title'),
        ('Race staff, race assets, and team policies are converted into these\n            standardized race-engine percentage bonuses. Hover or click a card\n            to see the source breakdown.', '{racePrepText("screen.bonusDescription")}', 'bonus description'),
        ('Starting freshness combines fatigue and race sharpness. High\n              fatigue can lower the red bar even when sharpness is good.', '{racePrepText("screen.startingFreshnessHelp")}', 'freshness help'),
        ('error instanceof Error ? error.message : "Failed to load page."', 'error instanceof Error ? localizeRacePrepBackendText(error.message) : racePrepText("screen.loadPageFailed")', 'load page fallback'),
        ('error instanceof Error\n          ? error.message\n          : "Failed to load selected race."', 'error instanceof Error\n          ? localizeRacePrepBackendText(error.message)\n          : racePrepText("screen.loadSelectedRaceFailed")', 'load selected race fallback'),
        ('error instanceof Error\n          ? error.message\n          : "Failed to change competing squad."', 'error instanceof Error\n          ? localizeRacePrepBackendText(error.message)\n          : racePrepText("errors.changeSquad")', 'change squad fallback'),
        ('nextOption\n          ? `Competing squad changed to ${nextOption.name}.`\n          : "Competing squad changed."', 'nextOption\n          ? racePrepText("racePlan.competingSquadChangedTo", { squad: nextOption.name })\n          : racePrepText("racePlan.competingSquadChanged")', 'change squad success'),
        ('setMessage("Race Plan quote refreshed.");', 'setMessage(racePrepText("racePlan.quoteRefreshed"));', 'quote success'),
        ('error instanceof Error ? error.message : "Failed to quote race plan."', 'error instanceof Error ? localizeRacePrepBackendText(error.message) : racePrepText("errors.quote")', 'quote error'),
        ('`Remove ${selectedRiderCount - maxRiders} rider${\n          selectedRiderCount - maxRiders === 1 ? "" : "s"\n        } before saving.`', 'racePrepText(\n          selectedRiderCount - maxRiders === 1\n            ? "racePlan.removeOneBeforeSaving"\n            : "racePlan.removeBeforeSaving",\n          { count: selectedRiderCount - maxRiders },\n        )', 'remove riders before save'),
        ('"Select a U23 Head Coach or switch the tactical planner back to Sport Director before saving the Race Plan."', 'racePrepText("errors.selectU23Save")', 'u23 save validation'),
        ('isDevelopingTeamSelected &&\n          effectiveTacticalPlannerChoice === "u23_head_coach"\n          ? "Race Plan saved. The U23 Head Coach will take control when the Race Plan is submitted."\n          : "Race Plan saved."', 'isDevelopingTeamSelected &&\n          effectiveTacticalPlannerChoice === "u23_head_coach"\n          ? racePrepText("racePlan.savedU23")\n          : racePrepText("racePlan.saved")', 'race plan saved messages'),
        ('error instanceof Error ? error.message : "Failed to save race plan."', 'error instanceof Error ? localizeRacePrepBackendText(error.message) : racePrepText("errors.save")', 'save error'),
        ('`Select ${minRiders}–${maxRiders} riders before submitting the Race Plan.`', 'racePrepText("errors.selectRidersSubmit", { min: minRiders, max: maxRiders })', 'select riders submit'),
        ('"Select a U23 Head Coach or switch the tactical planner back to Sport Director before submitting the Race Plan."', 'racePrepText("errors.selectU23Submit")', 'u23 submit validation'),
        ('"The Race Plan was submitted, but no U23 Head Coach was selected."', 'racePrepText("screen.submittedNoU23")', 'submitted no u23'),
        ('"The Race Plan was submitted, but the U23 Head Coach could not generate the first Stage Plan."', 'racePrepText("screen.submittedU23GenerateFailed")', 'u23 generate failed'),
        ('Boolean(initialGeneration.applied)\n          ? " The U23 Head Coach generated the first eligible Stage Plan."\n          : " U23 automation is active."', 'Boolean(initialGeneration.applied)\n          ? ` ${racePrepText("racePlan.u23GeneratedFirst")}`\n          : ` ${racePrepText("racePlan.u23ActiveShort")}`', 'u23 activation message'),
        ('result.message ?? "Race Plan submitted successfully."', 'localizeRacePrepBackendText(result.message ?? racePrepText("racePlan.submittedSuccess"))', 'submit result message'),
        ('error instanceof Error ? error.message : "Failed to submit race plan."', 'error instanceof Error ? localizeRacePrepBackendText(error.message) : racePrepText("errors.submit")', 'submit error'),
        ('"This rider is already assigned to an overlapping submitted race."', 'racePrepText("errors.blockedRider")', 'blocked rider'),
        ('`You can select at most ${maxRiders} riders.`', 'racePrepText("errors.maxRiders", { max: maxRiders })', 'max riders'),
        ('"This staff member is already assigned to an overlapping submitted race."', 'racePrepText("errors.blockedStaff")', 'blocked staff'),
        ('"This U23 Head Coach is already assigned to an overlapping submitted race."', 'racePrepText("errors.blockedU23")', 'blocked u23'),
        ('"This asset is already assigned to an overlapping submitted race."', 'racePrepText("errors.blockedAsset")', 'blocked asset'),
        ('"This asset is already selected in another Race Plan slot."', 'racePrepText("errors.duplicateAsset")', 'duplicate asset'),
        ('error instanceof Error\n              ? error.message\n              : "Failed to load stage profile."', 'error instanceof Error\n              ? localizeRacePrepBackendText(error.message)\n              : racePrepText("header.profileLoadFailed")', 'stage profile load'),
        ('? "Choose either a Sport Director or a U23 Head Coach."\n        : "Select a Sport Director."', '? racePrepText("screen.choosePlannerDeveloping")\n        : racePrepText("screen.selectSportDirector")', 'planner warning'),
        ('? `Maximum riders allowed: ${maxRiders}. You selected: ${selectedRiderCount}.`', '? racePrepText("screen.maxRidersWarning", { max: maxRiders, selected: selectedRiderCount })', 'max rider warning'),
        ('? `Maximum race staff slots: ${maxStaffSlots}. You selected: ${selectedStaffCount}.`', '? racePrepText("screen.maxStaffWarning", { max: maxStaffSlots, selected: selectedStaffCount })', 'max staff warning'),
        ('? `Maximum race asset slots: ${maxAssetSlots}. You selected: ${selectedAssetCount}.`', '? racePrepText("screen.maxAssetsWarning", { max: maxAssetSlots, selected: selectedAssetCount })', 'max asset warning'),
        ('"Select a U23 Head Coach before saving this Developing Team Race Plan."', 'racePrepText("errors.selectU23BeforeSave")', 'select u23 before save'),
        ('? "This race was canceled due to weather."\n    : selectedStageWeatherCanceled\n      ? "This stage was canceled due to weather."\n      : isU23ManagedRace\n        ? "This Developing Team race is managed by the U23 Head Coach."\n        : sportDirectorAutoFillDisabled\n          ? "Assign a Sport Director in the Race Plan first."', '? racePrepText("screen.raceCanceledWeather")\n    : selectedStageWeatherCanceled\n      ? racePrepText("screen.stageCanceledWeather")\n      : isU23ManagedRace\n        ? racePrepText("screen.developingManagedByU23")\n        : sportDirectorAutoFillDisabled\n          ? racePrepText("screen.assignSportDirectorFirst")', 'sport director disabled reason'),
        ('?.staff_name ?? "U23 Head Coach",', '?.staff_name ?? racePrepText("screen.u23HeadCoach"),', 'u23 fallback name'),
        ('? "Existing manual plan · view only"\n      : selectedStageManagementSource === "u23_head_coach" &&\n          selectedU23StageHasSavedPlan\n        ? "Coach plan"\n        : "Scheduled"', '? racePrepText("screen.existingManualViewOnly")\n      : selectedStageManagementSource === "u23_head_coach" &&\n          selectedU23StageHasSavedPlan\n        ? racePrepText("screen.coachPlan")\n        : racePrepText("screen.scheduled")', 'selected u23 status'),
        ('? "This older manual plan remains visible, but it cannot be changed while U23 automation is active."', '? racePrepText("screen.manualPlanViewOnlyHint")', 'manual view only hint'),
        ('? `${u23PlannerStaffName} generated and saved this Stage Plan automatically.`', '? racePrepText("screen.generatedSavedByCoach", { name: u23PlannerStaffName })', 'generated saved by coach'),
        ('? `The U23 Head Coach will generate this plan after Stage ${Math.max(\n              getNumber(selectedStage, "stage_number") - 1,\n              1,\n            )} finishes.`\n          : "The U23 Head Coach will generate Stage 1 immediately after automation is activated."', '? racePrepText("screen.coachWillGenerateAfterStage", {\n              stage: Math.max(getNumber(selectedStage, "stage_number") - 1, 1),\n            })\n          : racePrepText("screen.coachWillGenerateStage1")', 'u23 future plan hint'),
        ('"This Stage Plan is managed by the U23 Head Coach and is view-only. Switch the Tactical Planner to Sport Director in the Race Plan before making manual changes."', 'racePrepText("screen.managedViewOnlySwitch")', 'view-only save error'),
        ('? "U23 Head Coach Stage Plan schedule"\n                    : stagePlanReadinessLoading\n                      ? "Checking Stage Plans…"\n                      : (stagePlanReadinessSummary?.readiness_label ??\n                        "Stage Plan readiness")', '? racePrepText("screen.u23Schedule")\n                    : stagePlanReadinessLoading\n                      ? racePrepText("screen.checkingStagePlans")\n                      : stagePlanReadinessSummary?.readiness_label\n                        ? localizeRacePrepBackendText(stagePlanReadinessSummary.readiness_label)\n                        : racePrepText("screen.stagePlanReadiness")', 'readiness heading'),
        ('? "Stage 1 is generated immediately when automation is activated. Each later stage is generated after the previous stage finishes, using the latest results, fatigue, health, weather and race situation."\n                    : (stagePlanReadinessSummary?.recommended_action ??\n                      "Stage Plan readiness will appear after the Race Plan is submitted.")', '? racePrepText("screen.u23ReadinessIntro")\n                    : stagePlanReadinessSummary?.recommended_action\n                      ? localizeRacePrepBackendText(stagePlanReadinessSummary.recommended_action)\n                      : racePrepText("screen.stagePlanReadinessPending")', 'readiness description'),
        ('<div>\n                    Generated {u23GeneratedStageCount}/{stages.length} stages\n                  </div>', '<div>{racePrepText("screen.generatedStages", { generated: u23GeneratedStageCount, total: stages.length })}</div>', 'generated stage count'),
        ('<div>Scheduled {u23ScheduledStageCount}</div>', '<div>{racePrepText("screen.scheduledCount", { count: u23ScheduledStageCount })}</div>', 'scheduled stage count'),
        ('<div>Existing manual {u23ExistingManualStageCount}</div>', '<div>{racePrepText("screen.existingManualCount", { count: u23ExistingManualStageCount })}</div>', 'manual stage count'),
        ('? "Loading U23 Head Coach status…"\n                  : selectedStageManagementMode === "manual"\n                    ? "Existing manual plan"\n                    : selectedStageManagementSource === "u23_head_coach"\n                      ? "Managed by U23 Head Coach"\n                      : "U23 Head Coach automation active"', '? racePrepText("screen.loadingU23Status")\n                  : selectedStageManagementMode === "manual"\n                    ? racePrepText("screen.existingManualPlan")\n                    : selectedStageManagementSource === "u23_head_coach"\n                      ? racePrepText("screen.managedByU23")\n                      : racePrepText("screen.u23AutomationActiveTitle")', 'u23 status title'),
        ('? "This older manual plan remains visible but is now view-only. The U23 Head Coach continues with the next eligible stage."', '? racePrepText("screen.manualPlanViewOnlyBody")', 'u23 manual status body'),
        ('? `${u23PlannerStaffName} generated this plan automatically.${\n                        selectedStageBasedOnStageNumber > 0\n                          ? ` It was adapted after Stage ${selectedStageBasedOnStageNumber}.`\n                          : ""', '? `${racePrepText("screen.generatedThisPlan", { name: u23PlannerStaffName })}${\n                        selectedStageBasedOnStageNumber > 0\n                          ? ` ${racePrepText("screen.adaptedAfterStage", { stage: selectedStageBasedOnStageNumber })}`\n                          : ""', 'generated/adapted status body'),
        ('? "Manual plan"\n        : u23ManagementSource === "u23_head_coach" && u23HasSavedPlan\n          ? "Coach plan"\n          : "Scheduled"', '? racePrepText("screen.manualPlan")\n        : u23ManagementSource === "u23_head_coach" && u23HasSavedPlan\n          ? racePrepText("screen.coachPlan")\n          : racePrepText("screen.scheduled")', 'u23 stage badge'),
        ('? "Existing manual plan · view only."\n        : u23ManagementSource === "u23_head_coach" && u23HasSavedPlan\n          ? "Generated automatically by the U23 Head Coach."\n          : Number(stage.stage_number ?? index + 1) > 1\n            ? `Generated after Stage ${Math.max(\n                Number(stage.stage_number ?? index + 1) - 1,\n                1,\n              )} finishes.`\n            : "Generated immediately when U23 automation is activated."', '? racePrepText("screen.manualViewOnlyPeriod")\n        : u23ManagementSource === "u23_head_coach" && u23HasSavedPlan\n          ? racePrepText("screen.generatedAutomatically")\n          : Number(stage.stage_number ?? index + 1) > 1\n            ? racePrepText("screen.generatedAfterStage", {\n                stage: Math.max(Number(stage.stage_number ?? index + 1) - 1, 1),\n              })\n            : racePrepText("screen.generatedImmediately")', 'u23 stage hint'),
    ]

    # New error strings referenced above.
    for locale in LOCALES:
        path = ROOT / "src/i18n/locales" / locale / "racePreparation.json"
        data = json.loads(path.read_text(encoding="utf-8"))
        screen = data.setdefault("screen", {})
        screen.update(NEW_SCREEN_COPY[locale])
        # These two error cases are new and belong with the existing errors.
        errors = data.setdefault("errors", {})
        if locale == "en":
            errors.update({
                "submittedNoU23": "The Race Plan was submitted, but no U23 Head Coach was selected.",
                "submittedU23GenerateFailed": "The Race Plan was submitted, but the U23 Head Coach could not generate the first Stage Plan.",
            })
        elif locale == "sr-Latn":
            errors.update({
                "submittedNoU23": "Race Plan je poslat, ali U23 glavni trener nije izabran.",
                "submittedU23GenerateFailed": "Race Plan je poslat, ali U23 glavni trener nije uspeo da generiše prvi Stage Plan.",
            })
        elif locale == "de":
            errors.update({
                "submittedNoU23": "Der Race Plan wurde eingereicht, aber es wurde kein U23-Cheftrainer ausgewählt.",
                "submittedU23GenerateFailed": "Der Race Plan wurde eingereicht, aber der U23-Cheftrainer konnte den ersten Stage Plan nicht erstellen.",
            })
        elif locale == "hr":
            errors.update({
                "submittedNoU23": "Race Plan je poslan, ali U23 glavni trener nije odabran.",
                "submittedU23GenerateFailed": "Race Plan je poslan, ali U23 glavni trener nije uspio generirati prvi Stage Plan.",
            })
        elif locale == "es":
            errors.update({
                "submittedNoU23": "El Race Plan se envió, pero no se seleccionó ningún entrenador principal U23.",
                "submittedU23GenerateFailed": "El Race Plan se envió, pero el entrenador principal U23 no pudo generar el primer Stage Plan.",
            })
        elif locale == "it":
            errors.update({
                "submittedNoU23": "Il Race Plan è stato inviato, ma non è stato selezionato alcun allenatore capo U23.",
                "submittedU23GenerateFailed": "Il Race Plan è stato inviato, ma l'allenatore capo U23 non ha potuto generare il primo Stage Plan.",
            })
        elif locale == "fr":
            errors.update({
                "submittedNoU23": "Le Race Plan a été envoyé, mais aucun entraîneur principal U23 n'a été sélectionné.",
                "submittedU23GenerateFailed": "Le Race Plan a été envoyé, mais l'entraîneur principal U23 n'a pas pu générer le premier Stage Plan.",
            })
        elif locale == "ru":
            errors.update({
                "submittedNoU23": "Race Plan отправлен, но главный тренер U23 не выбран.",
                "submittedU23GenerateFailed": "Race Plan отправлен, но главный тренер U23 не смог создать первый Stage Plan.",
            })
        path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    # Use errors.* for submitted failure keys in the source replacements.
    replacements = [
        (a, b.replace('screen.submittedNoU23', 'errors.submittedNoU23').replace('screen.submittedU23GenerateFailed', 'errors.submittedU23GenerateFailed'), c)
        for a, b, c in replacements
    ]

    for old, new, label in replacements:
        src = replace_required(src, old, new, label)

    COMPONENT.write_text(src, encoding="utf-8")
    print("Applied remaining Race Preparation localization fixes")


if __name__ == "__main__":
    main()
