#!/usr/bin/env python3
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
LOCALES_DIR = ROOT / "src" / "i18n" / "locales"
PAGE_FILE = ROOT / "src" / "pages" / "InviteFriends.tsx"

PATCHES = {
    "en": {
        "v2Step3": "After activity on 3 separate real days, you receive 2 Coins.",
        "v2CappedDescription": "The player qualified as active, but the monthly free activity reward limit had already been reached.",
    },
    "sr-Latn": {
        "title": "Pozovi prijatelje",
        "linkTitle": "Tvoj pozivni link",
        "referralAria": "Pozivni link",
        "copy": "Kopiraj",
        "share": "Podeli",
        "activityTitle": "Aktivnost preporuka",
        "how": "Kako funkcioniše",
        "v2Subtitle": "Osvoji 2 Coins kada pozvani igrač postane zaista aktivan, plus 40 Coins ako kasnije kupi Premium ili svoj prvi Coin paket.",
        "v2LinkDescription": "Podeli svoj lični link. Preporuka se povezuje sa tvojim nalogom kada se prijatelj registruje i kreira svoj tim.",
        "v2StatsTitle": "Pregled preporuka",
        "v2TotalReferrals": "Ukupno preporuka",
        "v2PendingReferrals": "Na čekanju",
        "v2ActivePlayers": "Aktivni igrači",
        "v2PaidConversions": "Plaćene konverzije",
        "v2ActivityCoins": "Coins iz aktivnosti",
        "v2PaidCoins": "Coins iz kupovina",
        "v2TotalCoins": "Ukupno Coins",
        "v2ActivityDescription": "Nagrada od 2 Coins za aktivnost i nagrada od 40 Coins za kupovinu prate se odvojeno za svakog preporučenog igrača.",
        "v2NoActivity": "Još nema preporuka. Podeli pozivni link da počneš da pratiš pozvane igrače.",
        "v2ActiveDays": "Aktivni dani: {{count}}/3",
        "v2Coins": "Coins",
        "v2MonthlyCapReached": "Dostignuto mesečno ograničenje besplatnih nagrada",
        "v2PremiumConversion": "Premium",
        "v2CoinConversion": "Coin paket",
        "v2PaidConversion": "Plaćena konverzija",
        "v2RejectedDescription": "Ova preporuka više ne ispunjava uslove za nagrade.",
        "v2PaidCompletedDescription": "Plaćena konverzija je završena preko {{type}}. Dodeljena je jednokratna nagrada od 40 Coins.",
        "v2ActivityCompletedDescription": "Igrač je bio aktivan tokom 3 odvojena realna dana. Dodeljena je nagrada od 2 Coins za aktivnost.",
        "v2CappedDescription": "Igrač se kvalifikovao kao aktivan, ali je mesečno ograničenje besplatnih nagrada već bilo dostignuto.",
        "v2PendingDescription": "Igrač je zabeležio {{count}} od 3 odvojena aktivna dana potrebna za malu nagradu za aktivnost.",
        "v2Step1": "Kopiraj ili podeli svoj lični pozivni link.",
        "v2Step2": "Prijatelj otvara link, potvrđuje nalog, registruje se i kreira pravi tim.",
        "v2Step3": "Nakon aktivnosti tokom 3 odvojena realna dana dobijaš 2 Coins.",
        "v2Step4": "Ako isti preporučeni igrač kasnije obavi prvu Premium kupovinu ili kupi svoj prvi Coin paket, dobijaš dodatnu jednokratnu nagradu od 40 Coins. Premium + Coins se za ovu plaćenu nagradu računaju samo jednom.",
        "v2AntiAbuseNote": "Samopreporuke, obrisani timovi ili timovi bez vlasnika i duplirani preporučeni korisnici ne ispunjavaju uslove. Aktivnost se računa po različitim UTC kalendarskim danima, a besplatna nagrada ima mesečno ograničenje.",
    },
    "de": {
        "title": "Freunde einladen",
        "linkTitle": "Dein Einladungslink",
        "referralAria": "Einladungslink",
        "copy": "Kopieren",
        "share": "Teilen",
        "activityTitle": "Empfehlungsaktivität",
        "how": "So funktioniert es",
        "v2Subtitle": "Erhalte 2 Coins, wenn ein eingeladener Spieler wirklich aktiv wird, plus 40 Coins, wenn dieser Spieler später Premium oder sein erstes Coin-Paket kauft.",
        "v2LinkDescription": "Teile deinen persönlichen Link. Die Empfehlung wird zugeordnet, sobald dein Freund sich registriert und sein Team erstellt.",
        "v2StatsTitle": "Empfehlungsübersicht",
        "v2TotalReferrals": "Empfehlungen insgesamt",
        "v2PendingReferrals": "Ausstehend",
        "v2ActivePlayers": "Aktive Spieler",
        "v2PaidConversions": "Bezahlte Konversionen",
        "v2ActivityCoins": "Aktivitäts-Coins",
        "v2PaidCoins": "Kauf-Coins",
        "v2TotalCoins": "Coins insgesamt",
        "v2ActivityDescription": "Die 2-Coin-Aktivitätsbelohnung und die 40-Coin-Kaufbelohnung werden für jeden empfohlenen Spieler getrennt erfasst.",
        "v2NoActivity": "Noch keine Empfehlungen. Teile deinen Einladungslink, um eingeladene Spieler zu erfassen.",
        "v2ActiveDays": "Aktive Tage: {{count}}/3",
        "v2Coins": "Coins",
        "v2MonthlyCapReached": "Monatliches Limit für kostenlose Belohnungen erreicht",
        "v2PremiumConversion": "Premium",
        "v2CoinConversion": "Coin-Paket",
        "v2PaidConversion": "Bezahlte Konversion",
        "v2RejectedDescription": "Diese Empfehlung ist nicht mehr für Belohnungen berechtigt.",
        "v2PaidCompletedDescription": "Bezahlte Konversion über {{type}} abgeschlossen. Die einmalige Belohnung von 40 Coins wurde gutgeschrieben.",
        "v2ActivityCompletedDescription": "Der Spieler war an 3 verschiedenen realen Tagen aktiv. Die Aktivitätsbelohnung von 2 Coins wurde gutgeschrieben.",
        "v2CappedDescription": "Der Spieler hat sich als aktiv qualifiziert, aber das monatliche Limit für kostenlose Aktivitätsbelohnungen war bereits erreicht.",
        "v2PendingDescription": "Der Spieler hat {{count}} von 3 erforderlichen separaten aktiven Tagen für die kleine Aktivitätsbelohnung erreicht.",
        "v2Step1": "Kopiere oder teile deinen persönlichen Einladungslink.",
        "v2Step2": "Dein Freund öffnet den Link, bestätigt sein Konto, registriert sich und erstellt ein echtes Team.",
        "v2Step3": "Nach Aktivität an 3 verschiedenen realen Tagen erhältst du 2 Coins.",
        "v2Step4": "Wenn derselbe empfohlene Spieler später erstmals Premium oder sein erstes Coin-Paket kauft, erhältst du eine zusätzliche einmalige Belohnung von 40 Coins. Premium + Coins zählen für diese bezahlte Belohnung nur einmal.",
        "v2AntiAbuseNote": "Selbstempfehlungen, gelöschte oder besitzerlose Teams und doppelt empfohlene Benutzer sind nicht berechtigt. Aktivität wird nach unterschiedlichen UTC-Kalendertagen gezählt; die kostenlose Belohnung ist monatlich begrenzt.",
    },
    "hr": {
        "title": "Pozovi prijatelje",
        "linkTitle": "Tvoja poveznica za poziv",
        "referralAria": "Poveznica za poziv",
        "copy": "Kopiraj",
        "share": "Podijeli",
        "activityTitle": "Aktivnost preporuka",
        "how": "Kako funkcionira",
        "v2Subtitle": "Osvoji 2 Coins kada pozvani igrač postane stvarno aktivan, plus 40 Coins ako kasnije kupi Premium ili svoj prvi Coin paket.",
        "v2LinkDescription": "Podijeli svoju osobnu poveznicu. Preporuka se povezuje s tvojim računom kada se prijatelj registrira i stvori svoj tim.",
        "v2StatsTitle": "Pregled preporuka",
        "v2TotalReferrals": "Ukupno preporuka",
        "v2PendingReferrals": "Na čekanju",
        "v2ActivePlayers": "Aktivni igrači",
        "v2PaidConversions": "Plaćene konverzije",
        "v2ActivityCoins": "Coins iz aktivnosti",
        "v2PaidCoins": "Coins iz kupnji",
        "v2TotalCoins": "Ukupno Coins",
        "v2ActivityDescription": "Nagrada od 2 Coins za aktivnost i nagrada od 40 Coins za kupnju prate se odvojeno za svakog preporučenog igrača.",
        "v2NoActivity": "Još nema preporuka. Podijeli poveznicu za poziv kako bi počeo pratiti pozvane igrače.",
        "v2ActiveDays": "Aktivni dani: {{count}}/3",
        "v2Coins": "Coins",
        "v2MonthlyCapReached": "Dosegnuto mjesečno ograničenje besplatnih nagrada",
        "v2PremiumConversion": "Premium",
        "v2CoinConversion": "Coin paket",
        "v2PaidConversion": "Plaćena konverzija",
        "v2RejectedDescription": "Ova preporuka više ne ispunjava uvjete za nagrade.",
        "v2PaidCompletedDescription": "Plaćena konverzija dovršena je putem {{type}}. Dodijeljena je jednokratna nagrada od 40 Coins.",
        "v2ActivityCompletedDescription": "Igrač je bio aktivan tijekom 3 odvojena stvarna dana. Dodijeljena je nagrada od 2 Coins za aktivnost.",
        "v2CappedDescription": "Igrač se kvalificirao kao aktivan, ali je mjesečno ograničenje besplatnih nagrada već bilo dosegnuto.",
        "v2PendingDescription": "Igrač je zabilježio {{count}} od 3 odvojena aktivna dana potrebna za malu nagradu za aktivnost.",
        "v2Step1": "Kopiraj ili podijeli svoju osobnu poveznicu za poziv.",
        "v2Step2": "Prijatelj otvara poveznicu, potvrđuje račun, registrira se i stvara pravi tim.",
        "v2Step3": "Nakon aktivnosti tijekom 3 odvojena stvarna dana dobivaš 2 Coins.",
        "v2Step4": "Ako isti preporučeni igrač kasnije prvi put kupi Premium ili svoj prvi Coin paket, dobivaš dodatnu jednokratnu nagradu od 40 Coins. Premium + Coins za ovu plaćenu nagradu računaju se samo jednom.",
        "v2AntiAbuseNote": "Samopreporuke, obrisani timovi ili timovi bez vlasnika i duplicirani preporučeni korisnici ne ispunjavaju uvjete. Aktivnost se broji po različitim UTC kalendarskim danima, a besplatna nagrada ima mjesečno ograničenje.",
    },
    "es": {
        "title": "Invitar amigos",
        "linkTitle": "Tu enlace de invitación",
        "referralAria": "Enlace de invitación",
        "copy": "Copiar",
        "share": "Compartir",
        "activityTitle": "Actividad de referidos",
        "how": "Cómo funciona",
        "v2Subtitle": "Consigue 2 Coins cuando un jugador invitado se vuelva realmente activo, más 40 Coins si después compra Premium o su primer paquete de Coins.",
        "v2LinkDescription": "Comparte tu enlace personal. El referido queda vinculado cuando tu amigo se registra y crea su equipo.",
        "v2StatsTitle": "Resumen de referidos",
        "v2TotalReferrals": "Referidos totales",
        "v2PendingReferrals": "Pendientes",
        "v2ActivePlayers": "Jugadores activos",
        "v2PaidConversions": "Conversiones de pago",
        "v2ActivityCoins": "Coins por actividad",
        "v2PaidCoins": "Coins por compras",
        "v2TotalCoins": "Coins totales",
        "v2ActivityDescription": "La recompensa de 2 Coins por actividad y la recompensa de 40 Coins por compra se registran por separado para cada jugador referido.",
        "v2NoActivity": "Aún no hay referidos. Comparte tu enlace de invitación para empezar a registrar jugadores invitados.",
        "v2ActiveDays": "Días activos: {{count}}/3",
        "v2Coins": "Coins",
        "v2MonthlyCapReached": "Se alcanzó el límite mensual de recompensas gratuitas",
        "v2PremiumConversion": "Premium",
        "v2CoinConversion": "Paquete de Coins",
        "v2PaidConversion": "Conversión de pago",
        "v2RejectedDescription": "Este referido ya no cumple los requisitos para recibir recompensas.",
        "v2PaidCompletedDescription": "Conversión de pago completada mediante {{type}}. Se otorgó la recompensa única de 40 Coins.",
        "v2ActivityCompletedDescription": "El jugador registró actividad en 3 días reales distintos. Se otorgó la recompensa de 2 Coins por actividad.",
        "v2CappedDescription": "El jugador cumplió el requisito de actividad, pero ya se había alcanzado el límite mensual de recompensas gratuitas.",
        "v2PendingDescription": "El jugador ha registrado {{count}} de los 3 días activos distintos necesarios para la pequeña recompensa por actividad.",
        "v2Step1": "Copia o comparte tu enlace personal de invitación.",
        "v2Step2": "Tu amigo abre el enlace, verifica su cuenta, se registra y crea un equipo real.",
        "v2Step3": "Después de registrar actividad en 3 días reales distintos, recibes 2 Coins.",
        "v2Step4": "Si ese mismo jugador referido realiza después su primera compra de Premium o de un paquete de Coins, recibes una recompensa adicional única de 40 Coins. Premium + Coins solo cuentan una vez para esta recompensa de pago.",
        "v2AntiAbuseNote": "Los autorreferidos, los equipos eliminados o sin propietario y los usuarios referidos duplicados no cumplen los requisitos. La actividad se cuenta por días naturales UTC distintos y la recompensa gratuita tiene un límite mensual.",
    },
    "it": {
        "title": "Invita amici",
        "linkTitle": "Il tuo link di invito",
        "referralAria": "Link di invito",
        "copy": "Copia",
        "share": "Condividi",
        "activityTitle": "Attività dei referral",
        "how": "Come funziona",
        "v2Subtitle": "Guadagna 2 Coins quando un giocatore invitato diventa realmente attivo, più 40 Coins se in seguito acquista Premium o il suo primo pacchetto Coins.",
        "v2LinkDescription": "Condividi il tuo link personale. Il referral viene associato quando il tuo amico si registra e crea la propria squadra.",
        "v2StatsTitle": "Panoramica referral",
        "v2TotalReferrals": "Referral totali",
        "v2PendingReferrals": "In attesa",
        "v2ActivePlayers": "Giocatori attivi",
        "v2PaidConversions": "Conversioni a pagamento",
        "v2ActivityCoins": "Coins attività",
        "v2PaidCoins": "Coins acquisti",
        "v2TotalCoins": "Coins totali",
        "v2ActivityDescription": "La ricompensa di 2 Coins per l'attività e quella di 40 Coins per l'acquisto vengono monitorate separatamente per ogni giocatore invitato.",
        "v2NoActivity": "Non ci sono ancora referral. Condividi il tuo link di invito per iniziare a monitorare i giocatori invitati.",
        "v2ActiveDays": "Giorni attivi: {{count}}/3",
        "v2Coins": "Coins",
        "v2MonthlyCapReached": "Limite mensile delle ricompense gratuite raggiunto",
        "v2PremiumConversion": "Premium",
        "v2CoinConversion": "Pacchetto Coins",
        "v2PaidConversion": "Conversione a pagamento",
        "v2RejectedDescription": "Questo referral non è più idoneo alle ricompense.",
        "v2PaidCompletedDescription": "Conversione a pagamento completata tramite {{type}}. È stata assegnata la ricompensa una tantum di 40 Coins.",
        "v2ActivityCompletedDescription": "Il giocatore ha registrato attività in 3 giorni reali distinti. È stata assegnata la ricompensa di 2 Coins per l'attività.",
        "v2CappedDescription": "Il giocatore ha soddisfatto il requisito di attività, ma il limite mensile delle ricompense gratuite era già stato raggiunto.",
        "v2PendingDescription": "Il giocatore ha registrato {{count}} dei 3 giorni attivi distinti richiesti per la piccola ricompensa attività.",
        "v2Step1": "Copia o condividi il tuo link personale di invito.",
        "v2Step2": "Il tuo amico apre il link, verifica il proprio account, si registra e crea una squadra reale.",
        "v2Step3": "Dopo aver registrato attività in 3 giorni reali distinti, ricevi 2 Coins.",
        "v2Step4": "Se lo stesso giocatore invitato effettua in seguito il suo primo acquisto Premium o il suo primo acquisto di un pacchetto Coins, ricevi un'ulteriore ricompensa una tantum di 40 Coins. Premium + Coins contano una sola volta per questa ricompensa a pagamento.",
        "v2AntiAbuseNote": "I referral a se stessi, le squadre eliminate o senza proprietario e gli utenti invitati duplicati non sono idonei. L'attività viene conteggiata su giorni di calendario UTC distinti e la ricompensa gratuita ha un limite mensile.",
    },
    "fr": {
        "title": "Inviter des amis",
        "linkTitle": "Ton lien d'invitation",
        "referralAria": "Lien d'invitation",
        "copy": "Copier",
        "share": "Partager",
        "activityTitle": "Activité de parrainage",
        "how": "Comment ça marche",
        "v2Subtitle": "Gagne 2 Coins lorsqu'un joueur invité devient réellement actif, puis 40 Coins s'il achète ensuite Premium ou son premier pack de Coins.",
        "v2LinkDescription": "Partage ton lien personnel. Le parrainage est associé lorsque ton ami s'inscrit et crée son équipe.",
        "v2StatsTitle": "Aperçu des parrainages",
        "v2TotalReferrals": "Parrainages au total",
        "v2PendingReferrals": "En attente",
        "v2ActivePlayers": "Joueurs actifs",
        "v2PaidConversions": "Conversions payantes",
        "v2ActivityCoins": "Coins d'activité",
        "v2PaidCoins": "Coins d'achat",
        "v2TotalCoins": "Coins au total",
        "v2ActivityDescription": "La récompense de 2 Coins pour l'activité et celle de 40 Coins pour l'achat sont suivies séparément pour chaque joueur parrainé.",
        "v2NoActivity": "Aucun parrainage pour le moment. Partage ton lien d'invitation pour commencer à suivre les joueurs invités.",
        "v2ActiveDays": "Jours actifs : {{count}}/3",
        "v2Coins": "Coins",
        "v2MonthlyCapReached": "Limite mensuelle des récompenses gratuites atteinte",
        "v2PremiumConversion": "Premium",
        "v2CoinConversion": "Pack de Coins",
        "v2PaidConversion": "Conversion payante",
        "v2RejectedDescription": "Ce parrainage n'est plus éligible aux récompenses.",
        "v2PaidCompletedDescription": "Conversion payante effectuée via {{type}}. La récompense unique de 40 Coins a été accordée.",
        "v2ActivityCompletedDescription": "Le joueur a été actif pendant 3 jours réels distincts. La récompense de 2 Coins pour l'activité a été accordée.",
        "v2CappedDescription": "Le joueur a rempli la condition d'activité, mais la limite mensuelle des récompenses gratuites avait déjà été atteinte.",
        "v2PendingDescription": "Le joueur a enregistré {{count}} des 3 jours actifs distincts requis pour la petite récompense d'activité.",
        "v2Step1": "Copie ou partage ton lien personnel d'invitation.",
        "v2Step2": "Ton ami ouvre le lien, vérifie son compte, s'inscrit et crée une vraie équipe.",
        "v2Step3": "Après une activité sur 3 jours réels distincts, tu reçois 2 Coins.",
        "v2Step4": "Si ce même joueur parrainé effectue ensuite son premier achat Premium ou son premier achat d'un pack de Coins, tu reçois une récompense supplémentaire unique de 40 Coins. Premium + Coins ne comptent qu'une seule fois pour cette récompense payante.",
        "v2AntiAbuseNote": "Les auto-parrainages, les équipes supprimées ou sans propriétaire et les utilisateurs parrainés en double ne sont pas éligibles. L'activité est comptée sur des jours calendaires UTC distincts et la récompense gratuite est limitée chaque mois.",
    },
    "ru": {
        "title": "Пригласить друзей",
        "linkTitle": "Ваша пригласительная ссылка",
        "referralAria": "Пригласительная ссылка",
        "copy": "Копировать",
        "share": "Поделиться",
        "activityTitle": "Активность приглашений",
        "how": "Как это работает",
        "v2Subtitle": "Получите 2 Coins, когда приглашённый игрок станет действительно активным, и ещё 40 Coins, если позже он купит Premium или свой первый пакет Coins.",
        "v2LinkDescription": "Поделитесь личной ссылкой. Приглашение привязывается, когда ваш друг регистрируется и создаёт свою команду.",
        "v2StatsTitle": "Обзор приглашений",
        "v2TotalReferrals": "Всего приглашений",
        "v2PendingReferrals": "В ожидании",
        "v2ActivePlayers": "Активные игроки",
        "v2PaidConversions": "Платные конверсии",
        "v2ActivityCoins": "Coins за активность",
        "v2PaidCoins": "Coins за покупки",
        "v2TotalCoins": "Всего Coins",
        "v2ActivityDescription": "Награда 2 Coins за активность и награда 40 Coins за покупку учитываются отдельно для каждого приглашённого игрока.",
        "v2NoActivity": "Приглашений пока нет. Поделитесь своей ссылкой, чтобы начать отслеживать приглашённых игроков.",
        "v2ActiveDays": "Активные дни: {{count}}/3",
        "v2Coins": "Coins",
        "v2MonthlyCapReached": "Достигнут месячный лимит бесплатных наград",
        "v2PremiumConversion": "Premium",
        "v2CoinConversion": "Пакет Coins",
        "v2PaidConversion": "Платная конверсия",
        "v2RejectedDescription": "Это приглашение больше не соответствует условиям получения наград.",
        "v2PaidCompletedDescription": "Платная конверсия через {{type}} завершена. Начислена единовременная награда 40 Coins.",
        "v2ActivityCompletedDescription": "Игрок был активен в течение 3 отдельных реальных дней. Начислена награда 2 Coins за активность.",
        "v2CappedDescription": "Игрок выполнил условие активности, но месячный лимит бесплатных наград уже был достигнут.",
        "v2PendingDescription": "Игрок отметил {{count}} из 3 отдельных активных дней, необходимых для небольшой награды за активность.",
        "v2Step1": "Скопируйте или поделитесь своей личной пригласительной ссылкой.",
        "v2Step2": "Ваш друг открывает ссылку, подтверждает аккаунт, регистрируется и создаёт настоящую команду.",
        "v2Step3": "После активности в течение 3 отдельных реальных дней вы получаете 2 Coins.",
        "v2Step4": "Если этот же приглашённый игрок позже впервые купит Premium или свой первый пакет Coins, вы получите дополнительную единовременную награду 40 Coins. Premium + Coins учитываются для этой платной награды только один раз.",
        "v2AntiAbuseNote": "Самоприглашения, удалённые команды или команды без владельца и повторно приглашённые пользователи не учитываются. Активность считается по отдельным календарным дням UTC, а бесплатная награда имеет месячный лимит.",
    },
}

REQUIRED_V2_KEYS = {
    "v2Subtitle",
    "v2LinkDescription",
    "v2StatsTitle",
    "v2TotalReferrals",
    "v2PendingReferrals",
    "v2ActivePlayers",
    "v2PaidConversions",
    "v2ActivityCoins",
    "v2PaidCoins",
    "v2TotalCoins",
    "v2ActivityDescription",
    "v2NoActivity",
    "v2ActiveDays",
    "v2Coins",
    "v2MonthlyCapReached",
    "v2PremiumConversion",
    "v2CoinConversion",
    "v2PaidConversion",
    "v2RejectedDescription",
    "v2PaidCompletedDescription",
    "v2ActivityCompletedDescription",
    "v2CappedDescription",
    "v2PendingDescription",
    "v2Step1",
    "v2Step2",
    "v2Step3",
    "v2Step4",
    "v2AntiAbuseNote",
}

for locale, patch in PATCHES.items():
    path = LOCALES_DIR / locale / "accountPages.json"
    if not path.exists():
        raise SystemExit(f"Missing locale file: {path}")
    data = json.loads(path.read_text(encoding="utf-8"))
    invite = data.setdefault("invite", {})
    invite.update(patch)
    if locale != "en":
        missing = sorted(REQUIRED_V2_KEYS - set(invite))
        if missing:
            raise SystemExit(f"{locale} is missing Invite Friends v2 keys: {missing}")
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

# Remove the obsolete public-facing cap wording from the page documentation too.
page = PAGE_FILE.read_text(encoding="utf-8")
page = page.replace(" * - Maximum 10 free activity rewards per inviter per real calendar month.\n", "")
PAGE_FILE.write_text(page, encoding="utf-8")

# Guard against the removed exact limit wording returning to the visible Invite Friends copy.
for locale in PATCHES:
    path = LOCALES_DIR / locale / "accountPages.json"
    invite = json.loads(path.read_text(encoding="utf-8"))["invite"]
    combined = " ".join(str(value) for value in invite.values())
    if "maximum of 10" in combined.lower():
        raise SystemExit(f"Removed maximum-10 wording still present in {locale}")

print("Invite Friends localization updated for:", ", ".join(PATCHES))
