from __future__ import annotations

import json
from pathlib import Path

ROOT = Path('src/i18n/locales/hr')
PATCHES: dict[str, dict[str, str]] = {
    'publicInfo.json': {
        'about.intro': 'ProPeloton Manager je online biciklistička menadžerska igra u kojoj igrači stvaraju i razvijaju biciklistički tim, planiraju kalendar utrka, upravljaju vozačima, financijama i transferima, prate poretke i natječu se kroz dug sezonski biciklistički svijet.',
        'about.what1': 'ProPeloton Manager namijenjen je igračima koji vole biciklizam, strategiju, dugoročno planiranje i natjecanje s drugim igračima. Umjesto izravnog upravljanja vozačem, vi ste menadžer biciklističkog kluba. Vaš je zadatak izgraditi uravnoteženu momčad, pripremati utrke, čuvati financijsku stabilnost, razvijati vozače, upravljati osobljem, nadograđivati objekte i donositi odluke koje utječu na cijelu sezonu.',
        'about.what2': 'Svijet igre uključuje kalendar utrka, rangiranje timova, pripremu utrka, Stage Plans, opremu, trening, osoblje, sponzore, transfere, financijsko upravljanje i sustav Razvojnog tima. Svaki klub mora uskladiti ambicije s dugoročnom stabilnošću.',
        'about.teamText': 'Izgradite momčad sa sprinterima, brdašima, kronometrašima, pomagačima, liderima i mladim vozačima. Ugovori, moral, umor, potencijal i razvoj važni su.',
        'about.raceText': 'Prijavljujte se na utrke, birajte vozače, dodjeljujte osoblje i resurse, birajte opremu, pripremajte zalihe i izrađujte Stage Plans prije rokova.',
        'how.intro': 'ProPeloton Manager temelji se na povezanim odlukama. Svaka utrka, transfer, odabir treninga, cilj sponzora i financijska odluka mogu utjecati na budućnost vašeg kluba.',
        'how.step1Text': 'Počnite stvaranjem identiteta svojeg biciklističkog tima. Klub postaje središte vaše sezone: vozači, financije, kalendar utrka, sponzori, transferi, oprema i poretci povezani su s vašim timom.',
        'how.step2Text': 'Pregledajte vozače prije velikih odluka. Snažnoj momčadi potrebni su različiti tipovi vozača, poput sprintera, brdaša, kronometraša, pomagača, rouleur vozača i lidera. Ukupna ocjena korisna je, ali konkretne vještine i uloge vozača u mnogim utrkama znače više.',
        'how.step5Text': 'Prihvaćena prijava nije dovoljna. Prije utrke menadžeri pripremaju vozače, osoblje, timska vozila, opremu, zalihe i taktiku. Etapne utrke zahtijevaju i Stage Plans za svaku etapu.',
        'how.step6Title': '6. Upravljajte financijama',
        'how.step6Text': 'Vaš klub ima prihode i troškove. Plaće, osoblje, oprema, infrastruktura, trening kampovi, sponzori, porezi, putovanja i operativni troškovi utrka utječu na stanje proračuna. Financijska disciplina dio je dugoročnog uspjeha.',
        'how.system10': 'Financije, porez, plaće i operacije',
        'how.timeText': 'ProPeloton Manager koristi vrijeme u igri za rokove utrka, trening kampove, transfere, financijska razdoblja i tijek sezone. Menadžeri trebaju uvijek provjeriti prikazano vrijeme u igri i pripremiti sve prije posljednjeg roka. Propušten rok može ostaviti tim loše pripremljenim za važnu utrku.',
        'support.gameplayText': 'Pitajte o pripremi utrke, Stage Plans, transferima, sponzorima, financijama, rangiranju, treningu, umoru ili bilo kojem sustavu koji nije jasan.',
        'contactPage.publicIntro': 'Koristite ovu stranicu za zahtjeve za podršku, prijave pogrešaka, pitanja o računu, povratne informacije o igri, pitanja privatnosti i opći kontakt u vezi s ProPeloton Managerom.',
        'contactPage.dashboardIntro': 'Pošaljite zahtjev za podršku, prijavu pogreške, pitanje o računu, povratnu informaciju o igri, pitanje privatnosti ili opću poruku izravno podršci.',
        'privacy.s2p2': 'Podaci igre mogu uključivati pojedinosti kluba, vozače, osoblje, financije, pripremu utrka, obavijesti, poretke, kupnje, stanje Coins, Premium status, pretplate, aktivacije usluga i druge podatke igre povezane s računom.',
        'privacy.s3p3': 'Te podatke koristimo kako bismo aktivirali ili završili Premium pristup, dodijelili mjesečne Coins nakon uspješnog plaćanja, obradili jednokratne kupnje Coins, prikazali povijest naplate, spriječili dvostruke dodjele, upravljali otkazivanjima, istražili pogreške u plaćanju i odgovorili na povrate novca, sporove, storniranja ili prijevare.',
        'privacy.s8p2': 'Podaci o plaćanjima, računima, evidenciji Coins, pretplatama, povratima, sporovima i sprječavanju prijevara mogu se čuvati dulje kada je to potrebno zbog računovodstvenih, poreznih, zakonskih ili sigurnosnih obveza te zahtjeva pružatelja usluga plaćanja.',
        'privacy.s10p1': 'Ovisno o primjenjivom zakonu, možete imati prava na pristup, ispravak, brisanje, ograničenje obrade, prigovor ili prenosivost osobnih podataka. Neke podatke igre, plaćanja ili sigurnosti možda ćemo morati zadržati kada je čuvanje zakonski obvezno ili potrebno radi zaštite usluge.',
        'privacy.s11Prefix': 'Za pitanja ili zahtjeve povezane s privatnošću kontaktirajte nas na',
        'terms.s1p1': 'Stvaranjem računa, korištenjem ProPeloton Managera, kupnjom Coins ili pretplatom na Premium prihvaćate ove Uvjete korištenja. Ako se ne slažete, nemojte koristiti igru.',
        'terms.s2p1': 'ProPeloton Manager je online biciklistička menadžerska igra. Igra može uključivati stvaranje tima, upravljanje vozačima, trening, pripremu utrka, transfere, rangiranje, financijske sustave, sponzore, Premium funkcije, Coins i druge funkcije igre.',
        'terms.s4p2': 'Možemo ograničiti pristup, poništiti nepošteno stečenu korist, ukloniti neprihvatljiv sadržaj, ispraviti stanje ili suspendirati račune kada je to razumno potrebno radi zaštite igre i drugih igrača.',
        'terms.s5p1': 'Coins su valuta u igri povezana s računom i koriste se samo unutar ProPeloton Managera. Coins nisu pravi novac, nemaju novčanu vrijednost, ne mogu se povući niti prodavati, prenositi ili mijenjati izvan igre osim ako takvu mogućnost izričito ne uvedemo.',
        'terms.s5p3': 'Kada je plaćanje dovršeno i Coins su dodijeljeni, kupnja je konačna, osim kada je povrat novca obvezan prema primjenjivom zakonu ili kada potvrdimo dvostruku, neovlaštenu ili tehnički pogrešnu naplatu.',
        'terms.s8p2': 'Ništa u ovim uvjetima ne ukida prava potrošača koja se zakonski ne mogu isključiti. Kada primjenjivi zakon zahtijeva povrat novca, pravo otkaza, pravo na odustanak ili drugi pravni lijek, taj zakonski zahtjev ima prednost.',
    },
    'tutorials.json': {
        'overview.simpleOrDeep.body': 'Ne morate odmah razumjeti sve.\n\nNa početku možete igrati jednostavno: pratite upozorenja, provjeravajte momčad, prijavljujte se na utrke, pripremajte tim i pratite rezultate.\n\nKasnije, ako želite više dubine, možete koristiti napredne sustave kao što su umor vozača, moral, race sharpness, ciljevi sponzora, bonusi opreme, trening kampovi, skauting, pregovori o transferima, porezi, infrastruktura te promocija ili ispadanje.',
        'overview.purpose.body': 'Ovaj vodič provest će vas, korak po korak, kroz glavne stranice igre.\n\nSaznat ćete čemu svaka stranica služi, koji su gumbi važni i što bi novi menadžer trebao provjeravati.\n\nVodič neće odjednom objašnjavati svaki sitan detalj. Za detaljnija objašnjenja kasnije uvijek možete koristiti potpuni priručnik igre.',
        'overview.startOverview.body': 'Počet ćemo sa stranicom Pregled.\n\nTo je vaša glavna menadžerska nadzorna ploča. Najbrže vam pokazuje stanje tima: trenutačna upozorenja, vijesti, financije, utrke, poruke sponzora, stanje vozača i napredak sezone.\n\nNakon ovog uvoda objasnit ću stranicu Pregled korak po korak.',
        'overview.dashboard.body': 'Ovo je stranica Pregled — glavna nadzorna ploča vašeg tima.\n\nPromatrajte je kao svakodnevni kontrolni centar. Kada se prijavite, ovo je obično prvo mjesto koje trebate provjeriti.\n\nOvdje možete brzo vidjeti najvažnije informacije o klubu, uključujući stanje tima, trenutačna upozorenja, financije, utrke, stanje vozača i napredak sezone.',
        'overview.staffBriefing.title': 'Centar za izvještaje osoblja',
        'overview.staffBriefing.body': 'Ovaj panel prikazuje vaše pomoćno osoblje i uloge savjetnika.\n\nOvdje možete vidjeti važne članove tima kao što su glavni trener, sportski direktor, liječnik tima, glavni mehaničar i druge pomoćne uloge kada su dostupne.\n\nTi savjetnici pomažu vam učinkovitije upravljati važnim dijelovima kluba, kao što su planiranje utrke, zdravlje vozača, priprema i podrška oko opreme.\n\nNeke funkcije savjetnika, alati osoblja ili opcije povezane s automatizacijom mogu zahtijevati Premium račun ili kupnju Coins kako biste ih koristili u potpunosti.',
        'overview.nextRace.body': 'Panel Sljedeća utrka tima pomaže vam vidjeti što uskoro očekuje vaš tim.\n\nTo je važno jer prihvaćene utrke često i dalje zahtijevaju pripremu. Prije rokova možda ćete morati odabrati vozače, osoblje, vozila i druga sredstva, opremu, zalihe i taktiku za etape.\n\nAko ovaj panel prikazuje predstojeću utrku, trebali biste rano provjeriti Pripremu utrke.',
        'overview.lastRace.body': 'Panel Posljednja utrka tima prikazuje posljednju završenu utrku vašeg tima kada je dostupna.\n\nKoristite ga za brz pregled učinka tima. Rezultati vam mogu pomoći odlučiti trebaju li vozači odmor, je li taktika dobro funkcionirala ili je potrebno promijeniti momčad prije sljedećeg događaja.',
        'overview.sponsor.body': 'Panel Glavni sponzor prikazuje informacije o vašem glavnom sponzoru kada imate aktivan ugovor.\n\nSponzori su važni jer mogu donositi novac, bonuse, ciljeve i ponekad utjecati na brendiranje. Neki su ugovori jednostavni, dok sponzori s naming-rights pravima mogu privremeno promijeniti ime vašeg tima tijekom sezone.',
        'overview.progress.body': 'Ostatak stranice Pregled pomaže vam pratiti stanje i napredak tima.\n\nOvdje možete pratiti stanje vozača, financijsko zdravlje, aktivnosti sponzora, aktivnosti na utrkama, aktivne operacije, podatke pregleda sezone i opći napredak kroz sezonu.\n\nNeki napredni dijelovi nadzorne ploče, sažeci ili dodatni prikazi podataka mogu zahtijevati Premium račun ili kupnju Coins. Ako je panel zaključan, i dalje možete normalno igrati, ali Premium ili Coins mogu olakšati igru i dati detaljniji pregled kluba.\n\nKako klub raste, ova stranica postaje sve korisnija jer pomaže povezati kratkoročne zadatke, poput pripreme sljedeće utrke, s dugoročnim ciljevima kao što su izgradnja jače momčadi i poboljšanje plasmana.',
        'squad.riders.body': 'Ovo je stranica Momčad — glavno mjesto na kojem su prikazani vozači vašeg tima.\n\nU općem prikazu možete vidjeti važne informacije o vozaču kao što su godine, država, uloga, ukupna razina, stanje, tržišna vrijednost, plaća, pojedinosti ugovora i međunarodni bodovi.\n\nKoristite ovu stranicu kad god želite razumjeti trenutačnu snagu i strukturu svojeg tima.',
        'squad.details.body': 'Stranica Momčad nudi više načina za pregled vozača.\n\nMožete provjeriti financijske informacije, vještine, formu, razvoj, zdravlje i dostupnost. Vještine se s vremenom mogu poboljšavati, pa vam ova stranica pomaže pratiti razvoj svakog vozača.\n\nKlikom na gumb Prikaz možete otvoriti potpuni profil vozača s detaljnijim informacijama.\n\nNeki napredni alati za vozače, dodatne nadzorne ploče ili praktične funkcije mogu zahtijevati Premium račun ili kupnju Coins.',
        'squad.developing.body': 'Razvojni tim vaš je drugi tim. Može se koristiti za mlade vozače koji još nisu spremni za Prvi tim, ali se i dalje mogu natjecati u dodijeljenim natjecanjima.\n\nRazvojni tim prvo mora biti otključan. Više informacija možete pronaći u Postavkama.\n\nVozači se između Prvog i Razvojnog tima mogu premještati samo tijekom razdoblja za premještanje. Ta se razdoblja otvaraju četiri puta godišnje, a stranica Momčad pokazuje kada je dostupno sljedeće razdoblje.\n\nNeki dodatni alati za upravljanje, prošireni prikazi ili praktične funkcije povezane s ovim dijelom mogu zahtijevati Premium račun ili kupnju Coins.',
        'training.regular.body': 'Ovo je stranica Trening.\n\nU Redovnom treningu možete odrediti što vozači treniraju kada nisu raspoređeni na neku drugu aktivnost, kao što su utrka ili trening kamp.\n\nMožete postaviti zadani trening tima za Prvi tim i Razvojni tim, a možete mijenjati trening i za pojedinačne vozače. Svaki vozač može trenirati određeni fokus, kao što su sprint, usponi, ravnica, kronometar, izdržljivost, otpornost, Race IQ, timski rad ili oporavak.\n\nIntenzitet treninga važan je. Teži trening može brže unaprijediti vozače, ali ih može i više umoriti prije sljedećih utrka. Kada je vozaču potreban odmor i smanjenje umora, možete odabrati i Slobodan dan.',
        'equipment.overview.body': 'Ovo je stranica Oprema.\n\nKartica Pregled daje sažetak timske opreme i Race Setup konfiguracija.\n\nZadani Race Setup koristi se kada za određenu utrku ne odaberete poseban setup. Ispod njega možete izraditi različite Race Setup konfiguracije koje poslije možete odabrati u Race Preparation.\n\nSvaki setup može donijeti različite bonuse vozačima, ovisno o opremi koju sadrži i broju dostupnih upotrebljivih jedinica.',
        'equipment.inventory.body': 'Kartica Inventar prikazuje svu opremu koju vaš tim trenutačno posjeduje.\n\nOvdje možete vidjeti predmete kao što su bicikli, kotači, gume i druga kupljena oprema. Možete provjeriti kvalitetu, stanje, vrijednost, bonuse i dostupnost.\n\nAko vam neka oprema više nije potrebna, možete je prodati iz inventara.',
        'equipment.raceSupplies.body': 'Kartica Zalihe za utrku prikazuje potrošne zalihe koje vaš tim može koristiti na utrkama.\n\nNeke zalihe mogu se koristiti samo jednom, dok se druge mogu koristiti više puta. Zalihe mogu pomoći zaštititi vozače od teških uvjeta na utrci.\n\nBez odgovarajućih zaliha vozači mogu pretrpjeti negativne učinke u vrlo toplim, hladnim ili zahtjevnim vremenskim uvjetima.\n\nNakon Opreme, sljedeća preporučena stranica je Infrastruktura.',
        'facilities.assets.body': 'Kartica Sredstva prikazuje vozila i pomoćna sredstva koja vaš tim može koristiti.\n\nTo uključuje timske automobile, autobuse, kombije za opremu, mobilne radionice i medicinske kombije. Ta sredstva mogu podržati tim tijekom utrka, putovanja, pripreme i trening kampova.\n\nSvako sredstvo može imati različite razine, troškove, stanje, bonuse i ograničenja. Otvorite detalje svakog sredstva kako biste razumjeli što donosi i kako može pomoći timu da bude uspješniji.\n\nZa potpuno korištenje ove stranice neke napredne funkcije, opcije upravljanja ili prošireni alati mogu zahtijevati Premium račun ili kupnju Coins.',
        'calendar.welcome.body': 'Možemo vam pokazati kako Kalendar funkcionira, uključujući dnevne aktivnosti tima, mjesece utrka, ciljeve sponzora povezane s utrkama i profile utrka.',
        'calendar.openRace.body': 'Neke utrke mogu imati oznaku cilja sponzora. To znači da je utrka povezana s bonus ciljem sponzora, primjerice sudjelovanjem ili ostvarivanjem određenog rezultata.\n\nKoristite gumb Otvori utrku kada želite vidjeti više detalja o utrci ili se prijaviti.\n\nSljedeće ćemo otvoriti jedan profil utrke kako biste vidjeli koje su informacije tamo dostupne.',
        'raceDetail.stagesResults.body': 'Profil utrke prikazuje i detaljne informacije o etapama.\n\nMožete pregledati profile etapa, karte ruta, raspodjelu terena, vremenske uvjete na etapi, sprint bodove, brdske bodove i druge detalje. Vremenska prognoza objavljuje se tek neposredno prije utrke, pa se može pojaviti kasnije.\n\nNiže na stranici Informacije o utrci prikazuju timove i vozače sudionike prije utrke, a rezultate nakon utrke. Ako vaš tim sudjeluje i utrka je aktivna ili završena, možete koristiti Gledaj utrku ili Gledaj replay kako biste pratili akciju na karti.',
        'racePreparation.racePlan.body': 'Kartica Race Plan mjesto je na kojem pripremate tim za prihvaćenu utrku.\n\nVažno: vrijeme u igri teče brže nego u stvarnom životu. Jedan dan u igri traje 12 sati stvarnog vremena. To znači da dva dana u igri odgovaraju jednom stvarnom danu. Imajte to na umu kada provjeravate razdoblje za Race Plan, rok za prijavu vozača i rokove za Stage Plans.\n\nKada je razdoblje za Race Plan otvoreno, možete odabrati hoće li nastupiti Prvi tim ili Razvojni tim, ako vam je Razvojni tim dostupan.\n\nMorate provjeriti i rok za prijavu vozača. Do tog datuma možete birati vozače koji će sudjelovati. Stranica prikazuje minimalan i maksimalan broj dopuštenih vozača za utrku.\n\nPopis vozača pokazuje tko može biti odabran, a tko je blokiran jer je već raspoređen na drugu utrku koja se vremenski preklapa. Također možete dodijeliti osoblje i timska sredstva za utrku ako su dostupni.\n\nPregled troškova ažurira se dok izrađujete plan, tako da možete vidjeti koliko će utrka koštati. S desne strane pregled bonusa prikazuje moguće bonuse podrške od osoblja, sredstava, opreme i timskih politika.',
        'racePreparation.stagePlans.body': 'Kartica Stage Plans otvara se nakon što je Race Plan predan.\n\nOvdje pripremate taktiku za svaku etapu. Za svaku etapu možete definirati uloge vozača, opremu, zalihe, timsku taktiku i individualnu taktiku.\n\nStage Plans važni su jer različite etape zahtijevaju različite planove. Ravna sprinterska etapa, planinska etapa, kronometar ili valovita etapa mogu zahtijevati različite vozače, taktiku i podršku.\n\nNakon Pripreme utrke, sljedeća preporučena stranica je Rangiranje timova.',
        'teamRanking.competitions.body': 'Ovo je stranica Rangiranje timova.\n\nOvdje možete vidjeti poretke svih natjecanja i razina, uključujući WorldTeam, ProTeam, Continental i Amateur divizije.\n\nSvaki tim ima mjesto u svojem natjecanju na temelju međunarodnih bodova osvojenih tijekom sezone. Možete prelaziti između razina i divizija kako biste vidjeli kako su timovi rangirani u cijelom biciklističkom svijetu.',
        'statistics.welcome.body': 'Možemo vam pokazati kako funkcioniraju statistike timova i vozača, uključujući poretke trenutačne sezone, povijesne rezultate, bodove vozača, postolja i dresove.',
        'statistics.riders.body': 'Odjeljak Vozači prikazuje najbolje vozače u biciklističkom svijetu.\n\nMožete uspoređivati vozače prema međunarodnim bodovima, bodovima za plasmane na etapama, bodovima za generalni plasman i jednodnevne utrke. Možete vidjeti i vozače s najviše postolja i najviše dresova.\n\nOva stranica pomaže vam razumjeti koji vozači dominiraju sezonom i koje bi vozače moglo biti zanimljivo pratiti, skautirati ili potpisati.\n\nNakon Statistike, sljedeća preporučena stranica su Transferi.',
        'transfers.riderTransferList.body': 'Ovo je stranica Transferi.\n\nU odjeljku Vozači, Transfer lista prikazuje vozače koje su drugi timovi, uključujući AI timove, trenutačno stavili na transfer listu.\n\nPrije skautiranja neke informacije o vozaču mogu biti skrivene ili manje precizne. Skauting vam daje bolje informacije o njegovim vještinama i potencijalu.\n\nSvaka transfer ponuda prikazuje koliko dugo vrijedi i početnu cijenu za pregovore. Ako kliknete na Pošalji ponudu, možete ponuditi novac timu koji prodaje vozača. Ako tim prihvati, zatim pregovarate o ugovoru s vozačem.',
        'transfers.staff.body': 'Kartica Osoblje prikazuje dostupne članove osoblja bez ugovora.\n\nOvdje možete pregledati vještine osoblja, ulogu, plaću, specijalizaciju i dostupnost. Mogu se zaposliti samo članovi osoblja koji su slobodni.\n\nOgraničenja osoblja važna su. Ako je klub već dosegnuo maksimalan broj za određenu ulogu, ne možete zaposliti još jednu osobu za tu ulogu dok ne povećate limit, obično nadogradnjom infrastrukture.\n\nNakon Transfera, sljedeća preporučena stranica su Financije.',
        'transfers.staff.primary': 'Nastavi na Financije',
        'finance.welcome.title': 'Trebate pomoć s Financijama?',
        'finance.welcome.body': 'Možemo vam pokazati kako funkcioniraju financije kluba, uključujući stanje računa, sponzore, transakcije, poreze i timske politike.',
        'finance.overview.title': 'Pregled financija',
        'finance.overview.body': 'Ovo je stranica Financije.\n\nKartica Pregled prikazuje glavnu financijsku situaciju kluba, uključujući trenutačno stanje, prihode, rashode, novčani tok i financijske sažetke.\n\nAko vaš tim ima hitan dug ili financijske probleme, ovdje možete brzo razumjeti trenutačno stanje.',
        'finance.transactions.body': 'Kartica Transakcije prikazuje financijsku povijest vašeg kluba.\n\nOvdje možete vidjeti prihode i rashode tijekom sezone, uključujući nagradni novac, uplate sponzora, plaće, transfere, troškove infrastrukture, kupnju opreme, trening kampove, naplatu poreza i druga financijska kretanja.',
        'finance.tax.body': 'Kartica Porez prikazuje poreznu situaciju vašeg kluba.\n\nTransakcije mogu stvarati porezne obveze, a porezna kontrola obavlja se jednom mjesečno. Ova stranica pomaže vam vidjeti koliko je poreza obračunato, koliko je već plaćeno i koliko još treba platiti.',
        'finance.policies.body': 'Timske politike i operacije određuju kako se vaš klub vodi.\n\nPromjena politika može učiniti klub privlačnijim vozačima i osoblju, ali može povećati i troškove putovanja, podrške na utrkama, trening kampova i svakodnevnih operacija.\n\nOvaj odjeljak pomaže vam pronaći ravnotežu između udobnosti, učinka, privlačnosti i troškova.\n\nNakon Financija, sljedeći dio vodiča objasnit će glavni Meni.',
        'menu.notifications.body': 'Ova ikona zvona otvara obavijesti u igri.\n\nObavijesti vas informiraju o važnim događajima kao što su rokovi za utrke, podsjetnici za pripremu, novosti sponzora, financije, transferi i druge radnje u igri koje zahtijevaju vašu pažnju.\n\nKoje obavijesti želite primati možete postaviti kroz opciju Postavke u Meniju.',
        'menu.coins.body': 'Ovdje vidite trenutačno stanje Coins.\n\nCoins se koriste za određene funkcije igre, otključavanja i dodatne praktične opcije u ProPeloton Manageru.\n\nStanje možete provjeriti ovdje u bilo kojem trenutku, a dodatne Coins možete kupiti kroz Meni → Pro paketi.\n\nMalo Coins neće suspendirati vaš račun. Možete nastaviti igrati, ali neke opcionalne funkcije ili radnje slične Premium funkcijama možda neće biti dostupne dok ne dodate još Coins.',
    },
}


def set_path(data: dict, dotted: str, value: str) -> None:
    node = data
    parts = dotted.split('.')
    for part in parts[:-1]:
        node = node[part]
    if parts[-1] not in node:
        raise KeyError(f'Missing key {dotted}')
    node[parts[-1]] = value

count = 0
for filename, patch in PATCHES.items():
    path = ROOT / filename
    data = json.loads(path.read_text(encoding='utf-8'))
    for dotted, value in patch.items():
        set_path(data, dotted, value)
        count += 1
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
    print(f'{filename}: polished {len(patch)} strings')
print(f'Croatian public/tutorial polish prepared: {count} strings.')
