from __future__ import annotations

import json
from pathlib import Path

PATH = Path('src/i18n/locales/de/staff.json')

def set_path(data, path, value):
    node = data
    parts = path.split('.')
    for part in parts[:-1]:
        node = node[part]
    node[parts[-1]] = value

PATCHES = {
    'page.title': 'Teampersonal',
    'page.subtitle': 'Verwalten Sie verschiedene Personalrollen über eigene Rollen-Tabs und separate Mitarbeiterlisten.',
    'page.loading': 'Personal wird geladen...',
    'page.explainPositions': 'Alle Personalpositionen erklären',
    'summary.weeklyWages': 'Wöchentliche Personalkosten',
    'summary.weeklyWagesSubtext': 'Aktuelle gesamte Gehaltssumme',
    'summary.openSlots': 'Freie Personalplätze',
    'summary.openSlotsSubtext': 'Aktuell freie Plätze über alle Personalrollen hinweg',
    'summary.totalCapacity': 'Gesamte Personalkapazität',
    'summary.totalCapacitySubtext': 'Aktuelle Rollenlimits aus dem Backend',
    'summary.warnings': 'Warnungen',
    'summary.warningsSubtext': 'Die Einrichtungsstufe kann einige Boni begrenzen',
    'rolesSection.title': 'Personalrollen',
    'rolesSection.subtitle': 'Wählen Sie eine Rolle aus, um zugewiesene Mitarbeiter, das aktuelle Rollenlimit und eine Zusammenfassung ihres Beitrags zu sehen.',
    'rolesSection.staffList': 'Mitarbeiterliste: {{role}}',
    'rolesSection.assigned': '{{count}}/{{limit}} für diese Rolle zugewiesen.',
    'rolesSection.assignedCompact': 'Zugewiesen {{count}}/{{limit}}',
    'rolesSection.noAssigned': 'Kein {{role}} zugewiesen',
    'rolesSection.usage': 'Aktuelle Belegung dieser Rolle: {{count}}/{{limit}}. Verpflichten Sie Personal über den Personalmarkt, um diese Rolle zu besetzen.',
    'rolesSection.findStaff': 'Personal suchen',
    'roles.headCoach.label': 'Cheftrainer',
    'roles.headCoach.subtitle': 'Leitet Coaching, Trainingsplanung und langfristige Fahrerentwicklung.',
    'roles.trainer.label': 'Trainer',
    'roles.trainer.subtitle': 'Verbessert die tägliche Trainingsleistung und unterstützt die Pläne des Cheftrainers.',
    'roles.teamDoctor.label': 'Teamarzt',
    'roles.teamDoctor.subtitle': 'Leitet medizinische Erholung, Diagnose und Verletzungsprävention.',
    'roles.physio.label': 'Physiotherapeut',
    'roles.physio.subtitle': 'Konzentriert sich auf Rehabilitation, Erholungsgeschwindigkeit und die Rückkehr zur vollen Fitness.',
    'roles.nutritionist.label': 'Ernährungsberater',
    'roles.nutritionist.subtitle': 'Unterstützt Erholung, konstante Fitness und die Arbeit des medizinischen Personals.',
    'roles.mechanic.label': 'Mechaniker',
    'roles.mechanic.subtitle': 'Fahrrad-Setup, effiziente Wartung und mechanische Zuverlässigkeit am Renntag.',
    'roles.sportDirector.label': 'Sportdirektor',
    'roles.sportDirector.subtitle': 'Plant Renntaktik, Moral, Teamarbeit und Helferunterstützung.',
    'roles.scoutAnalyst.label': 'Scout / Analyst',
    'roles.scoutAnalyst.subtitle': 'Scouting-Qualität, Sichtbarkeit von Talenten und Transferinformationen.',
    'roles.u23HeadCoach.label': 'U23-Cheftrainer',
    'roles.u23HeadCoach.subtitle': 'Plant Training des Entwicklungsteams und taktische Unterstützung bei U23-Rennen.',
    'impactAreas.regularTraining': 'Reguläres Training',
    'impactAreas.trainingCamps': 'Trainingslager',
    'impactAreas.riderDevelopment': 'Fahrerentwicklung',
    'impactAreas.dailyTraining': 'Tägliches Training',
    'impactAreas.trainingQuality': 'Trainingsqualität',
    'impactAreas.recoverySpeed': 'Erholungsgeschwindigkeit',
    'impactAreas.injuryPrevention': 'Verletzungsprävention',
    'impactAreas.medicalCaseHandling': 'Behandlung medizinischer Fälle',
    'impactAreas.returnToFitness': 'Rückkehr zur Fitness',
    'impactAreas.fatigueRecovery': 'Erholung von Ermüdung',
    'impactAreas.recoverySupport': 'Erholungsunterstützung',
    'impactAreas.fitnessConsistency': 'Konstante Fitness',
    'impactAreas.racePreparation': 'Rennvorbereitung',
    'impactAreas.equipmentSetup': 'Ausrüstungs-Setup',
    'impactAreas.maintenanceEfficiency': 'Wartungseffizienz',
    'impactAreas.mechanicalReliability': 'Mechanische Zuverlässigkeit',
    'impactAreas.raceTactics': 'Renntaktik',
    'impactAreas.teamMorale': 'Teammoral',
    'impactAreas.domestiqueSupport': 'Helferunterstützung',
    'impactAreas.scoutingAccuracy': 'Scouting-Genauigkeit',
    'impactAreas.prospectDiscovery': 'Talentsuche',
    'impactAreas.transferIntelligence': 'Transferinformationen',
    'impactAreas.u23Training': 'U23-Training',
    'impactAreas.youthDevelopment': 'Nachwuchsentwicklung',
    'impactAreas.u23RaceTactics': 'U23-Renntaktik',
    'common.close': 'Schließen',
    'common.cancel': 'Abbrechen',
    'common.unknown': 'Unbekannt',
    'common.age': 'Alter',
    'common.ageUnknown': 'Alter unbekannt',
    'common.ageYears': '{{age}} Jahre',
    'common.born': 'Geboren: {{date}}',
    'common.scope': 'Bereich: {{scope}}',
    'common.firstTeam': 'erste Mannschaft',
    'common.u23': 'U23',
    'common.all': 'alle',
    'common.weeklyWage': 'Wochengehalt',
    'common.contract': 'Vertrag',
    'common.currentAssignment': 'Aktuelle Zuweisung',
    'common.activeEffects': 'Aktive Effekte',
    'common.staffAttributes': 'Personalwerte',
    'common.focus': 'Schwerpunkt: {{value}}',
    'common.duration': 'Dauer: {{count}} Tage',
    'common.cost': 'Kosten: {{value}}',
    'common.completed': 'Abgeschlossen: {{date}}',
    'assignment.notAssigned': 'Derzeit nicht zugewiesen',
    'assignment.expiresToday': 'Läuft heute aus',
    'assignment.oneDayLeft': 'Noch 1 Tag',
    'assignment.daysLeft': 'Noch {{count}} Tage',
    'assignment.openProfile': 'Mitarbeiterprofil öffnen',
    'attributes.training': 'Training',
    'attributes.recoveryPlanning': 'Erholungsplanung',
    'attributes.youthDevelopment': 'Nachwuchsentwicklung',
    'attributes.experience': 'Erfahrung',
    'attributes.leadership': 'Führungsstärke',
    'attributes.loyalty': 'Loyalität',
    'attributes.dailyTraining': 'Tägliches Training',
    'attributes.trainingEfficiency': 'Trainingseffizienz',
    'attributes.potentialGrowth': 'Potenzialentwicklung',
    'attributes.recovery': 'Erholung',
    'attributes.prevention': 'Prävention',
    'attributes.diagnosis': 'Diagnose',
    'attributes.rehabilitation': 'Rehabilitation',
    'attributes.recoverySpeed': 'Erholungsgeschwindigkeit',
    'attributes.nutrition': 'Ernährung',
    'attributes.consistency': 'Konstanz',
    'attributes.bikeSetup': 'Fahrrad-Setup',
    'attributes.reliability': 'Zuverlässigkeit',
    'attributes.racePlanning': 'Rennplanung',
    'attributes.teamControl': 'Teamkontrolle',
    'attributes.evaluation': 'Bewertung',
    'attributes.network': 'Netzwerk',
    'attributes.accuracy': 'Genauigkeit',
    'premium.analysisTitle': 'Premium-Personalanalyse',
    'premium.analysisDescription': 'Sehen Sie den kombinierten Einfluss des Personals, durchschnittliche Fähigkeitsprofile und Ergebnisse abgeschlossener Kurse.',
    'premium.detailDescription': 'Sehen Sie berechnete Coaching-Qualität, Infrastrukturgrenzen, Personalvergleiche und empfohlene Entwicklungspfade.',
    'premium.loading': 'Premium-Zugang wird geladen',
    'analysis.averageSkillProfile': 'Durchschnittliches Fähigkeitsprofil',
    'analysis.averageSkillProfileSubtitle': 'Durchschnittswerte der aktuell dieser Einflussgruppe zugewiesenen Mitarbeiter.',
    'analysis.noStaff': 'Dieser Einflussgruppe ist noch kein Personal zugewiesen, daher gibt es noch kein aktives Fähigkeitsprofil.',
    'analysis.whereRoleHelps': 'Wo diese Rolle hilft',
    'analysis.whereRoleHelpsSubtitle': 'Die wichtigsten Spielsysteme, die von dieser Rolle beeinflusst werden.',
    'analysis.recentCourseResults': 'Letzte Kursergebnisse',
    'analysis.recentCourseResultsSubtitle': 'Abgeschlossene Weiterbildungskurse und angewendete Attributsverbesserungen.',
    'quality.facility': 'Einrichtung',
    'quality.scoutingQuality': 'Scouting-Qualität',
    'quality.scoutAbility': 'Scout-Fähigkeit',
    'quality.currentReportQuality': 'Aktuelle Berichtsqualität',
    'quality.reportTime': 'Berichtsdauer',
    'quality.scoutingOffice': 'Scouting-Büro',
    'quality.coachingQuality': 'Coaching-Qualität',
    'quality.coachAbility': 'Trainerfähigkeit',
    'quality.trainingQuality': 'Trainingsqualität',
    'quality.developmentSupport': 'Entwicklungsunterstützung',
    'quality.trainerAbility': 'Trainerfähigkeit',
    'quality.sessionQuality': 'Einheitenqualität',
    'quality.loadManagement': 'Belastungssteuerung',
    'quality.medicalQuality': 'Medizinische Qualität',
    'quality.medicalAbility': 'Medizinische Fähigkeit',
    'quality.injuryPrevention': 'Verletzungsprävention',
    'quality.returnToFitness': 'Rückkehr zur Fitness',
    'quality.recoveryQuality': 'Erholungsqualität',
    'quality.recoveryAbility': 'Erholungsfähigkeit',
    'quality.rehabilitationQuality': 'Rehabilitationsqualität',
    'quality.recoverySpeed': 'Erholungsgeschwindigkeit',
    'quality.nutritionQuality': 'Ernährungsqualität',
    'quality.nutritionAbility': 'Ernährungsfähigkeit',
    'quality.recoverySupport': 'Erholungsunterstützung',
    'quality.consistencySupport': 'Unterstützung der Konstanz',
    'quality.technicalQuality': 'Technische Qualität',
    'quality.technicalAbility': 'Technische Fähigkeit',
    'quality.bikeSetupQuality': 'Qualität des Fahrrad-Setups',
    'quality.reliabilitySupport': 'Unterstützung der Zuverlässigkeit',
    'quality.tacticalQuality': 'Taktische Qualität',
    'quality.directorAbility': 'Fähigkeit des Sportdirektors',
    'quality.racePlanQuality': 'Race Plan-Qualität',
    'quality.teamControl': 'Teamkontrolle',
    'quality.raceEngineRole': 'Rolle in der Race Engine',
    'quality.prepared': 'Vorbereitet',
    'quality.youthCoachingQuality': 'Qualität des Nachwuchscoachings',
    'quality.youthCoachAbility': 'Fähigkeit des Nachwuchstrainers',
    'quality.talentDevelopment': 'Talententwicklung',
    'quality.raceReadiness': 'Rennbereitschaft',
    'detail.currentCourse': 'Aktueller Kurs',
    'detail.courseInProgress': 'Kurs läuft: {{course}}. Abschluss: {{date}}.',
    'detail.courseCannotCancel': 'Dieser Kurs kann nach der Buchung nicht mehr abgebrochen werden. Personalboni dieser Rolle sind bis zum Abschluss pausiert.',
    'detail.lastCourseGains': 'Verbesserungen aus dem letzten Kurs',
    'detail.extendContract': 'Vertrag verlängern',
    'detail.courseInProgressButton': 'Kurs läuft',
    'detail.sendOnCourse': 'Zum Kurs schicken',
    'detail.release': 'Freistellen',
    'detail.scoutingReports': 'Scouting-Berichte',
    'release.title': 'Mitarbeiter freistellen',
    'release.subtitle': 'Bestätigen Sie diese Personalentscheidung, bevor Sie fortfahren.',
    'release.aboutToRelease': 'Sie sind dabei, {{name}} freizustellen',
    'release.role': 'Rolle: {{role}}',
    'release.weeklyWage': 'Wochengehalt: {{value}}',
    'release.age': 'Alter: {{value}}',
    'release.compensation': 'Abfindung (6 Wochen): {{value}}',
    'release.warning': 'Der Mitarbeiter wird sofort aus dem Personal entfernt. Die Boni dieses Platzes entfallen, bis Sie einen Ersatz verpflichten.',
    'release.payment': 'Der Club zahlt einmalig eine Abfindung in Höhe von 6 Wochengehältern.',
    'release.releasing': 'Wird freigestellt...',
    'release.confirm': 'Freistellung bestätigen',
    'contract.title': 'Vertrag verlängern',
    'contract.subtitle': 'Verhandeln Sie einen neuen Personalvertrag für {{name}}.',
    'contract.currentSalary': 'Aktuelles Gehalt',
    'contract.currentContract': 'Aktueller Vertrag',
    'contract.extensionLength': 'Vertragsverlängerung',
    'contract.oneSeason': '1 Saison',
    'contract.twoSeasons': '2 Saisons',
    'contract.loadingQuote': 'Vertragsangebot wird geladen...',
    'contract.requestedSalary': 'Gefordertes Gehalt',
    'contract.raiseRequest': 'Geforderte Erhöhung: {{value}} %',
    'contract.minimumAcceptable': 'Mindestens akzeptabel',
    'contract.newContractTarget': 'Ziel des neuen Vertrags',
    'contract.staffInterest': 'Interesse des Mitarbeiters',
    'contract.interestUnknown': 'Interesse unbekannt',
    'contract.chanceRenew': 'Chance auf Verlängerung',
    'contract.chanceUnknown': 'Chance unbekannt',
    'contract.veryLikely': 'Annahme sehr wahrscheinlich',
    'contract.possible': 'Möglich, könnte aber mehr verlangen',
    'contract.unlikely': 'Bei diesem Gehalt unwahrscheinlich',
    'contract.veryUnlikely': 'Sehr unwahrscheinlich',
    'contract.noQuote': 'Kein Angebot verfügbar.',
    'contract.salaryOffer': 'Ihr Gehaltsangebot',
    'contract.salaryPlaceholder': 'Wochengehalt eingeben',
    'contract.submitting': 'Wird gesendet...',
    'contract.submit': 'Angebot senden',
    'contract.extended': 'Personalvertrag erfolgreich verlängert.',
    'contract.discussionCompleted': 'Vertragsverhandlung abgeschlossen.',
    'course.title': 'Personalkurs',
    'course.subtitle': 'Planen Sie die Weiterbildung für {{name}}.',
    'course.liveStart': 'Kurs tatsächlich starten',
    'course.liveStartText': 'Beim Start eines Kurses wird ein echter Personalkurs angelegt. Attributsverbesserungen werden angewendet, wenn der Backend-Prozess den Kurs abschließt. Gebuchte Kurse können nicht abgebrochen werden. Personalboni dieser Rolle sind bis zum Kursabschluss pausiert.',
    'course.staffAge': 'Alter des Mitarbeiters',
    'course.start': 'Kurs starten',
    'course.starting': 'Wird gestartet...',
    'course.none': 'Für diese Personalrolle sind noch keine Kursoptionen konfiguriert. Dadurch wird verhindert, dass ein falscher Kurstyp gestartet wird, bevor die entsprechenden Backend-Kurscodes für diese Rolle hinzugefügt wurden.',
    'course.back': 'Zurück zum Personal',
    'information.title': 'Personalpositionen erklärt',
    'information.subtitle': 'Aufgaben, wichtige Attribute und aktuelle Spielanbindung jeder Personalrolle.',
    'information.close': 'Informationen zu Personalpositionen schließen',
    'information.importantAttributes': 'Wichtige Attribute',
    'information.gameplayConnection': 'Anbindung ans Gameplay',
    'information.live': 'Aktiv',
    'information.coreLive': 'Kernfunktion aktiv',
    'information.trainingLive': 'Training aktiv',
    'information.plannedConnection': 'Geplante Anbindung',
    'impactI18n.assigned': 'Zugewiesen',
    'impactI18n.openSlotAvailable': 'Freier Platz verfügbar',
    'impactI18n.currentBasicCapReached': 'Aktuelle Basisgrenze erreicht',
    'impactI18n.forGroup': 'Für diese Einflussgruppe',
    'impactI18n.activeCourses': 'Aktive Kurse',
    'impactI18n.coursesPaused': 'Boni sind teilweise pausiert, solange Mitarbeiter einen Kurs besuchen',
    'impactI18n.fillVacancies': 'Verwenden Sie Transfers → Personal, um freie Stellen zu besetzen',
    'impactI18n.combinedTitle': 'Kombinierter Teameinfluss',
    'impactI18n.combinedMedical': 'Kombinierte medizinische Unterstützung durch Teamarzt, Physiotherapeut und Ernährungsberater.',
    'impactI18n.combinedCoach': 'Vom Backend angewendeter Coaching-Effekt von {{name}}.',
    'impactI18n.combinedCurrent': 'Aktueller kombinierter Einfluss des aktiven Personals in dieser Gruppe.',
    'impactI18n.coachingTitle': 'Kombinierter Einfluss des Trainerpersonals',
    'impactI18n.medicalTitle': 'Kombinierter Einfluss des medizinischen Personals',
    'impactI18n.mechanicTitle': 'Einfluss der Mechaniker',
    'impactI18n.directorTitle': 'Einfluss des Sportdirektors',
    'impactI18n.u23Title': 'Einfluss des U23-Trainerpersonals',
    'impactI18n.scoutingTitle': 'Einfluss des Scouting-Personals',
    'scoutingExplainer.title': 'So funktioniert Scout-Qualität',
    'scoutingExplainer.body': 'Die Attribute eines Scouts bestimmen seine tatsächliche Fähigkeit. Das Scouting-Büro kann die endgültige Berichtsqualität begrenzen. Daher kann selbst ein starker Scout nur Basisberichte erstellen, solange das Büro nicht ausgebaut wurde.',
    'scoutingExplainer.abilityLevels': 'Stufen der Scout-Fähigkeit',
    'scoutingExplainer.reportLevels': 'Stufen der Berichtsqualität',
    'scoutingExplainer.levelScale': 'Basis → Solide → Stark → Elite',
    'scoutingExplainer.thresholds': 'Grenzwerte der Scout-Fähigkeit',
    'scoutingExplainer.thresholdValues': 'Basis: unter 55 · Solide: 55–69 · Stark: 70–84 · Elite: 85+',
    'scoutingExplainer.upgrade': 'Ein besseres Scouting-Büro ermöglicht eine höhere Berichtsqualität. Aktuelle Stufe: Lv {{level}}.',
    'scoutingExplainer.upgradeNoLevel': 'Ein besseres Scouting-Büro ermöglicht eine höhere Berichtsqualität.',
    'scoutingExplainer.limited': 'Begrenzt durch Scouting-Büro Lv {{level}}.',
    'scoutingExplainer.basicWithScore': 'Basis ({{score}})',
    'scoutingExplainer.solidWithScore': 'Solide ({{score}})',
    'scoutingExplainer.strongWithScore': 'Stark ({{score}})',
    'scoutingExplainer.eliteWithScore': 'Elite ({{score}})',
    'effectText.scoutingAccuracy': '+{{value}} % Scouting-Genauigkeit',
    'effectText.prospectVisibility': '+{{value}} % Talentsichtbarkeit',
    'effectText.combinedScoutingAccuracy': '+{{value}} % kombinierte Scouting-Genauigkeit',
    'effectText.combinedProspectVisibility': '+{{value}} % kombinierte Talentsichtbarkeit',
    'effectText.futureTransferYouth': 'Zukünftig: Transferinformationen und Nachwuchsberichte',
    'effectText.futureBroaderTransferYouth': 'Zukünftig: umfassendere Transfer- und Nachwuchsinformationen',
    'effectText.scoutingOfficeCap': 'Scouting-Büro Lv {{level}} begrenzt einen Teil der Scout- und Analystenboni.'
}

data = json.loads(PATH.read_text(encoding='utf-8'))
for key, value in PATCHES.items():
    set_path(data, key, value)
PATH.write_text(json.dumps(data, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
print(f'Applied {len(PATCHES)} German Staff core translations.')
