create table if not exists public.rider_fatigue_reconciliation_audit_v1 (
  id bigint generated by default as identity primary key,
  run_key text not null,
  rider_id uuid not null references public.riders(id) on delete cascade,
  game_date date not null,
  before_fatigue integer not null,
  rebuilt_fatigue integer not null,
  fatigue_delta integer not null,
  previous_fatigue_updated_on date,
  rebuilt_fatigue_updated_on date not null,
  previous_consecutive_heavy_days integer,
  rebuilt_consecutive_heavy_days integer not null,
  reason text not null,
  created_at timestamptz not null default clock_timestamp(),
  unique (run_key, rider_id)
);

comment on table public.rider_fatigue_reconciliation_audit_v1 is
'One-time or maintenance audit snapshots for deterministic rider-fatigue reconciliation after game-clock/day-processing gaps.';

alter table public.rider_fatigue_reconciliation_audit_v1 enable row level security;
