import { TEAM_TIERS, TeamRankingRecord } from '../constants/teamRanking'
import { applySeasonReset, getSeasonMovements } from './teamRanking.utils'

const now = new Date().toISOString()

const demoTeams: TeamRankingRecord[] = [
  {
    id: 'w1',
    name: 'World One',
    country: 'FR',
    tier: TEAM_TIERS.WORLD,
    amateurDivision: null,
    seasonPoints: 1000,
    overallRank: null,
    tierRank: null,
    divisionRank: null,
    createdAt: now,
  },
  {
    id: 'w2',
    name: 'World Two',
    country: 'GB',
    tier: TEAM_TIERS.WORLD,
    amateurDivision: null,
    seasonPoints: 900,
    overallRank: null,
    tierRank: null,
    divisionRank: null,
    createdAt: now,
  },
  {
    id: 'p1',
    name: 'Pro One',
    country: 'HR',
    tier: TEAM_TIERS.PRO,
    amateurDivision: null,
    seasonPoints: 950,
    overallRank: null,
    tierRank: null,
    divisionRank: null,
    createdAt: now,
  },
  {
    id: 'p2',
    name: 'Pro Two',
    country: 'IT',
    tier: TEAM_TIERS.PRO,
    amateurDivision: null,
    seasonPoints: 870,
    overallRank: null,
    tierRank: null,
    divisionRank: null,
    createdAt: now,
  },
  {
    id: 'c1',
    name: 'Cont One',
    country: 'ES',
    tier: TEAM_TIERS.CONTINENTAL,
    amateurDivision: null,
    seasonPoints: 800,
    overallRank: null,
    tierRank: null,
    divisionRank: null,
    createdAt: now,
  },
  {
    id: 'c2',
    name: 'Cont Two',
    country: 'DE',
    tier: TEAM_TIERS.CONTINENTAL,
    amateurDivision: null,
    seasonPoints: 700,
    overallRank: null,
    tierRank: null,
    divisionRank: null,
    createdAt: now,
  },
  {
    id: 'a1',
    name: 'Amateur Winner',
    country: 'HR',
    tier: TEAM_TIERS.AMATEUR,
    amateurDivision: 'SOUTHERN_BALKAN_EUROPE',
    seasonPoints: 600,
    overallRank: null,
    tierRank: null,
    divisionRank: null,
    createdAt: now,
  },
  {
    id: 'a2',
    name: 'Amateur Second',
    country: 'SI',
    tier: TEAM_TIERS.AMATEUR,
    amateurDivision: 'SOUTHERN_BALKAN_EUROPE',
    seasonPoints: 590,
    overallRank: null,
    tierRank: null,
    divisionRank: null,
    createdAt: now,
  },
  {
    id: 'a3',
    name: 'Amateur Third',
    country: 'RS',
    tier: TEAM_TIERS.AMATEUR,
    amateurDivision: 'SOUTHERN_BALKAN_EUROPE',
    seasonPoints: 580,
    overallRank: null,
    tierRank: null,
    divisionRank: null,
    createdAt: now,
  },
  {
    id: 'a4',
    name: 'Amateur Fourth',
    country: 'GR',
    tier: TEAM_TIERS.AMATEUR,
    amateurDivision: 'SOUTHERN_BALKAN_EUROPE',
    seasonPoints: 570,
    overallRank: null,
    tierRank: null,
    divisionRank: null,
    createdAt: now,
  },
]

console.log('MOVEMENTS', getSeasonMovements(demoTeams))
console.log('RESET RESULT', applySeasonReset(demoTeams))