-- Restore configuration rows required by business-health checks on fresh databases.
-- These are configuration definitions, not production runtime/history data.
with seed as (
  select *
  from jsonb_to_recordset($seed$
[
  {
    "label": "System health watchdog",
    "category": "Core",
    "is_enabled": true,
    "sort_order": 1,
    "source_ref": "ppm-system-health-watchdog-v1",
    "description": "Synchronizes scheduler history and evaluates business-state health checks.",
    "process_key": "watchdog:system-health",
    "source_kind": "watchdog",
    "user_sensitive": true,
    "incident_severity": "critical",
    "stale_after_minutes": 15,
    "email_alerts_enabled": true,
    "expected_interval_minutes": 5
  },
  {
    "label": "Daily game processing",
    "category": "Core",
    "is_enabled": true,
    "sort_order": 10,
    "source_ref": "run-daily-tick-every-minute",
    "description": "Advances daily gameplay processors, rider state, scouting, finance and automation.",
    "process_key": "cron:run-daily-tick-every-minute",
    "source_kind": "cron",
    "user_sensitive": true,
    "incident_severity": "critical",
    "stale_after_minutes": 8,
    "email_alerts_enabled": true,
    "expected_interval_minutes": 1
  },
  {
    "label": "Due game events",
    "category": "Core",
    "is_enabled": true,
    "sort_order": 20,
    "source_ref": "forward-due-game-events-every-minute",
    "description": "Processes infrastructure and equipment jobs that are due in game time.",
    "process_key": "cron:forward-due-game-events-every-minute",
    "source_kind": "cron",
    "user_sensitive": true,
    "incident_severity": "critical",
    "stale_after_minutes": 10,
    "email_alerts_enabled": true,
    "expected_interval_minutes": 2
  },
  {
    "label": "Forward daily automation",
    "category": "Core",
    "is_enabled": true,
    "sort_order": 30,
    "source_ref": "forward-daily-automation-every-minute",
    "description": "Runs retry-safe forward daily processors after game-time progression.",
    "process_key": "cron:forward-daily-automation-every-minute",
    "source_kind": "cron",
    "user_sensitive": true,
    "incident_severity": "critical",
    "stale_after_minutes": 75,
    "email_alerts_enabled": true,
    "expected_interval_minutes": 30
  },
  {
    "label": "Universal race stage runner",
    "category": "Race Engine",
    "is_enabled": true,
    "sort_order": 40,
    "source_ref": "universal-race-stage-runner-supabase-v1",
    "description": "Claims and runs due race stages through the production TypeScript engine.",
    "process_key": "cron:universal-race-stage-runner-supabase-v1",
    "source_kind": "cron",
    "user_sensitive": true,
    "incident_severity": "critical",
    "stale_after_minutes": 12,
    "email_alerts_enabled": true,
    "expected_interval_minutes": 3
  },
  {
    "label": "Race engine pass 1 resume",
    "category": "Race Engine",
    "is_enabled": true,
    "sort_order": 50,
    "source_ref": "universal-race-stage-pass1-resume-v1",
    "description": "Resumes interrupted first-pass race calculations.",
    "process_key": "cron:universal-race-stage-pass1-resume-v1",
    "source_kind": "cron",
    "user_sensitive": true,
    "incident_severity": "critical",
    "stale_after_minutes": 12,
    "email_alerts_enabled": true,
    "expected_interval_minutes": 3
  },
  {
    "label": "Race engine pass 2 resume",
    "category": "Race Engine",
    "is_enabled": true,
    "sort_order": 60,
    "source_ref": "universal-race-stage-pass2-resume-v2",
    "description": "Resumes interrupted second-pass race calculations.",
    "process_key": "cron:universal-race-stage-pass2-resume-v2",
    "source_kind": "cron",
    "user_sensitive": true,
    "incident_severity": "critical",
    "stale_after_minutes": 12,
    "email_alerts_enabled": true,
    "expected_interval_minutes": 3
  },
  {
    "label": "Race calculation survival",
    "category": "Race Engine",
    "is_enabled": true,
    "sort_order": 70,
    "source_ref": "universal-race-calculation-survival-v1",
    "description": "Recovers stalled or orphaned race calculation runs.",
    "process_key": "cron:universal-race-calculation-survival-v1",
    "source_kind": "cron",
    "user_sensitive": true,
    "incident_severity": "critical",
    "stale_after_minutes": 20,
    "email_alerts_enabled": true,
    "expected_interval_minutes": 5
  },
  {
    "label": "Race fast safety guard",
    "category": "Race Engine",
    "is_enabled": true,
    "sort_order": 72,
    "source_ref": "universal-race-fast-safe-guard-v1",
    "description": "Fast safety guard for stalled or inconsistent production race calculations.",
    "process_key": "cron:universal-race-fast-safe-guard-v1",
    "source_kind": "cron",
    "user_sensitive": true,
    "incident_severity": "critical",
    "stale_after_minutes": 5,
    "email_alerts_enabled": true,
    "expected_interval_minutes": 1
  },
  {
    "label": "Race safe-mode watchdog",
    "category": "Race Engine",
    "is_enabled": true,
    "sort_order": 73,
    "source_ref": "universal-race-safe-mode-watchdog-v1",
    "description": "Continuously detects race-engine conditions requiring safe recovery mode.",
    "process_key": "cron:universal-race-safe-mode-watchdog-v1",
    "source_kind": "cron",
    "user_sensitive": true,
    "incident_severity": "critical",
    "stale_after_minutes": 5,
    "email_alerts_enabled": true,
    "expected_interval_minutes": 1
  },
  {
    "label": "Race safe resume worker",
    "category": "Race Engine",
    "is_enabled": true,
    "sort_order": 74,
    "source_ref": "universal-race-stage-safe-resume-v1",
    "description": "Resumes race calculations through the safe recovery path when required.",
    "process_key": "cron:universal-race-stage-safe-resume-v1",
    "source_kind": "cron",
    "user_sensitive": true,
    "incident_severity": "critical",
    "stale_after_minutes": 5,
    "email_alerts_enabled": true,
    "expected_interval_minutes": 1
  },
  {
    "label": "Race calculation guard",
    "category": "Race Engine",
    "is_enabled": true,
    "sort_order": 80,
    "source_ref": "universal-race-calculation-guard-v1",
    "description": "Guards duplicate and stuck race calculations.",
    "process_key": "cron:universal-race-calculation-guard-v1",
    "source_kind": "cron",
    "user_sensitive": true,
    "incident_severity": "critical",
    "stale_after_minutes": 20,
    "email_alerts_enabled": true,
    "expected_interval_minutes": 5
  },
  {
    "label": "Race release supervisor",
    "category": "Race Engine",
    "is_enabled": true,
    "sort_order": 90,
    "source_ref": "universal-race-release-supervisor-v1",
    "description": "Supervises replay/result release and publication lifecycle.",
    "process_key": "cron:universal-race-release-supervisor-v1",
    "source_kind": "cron",
    "user_sensitive": true,
    "incident_severity": "critical",
    "stale_after_minutes": 10,
    "email_alerts_enabled": true,
    "expected_interval_minutes": 2
  },
  {
    "label": "Race publication retry",
    "category": "Race Engine",
    "is_enabled": true,
    "sort_order": 100,
    "source_ref": "universal-race-publication-retry-v1",
    "description": "Retries incomplete race result/replay publication.",
    "process_key": "cron:universal-race-publication-retry-v1",
    "source_kind": "cron",
    "user_sensitive": true,
    "incident_severity": "critical",
    "stale_after_minutes": 20,
    "email_alerts_enabled": true,
    "expected_interval_minutes": 5
  },
  {
    "label": "Due race-stage watchdog",
    "category": "Race Engine",
    "is_enabled": true,
    "sort_order": 110,
    "source_ref": "race-engine-due-stage-watchdog-v1",
    "description": "Detects due stages that did not enter normal production processing.",
    "process_key": "cron:race-engine-due-stage-watchdog-v1",
    "source_kind": "cron",
    "user_sensitive": true,
    "incident_severity": "critical",
    "stale_after_minutes": 30,
    "email_alerts_enabled": true,
    "expected_interval_minutes": 10
  },
  {
    "label": "Race operations monitor",
    "category": "Race Engine",
    "is_enabled": true,
    "sort_order": 120,
    "source_ref": "race-operations-monitor-v1",
    "description": "Maintains calculation, replay and result-publication health status.",
    "process_key": "cron:race-operations-monitor-v1",
    "source_kind": "cron",
    "user_sensitive": true,
    "incident_severity": "critical",
    "stale_after_minutes": 45,
    "email_alerts_enabled": true,
    "expected_interval_minutes": 15
  },
  {
    "label": "National & World championship runtime",
    "category": "Championship Operations",
    "is_enabled": true,
    "sort_order": 121,
    "source_ref": "national-championship-planner-v1",
    "description": "Schedules National Championships and the World Road Championship, creates event races, processes qualification/final results, honours and World invitations.",
    "process_key": "cron:national-championship-planner-v1",
    "source_kind": "cron",
    "user_sensitive": true,
    "incident_severity": "critical",
    "stale_after_minutes": 45,
    "email_alerts_enabled": true,
    "expected_interval_minutes": 15
  },
  {
    "label": "National Association & World Nations runtime",
    "category": "Championship Operations",
    "is_enabled": true,
    "sort_order": 122,
    "source_ref": "national-association-nations-runtime-v1",
    "description": "Maintains National Association eligibility and elections, National Team call-ups/duty, World Nations scheduling, round draws and host selection.",
    "process_key": "cron:national-association-nations-runtime-v1",
    "source_kind": "cron",
    "user_sensitive": true,
    "incident_severity": "critical",
    "stale_after_minutes": 45,
    "email_alerts_enabled": true,
    "expected_interval_minutes": 15
  },
  {
    "label": "Race result notifications",
    "category": "Messaging",
    "is_enabled": true,
    "sort_order": 130,
    "source_ref": "race-results-summary-notifications-v2",
    "description": "Creates personalized post-race result notifications.",
    "process_key": "cron:race-results-summary-notifications-v2",
    "source_kind": "cron",
    "user_sensitive": true,
    "incident_severity": "high",
    "stale_after_minutes": 15,
    "email_alerts_enabled": true,
    "expected_interval_minutes": 5
  },
  {
    "label": "Due game notifications",
    "category": "Messaging",
    "is_enabled": true,
    "sort_order": 140,
    "source_ref": "ppm_due_game_notifications_scheduler_v1",
    "description": "Creates time-sensitive game notifications.",
    "process_key": "cron:ppm_due_game_notifications_scheduler_v1",
    "source_kind": "cron",
    "user_sensitive": true,
    "incident_severity": "high",
    "stale_after_minutes": 75,
    "email_alerts_enabled": true,
    "expected_interval_minutes": 30
  },
  {
    "label": "Sponsor objectives",
    "category": "Finance",
    "is_enabled": true,
    "sort_order": 150,
    "source_ref": "sponsor-objectives-due-by-game-clock-v1",
    "description": "Evaluates due sponsor objectives and payouts.",
    "process_key": "cron:sponsor-objectives-due-by-game-clock-v1",
    "source_kind": "cron",
    "user_sensitive": true,
    "incident_severity": "high",
    "stale_after_minutes": 30,
    "email_alerts_enabled": true,
    "expected_interval_minutes": 10
  },
  {
    "label": "Rider wages",
    "category": "Finance",
    "is_enabled": true,
    "sort_order": 160,
    "source_ref": "weekly-rider-wages-check",
    "description": "Posts due rider wage expenses.",
    "process_key": "cron:weekly-rider-wages-check",
    "source_kind": "cron",
    "user_sensitive": true,
    "incident_severity": "critical",
    "stale_after_minutes": 900,
    "email_alerts_enabled": true,
    "expected_interval_minutes": 720
  },
  {
    "label": "Staff wages",
    "category": "Finance",
    "is_enabled": true,
    "sort_order": 170,
    "source_ref": "weekly-staff-wages-check",
    "description": "Posts due staff wage expenses.",
    "process_key": "cron:weekly-staff-wages-check",
    "source_kind": "cron",
    "user_sensitive": true,
    "incident_severity": "critical",
    "stale_after_minutes": 900,
    "email_alerts_enabled": true,
    "expected_interval_minutes": 720
  },
  {
    "label": "Finance summaries",
    "category": "Finance",
    "is_enabled": true,
    "sort_order": 180,
    "source_ref": "finance_recompute_weekly_summaries_hourly",
    "description": "Recomputes weekly finance summary values.",
    "process_key": "cron:finance_recompute_weekly_summaries_hourly",
    "source_kind": "cron",
    "user_sensitive": true,
    "incident_severity": "high",
    "stale_after_minutes": 150,
    "email_alerts_enabled": true,
    "expected_interval_minutes": 60
  },
  {
    "label": "Transfer expiry maintenance",
    "category": "Transfers",
    "is_enabled": true,
    "sort_order": 190,
    "source_ref": "expire-rider-transfer-market-every-minute",
    "description": "Expires transfer listings, offers and negotiation state.",
    "process_key": "cron:expire-rider-transfer-market-every-minute",
    "source_kind": "cron",
    "user_sensitive": true,
    "incident_severity": "high",
    "stale_after_minutes": 150,
    "email_alerts_enabled": true,
    "expected_interval_minutes": 60
  },
  {
    "label": "Free-agent maintenance",
    "category": "Transfers",
    "is_enabled": true,
    "sort_order": 200,
    "source_ref": "free-agent-maintenance-unlimited-every-minute",
    "description": "Maintains free-agent lifecycle and availability.",
    "process_key": "cron:free-agent-maintenance-unlimited-every-minute",
    "source_kind": "cron",
    "user_sensitive": true,
    "incident_severity": "high",
    "stale_after_minutes": 45,
    "email_alerts_enabled": true,
    "expected_interval_minutes": 15
  },
  {
    "label": "Equipment maintenance reminders",
    "category": "Equipment",
    "is_enabled": true,
    "sort_order": 205,
    "source_ref": "equipment-maintenance-reminders-v1",
    "description": "Checks Premium maintenance thresholds and creates due equipment reminders.",
    "process_key": "cron:equipment-maintenance-reminders-v1",
    "source_kind": "cron",
    "user_sensitive": true,
    "incident_severity": "high",
    "stale_after_minutes": 90,
    "email_alerts_enabled": true,
    "expected_interval_minutes": 30
  },
  {
    "label": "Equipment auto-restock",
    "category": "Equipment",
    "is_enabled": true,
    "sort_order": 206,
    "source_ref": "equipment-auto-restock-v1",
    "description": "Executes Premium race-supply auto-restock rules in the backend.",
    "process_key": "cron:equipment-auto-restock-v1",
    "source_kind": "cron",
    "user_sensitive": true,
    "incident_severity": "high",
    "stale_after_minutes": 60,
    "email_alerts_enabled": true,
    "expected_interval_minutes": 15
  },
  {
    "label": "Premium manager automation",
    "category": "Premium",
    "is_enabled": true,
    "sort_order": 207,
    "source_ref": "premium-manager-automation-v1",
    "description": "Applies safe Premium training and race-strategy prefills to untouched drafts.",
    "process_key": "cron:premium-manager-automation-v1",
    "source_kind": "cron",
    "user_sensitive": true,
    "incident_severity": "high",
    "stale_after_minutes": 90,
    "email_alerts_enabled": true,
    "expected_interval_minutes": 30
  },
  {
    "label": "Transfer market alerts",
    "category": "Transfers",
    "is_enabled": true,
    "sort_order": 208,
    "source_ref": "transfer-refresh-market-alerts-v1",
    "description": "Refreshes Premium saved-search alerts for transfer riders, free agents and staff.",
    "process_key": "cron:transfer-refresh-market-alerts-v1",
    "source_kind": "cron",
    "user_sensitive": true,
    "incident_severity": "high",
    "stale_after_minutes": 150,
    "email_alerts_enabled": true,
    "expected_interval_minutes": 60
  },
  {
    "label": "Transfer market AI",
    "category": "Transfers",
    "is_enabled": true,
    "sort_order": 210,
    "source_ref": "market-ai-hourly-by-game-clock",
    "description": "Runs AI transfer market behavior.",
    "process_key": "cron:market-ai-hourly-by-game-clock",
    "source_kind": "cron",
    "user_sensitive": false,
    "incident_severity": "warning",
    "stale_after_minutes": 45,
    "email_alerts_enabled": true,
    "expected_interval_minutes": 15
  },
  {
    "label": "Staff market refresh",
    "category": "Staff",
    "is_enabled": true,
    "sort_order": 230,
    "source_ref": "staff-market-daily-refresh",
    "description": "Refreshes staff-market candidate stock and expiries.",
    "process_key": "cron:staff-market-daily-refresh",
    "source_kind": "cron",
    "user_sensitive": true,
    "incident_severity": "high",
    "stale_after_minutes": 1800,
    "email_alerts_enabled": true,
    "expected_interval_minutes": 1440
  },
  {
    "label": "Staff advisory reports",
    "category": "Staff",
    "is_enabled": true,
    "sort_order": 240,
    "source_ref": "staff-advisory-reports-hourly",
    "description": "Generates due staff advisory reports.",
    "process_key": "cron:staff-advisory-reports-hourly",
    "source_kind": "cron",
    "user_sensitive": true,
    "incident_severity": "high",
    "stale_after_minutes": 150,
    "email_alerts_enabled": true,
    "expected_interval_minutes": 60
  },
  {
    "label": "Weather cancellation processing",
    "category": "Races",
    "is_enabled": true,
    "sort_order": 250,
    "source_ref": "weather-cancellations-due-by-game-clock",
    "description": "Processes weather-related race cancellations.",
    "process_key": "cron:weather-cancellations-due-by-game-clock",
    "source_kind": "cron",
    "user_sensitive": true,
    "incident_severity": "high",
    "stale_after_minutes": 45,
    "email_alerts_enabled": true,
    "expected_interval_minutes": 15
  },
  {
    "label": "Race startlist captains",
    "category": "Races",
    "is_enabled": true,
    "sort_order": 260,
    "source_ref": "race-startlist-captains-by-game-clock",
    "description": "Processes due startlist/captain lifecycle actions.",
    "process_key": "cron:race-startlist-captains-by-game-clock",
    "source_kind": "cron",
    "user_sensitive": true,
    "incident_severity": "critical",
    "stale_after_minutes": 45,
    "email_alerts_enabled": true,
    "expected_interval_minutes": 15
  },
  {
    "label": "Competition field sizes",
    "category": "Races",
    "is_enabled": true,
    "sort_order": 270,
    "source_ref": "ensure-competition-sizes-hourly",
    "description": "Keeps competition fields at configured size.",
    "process_key": "cron:ensure-competition-sizes-hourly",
    "source_kind": "cron",
    "user_sensitive": false,
    "incident_severity": "warning",
    "stale_after_minutes": 150,
    "email_alerts_enabled": true,
    "expected_interval_minutes": 60
  },
  {
    "label": "Monthly rider market values",
    "category": "Riders",
    "is_enabled": true,
    "sort_order": 280,
    "source_ref": "refresh-market-values-if-new-game-month",
    "description": "Refreshes rider market values when the game month changes.",
    "process_key": "cron:refresh-market-values-if-new-game-month",
    "source_kind": "cron",
    "user_sensitive": true,
    "incident_severity": "high",
    "stale_after_minutes": 1800,
    "email_alerts_enabled": true,
    "expected_interval_minutes": 1440
  },
  {
    "label": "Team inactivity",
    "category": "Accounts",
    "is_enabled": true,
    "sort_order": 290,
    "source_ref": "process-team-inactivity-daily-0600-utc",
    "description": "Processes inactive human clubs and lifecycle actions.",
    "process_key": "cron:process-team-inactivity-daily-0600-utc",
    "source_kind": "cron",
    "user_sensitive": true,
    "incident_severity": "high",
    "stale_after_minutes": 1800,
    "email_alerts_enabled": true,
    "expected_interval_minutes": 1440
  },
  {
    "label": "Birthday gifts",
    "category": "Accounts",
    "is_enabled": true,
    "sort_order": 300,
    "source_ref": "process-birthday-gifts-daily-1200-utc",
    "description": "Processes real birthday gifts for users.",
    "process_key": "cron:process-birthday-gifts-daily-1200-utc",
    "source_kind": "cron",
    "user_sensitive": true,
    "incident_severity": "warning",
    "stale_after_minutes": 1800,
    "email_alerts_enabled": true,
    "expected_interval_minutes": 1440
  },
  {
    "label": "Cycling world news",
    "category": "Content",
    "is_enabled": true,
    "sort_order": 310,
    "source_ref": "import-cycling-world-news-every-6-hours",
    "description": "Imports current Cycling World News items.",
    "process_key": "cron:import-cycling-world-news-every-6-hours",
    "source_kind": "cron",
    "user_sensitive": false,
    "incident_severity": "warning",
    "stale_after_minutes": 540,
    "email_alerts_enabled": true,
    "expected_interval_minutes": 360
  },
  {
    "label": "Race operations state",
    "category": "Race Engine",
    "is_enabled": true,
    "sort_order": 400,
    "source_ref": null,
    "description": "Detects active race calculation, replay or publication problems.",
    "process_key": "check:race_operations",
    "source_kind": "business_check",
    "user_sensitive": true,
    "incident_severity": "critical",
    "stale_after_minutes": 15,
    "email_alerts_enabled": true,
    "expected_interval_minutes": 5
  },
  {
    "label": "Championship calendar draw",
    "category": "Championship Operations",
    "is_enabled": true,
    "sort_order": 404,
    "source_ref": null,
    "description": "Strict January draw monitor: 15 national draws per game day, World Grand Finale locked immediately, and all schedules locked by the end of January.",
    "process_key": "check:championship_calendar_draw",
    "source_kind": "business_check",
    "user_sensitive": true,
    "incident_severity": "critical",
    "stale_after_minutes": 15,
    "email_alerts_enabled": true,
    "expected_interval_minutes": 5
  },
  {
    "label": "National & World Championship operations",
    "category": "Championship Operations",
    "is_enabled": true,
    "sort_order": 405,
    "source_ref": null,
    "description": "Checks championship scheduling, Race Operations coverage, post-race processing, podium honours and National Champion to World Championship qualification.",
    "process_key": "check:championship_operations",
    "source_kind": "business_check",
    "user_sensitive": true,
    "incident_severity": "critical",
    "stale_after_minutes": 15,
    "email_alerts_enabled": true,
    "expected_interval_minutes": 5
  },
  {
    "label": "National Association & World Nations operations",
    "category": "Championship Operations",
    "is_enabled": true,
    "sort_order": 406,
    "source_ref": null,
    "description": "Validates the World Nations edition, schedules, group draws, overdue events, National Team squads and seven-rider lineups.",
    "process_key": "check:nations_operations",
    "source_kind": "business_check",
    "user_sensitive": true,
    "incident_severity": "critical",
    "stale_after_minutes": 45,
    "email_alerts_enabled": true,
    "expected_interval_minutes": 15
  },
  {
    "label": "Sponsor objective state",
    "category": "Finance",
    "is_enabled": true,
    "sort_order": 410,
    "source_ref": null,
    "description": "Detects sponsor objectives overdue for evaluation.",
    "process_key": "check:sponsor_objectives",
    "source_kind": "business_check",
    "user_sensitive": true,
    "incident_severity": "high",
    "stale_after_minutes": 15,
    "email_alerts_enabled": true,
    "expected_interval_minutes": 5
  },
  {
    "label": "Scouting task completion",
    "category": "Scouting",
    "is_enabled": true,
    "sort_order": 420,
    "source_ref": null,
    "description": "Detects scouting tasks left open after their completion game time.",
    "process_key": "check:scouting_tasks",
    "source_kind": "business_check",
    "user_sensitive": true,
    "incident_severity": "high",
    "stale_after_minutes": 15,
    "email_alerts_enabled": true,
    "expected_interval_minutes": 5
  },
  {
    "label": "Infrastructure jobs",
    "category": "Infrastructure",
    "is_enabled": true,
    "sort_order": 430,
    "source_ref": null,
    "description": "Detects due upgrades or deliveries not completed.",
    "process_key": "check:infrastructure_jobs",
    "source_kind": "business_check",
    "user_sensitive": true,
    "incident_severity": "high",
    "stale_after_minutes": 15,
    "email_alerts_enabled": true,
    "expected_interval_minutes": 5
  },
  {
    "label": "Equipment maintenance",
    "category": "Equipment",
    "is_enabled": true,
    "sort_order": 440,
    "source_ref": null,
    "description": "Detects due maintenance jobs not completed.",
    "process_key": "check:equipment_jobs",
    "source_kind": "business_check",
    "user_sensitive": true,
    "incident_severity": "high",
    "stale_after_minutes": 15,
    "email_alerts_enabled": true,
    "expected_interval_minutes": 5
  },
  {
    "label": "Infrastructure asset repairs",
    "category": "Infrastructure",
    "is_enabled": true,
    "sort_order": 450,
    "source_ref": null,
    "description": "Detects due asset repair jobs not completed.",
    "process_key": "check:asset_repairs",
    "source_kind": "business_check",
    "user_sensitive": true,
    "incident_severity": "high",
    "stale_after_minutes": 15,
    "email_alerts_enabled": true,
    "expected_interval_minutes": 5
  },
  {
    "label": "Staff courses",
    "category": "Staff",
    "is_enabled": true,
    "sort_order": 460,
    "source_ref": null,
    "description": "Detects active staff courses past their completion game date.",
    "process_key": "check:staff_courses",
    "source_kind": "business_check",
    "user_sensitive": true,
    "incident_severity": "high",
    "stale_after_minutes": 15,
    "email_alerts_enabled": true,
    "expected_interval_minutes": 5
  },
  {
    "label": "Transfer negotiations",
    "category": "Transfers",
    "is_enabled": true,
    "sort_order": 470,
    "source_ref": null,
    "description": "Detects open transfer negotiations past their game-date expiry.",
    "process_key": "check:transfer_negotiations",
    "source_kind": "business_check",
    "user_sensitive": true,
    "incident_severity": "high",
    "stale_after_minutes": 15,
    "email_alerts_enabled": true,
    "expected_interval_minutes": 5
  },
  {
    "label": "Game clock sanity",
    "category": "Core",
    "is_enabled": true,
    "sort_order": 480,
    "source_ref": null,
    "description": "Detects invalid game clock configuration or inconsistent state.",
    "process_key": "check:game_clock",
    "source_kind": "business_check",
    "user_sensitive": true,
    "incident_severity": "critical",
    "stale_after_minutes": 15,
    "email_alerts_enabled": true,
    "expected_interval_minutes": 5
  },
  {
    "label": "Administrator alert email",
    "category": "Core",
    "is_enabled": true,
    "sort_order": 490,
    "source_ref": null,
    "description": "Detects system-health alert email jobs repeatedly failing or stuck.",
    "process_key": "check:admin_alert_email",
    "source_kind": "business_check",
    "user_sensitive": true,
    "incident_severity": "critical",
    "stale_after_minutes": 15,
    "email_alerts_enabled": false,
    "expected_interval_minutes": 5
  }
]
$seed$::jsonb) as x(
    process_key text,
    label text,
    category text,
    description text,
    source_kind text,
    source_ref text,
    user_sensitive boolean,
    incident_severity text,
    expected_interval_minutes integer,
    stale_after_minutes integer,
    email_alerts_enabled boolean,
    is_enabled boolean,
    sort_order integer
  )
)
insert into public.system_monitor_processes(
  process_key,label,category,description,source_kind,source_ref,
  user_sensitive,incident_severity,expected_interval_minutes,stale_after_minutes,
  email_alerts_enabled,is_enabled,sort_order
)
select
  process_key,label,category,description,source_kind,source_ref,
  user_sensitive,incident_severity,expected_interval_minutes,stale_after_minutes,
  email_alerts_enabled,is_enabled,sort_order
from seed
on conflict(process_key) do update set
  label=excluded.label,
  category=excluded.category,
  description=excluded.description,
  source_kind=excluded.source_kind,
  source_ref=excluded.source_ref,
  user_sensitive=excluded.user_sensitive,
  incident_severity=excluded.incident_severity,
  expected_interval_minutes=excluded.expected_interval_minutes,
  stale_after_minutes=excluded.stale_after_minutes,
  email_alerts_enabled=excluded.email_alerts_enabled,
  is_enabled=excluded.is_enabled,
  sort_order=excluded.sort_order,
  updated_at=clock_timestamp();
