CREATE TRIGGER trg_st_persist_7f5dea02c66e BEFORE INSERT OR DELETE OR UPDATE ON finance.account_balances FOR EACH ROW EXECUTE FUNCTION block_season_transition_protected_write_v1();
CREATE TRIGGER trg_st_persist_c351551d2bc9 BEFORE INSERT OR DELETE OR UPDATE ON finance.accounts FOR EACH ROW EXECUTE FUNCTION block_season_transition_protected_write_v1();
CREATE TRIGGER trg_club_insolvency_state_set_updated_at BEFORE UPDATE ON finance.club_insolvency_state FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_emergency_loans_set_updated_at BEFORE UPDATE ON finance.emergency_loans FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_st_persist_bda23c6d83a0 BEFORE INSERT OR DELETE OR UPDATE ON finance.emergency_loans FOR EACH ROW EXECUTE FUNCTION block_season_transition_protected_write_v1();
CREATE TRIGGER trg_bump_weekly AFTER INSERT ON finance.entries FOR EACH ROW EXECUTE FUNCTION finance._bump_weekly_from_entry();
CREATE TRIGGER trg_entries_apply_balance AFTER INSERT ON finance.entries FOR EACH ROW EXECUTE FUNCTION finance._apply_entry_to_balance();
CREATE TRIGGER trg_entries_immutable BEFORE DELETE OR UPDATE ON finance.entries FOR EACH ROW EXECUTE FUNCTION finance._immutable_guard();
CREATE TRIGGER trg_st_persist_3220eca2a4b8 BEFORE INSERT OR DELETE OR UPDATE ON finance.entries FOR EACH ROW EXECUTE FUNCTION block_season_transition_protected_write_v1();
CREATE TRIGGER trg_sync_club_balances AFTER INSERT ON finance.entries FOR EACH ROW EXECUTE FUNCTION finance._sync_club_balances_from_entry_ai_safe_v1();
CREATE CONSTRAINT TRIGGER trg_tx_balanced AFTER INSERT ON finance.entries DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION finance._check_tx_balanced();
CREATE TRIGGER trg_st_persist_80efb78d48ba BEFORE INSERT OR DELETE OR UPDATE ON finance.event_locks FOR EACH ROW EXECUTE FUNCTION block_season_transition_protected_write_v1();
CREATE TRIGGER trg_finance_transaction_types_set_updated_at BEFORE UPDATE ON finance.transaction_types FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_finance_club_house_transaction_savings_v1 AFTER INSERT ON finance.transactions FOR EACH ROW EXECUTE FUNCTION finance_apply_club_house_transaction_savings_v1();
CREATE TRIGGER trg_set_transaction_game_date_metadata BEFORE INSERT ON finance.transactions FOR EACH ROW EXECUTE FUNCTION finance.set_transaction_game_date_metadata();
CREATE TRIGGER trg_st_persist_a616ed5766d3 BEFORE INSERT OR DELETE OR UPDATE ON finance.transactions FOR EACH ROW EXECUTE FUNCTION block_season_transition_protected_write_v1();
CREATE TRIGGER trg_transactions_immutable BEFORE DELETE OR UPDATE ON finance.transactions FOR EACH ROW EXECUTE FUNCTION finance._immutable_guard();
CREATE TRIGGER gcc_live_bug_reports AFTER INSERT OR DELETE OR UPDATE ON bug_reports FOR EACH STATEMENT EXECUTE FUNCTION control_center_private.notify_admin_module_snapshot('bug-reports', '2');
CREATE TRIGGER trg_club_equipment_default_setup_set_updated_at BEFORE UPDATE ON club_equipment_default_setup FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_st_persist_830cab585f3d BEFORE INSERT OR DELETE OR UPDATE ON club_equipment_default_setup FOR EACH ROW EXECUTE FUNCTION block_season_transition_protected_write_v1();
CREATE TRIGGER trg_club_equipment_inventory_set_updated_at BEFORE UPDATE ON club_equipment_inventory FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_equipment_ai_inventory_guard BEFORE INSERT OR DELETE OR UPDATE ON club_equipment_inventory FOR EACH ROW EXECUTE FUNCTION equipment_ai_inventory_guard();
CREATE TRIGGER trg_st_persist_74f818d6229e BEFORE INSERT OR DELETE OR UPDATE ON club_equipment_inventory FOR EACH ROW EXECUTE FUNCTION block_season_transition_protected_write_v1();
CREATE TRIGGER trg_club_equipment_maintenance_jobs_set_updated_at BEFORE UPDATE ON club_equipment_maintenance_jobs FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_st_persist_f28f9f3de1e9 BEFORE INSERT OR DELETE OR UPDATE ON club_equipment_maintenance_jobs FOR EACH ROW EXECUTE FUNCTION block_season_transition_protected_write_v1();
CREATE TRIGGER trg_equipment_enforce_setup_slot_access_v1 BEFORE INSERT OR UPDATE ON club_equipment_setup_presets FOR EACH ROW EXECUTE FUNCTION equipment_enforce_setup_slot_access_v1();
CREATE TRIGGER trg_st_persist_7eb52799d013 BEFORE INSERT OR DELETE OR UPDATE ON club_equipment_setup_presets FOR EACH ROW EXECUTE FUNCTION block_season_transition_protected_write_v1();
CREATE TRIGGER trg_notify_equipment_van_asset_state_change AFTER UPDATE ON club_equipment_vans FOR EACH ROW EXECUTE FUNCTION notify_infrastructure_asset_state_change();
CREATE TRIGGER trg_st_persist_b007f333bf32 BEFORE INSERT OR DELETE OR UPDATE ON club_equipment_vans FOR EACH ROW EXECUTE FUNCTION block_season_transition_protected_write_v1();
CREATE TRIGGER trg_club_finance_summary_set_updated_at BEFORE UPDATE ON club_finance_summary FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_guard_club_finance_summary BEFORE UPDATE ON club_finance_summary FOR EACH ROW EXECUTE FUNCTION _guard_club_finance_summary();
CREATE TRIGGER trg_club_infrastructure_set_updated_at BEFORE UPDATE ON club_infrastructure FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_st_persist_6f1ddeca475f BEFORE INSERT OR DELETE OR UPDATE ON club_infrastructure FOR EACH ROW EXECUTE FUNCTION block_season_transition_protected_write_v1();
CREATE TRIGGER trg_club_infrastructure_asset_holdings_set_updated_at BEFORE UPDATE ON club_infrastructure_asset_holdings FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_st_persist_8844ff5a39bc BEFORE INSERT OR DELETE OR UPDATE ON club_infrastructure_asset_holdings FOR EACH ROW EXECUTE FUNCTION block_season_transition_protected_write_v1();
CREATE TRIGGER trg_club_infrastructure_asset_repair_jobs_set_updated_at BEFORE UPDATE ON club_infrastructure_asset_repair_jobs FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_st_persist_a71a5d66cd07 BEFORE INSERT OR DELETE OR UPDATE ON club_infrastructure_asset_repair_jobs FOR EACH ROW EXECUTE FUNCTION block_season_transition_protected_write_v1();
CREATE TRIGGER limit_active_facility_infrastructure_jobs BEFORE INSERT OR UPDATE OF club_id, job_type, status ON club_infrastructure_jobs FOR EACH ROW EXECUTE FUNCTION trg_limit_active_facility_infrastructure_jobs();
CREATE TRIGGER trg_club_infrastructure_jobs_set_updated_at BEFORE UPDATE ON club_infrastructure_jobs FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_create_medical_van_from_completed_delivery AFTER UPDATE OF status ON club_infrastructure_jobs FOR EACH ROW EXECUTE FUNCTION create_medical_van_from_completed_delivery();
CREATE TRIGGER trg_infrastructure_enforce_asset_delivery_capacity_v1 BEFORE INSERT OR UPDATE OF job_type, target_key, status, asset_quantity, club_id ON club_infrastructure_jobs FOR EACH ROW EXECUTE FUNCTION infrastructure_enforce_asset_delivery_capacity_v1();
CREATE TRIGGER trg_notify_infrastructure_asset_delivery_ordered AFTER INSERT ON club_infrastructure_jobs FOR EACH ROW EXECUTE FUNCTION notify_infrastructure_asset_delivery_ordered();
CREATE TRIGGER trg_st_persist_357d0dae82de BEFORE INSERT OR DELETE OR UPDATE ON club_infrastructure_jobs FOR EACH ROW EXECUTE FUNCTION block_season_transition_protected_write_v1();
CREATE TRIGGER trg_notify_medical_van_asset_state_change AFTER INSERT OR UPDATE OF status, condition_percent ON club_medical_vans FOR EACH ROW EXECUTE FUNCTION notify_infrastructure_asset_state_change();
CREATE TRIGGER trg_notify_mobile_workshop_asset_state_change AFTER UPDATE ON club_mobile_workshops FOR EACH ROW EXECUTE FUNCTION notify_infrastructure_asset_state_change();
CREATE TRIGGER trg_club_race_supplies_set_updated_at BEFORE UPDATE ON club_race_supplies FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_st_persist_f6914465cecb BEFORE INSERT OR DELETE OR UPDATE ON club_race_supply_units FOR EACH ROW EXECUTE FUNCTION block_season_transition_protected_write_v1();
CREATE TRIGGER trg_st_persist_53cf9a8b28e0 BEFORE INSERT OR DELETE OR UPDATE ON club_regular_training_automation FOR EACH ROW EXECUTE FUNCTION block_season_transition_protected_write_v1();
CREATE TRIGGER trg_st_persist_6225b7f3a81c BEFORE INSERT OR DELETE OR UPDATE ON club_regular_training_defaults FOR EACH ROW EXECUTE FUNCTION block_season_transition_protected_write_v1();
CREATE TRIGGER trg_club_riders_national_team_country_lock_v1 BEFORE INSERT OR UPDATE OF club_id, rider_id ON club_riders FOR EACH ROW EXECUTE FUNCTION trg_national_team_country_lock_club_rider_pair_v1();
CREATE CONSTRAINT TRIGGER trg_enforce_first_squad_limit AFTER INSERT OR UPDATE OF club_id ON club_riders DEFERRABLE INITIALLY IMMEDIATE FOR EACH ROW EXECUTE FUNCTION enforce_first_squad_limit();
CREATE TRIGGER trg_guard_retired_rider_roster_membership_v1 BEFORE INSERT OR UPDATE ON club_riders FOR EACH ROW EXECUTE FUNCTION guard_retired_rider_roster_membership_v1();
CREATE TRIGGER trg_club_season_identities_set_updated_at BEFORE UPDATE ON club_season_identities FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_club_settings_set_updated_at BEFORE UPDATE ON club_settings FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_club_sponsor_objectives_set_updated_at BEFORE UPDATE ON club_sponsor_objectives FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_notify_main_sponsor_objective_result_v1 AFTER UPDATE OF status, check_state, objective_result_state, current_value, payout_transaction_id, failed_reason, checked_at ON club_sponsor_objectives FOR EACH ROW EXECUTE FUNCTION notify_main_sponsor_objective_result_v1();
CREATE TRIGGER trg_sponsor_objective_completed_state_preserve_guard_v1 BEFORE UPDATE ON club_sponsor_objectives FOR EACH ROW EXECUTE FUNCTION sponsor_objective_completed_state_preserve_guard_v1();
CREATE TRIGGER trg_sponsor_objective_race_start_false_fail_guard_v1 BEFORE UPDATE ON club_sponsor_objectives FOR EACH ROW EXECUTE FUNCTION sponsor_objective_race_start_false_fail_guard_v1();
CREATE TRIGGER trg_club_sponsor_offers_set_updated_at BEFORE UPDATE ON club_sponsor_offers FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_sponsor_keep_test_season_start_preview_offer_v1 BEFORE UPDATE ON club_sponsor_offers FOR EACH ROW EXECUTE FUNCTION sponsor_keep_test_season_start_preview_offer_v1();
CREATE TRIGGER trg_sponsor_offer_visibility_preview_normalizer_v1 BEFORE INSERT OR UPDATE OF status, sponsor_kind, bonus_pool_amount, coverage_months, generated_game_month ON club_sponsor_offers FOR EACH ROW EXECUTE FUNCTION sponsor_offer_visibility_preview_normalizer_v1();
CREATE TRIGGER trg_sponsor_prepare_main_sponsor_objectives_on_offer_accept_v1 AFTER UPDATE OF status ON club_sponsor_offers FOR EACH ROW WHEN (new.sponsor_kind = 'main'::text AND new.status = 'accepted'::text AND old.status IS DISTINCT FROM new.status) EXECUTE FUNCTION sponsor_prepare_main_sponsor_objectives_on_offer_accept_v1();
CREATE TRIGGER trg_sponsor_secondary_offer_balance_guard_v2 BEFORE INSERT OR UPDATE OF sponsor_kind, status, full_season_guaranteed_amount, proration_factor, coverage_months, guaranteed_amount, monthly_amount, bonus_pool_amount, full_season_bonus_pool_amount ON club_sponsor_offers FOR EACH ROW EXECUTE FUNCTION sponsor_secondary_offer_balance_guard_v2();
CREATE TRIGGER trg_sponsor_sync_naming_rights_from_accepted_offer_v1 AFTER UPDATE OF status, main_sponsor_deal_type, metadata ON club_sponsor_offers FOR EACH ROW EXECUTE FUNCTION sponsor_sync_naming_rights_from_accepted_offer_v1();
CREATE TRIGGER trg_zz_sponsor_offer_economic_description_v1 BEFORE INSERT OR UPDATE OF guaranteed_amount, bonus_pool_amount, metadata, sponsor_kind, status ON club_sponsor_offers FOR EACH ROW EXECUTE FUNCTION sponsor_offer_economic_description_v1();
CREATE TRIGGER trg_club_sponsors_set_updated_at BEFORE UPDATE ON club_sponsors FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_sponsor_apply_naming_rights_identity_from_contract_v1 AFTER INSERT OR UPDATE OF main_sponsor_deal_type, metadata, status ON club_sponsors FOR EACH ROW EXECUTE FUNCTION sponsor_apply_naming_rights_identity_from_contract_v1();
CREATE TRIGGER trg_sponsor_sync_signed_offer_preview_objectives_v1 AFTER INSERT OR UPDATE OF status ON club_sponsors FOR EACH ROW EXECUTE FUNCTION trg_sponsor_sync_signed_offer_preview_objectives_v1();
CREATE TRIGGER enforce_staff_role_capacity_on_club_staff BEFORE INSERT OR UPDATE OF club_id, role_type, is_active ON club_staff FOR EACH ROW EXECUTE FUNCTION trg_enforce_staff_role_capacity();
CREATE TRIGGER trg_club_staff_set_updated_at BEFORE UPDATE ON club_staff FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_guard_staff_persistence_during_transition_v1 BEFORE INSERT OR DELETE OR UPDATE ON club_staff FOR EACH ROW EXECUTE FUNCTION guard_staff_persistence_during_transition_v1();
CREATE TRIGGER trg_staff_advisory_after_staff_lifecycle_v1 AFTER INSERT OR DELETE OR UPDATE OF is_active, club_id, role_type ON club_staff FOR EACH ROW EXECUTE FUNCTION staff_advisory_after_staff_lifecycle_v1();
CREATE TRIGGER trg_staff_advisory_before_staff_lifecycle_v1 BEFORE DELETE OR UPDATE OF is_active, club_id, role_type ON club_staff FOR EACH ROW EXECUTE FUNCTION staff_advisory_before_staff_lifecycle_v1();
CREATE TRIGGER trg_sync_staff_identity_fields_club_staff BEFORE INSERT OR UPDATE ON club_staff FOR EACH ROW EXECUTE FUNCTION sync_staff_identity_fields();
CREATE TRIGGER trg_club_team_buses_set_updated_at BEFORE UPDATE ON club_team_buses FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_notify_team_bus_asset_state_change AFTER UPDATE ON club_team_buses FOR EACH ROW EXECUTE FUNCTION notify_infrastructure_asset_state_change();
CREATE TRIGGER trg_club_team_cars_set_updated_at BEFORE UPDATE ON club_team_cars FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_notify_team_car_asset_state_change AFTER UPDATE ON club_team_cars FOR EACH ROW EXECUTE FUNCTION notify_infrastructure_asset_state_change();
CREATE TRIGGER trg_club_team_policies_set_updated_at BEFORE UPDATE ON club_team_policies FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_assign_new_real_club_to_ai_slot AFTER INSERT ON clubs FOR EACH ROW WHEN (new.is_ai = false) EXECUTE FUNCTION trg_assign_new_real_club_to_ai_slot();
CREATE TRIGGER trg_block_locked_club_branding_update_v1 BEFORE UPDATE OF name, primary_color, secondary_color ON clubs FOR EACH ROW EXECUTE FUNCTION block_locked_club_branding_update_v1();
CREATE TRIGGER trg_block_placeholder_ai_main_clubs_v1 BEFORE INSERT OR UPDATE OF name, is_ai, club_type, deleted_at, logo_path ON clubs FOR EACH ROW EXECUTE FUNCTION trg_block_placeholder_ai_main_clubs_v1();
CREATE TRIGGER trg_clubs_after_insert_seed_starter_equipment_v1 AFTER INSERT ON clubs FOR EACH ROW EXECUTE FUNCTION _clubs_after_insert_seed_starter_equipment_v1();
CREATE TRIGGER trg_clubs_set_updated_at BEFORE UPDATE ON clubs FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_create_default_club_infrastructure AFTER INSERT ON clubs FOR EACH ROW EXECUTE FUNCTION create_default_club_infrastructure();
CREATE TRIGGER trg_create_new_club_race_supplies_low_notification_v1 AFTER INSERT ON clubs FOR EACH ROW WHEN (new.is_ai IS FALSE) EXECUTE FUNCTION create_new_club_race_supplies_low_notification_v1();
CREATE TRIGGER trg_guard_club_persistence_during_transition_v1 BEFORE INSERT OR DELETE OR UPDATE ON clubs FOR EACH ROW EXECUTE FUNCTION guard_club_persistence_during_transition_v1();
CREATE TRIGGER trg_guard_clubs_cash_balance BEFORE UPDATE ON clubs FOR EACH ROW EXECUTE FUNCTION _guard_clubs_cash_balance();
CREATE TRIGGER trg_new_club_creation_setup_v1 AFTER INSERT ON clubs FOR EACH ROW EXECUTE FUNCTION _clubs_after_insert_new_team_setup_v1();
CREATE TRIGGER trg_rebalance_top3_overflow_ai_to_pool_v1 AFTER INSERT OR UPDATE OF club_tier, tier2_division, tier3_division, amateur_division, is_ai, is_active, deleted_at, owner_user_id ON clubs FOR EACH ROW EXECUTE FUNCTION trg_rebalance_top3_overflow_ai_to_pool_v1();
CREATE TRIGGER trg_set_club_created_game_date BEFORE INSERT ON clubs FOR EACH ROW EXECUTE FUNCTION set_club_created_game_date();
CREATE TRIGGER trg_set_new_club_starting_cash_v1 BEFORE INSERT ON clubs FOR EACH ROW EXECUTE FUNCTION _clubs_before_insert_set_starting_cash_v1();
CREATE TRIGGER trg_sync_developing_team_logo_from_parent AFTER UPDATE OF logo_path ON clubs FOR EACH ROW WHEN (new.club_type = 'main'::text) EXECUTE FUNCTION sync_developing_team_logo_from_parent();
CREATE TRIGGER gcc_live_contact_messages AFTER INSERT OR DELETE OR UPDATE ON contact_messages FOR EACH STATEMENT EXECUTE FUNCTION control_center_private.notify_admin_module_snapshot('contact-messages', '2');
CREATE TRIGGER trg_country_market_group_members_set_updated_at BEFORE UPDATE ON country_market_group_members FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_country_market_groups_set_updated_at BEFORE UPDATE ON country_market_groups FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_equipment_catalog_set_updated_at BEFORE UPDATE ON equipment_catalog FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_st_persist_66c6130d4bfd BEFORE INSERT OR DELETE OR UPDATE ON equipment_premium_preferences FOR EACH ROW EXECUTE FUNCTION block_season_transition_protected_write_v1();
CREATE TRIGGER trg_st_persist_8212a7b09bfb BEFORE INSERT OR DELETE OR UPDATE ON equipment_setup_slot_unlocks FOR EACH ROW EXECUTE FUNCTION block_season_transition_protected_write_v1();
CREATE TRIGGER trg_game_world_reset_clear_runtime_execution_state_v1 AFTER UPDATE OF base_game_at, base_season, is_paused ON game_clock_config FOR EACH ROW EXECUTE FUNCTION trg_game_world_reset_clear_runtime_execution_state_v1();
CREATE TRIGGER trg_game_world_reset_rebase_race_engine_activation_v1 AFTER UPDATE OF base_game_at, base_season, is_paused ON game_clock_config FOR EACH ROW EXECUTE FUNCTION trg_game_world_reset_rebase_race_engine_activation_v1();
CREATE TRIGGER trg_rebase_race_engine_activation_on_clock_rewind_v1 AFTER UPDATE OF base_game_at, base_season ON game_clock_config FOR EACH ROW EXECUTE FUNCTION trg_rebase_race_engine_activation_on_clock_rewind_v1();
CREATE TRIGGER national_association_game_day_maintenance AFTER UPDATE OF season_number, month_number, day_number ON game_state FOR EACH ROW EXECUTE FUNCTION private.national_association_game_state_trigger_v1();
CREATE TRIGGER trg_run_game_time_processors_after_clock_update_v1 AFTER UPDATE OF season_number, month_number, day_number, hour_number, minute_number ON game_state FOR EACH ROW WHEN (old.season_number IS DISTINCT FROM new.season_number OR old.month_number IS DISTINCT FROM new.month_number OR old.day_number IS DISTINCT FROM new.day_number OR old.hour_number IS DISTINCT FROM new.hour_number OR old.minute_number IS DISTINCT FROM new.minute_number) EXECUTE FUNCTION run_game_time_processors_after_clock_update_v1();
CREATE TRIGGER trg_seed_rider_skill_snapshots_after_world_reset_v1 AFTER UPDATE OF status ON game_world_reset_runs FOR EACH ROW WHEN (new.status = 'completed'::text) EXECUTE FUNCTION trg_seed_rider_skill_snapshots_after_world_reset_v1();
CREATE TRIGGER gcc_live_reviews AFTER INSERT OR DELETE OR UPDATE ON homepage_player_reviews FOR EACH STATEMENT EXECUTE FUNCTION control_center_private.notify_admin_module_snapshot('player-reviews', '2');
CREATE TRIGGER trg_homepage_player_reviews_updated_at_v1 BEFORE UPDATE ON homepage_player_reviews FOR EACH ROW EXECUTE FUNCTION homepage_player_reviews_set_updated_at_v1();
CREATE TRIGGER trg_inbox_conversations_set_updated_at BEFORE UPDATE ON inbox_conversations FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_handle_inbox_message_insert AFTER INSERT ON inbox_messages FOR EACH ROW EXECUTE FUNCTION handle_inbox_message_insert();
CREATE TRIGGER trg_infrastructure_asset_config_set_updated_at BEFORE UPDATE ON infrastructure_asset_config FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_st_persist_12b340014fad BEFORE INSERT OR DELETE OR UPDATE ON infrastructure_asset_slot_unlocks FOR EACH ROW EXECUTE FUNCTION block_season_transition_protected_write_v1();
CREATE TRIGGER trg_infrastructure_facility_upgrade_config_set_updated_at BEFORE UPDATE ON infrastructure_facility_upgrade_config FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER national_association_config_set_updated_at BEFORE UPDATE ON national_association_config FOR EACH ROW EXECUTE FUNCTION private.ppm_set_updated_at_v1();
CREATE TRIGGER national_association_memberships_set_updated_at BEFORE UPDATE ON national_association_memberships FOR EACH ROW EXECUTE FUNCTION private.ppm_set_updated_at_v1();
CREATE TRIGGER national_associations_set_updated_at BEFORE UPDATE ON national_associations FOR EACH ROW EXECUTE FUNCTION private.ppm_set_updated_at_v1();
CREATE TRIGGER trg_notify_national_association_status_v1 AFTER INSERT OR UPDATE OF status ON national_associations FOR EACH ROW EXECUTE FUNCTION private.trg_notify_national_association_status_v1();
CREATE TRIGGER trg_national_champion_world_qualification_v1 AFTER UPDATE OF status, champion_rider_id ON national_championship_editions FOR EACH ROW WHEN (new.status = 'completed'::text AND new.champion_rider_id IS NOT NULL AND (old.status IS DISTINCT FROM new.status OR old.champion_rider_id IS DISTINCT FROM new.champion_rider_id)) EXECUTE FUNCTION on_national_champion_world_qualification_v1();
CREATE TRIGGER national_coach_candidates_set_updated_at BEFORE UPDATE ON national_coach_candidates FOR EACH ROW EXECUTE FUNCTION private.ppm_set_updated_at_v1();
CREATE TRIGGER national_coach_elections_set_updated_at BEFORE UPDATE ON national_coach_elections FOR EACH ROW EXECUTE FUNCTION private.ppm_set_updated_at_v1();
CREATE TRIGGER trg_notify_national_coach_election_v1 AFTER INSERT OR UPDATE OF status, current_round, winning_candidate_id ON national_coach_elections FOR EACH ROW EXECUTE FUNCTION private.trg_notify_national_coach_election_v1();
CREATE TRIGGER national_coach_terms_set_updated_at BEFORE UPDATE ON national_coach_terms FOR EACH ROW EXECUTE FUNCTION private.ppm_set_updated_at_v1();
CREATE TRIGGER national_team_callups_set_updated_at BEFORE UPDATE ON national_team_callups FOR EACH ROW EXECUTE FUNCTION private.ppm_set_updated_at_v1();
CREATE TRIGGER trg_notify_national_team_callup_v1 AFTER INSERT OR UPDATE OF status ON national_team_callups FOR EACH ROW EXECUTE FUNCTION private.trg_notify_national_team_callup_v1();
CREATE TRIGGER national_team_duties_set_updated_at BEFORE UPDATE ON national_team_duties FOR EACH ROW EXECUTE FUNCTION private.ppm_set_updated_at_v1();
CREATE TRIGGER trg_notify_national_team_duty_status_v1 AFTER UPDATE OF status ON national_team_duties FOR EACH ROW EXECUTE FUNCTION private.trg_notify_national_team_duty_status_v1();
CREATE TRIGGER national_team_lineups_set_updated_at BEFORE UPDATE ON national_team_lineups FOR EACH ROW EXECUTE FUNCTION private.ppm_set_updated_at_v1();
CREATE TRIGGER national_team_squads_set_updated_at BEFORE UPDATE ON national_team_squads FOR EACH ROW EXECUTE FUNCTION private.ppm_set_updated_at_v1();
CREATE TRIGGER trg_notify_national_team_squad_v1 AFTER INSERT OR UPDATE OF status, confirmed_on_game_date ON national_team_squads FOR EACH ROW EXECUTE FUNCTION private.trg_notify_national_team_squad_v1();
CREATE TRIGGER trg_sync_nations_squad_duty_v1 AFTER INSERT OR UPDATE OF status ON national_team_squads FOR EACH ROW EXECUTE FUNCTION private.trg_sync_nations_squad_duty_v1();
CREATE TRIGGER national_team_standard_assets_set_updated_at BEFORE UPDATE ON national_team_standard_assets FOR EACH ROW EXECUTE FUNCTION private.ppm_set_updated_at_v1();
CREATE TRIGGER national_team_standard_equipment_set_updated_at BEFORE UPDATE ON national_team_standard_equipment FOR EACH ROW EXECUTE FUNCTION private.ppm_set_updated_at_v1();
CREATE TRIGGER national_team_standard_supplies_set_updated_at BEFORE UPDATE ON national_team_standard_supplies FOR EACH ROW EXECUTE FUNCTION private.ppm_set_updated_at_v1();
CREATE TRIGGER nations_competition_editions_set_updated_at BEFORE UPDATE ON nations_competition_editions FOR EACH ROW EXECUTE FUNCTION private.ppm_set_updated_at_v1();
CREATE TRIGGER trg_notify_nations_edition_milestone_v1 AFTER INSERT OR UPDATE OF host_association_id, champion_association_id ON nations_competition_editions FOR EACH ROW EXECUTE FUNCTION private.trg_notify_nations_edition_milestone_v1();
CREATE TRIGGER nations_competition_entries_set_updated_at BEFORE UPDATE ON nations_competition_entries FOR EACH ROW EXECUTE FUNCTION private.ppm_set_updated_at_v1();
CREATE TRIGGER nations_competition_groups_set_updated_at BEFORE UPDATE ON nations_competition_groups FOR EACH ROW EXECUTE FUNCTION private.ppm_set_updated_at_v1();
CREATE TRIGGER trg_ensure_nations_group_runtime_v1 AFTER INSERT OR UPDATE OF status ON nations_competition_groups FOR EACH ROW EXECUTE FUNCTION private.trg_ensure_nations_group_runtime_v1();
CREATE TRIGGER nations_competition_rounds_set_updated_at BEFORE UPDATE ON nations_competition_rounds FOR EACH ROW EXECUTE FUNCTION private.ppm_set_updated_at_v1();
CREATE TRIGGER trg_notify_nations_round_draw_v1 AFTER UPDATE OF status ON nations_competition_rounds FOR EACH ROW EXECUTE FUNCTION private.trg_notify_nations_round_draw_v1();
CREATE TRIGGER nations_group_entries_set_updated_at BEFORE UPDATE ON nations_group_entries FOR EACH ROW EXECUTE FUNCTION private.ppm_set_updated_at_v1();
CREATE TRIGGER trg_notify_nations_final_result_v1 AFTER UPDATE OF status ON nations_group_entries FOR EACH ROW EXECUTE FUNCTION private.trg_notify_nations_final_result_v1();
CREATE TRIGGER trg_notify_nations_group_entry_outcome_v1 AFTER UPDATE OF status ON nations_group_entries FOR EACH ROW EXECUTE FUNCTION private.trg_notify_nations_group_entry_outcome_v1();
CREATE TRIGGER trg_notify_nations_event_result_v1 AFTER INSERT OR UPDATE OF status ON nations_group_events FOR EACH ROW EXECUTE FUNCTION private.trg_notify_nations_event_result_v1();
CREATE TRIGGER nations_host_applications_set_updated_at BEFORE UPDATE ON nations_host_applications FOR EACH ROW EXECUTE FUNCTION private.ppm_set_updated_at_v1();
CREATE TRIGGER trg_enrich_race_application_and_jersey_notification_v1 BEFORE INSERT OR UPDATE OF type_id, action_url, payload_json, title, message ON notifications FOR EACH ROW EXECUTE FUNCTION enrich_race_application_and_jersey_notification_v1();
CREATE TRIGGER trg_enrich_race_results_summary_notification_v1 BEFORE INSERT OR UPDATE OF type_id, action_url, payload_json, title, message ON notifications FOR EACH ROW EXECUTE FUNCTION enrich_race_results_summary_notification_v1();
CREATE TRIGGER trg_enrich_rider_unhappy_notification_payload_v1 BEFORE INSERT OR UPDATE OF payload_json, action_url, title, message ON notifications FOR EACH ROW EXECUTE FUNCTION enrich_rider_unhappy_notification_payload_v1();
CREATE TRIGGER trg_enrich_sport_director_notification_context_v2 BEFORE INSERT OR UPDATE OF payload_json ON notifications FOR EACH ROW EXECUTE FUNCTION enrich_sport_director_notification_context_v2();
CREATE TRIGGER trg_enrich_startlist_missed_notification_v1 BEFORE INSERT OR UPDATE OF payload_json, type_id ON notifications FOR EACH ROW EXECUTE FUNCTION enrich_startlist_missed_notification_trg_v1();
CREATE TRIGGER trg_normalize_priority_game_notification_v1 BEFORE INSERT OR UPDATE OF type_id, title, message, action_url, payload_json ON notifications FOR EACH ROW EXECUTE FUNCTION normalize_priority_game_notification_v1();
CREATE TRIGGER trg_normalize_season_started_race_schedule_notice_v1 BEFORE INSERT ON notifications FOR EACH ROW EXECUTE FUNCTION normalize_season_started_race_schedule_notice_v1();
CREATE TRIGGER trg_normalize_weather_cancellation_notification_v1 BEFORE INSERT OR UPDATE ON notifications FOR EACH ROW EXECUTE FUNCTION normalize_weather_cancellation_notification_v1();
CREATE TRIGGER trg_notification_enrich_rider_identity_v1 BEFORE INSERT OR UPDATE OF payload_json, title, message, type_id ON notifications FOR EACH ROW EXECUTE FUNCTION notification_enrich_rider_identity_trg_v1();
CREATE TRIGGER trg_set_merged_daily_notification_image_v1 BEFORE INSERT OR UPDATE OF type_id, payload_json ON notifications FOR EACH ROW EXECUTE FUNCTION set_merged_daily_notification_image_v1();
CREATE TRIGGER trg_staff_advisory_enrich_notification_riders_v1 BEFORE INSERT OR UPDATE OF payload_json, message, type_id ON notifications FOR EACH ROW EXECUTE FUNCTION staff_advisory_enrich_notification_riders_trg_v1();
CREATE TRIGGER trg_zz_normalize_sport_director_notification_display_context_v1 BEFORE INSERT OR UPDATE OF payload_json ON notifications FOR EACH ROW EXECUTE FUNCTION normalize_sport_director_notification_display_context_v1();
CREATE TRIGGER premium_invoice_referral_reward_v1 AFTER INSERT ON premium_invoice_payments FOR EACH ROW EXECUTE FUNCTION trg_premium_invoice_referral_reward_v1();
CREATE TRIGGER trg_st_persist_75a48cc3b1af BEFORE INSERT OR DELETE OR UPDATE ON premium_invoice_payments FOR EACH ROW EXECUTE FUNCTION block_season_transition_protected_write_v1();
CREATE TRIGGER trg_st_persist_a4f361cac63d BEFORE INSERT OR DELETE OR UPDATE ON premium_payment_failures FOR EACH ROW EXECUTE FUNCTION block_season_transition_protected_write_v1();
CREATE TRIGGER premium_plans_set_updated_at BEFORE UPDATE ON premium_plans FOR EACH ROW EXECUTE FUNCTION premium_set_updated_at_v1();
CREATE TRIGGER trg_create_welcome_notification_on_profile_insert AFTER INSERT ON profiles FOR EACH ROW EXECUTE FUNCTION create_welcome_notification_for_new_profile();
CREATE TRIGGER trg_grant_welcome_coins_on_profile_insert AFTER INSERT ON profiles FOR EACH ROW EXECUTE FUNCTION grant_welcome_coins_for_new_profile();
CREATE TRIGGER trg_profiles_mark_club_inactive_on_delete BEFORE DELETE ON profiles FOR EACH ROW EXECUTE FUNCTION trg_profiles_mark_club_inactive_on_delete();
CREATE TRIGGER trg_profiles_set_updated_at BEFORE UPDATE ON profiles FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_validate_profile_birthday_v1 BEFORE INSERT OR UPDATE ON profiles FOR EACH ROW EXECUTE FUNCTION validate_profile_birthday_v1();
CREATE TRIGGER trg_race_category_rules_set_updated_at BEFORE UPDATE ON race_category_rules FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_st_persist_6d5ae92642d5 BEFORE INSERT OR DELETE OR UPDATE ON race_classification_standings FOR EACH ROW EXECUTE FUNCTION block_season_transition_protected_write_v1();
CREATE TRIGGER trg_race_engine_guard_effect_adapter_registry_v2 BEFORE DELETE OR UPDATE ON race_engine_effect_adapter_registry_v2 FOR EACH ROW EXECUTE FUNCTION race_engine_guard_effect_adapter_registry_v2();
CREATE TRIGGER trg_race_engine_guard_stage_effect_history_v2 BEFORE DELETE OR UPDATE ON race_engine_stage_effect_history_v2 FOR EACH ROW EXECUTE FUNCTION race_engine_guard_stage_effect_history_v2();
CREATE TRIGGER trg_race_engine_capture_stage_effect_history_v2 AFTER INSERT OR UPDATE ON race_engine_stage_effect_ledger_v2 FOR EACH ROW EXECUTE FUNCTION race_engine_capture_stage_effect_history_v2();
CREATE TRIGGER trg_race_engine_guard_stage_immutable_state_v2 BEFORE DELETE OR UPDATE ON race_engine_stage_immutable_state_v2 FOR EACH ROW EXECUTE FUNCTION race_engine_guard_stage_immutable_state_v2();
CREATE TRIGGER trg_race_engine_stage_immutable_state_updated_at_v2 BEFORE UPDATE ON race_engine_stage_immutable_state_v2 FOR EACH ROW EXECUTE FUNCTION race_engine_set_stage_immutable_state_updated_at_v2();
CREATE TRIGGER trg_race_engine_stage_interaction_events_touch BEFORE UPDATE ON race_engine_stage_interaction_events FOR EACH ROW EXECUTE FUNCTION race_engine_stage_interactions_touch_updated_at_v1();
CREATE TRIGGER trg_race_engine_guard_stage_process_claim_history_v2 BEFORE DELETE OR UPDATE ON race_engine_stage_process_claim_history_v2 FOR EACH ROW EXECUTE FUNCTION race_engine_guard_stage_process_claim_history_v2();
CREATE TRIGGER trg_race_engine_capture_stage_process_claim_history_v2 AFTER INSERT OR UPDATE ON race_engine_stage_process_claim_v2 FOR EACH ROW EXECUTE FUNCTION race_engine_capture_stage_process_claim_history_v2();
CREATE TRIGGER trg_race_engine_guard_stage_process_claim_v2 BEFORE DELETE OR UPDATE ON race_engine_stage_process_claim_v2 FOR EACH ROW EXECUTE FUNCTION race_engine_guard_stage_process_claim_v2();
CREATE TRIGGER trg_race_engine_stage_process_claim_updated_at_v2 BEFORE UPDATE ON race_engine_stage_process_claim_v2 FOR EACH ROW EXECUTE FUNCTION race_engine_set_stage_process_claim_updated_at_v2();
CREATE TRIGGER trg_race_engine_validate_new_stage_process_claim_v2 BEFORE INSERT ON race_engine_stage_process_claim_v2 FOR EACH ROW EXECUTE FUNCTION race_engine_validate_new_stage_process_claim_v2();
CREATE TRIGGER trg_race_engine_guard_terminal_process_run_v2 BEFORE DELETE OR UPDATE ON race_engine_stage_process_runs_v2 FOR EACH ROW EXECUTE FUNCTION race_engine_guard_terminal_process_run_v2();
CREATE TRIGGER trg_race_engine_guard_stage_runner_handoff_history_v2 BEFORE DELETE OR UPDATE ON race_engine_stage_runner_handoff_history_v2 FOR EACH ROW EXECUTE FUNCTION race_engine_guard_stage_runner_handoff_history_v2();
CREATE TRIGGER trg_race_engine_capture_stage_runner_handoff_history_v2 AFTER INSERT OR UPDATE ON race_engine_stage_runner_handoff_v2 FOR EACH ROW EXECUTE FUNCTION race_engine_capture_stage_runner_handoff_history_v2();
CREATE TRIGGER trg_race_engine_guard_stage_runner_handoff_v2 BEFORE DELETE OR UPDATE ON race_engine_stage_runner_handoff_v2 FOR EACH ROW EXECUTE FUNCTION race_engine_guard_stage_runner_handoff_v2();
CREATE TRIGGER trg_enforce_early_january_application_window_v1 BEFORE INSERT OR UPDATE OF race_season_number, race_start_month_number, race_start_day_number, applications_open_season_number, applications_close_season_number, team_list_announcement_season_number, rider_submission_deadline_season_number ON race_entry_rules FOR EACH ROW EXECUTE FUNCTION enforce_early_january_application_window_v1();
CREATE TRIGGER trg_race_entry_rules_exact_early_january_deadline_v1 BEFORE INSERT OR UPDATE ON race_entry_rules FOR EACH ROW EXECUTE FUNCTION trg_race_entry_rules_exact_early_january_deadline_v1();
CREATE TRIGGER trg_race_entry_rules_set_rider_deadline_v1 BEFORE INSERT OR UPDATE OF race_id, rider_submission_deadline, rider_submission_deadline_season_number, rider_submission_deadline_month_number, rider_submission_deadline_day_number ON race_entry_rules FOR EACH ROW EXECUTE FUNCTION race_entry_rules_set_rider_deadline_v1();
CREATE TRIGGER trg_race_entry_rules_set_updated_at BEFORE UPDATE ON race_entry_rules FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER gcc_live_race_incidents AFTER INSERT OR DELETE OR UPDATE ON race_operations_incidents_v1 FOR EACH STATEMENT EXECUTE FUNCTION control_center_private.notify_admin_module_snapshot('race-operations', '15');
CREATE TRIGGER gcc_live_race_status AFTER INSERT OR DELETE OR UPDATE ON race_operations_stage_status_v1 FOR EACH STATEMENT EXECUTE FUNCTION control_center_private.notify_admin_module_snapshot('race-operations', '15');
CREATE TRIGGER trg_assign_race_captains_after_participant_insert_v1 AFTER INSERT ON race_participant_riders REFERENCING NEW TABLE AS new_participant_rows FOR EACH STATEMENT EXECUTE FUNCTION trg_assign_race_captains_after_participant_insert_v1();
CREATE TRIGGER trg_enforce_race_participant_rider_health BEFORE INSERT OR UPDATE OF rider_id ON race_participant_riders FOR EACH ROW EXECUTE FUNCTION enforce_race_participant_rider_health_v1();
CREATE TRIGGER trg_invalidate_race_captains_on_participant_change_v1 AFTER INSERT OR DELETE OR UPDATE OF team_id, rider_id ON race_participant_riders FOR EACH ROW EXECUTE FUNCTION invalidate_race_startlist_captain_finalization_v1();
CREATE TRIGGER trg_race_participant_riders_assign_numbers_v1 AFTER INSERT OR UPDATE OF race_id, team_id, role_snapshot, overall_snapshot ON race_participant_riders FOR EACH ROW EXECUTE FUNCTION trg_race_participant_riders_assign_numbers_v1();
CREATE TRIGGER trg_race_participant_riders_national_team_country_lock_v1 BEFORE INSERT OR UPDATE OF team_id, rider_id ON race_participant_riders FOR EACH ROW EXECUTE FUNCTION trg_national_team_country_lock_team_rider_pair_v1();
CREATE TRIGGER trg_set_race_participant_rider_snapshots_v1 BEFORE INSERT OR UPDATE OF rider_id, team_id ON race_participant_riders FOR EACH ROW EXECUTE FUNCTION set_race_participant_rider_snapshots_v1();
CREATE TRIGGER trg_st_persist_1c6ee05fafca BEFORE INSERT OR DELETE OR UPDATE ON race_participant_riders FOR EACH ROW EXECUTE FUNCTION block_season_transition_protected_write_v1();
CREATE TRIGGER trg_race_participant_teams_assign_numbers_v1 AFTER INSERT OR UPDATE OF race_id, status, team_id ON race_participant_teams FOR EACH ROW EXECUTE FUNCTION trg_race_participant_teams_assign_numbers_v1();
CREATE TRIGGER trg_st_persist_3304e5c327ed BEFORE INSERT OR DELETE OR UPDATE ON race_participant_teams FOR EACH ROW EXECUTE FUNCTION block_season_transition_protected_write_v1();
CREATE TRIGGER trg_block_nc_assets_v1 BEFORE INSERT OR UPDATE ON race_preparation_assets FOR EACH ROW EXECUTE FUNCTION block_national_championship_preparation_resource_v1();
CREATE TRIGGER trg_race_preparation_assets_set_updated_at BEFORE UPDATE ON race_preparation_assets FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_enforce_race_preparation_rider_health BEFORE INSERT OR UPDATE OF rider_id ON race_preparation_riders FOR EACH ROW EXECUTE FUNCTION enforce_race_preparation_rider_health_v1();
CREATE TRIGGER trg_enforce_race_preparation_rider_max BEFORE INSERT OR UPDATE ON race_preparation_riders FOR EACH ROW EXECUTE FUNCTION enforce_race_preparation_rider_max_v1();
CREATE TRIGGER trg_race_preparation_riders_set_updated_at BEFORE UPDATE ON race_preparation_riders FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_block_nc_staff_v1 BEFORE INSERT OR UPDATE ON race_preparation_staff FOR EACH ROW EXECUTE FUNCTION block_national_championship_preparation_resource_v1();
CREATE TRIGGER trg_race_preparation_staff_set_updated_at BEFORE UPDATE ON race_preparation_staff FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_sport_director_selection_clears_u23_planner_v1 AFTER INSERT OR UPDATE OF staff_id, role_type ON race_preparation_staff FOR EACH ROW WHEN (new.role_type = 'sport_director'::text) EXECUTE FUNCTION trg_sport_director_selection_clears_u23_planner_v1();
CREATE TRIGGER trg_mark_u23_submit_hook_installed_v1 BEFORE INSERT OR UPDATE ON race_preparation_stage_plan_automation FOR EACH ROW EXECUTE FUNCTION trg_mark_u23_submit_hook_installed_v1();
CREATE TRIGGER trg_u23_planner_selection_clears_sport_director_v1 AFTER INSERT OR UPDATE OF is_enabled, planner_staff_id ON race_preparation_stage_plan_automation FOR EACH ROW WHEN (new.is_enabled = true AND new.planner_staff_id IS NOT NULL) EXECUTE FUNCTION trg_u23_planner_selection_clears_sport_director_v1();
CREATE TRIGGER trg_block_nc_supplies_v1 BEFORE INSERT OR UPDATE ON race_preparation_supplies FOR EACH ROW EXECUTE FUNCTION block_national_championship_preparation_resource_v1();
CREATE TRIGGER trg_race_preparation_supplies_set_updated_at BEFORE UPDATE ON race_preparation_supplies FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER race_preparation_sync_participants_after_submit AFTER INSERT OR UPDATE ON race_preparations FOR EACH ROW EXECUTE FUNCTION trigger_sync_submitted_race_preparation_participants_v1();
CREATE TRIGGER trg_enforce_race_preparation_no_overlap_on_submit BEFORE UPDATE OF status, startlist_status ON race_preparations FOR EACH ROW EXECUTE FUNCTION enforce_race_preparation_no_overlap_on_submit_v1();
CREATE TRIGGER trg_enforce_race_preparation_submit_rider_count BEFORE UPDATE OF status, startlist_status ON race_preparations FOR EACH ROW EXECUTE FUNCTION enforce_race_preparation_submit_rider_count_v1();
CREATE TRIGGER trg_race_preparations_participating_club BEFORE INSERT OR UPDATE OF club_id, participating_club_id ON race_preparations FOR EACH ROW EXECUTE FUNCTION race_prep_enforce_participating_club_v1();
CREATE TRIGGER trg_race_preparations_set_updated_at BEFORE UPDATE ON race_preparations FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_st_persist_fe7dafa3e8b5 BEFORE INSERT OR DELETE OR UPDATE ON race_preparations FOR EACH ROW EXECUTE FUNCTION block_season_transition_protected_write_v1();
CREATE TRIGGER trg_sync_submitted_race_preparation_to_participants AFTER UPDATE OF status, startlist_status ON race_preparations FOR EACH ROW EXECUTE FUNCTION trg_sync_submitted_race_preparation_to_participants_v1();
CREATE TRIGGER trg_u23_stage_plan_on_race_plan_submit_v1 AFTER UPDATE OF status ON race_preparations FOR EACH ROW EXECUTE FUNCTION trg_u23_stage_plan_on_race_plan_submit_v1();
CREATE TRIGGER trg_block_nations_prize_awards_v1 BEFORE INSERT ON race_prize_awards FOR EACH ROW EXECUTE FUNCTION private.block_nations_competition_prize_award_v1();
CREATE TRIGGER trg_race_prize_awards_set_updated_at BEFORE UPDATE ON race_prize_awards FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_st_persist_8c2f8fd58555 BEFORE INSERT OR DELETE OR UPDATE ON race_prize_awards FOR EACH ROW EXECUTE FUNCTION block_season_transition_protected_write_v1();
CREATE TRIGGER trg_race_prize_bucket_rules_set_updated_at BEFORE UPDATE ON race_prize_bucket_rules FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_block_nations_ranking_awards_v1 BEFORE INSERT ON race_ranking_point_awards FOR EACH ROW EXECUTE FUNCTION private.block_nations_competition_ranking_award_v1();
CREATE TRIGGER trg_merge_duplicate_ranking_point_award_v1 BEFORE INSERT ON race_ranking_point_awards FOR EACH ROW EXECUTE FUNCTION trg_merge_duplicate_ranking_point_award_v1();
CREATE TRIGGER trg_race_ranking_point_awards_set_updated_at BEFORE UPDATE ON race_ranking_point_awards FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_st_persist_95d325e48757 BEFORE INSERT OR DELETE OR UPDATE ON race_ranking_point_awards FOR EACH ROW EXECUTE FUNCTION block_season_transition_protected_write_v1();
CREATE TRIGGER trg_race_ranking_point_rules_set_updated_at BEFORE UPDATE ON race_ranking_point_rules FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_st_persist_34b1caeab41d BEFORE INSERT OR DELETE OR UPDATE ON race_replay_coin_unlocks FOR EACH ROW EXECUTE FUNCTION block_season_transition_protected_write_v1();
CREATE TRIGGER trg_enrich_missed_startlist_deadline_event_penalty_v1 BEFORE INSERT ON race_rider_submission_deadline_events FOR EACH ROW EXECUTE FUNCTION enrich_missed_startlist_deadline_event_penalty_v1();
CREATE TRIGGER set_race_rule_sets_updated_at BEFORE UPDATE ON race_rule_sets FOR EACH ROW EXECUTE FUNCTION set_race_rule_sets_updated_at();
CREATE TRIGGER trg_race_rules_config_set_updated_at BEFORE UPDATE ON race_rules_config FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_universal_race_stage_activate_parent_race_v1 AFTER INSERT ON race_stage_authoritative_runs FOR EACH ROW EXECUTE FUNCTION universal_race_stage_activate_parent_race_trigger_v1();
CREATE TRIGGER trg_universal_race_stage_validate_authority_v1 BEFORE INSERT ON race_stage_authoritative_runs FOR EACH ROW EXECUTE FUNCTION universal_race_stage_validate_authority_trigger_v1();
CREATE TRIGGER validate_race_stage_authoritative_run_v1 BEFORE INSERT OR UPDATE ON race_stage_authoritative_runs FOR EACH ROW EXECUTE FUNCTION validate_race_stage_authoritative_run_v1();
CREATE TRIGGER trg_st_persist_34ea618e5ee3 BEFORE INSERT OR DELETE OR UPDATE ON race_stage_incidents FOR EACH ROW EXECUTE FUNCTION block_season_transition_protected_write_v1();
CREATE TRIGGER trg_race_stage_plan_assets_set_updated_at BEFORE UPDATE ON race_stage_plan_assets FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_st_persist_75729ad3b905 BEFORE INSERT OR DELETE OR UPDATE ON race_stage_plan_management FOR EACH ROW EXECUTE FUNCTION block_season_transition_protected_write_v1();
CREATE TRIGGER trg_race_stage_plan_riders_set_updated_at BEFORE UPDATE ON race_stage_plan_riders FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_race_stage_plan_supplies_set_updated_at BEFORE UPDATE ON race_stage_plan_supplies FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_capture_u23_stage_plan_manual_save_v1 AFTER UPDATE OF last_saved_at ON race_stage_plans FOR EACH ROW EXECUTE FUNCTION capture_u23_stage_plan_manual_save_v1();
CREATE TRIGGER trg_enforce_national_championship_individual_stage_plan_v1 BEFORE INSERT OR UPDATE ON race_stage_plans FOR EACH ROW EXECUTE FUNCTION enforce_national_championship_individual_stage_plan_v1();
CREATE TRIGGER trg_guard_u23_managed_stage_plan_read_only_v1 BEFORE UPDATE OF last_saved_at ON race_stage_plans FOR EACH ROW EXECUTE FUNCTION guard_u23_managed_stage_plan_read_only_v1();
CREATE TRIGGER trg_race_stage_plans_set_updated_at BEFORE UPDATE ON race_stage_plans FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_st_persist_a4dafbccca4c BEFORE INSERT OR DELETE OR UPDATE ON race_stage_plans FOR EACH ROW EXECUTE FUNCTION block_season_transition_protected_write_v1();
CREATE TRIGGER trg_validate_race_stage_supply_reservation_v1 BEFORE INSERT OR UPDATE OF rider_supplies_json, last_saved_at ON race_stage_plans FOR EACH ROW EXECUTE FUNCTION validate_race_stage_supply_reservation_v1();
CREATE TRIGGER trg_one_day_zero_point_result_bonus_v1 BEFORE INSERT OR UPDATE OF stage_id, bonus_seconds_awarded ON race_stage_point_results FOR EACH ROW EXECUTE FUNCTION trg_one_day_zero_point_result_bonus_v1();
CREATE TRIGGER trg_st_persist_7b2d5ac14e08 BEFORE INSERT OR DELETE OR UPDATE ON race_stage_point_results FOR EACH ROW EXECUTE FUNCTION block_season_transition_protected_write_v1();
CREATE TRIGGER trg_normalize_race_stage_point_v1 BEFORE INSERT OR UPDATE ON race_stage_points FOR EACH ROW EXECUTE FUNCTION trg_normalize_race_stage_point_v1();
CREATE TRIGGER trg_one_day_zero_stage_point_bonus_def_v1 BEFORE INSERT OR UPDATE OF stage_id, time_bonus_seconds ON race_stage_points FOR EACH ROW EXECUTE FUNCTION trg_one_day_zero_stage_point_bonus_def_v1();
CREATE TRIGGER trg_race_stage_points_set_updated_at BEFORE UPDATE ON race_stage_points FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_race_stage_profile_details_set_updated_at BEFORE UPDATE ON race_stage_profile_details FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_sync_race_stage_profile_metadata_v1 AFTER INSERT OR UPDATE OF terrain_type, profile_type, terrain_split, elevation_gain_m, mountain_climbs, distance_km ON race_stage_profile_details FOR EACH ROW EXECUTE FUNCTION sync_race_stage_profile_metadata_v1();
CREATE TRIGGER race_stage_replay_frames_normalize_entity BEFORE INSERT OR UPDATE ON race_stage_replay_frames FOR EACH ROW EXECUTE FUNCTION normalize_race_stage_replay_frame_entity_v1();
CREATE TRIGGER trg_race_engine_guard_replay_frame_write_v1 BEFORE INSERT OR DELETE OR UPDATE ON race_stage_replay_frames FOR EACH ROW EXECUTE FUNCTION race_engine_guard_run_scoped_output_write_v1();
CREATE TRIGGER trg_race_stage_report_events_set_updated_at BEFORE UPDATE ON race_stage_report_events FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_st_persist_607e31b722e2 BEFORE INSERT OR DELETE OR UPDATE ON race_stage_report_events FOR EACH ROW EXECUTE FUNCTION block_season_transition_protected_write_v1();
CREATE TRIGGER trg_one_day_zero_stage_result_bonus_v1 BEFORE INSERT OR UPDATE OF stage_id, bonus_seconds ON race_stage_results FOR EACH ROW EXECUTE FUNCTION trg_one_day_zero_stage_result_bonus_v1();
CREATE TRIGGER trg_race_engine_guard_result_write_v1 BEFORE INSERT OR DELETE OR UPDATE ON race_stage_results FOR EACH ROW EXECUTE FUNCTION race_engine_guard_result_write_v1();
CREATE TRIGGER trg_race_stage_results_upsert_daily_activity_v1 AFTER INSERT ON race_stage_results FOR EACH ROW EXECUTE FUNCTION trg_race_stage_results_upsert_daily_activity_v1();
CREATE TRIGGER trg_st_persist_75af02b757c3 BEFORE INSERT OR DELETE OR UPDATE ON race_stage_results FOR EACH ROW EXECUTE FUNCTION block_season_transition_protected_write_v1();
CREATE TRIGGER trg_award_race_development_on_rider_state_v1 AFTER INSERT OR UPDATE OF stage_status, finish_position, start_stamina, stamina_spent, finish_stamina, fatigue_before_stage, fatigue_gain, fatigue_after_stage, metadata ON race_stage_rider_states FOR EACH ROW EXECUTE FUNCTION trg_award_race_development_on_rider_state_v1();
CREATE TRIGGER trg_promote_tt_race_sharpness_metadata_v1 BEFORE INSERT OR UPDATE OF metadata ON race_stage_rider_states FOR EACH ROW EXECUTE FUNCTION trg_promote_tt_race_sharpness_metadata_v1();
CREATE TRIGGER trg_race_engine_guard_rider_state_write_v1 BEFORE INSERT OR DELETE OR UPDATE ON race_stage_rider_states FOR EACH ROW EXECUTE FUNCTION race_engine_guard_run_scoped_output_write_v1();
CREATE TRIGGER set_race_stage_route_profile_jobs_updated_at BEFORE UPDATE ON race_stage_route_profile_jobs FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER set_race_stage_route_profiles_updated_at BEFORE UPDATE ON race_stage_route_profiles FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_race_engine_guard_simulation_event_write_v1 BEFORE INSERT OR DELETE OR UPDATE ON race_stage_simulation_events FOR EACH ROW EXECUTE FUNCTION race_engine_guard_run_scoped_output_write_v1();
CREATE TRIGGER trg_award_race_development_on_run_completed_v1 AFTER INSERT OR UPDATE OF status ON race_stage_simulation_runs FOR EACH ROW EXECUTE FUNCTION trg_award_race_development_on_run_completed_v1();
CREATE TRIGGER trg_race_engine_auto_finalize_weather_race_state_from_run_v1 AFTER INSERT OR UPDATE OF status, engine_version, simulation_mode, completed_at ON race_stage_simulation_runs FOR EACH ROW EXECUTE FUNCTION race_engine_auto_finalize_weather_race_state_from_run_v1();
CREATE TRIGGER trg_race_engine_guard_simulation_run_write_v1 BEFORE INSERT OR DELETE OR UPDATE ON race_stage_simulation_runs FOR EACH ROW EXECUTE FUNCTION race_engine_guard_simulation_run_write_v1();
CREATE TRIGGER trg_st_persist_f6174ee35915 BEFORE INSERT OR DELETE OR UPDATE ON race_stage_simulation_runs FOR EACH ROW EXECUTE FUNCTION block_season_transition_protected_write_v1();
CREATE CONSTRAINT TRIGGER trg_u23_next_stage_from_completed_run_v1 AFTER INSERT OR UPDATE ON race_stage_simulation_runs DEFERRABLE INITIALLY DEFERRED FOR EACH ROW WHEN (new.status = 'completed'::text) EXECUTE FUNCTION trg_process_u23_next_stage_from_completed_run_v1();
CREATE TRIGGER trg_universal_race_stage_prepare_point_contract_v1 BEFORE INSERT ON race_stage_simulation_runs FOR EACH ROW EXECUTE FUNCTION universal_race_stage_prepare_point_contract_trigger_v1();
CREATE TRIGGER trg_universal_race_stage_validate_hidden_submission_v1 BEFORE UPDATE OF input_snapshot_json, result_summary_json ON race_stage_simulation_runs FOR EACH ROW EXECUTE FUNCTION universal_race_stage_validate_hidden_submission_trigger_v1();
CREATE TRIGGER race_stage_time_trial_rules_validate BEFORE INSERT OR UPDATE ON race_stage_time_trial_rules FOR EACH ROW EXECUTE FUNCTION validate_race_stage_time_trial_rules_v1();
CREATE TRIGGER auto_generate_race_stage_weather_v1 AFTER INSERT ON race_stages FOR EACH ROW EXECUTE FUNCTION auto_generate_race_stage_weather_v1();
CREATE TRIGGER auto_regenerate_race_stage_weather_v1 AFTER UPDATE OF stage_date, host_country_code, host_city, start_city, finish_city ON race_stages FOR EACH ROW EXECUTE FUNCTION auto_regenerate_race_stage_weather_v1();
CREATE TRIGGER race_stages_sync_time_trial_rules AFTER INSERT OR UPDATE OF stage_format ON race_stages FOR EACH ROW EXECUTE FUNCTION sync_race_stage_time_trial_rules_from_stage_v1();
CREATE TRIGGER trg_race_stage_enforce_parent_start_time_v1 BEFORE INSERT OR UPDATE OF race_id, planned_start_hour_number, planned_start_minute, planned_start_time_label ON race_stages FOR EACH ROW EXECUTE FUNCTION race_stage_enforce_parent_start_time_v1();
CREATE TRIGGER trg_race_stage_normalize_contiguous_calendar_v1 AFTER INSERT OR UPDATE OF race_id, stage_number, stage_date ON race_stages FOR EACH ROW EXECUTE FUNCTION race_stage_normalize_contiguous_calendar_trigger_v1();
CREATE TRIGGER trg_race_stages_set_updated_at BEFORE UPDATE ON race_stages FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_st_persist_178fd5f8770b BEFORE INSERT OR DELETE OR UPDATE ON race_stages FOR EACH ROW EXECUTE FUNCTION block_season_transition_protected_write_v1();
CREATE TRIGGER trg_sync_race_stage_plan_shell_from_race_stage_v1 AFTER UPDATE OF race_id, stage_number, stage_date, planned_start_hour_number, planned_start_minute ON race_stages FOR EACH ROW WHEN (old.race_id IS DISTINCT FROM new.race_id OR old.stage_number IS DISTINCT FROM new.stage_number OR old.stage_date IS DISTINCT FROM new.stage_date OR old.planned_start_hour_number IS DISTINCT FROM new.planned_start_hour_number OR old.planned_start_minute IS DISTINCT FROM new.planned_start_minute) EXECUTE FUNCTION sync_race_stage_plan_shell_from_race_stage_v1();
CREATE TRIGGER trg_sync_race_stage_summary_v1 AFTER INSERT OR DELETE OR UPDATE ON race_stages FOR EACH ROW EXECUTE FUNCTION trg_sync_race_stage_summary_v1();
CREATE TRIGGER trg_race_team_applications_set_updated_at BEFORE UPDATE ON race_team_applications FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_st_persist_4b20e566d148 BEFORE INSERT OR DELETE OR UPDATE ON race_team_applications FOR EACH ROW EXECUTE FUNCTION block_season_transition_protected_write_v1();
CREATE TRIGGER trg_invalidate_race_captains_on_team_entry_change_v1 AFTER INSERT OR DELETE OR UPDATE OF status, club_id, participating_club_id, missed_startlist_at ON race_team_entries FOR EACH ROW EXECUTE FUNCTION invalidate_race_startlist_captain_finalization_v1();
CREATE TRIGGER trg_notify_race_application_decision_v1 AFTER UPDATE OF status ON race_team_entries FOR EACH ROW WHEN (old.status IS DISTINCT FROM new.status) EXECUTE FUNCTION notify_race_application_decision_from_entry_v1();
CREATE TRIGGER trg_race_team_entries_participating_club BEFORE INSERT OR UPDATE OF club_id, participating_club_id ON race_team_entries FOR EACH ROW EXECUTE FUNCTION race_prep_enforce_participating_club_v1();
CREATE TRIGGER trg_st_persist_19a3b5983ccd BEFORE INSERT OR DELETE OR UPDATE ON race_team_entries FOR EACH ROW EXECUTE FUNCTION block_season_transition_protected_write_v1();
CREATE TRIGGER trg_race_team_stage_disqualification_penalty_v1 AFTER INSERT ON race_team_stage_disqualifications FOR EACH ROW EXECUTE FUNCTION race_team_stage_disqualification_penalty_trg_v1();
CREATE TRIGGER trg_race_normalize_contiguous_stage_calendar_v1 AFTER UPDATE OF start_date, end_date, stage_count ON races FOR EACH ROW EXECUTE FUNCTION race_normalize_contiguous_stage_calendar_trigger_v1();
CREATE TRIGGER trg_race_propagate_start_time_to_stages_v1 AFTER UPDATE OF planned_start_hour_number, planned_start_minute, planned_start_time_label ON races FOR EACH ROW EXECUTE FUNCTION race_propagate_start_time_to_stages_v1();
CREATE TRIGGER trg_races_set_updated_at BEFORE UPDATE ON races FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_sponsor_process_visibility_objectives_after_race_status_v1 AFTER UPDATE OF status ON races FOR EACH ROW WHEN (old.status IS DISTINCT FROM new.status) EXECUTE FUNCTION trg_sponsor_process_visibility_objectives_after_race_status_v1();
CREATE TRIGGER trg_st_persist_9eb26da97d43 BEFORE INSERT OR DELETE OR UPDATE ON races FOR EACH ROW EXECUTE FUNCTION block_season_transition_protected_write_v1();
CREATE TRIGGER trg_apply_retirement_finalization_effects AFTER UPDATE OF status ON retirement_decisions FOR EACH ROW WHEN (new.status = 'finalized'::text) EXECUTE FUNCTION apply_retirement_finalization_effects();
CREATE TRIGGER trg_rider_contract_negotiations_national_team_country_lock_v1 BEFORE INSERT OR UPDATE OF club_id, rider_id ON rider_contract_negotiations FOR EACH ROW EXECUTE FUNCTION trg_national_team_country_lock_club_rider_pair_v1();
CREATE TRIGGER trg_rider_contract_negotiations_set_updated_at BEFORE UPDATE ON rider_contract_negotiations FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_guard_retired_rider_active_contract_v1 BEFORE INSERT OR UPDATE ON rider_contracts FOR EACH ROW EXECUTE FUNCTION guard_retired_rider_active_contract_v1();
CREATE TRIGGER trg_rider_contracts_national_team_country_lock_v1 BEFORE INSERT OR UPDATE OF club_id, rider_id ON rider_contracts FOR EACH ROW EXECUTE FUNCTION trg_national_team_country_lock_club_rider_pair_v1();
CREATE TRIGGER trg_rider_contracts_set_updated_at BEFORE UPDATE ON rider_contracts FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_rider_contracts_sync_rider_snapshot AFTER INSERT OR DELETE OR UPDATE ON rider_contracts FOR EACH ROW EXECUTE FUNCTION trg_sync_rider_contract_snapshot();
CREATE TRIGGER trg_aaa_training_camp_star_modifiers BEFORE INSERT OR UPDATE ON rider_daily_activity FOR EACH ROW EXECUTE FUNCTION apply_training_camp_star_modifiers_to_activity();
CREATE TRIGGER trg_apply_training_camp_staff_boosts BEFORE INSERT OR UPDATE ON rider_daily_activity FOR EACH ROW EXECUTE FUNCTION trg_apply_training_camp_staff_boosts();
CREATE TRIGGER trg_guard_training_activity_rows BEFORE INSERT OR UPDATE ON rider_daily_activity FOR EACH ROW EXECUTE FUNCTION trg_guard_training_activity_rows();
CREATE TRIGGER trg_zzz_training_activity_development_normalizer BEFORE INSERT OR UPDATE ON rider_daily_activity FOR EACH ROW EXECUTE FUNCTION trg_zzz_training_activity_development_normalizer();
CREATE TRIGGER trg_zzz_training_camp_development_v1 BEFORE INSERT OR UPDATE OF metadata, fatigue_load, participated, activity_type, source ON rider_daily_activity FOR EACH ROW WHEN (new.activity_type = 'training_camp'::text) EXECUTE FUNCTION trg_normalize_training_camp_development_v1();
CREATE TRIGGER trg_zzzz_regular_training_staff_boosts BEFORE INSERT OR UPDATE ON rider_daily_activity FOR EACH ROW EXECUTE FUNCTION trg_apply_regular_training_staff_boosts();
CREATE TRIGGER trg_zzzz_training_camp_weather_effects_v1 BEFORE INSERT OR UPDATE OF metadata, fatigue_load ON rider_daily_activity FOR EACH ROW EXECUTE FUNCTION trg_apply_training_camp_weather_effects_v1();
CREATE TRIGGER trg_zzzzz_training_center_regular_training_v1 BEFORE INSERT OR UPDATE ON rider_daily_activity FOR EACH ROW EXECUTE FUNCTION trg_apply_training_center_regular_training_v1();
CREATE TRIGGER trg_zzzzzz_youth_academy_regular_training_v1 BEFORE INSERT OR UPDATE ON rider_daily_activity FOR EACH ROW EXECUTE FUNCTION trg_apply_youth_academy_regular_training_v1();
CREATE TRIGGER trg_rider_free_agent_negotiations_national_team_country_lock_v1 BEFORE INSERT OR UPDATE OF club_id, rider_id ON rider_free_agent_negotiations FOR EACH ROW EXECUTE FUNCTION trg_national_team_country_lock_club_rider_pair_v1();
CREATE TRIGGER trg_rider_free_agent_negotiations_set_updated_at BEFORE UPDATE ON rider_free_agent_negotiations FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_rider_free_agents_set_updated_at BEFORE UPDATE ON rider_free_agents FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER rider_health_case_context_sync_fatigue_floor_trg AFTER INSERT OR UPDATE OF severity, notes ON rider_health_case_context_v1 FOR EACH ROW EXECUTE FUNCTION health_sync_case_fatigue_floor_v1();
CREATE TRIGGER trg_rider_health_cases_set_updated_at BEFORE UPDATE ON rider_health_cases FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_st_persist_4993d48dbda2 BEFORE INSERT OR DELETE OR UPDATE ON rider_health_cases FOR EACH ROW EXECUTE FUNCTION block_season_transition_protected_write_v1();
CREATE TRIGGER trg_rider_payroll_state_set_updated_at BEFORE UPDATE ON rider_payroll_state FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_apply_race_development_condition_v2 AFTER INSERT ON rider_race_development_events FOR EACH ROW EXECUTE FUNCTION trg_apply_race_development_condition_v2();
CREATE TRIGGER trg_apply_race_development_progress_bank_v1 AFTER INSERT ON rider_race_development_events FOR EACH ROW EXECUTE FUNCTION trg_apply_race_development_progress_bank_v1();
CREATE TRIGGER trg_apply_race_result_morale_v1 AFTER INSERT ON rider_race_development_events FOR EACH ROW EXECUTE FUNCTION trg_apply_race_result_morale_v1();
CREATE TRIGGER trg_youth_academy_race_development_v1 BEFORE INSERT ON rider_race_development_events FOR EACH ROW EXECUTE FUNCTION trg_apply_youth_academy_race_development_v1();
CREATE TRIGGER trg_st_persist_13fc0c9a6b90 BEFORE INSERT OR DELETE OR UPDATE ON rider_regular_training_daily_plans FOR EACH ROW EXECUTE FUNCTION block_season_transition_protected_write_v1();
CREATE TRIGGER trg_st_persist_7da068fa2f82 BEFORE INSERT OR DELETE OR UPDATE ON rider_regular_training_management FOR EACH ROW EXECUTE FUNCTION block_season_transition_protected_write_v1();
CREATE TRIGGER trg_st_persist_510094484b90 BEFORE INSERT OR DELETE OR UPDATE ON rider_regular_training_plans FOR EACH ROW EXECUTE FUNCTION block_season_transition_protected_write_v1();
CREATE TRIGGER trg_rider_transfer_listings_set_updated_at BEFORE UPDATE ON rider_transfer_listings FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_rider_transfer_listings_status_game_ts BEFORE INSERT OR UPDATE ON rider_transfer_listings FOR EACH ROW EXECUTE FUNCTION trg_set_market_status_changed_at_game_ts();
CREATE TRIGGER trg_rider_transfer_negotiations_set_updated_at BEFORE UPDATE ON rider_transfer_negotiations FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_rider_transfer_negotiations_status_game_ts BEFORE INSERT OR UPDATE ON rider_transfer_negotiations FOR EACH ROW EXECUTE FUNCTION trg_set_market_status_changed_at_game_ts();
CREATE TRIGGER trg_rider_transfer_offers_set_updated_at BEFORE UPDATE ON rider_transfer_offers FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_rider_transfer_offers_status_game_ts BEFORE INSERT OR UPDATE ON rider_transfer_offers FOR EACH ROW EXECUTE FUNCTION trg_set_market_status_changed_at_game_ts();
CREATE TRIGGER trg_rider_transfer_offers_status_stamp BEFORE INSERT OR UPDATE OF status ON rider_transfer_offers FOR EACH ROW EXECUTE FUNCTION _stamp_rider_transfer_offer_game_status();
CREATE TRIGGER zzz_guard_ai_transfer_offer_daily_limit BEFORE INSERT ON rider_transfer_offers FOR EACH ROW EXECUTE FUNCTION trg_guard_ai_transfer_offer_daily_limit();
CREATE TRIGGER trg_unsolicited_transfer_bids_set_updated_at BEFORE UPDATE ON rider_unsolicited_transfer_bids FOR EACH ROW EXECUTE FUNCTION trg_unsolicited_transfer_bids_set_updated_at();
CREATE TRIGGER trg_guard_retired_rider_terminal_status_v1 BEFORE UPDATE ON riders FOR EACH ROW EXECUTE FUNCTION guard_retired_rider_terminal_status_v1();
CREATE TRIGGER trg_guard_rider_persistence_during_transition_v1 BEFORE INSERT OR DELETE OR UPDATE ON riders FOR EACH ROW EXECUTE FUNCTION guard_rider_persistence_during_transition_v1();
CREATE TRIGGER trg_notify_rider_negative_morale_state_v1 AFTER UPDATE OF morale, morale_updated_on, low_morale_since, asked_for_more_selection, release_requested ON riders FOR EACH ROW WHEN (COALESCE(old.asked_for_more_selection, false) = false AND COALESCE(new.asked_for_more_selection, false) = true OR COALESCE(old.morale::integer, 50) > 39 AND COALESCE(new.morale::integer, 50) <= 39 OR old.low_morale_since IS NULL AND new.low_morale_since IS NOT NULL OR COALESCE(old.release_requested, false) = false AND COALESCE(new.release_requested, false) = true) EXECUTE FUNCTION notify_rider_negative_morale_state_v1();
CREATE TRIGGER trg_record_rider_skill_snapshot_v1 AFTER UPDATE OF sprint, climbing, time_trial, endurance, flat, recovery, resistance, race_iq, teamwork ON riders FOR EACH ROW WHEN (old.sprint IS DISTINCT FROM new.sprint OR old.climbing IS DISTINCT FROM new.climbing OR old.time_trial IS DISTINCT FROM new.time_trial OR old.endurance IS DISTINCT FROM new.endurance OR old.flat IS DISTINCT FROM new.flat OR old.recovery IS DISTINCT FROM new.recovery OR old.resistance IS DISTINCT FROM new.resistance OR old.race_iq IS DISTINCT FROM new.race_iq OR old.teamwork IS DISTINCT FROM new.teamwork) EXECUTE FUNCTION trg_record_rider_skill_snapshot_v1();
CREATE TRIGGER trg_refresh_market_value_on_riders AFTER INSERT OR UPDATE OF salary, birth_date, contract_expires_at, morale, release_requested, potential, overall, role, sprint, climbing, time_trial, endurance, flat, recovery, resistance, race_iq, teamwork ON riders FOR EACH ROW EXECUTE FUNCTION trg_refresh_rider_market_value();
CREATE TRIGGER trg_riders_national_team_country_lock_v1 BEFORE UPDATE OF country_code ON riders FOR EACH ROW EXECUTE FUNCTION trg_riders_national_team_country_lock_v1();
CREATE TRIGGER trg_staff_advisory_head_coach_skill_change_v1 AFTER UPDATE OF sprint, climbing, flat, time_trial, endurance, teamwork, race_iq, recovery ON riders FOR EACH ROW WHEN (old.sprint IS DISTINCT FROM new.sprint OR old.climbing IS DISTINCT FROM new.climbing OR old.flat IS DISTINCT FROM new.flat OR old.time_trial IS DISTINCT FROM new.time_trial OR old.endurance IS DISTINCT FROM new.endurance OR old.teamwork IS DISTINCT FROM new.teamwork OR old.race_iq IS DISTINCT FROM new.race_iq OR old.recovery IS DISTINCT FROM new.recovery) EXECUTE FUNCTION staff_advisory_notify_head_coach_skill_change_v1();
CREATE TRIGGER gcc_live_migration_readiness AFTER INSERT OR DELETE OR UPDATE ON season_transition_component_readiness_v1 FOR EACH STATEMENT EXECUTE FUNCTION control_center_private.notify_admin_module_snapshot('migration-process', '10');
CREATE TRIGGER gcc_live_migration_control AFTER INSERT OR DELETE OR UPDATE ON season_transition_control_v1 FOR EACH STATEMENT EXECUTE FUNCTION control_center_private.notify_admin_module_snapshot('migration-process', '10');
CREATE TRIGGER gcc_live_migration_events AFTER INSERT OR DELETE OR UPDATE ON season_transition_engine_events_v2 FOR EACH STATEMENT EXECUTE FUNCTION control_center_private.notify_admin_module_snapshot('migration-process', '10');
CREATE TRIGGER gcc_live_migration_runs AFTER INSERT OR DELETE OR UPDATE ON season_transition_engine_runs_v2 FOR EACH STATEMENT EXECUTE FUNCTION control_center_private.notify_admin_module_snapshot('migration-process', '10');
CREATE TRIGGER trg_sponsor_companies_set_updated_at BEFORE UPDATE ON sponsor_companies FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_sponsor_company_eligibility_set_updated_at BEFORE UPDATE ON sponsor_company_eligibility FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_st_persist_6a3666e2fb0e BEFORE INSERT OR DELETE OR UPDATE ON staff_advisory_access FOR EACH ROW EXECUTE FUNCTION block_season_transition_protected_write_v1();
CREATE TRIGGER trg_staff_advisory_after_access_change_v1 AFTER INSERT OR UPDATE OF staff_id, expires_at ON staff_advisory_access FOR EACH ROW EXECUTE FUNCTION staff_advisory_after_access_change_v1();
CREATE TRIGGER trg_st_persist_3b77c66229c3 BEFORE INSERT OR DELETE OR UPDATE ON staff_advisory_event_state FOR EACH ROW EXECUTE FUNCTION block_season_transition_protected_write_v1();
CREATE TRIGGER trg_st_persist_f0f94d8d0d57 BEFORE INSERT OR DELETE OR UPDATE ON staff_advisory_medical_case_state FOR EACH ROW EXECUTE FUNCTION block_season_transition_protected_write_v1();
CREATE TRIGGER trg_st_persist_e8127f2e27e6 BEFORE INSERT OR DELETE OR UPDATE ON staff_advisory_purchases FOR EACH ROW EXECUTE FUNCTION block_season_transition_protected_write_v1();
CREATE TRIGGER trg_st_persist_0a2560834812 BEFORE INSERT OR DELETE OR UPDATE ON staff_advisory_reports FOR EACH ROW EXECUTE FUNCTION block_season_transition_protected_write_v1();
CREATE TRIGGER trg_staff_advisory_enrich_report_riders_v1 BEFORE INSERT OR UPDATE OF report_json, summary, role_type ON staff_advisory_reports FOR EACH ROW EXECUTE FUNCTION staff_advisory_enrich_report_riders_trg_v1();
CREATE TRIGGER trg_staff_candidates_set_updated_at BEFORE UPDATE ON staff_candidates FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_sync_staff_identity_fields_staff_candidates BEFORE INSERT OR UPDATE ON staff_candidates FOR EACH ROW EXECUTE FUNCTION sync_staff_identity_fields();
CREATE TRIGGER gcc_live_health_incidents AFTER INSERT OR DELETE OR UPDATE ON system_incidents FOR EACH STATEMENT EXECUTE FUNCTION control_center_private.notify_admin_module_snapshot('system-health', '20');
CREATE TRIGGER gcc_live_health_runs AFTER INSERT OR DELETE OR UPDATE ON system_monitor_runs FOR EACH STATEMENT EXECUTE FUNCTION control_center_private.notify_admin_module_snapshot('system-health', '20');
CREATE TRIGGER trg_team_policy_option_catalog_set_updated_at BEFORE UPDATE ON team_policy_option_catalog FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_team_trip_cost_forecasts_set_updated_at BEFORE UPDATE ON team_trip_cost_forecasts FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_st_persist_7f61c957358c BEFORE INSERT OR DELETE OR UPDATE ON training_camp_bookings FOR EACH ROW EXECUTE FUNCTION block_season_transition_protected_write_v1();
CREATE TRIGGER trg_training_camp_bookings_fill_snapshots BEFORE INSERT OR UPDATE ON training_camp_bookings FOR EACH ROW EXECUTE FUNCTION trg_training_camp_bookings_fill_snapshots();
CREATE TRIGGER trg_st_persist_138c3a4833bb BEFORE INSERT OR DELETE OR UPDATE ON training_camp_daily_reports FOR EACH ROW EXECUTE FUNCTION block_season_transition_protected_write_v1();
CREATE TRIGGER trg_sync_training_camp_activity_from_report AFTER INSERT ON training_camp_daily_reports FOR EACH ROW EXECUTE FUNCTION trg_sync_training_camp_activity_from_report();
CREATE TRIGGER trg_st_persist_e81bc3724b00 BEFORE INSERT OR DELETE OR UPDATE ON training_camp_day_training_plans FOR EACH ROW EXECUTE FUNCTION block_season_transition_protected_write_v1();
CREATE TRIGGER trg_st_persist_75ca3e1b3b88 BEFORE INSERT OR DELETE OR UPDATE ON training_camp_notification_log FOR EACH ROW EXECUTE FUNCTION block_season_transition_protected_write_v1();
CREATE TRIGGER trg_st_persist_76c0f325ad6a BEFORE INSERT OR DELETE OR UPDATE ON training_camp_participants FOR EACH ROW EXECUTE FUNCTION block_season_transition_protected_write_v1();
CREATE TRIGGER trg_st_persist_af5d3fa0db3d BEFORE INSERT OR DELETE OR UPDATE ON training_camp_staff_assignments FOR EACH ROW EXECUTE FUNCTION block_season_transition_protected_write_v1();
CREATE TRIGGER trg_guard_coin_ledger_persistence_during_transition_v1 BEFORE INSERT OR DELETE OR UPDATE ON user_coin_ledger FOR EACH ROW EXECUTE FUNCTION guard_coin_ledger_persistence_during_transition_v1();
CREATE TRIGGER trg_notify_user_low_coins_after_ledger_insert_v1 AFTER INSERT ON user_coin_ledger FOR EACH ROW EXECUTE FUNCTION notify_user_low_coins_after_ledger_insert_v1();
CREATE TRIGGER trg_st_persist_1dae673ff088 BEFORE INSERT OR DELETE OR UPDATE ON user_premium_subscriptions FOR EACH ROW EXECUTE FUNCTION block_season_transition_protected_write_v1();
CREATE TRIGGER user_premium_subscriptions_set_updated_at BEFORE UPDATE ON user_premium_subscriptions FOR EACH ROW EXECUTE FUNCTION premium_set_updated_at_v1();
CREATE TRIGGER trg_touch_user_tutorial_progress_updated_at BEFORE UPDATE ON user_tutorial_progress FOR EACH ROW EXECUTE FUNCTION touch_user_tutorial_progress_updated_at();
CREATE TRIGGER trg_guard_wallet_persistence_during_transition_v1 BEFORE INSERT OR DELETE OR UPDATE ON user_wallets FOR EACH ROW EXECUTE FUNCTION guard_wallet_persistence_during_transition_v1();
CREATE TRIGGER trg_user_wallets_set_updated_at BEFORE UPDATE ON user_wallets FOR EACH ROW EXECUTE FUNCTION set_updated_at();