-- Premium Youth Academy / U16 - competition hierarchy v1
-- Results-only racing with World / Continental West-East / Regional classes,
-- city-based race generation, invitations, wildcards and monthly participation plans.

alter table public.youth_races
  add column if not exists competition_class text not null default 'regional';
alter table public.youth_races
  add column if not exists division_code text;
alter table public.youth_races
  add column if not exists host_city text;
alter table public.youth_races
  add column if not exists host_country_code text;
alter table public.youth_races
  add column if not exists team_limit smallint not null default 16;
alter table public.youth_races
  add column if not exists race_days smallint not null default 1;
alter table public.youth_races
  add column if not exists race_end_date date;
alter table public.youth_races
  add column if not exists invitation_response_deadline date;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname='youth_races_competition_class_check'
      and conrelid='public.youth_races'::regclass
  ) then
    alter table public.youth_races
      add constraint youth_races_competition_class_check
      check(competition_class in ('world','continental','regional'));
  end if;
  if not exists (
    select 1 from pg_constraint
    where conname='youth_races_team_limit_check'
      and conrelid='public.youth_races'::regclass
  ) then
    alter table public.youth_races
      add constraint youth_races_team_limit_check
      check(team_limit between 8 and 24);
  end if;
  if not exists (
    select 1 from pg_constraint
    where conname='youth_races_race_days_check'
      and conrelid='public.youth_races'::regclass
  ) then
    alter table public.youth_races
      add constraint youth_races_race_days_check
      check(race_days between 1 and 7);
  end if;
end $$;

update public.youth_races
set race_end_date=coalesce(race_end_date,race_date)
where race_end_date is null;

create index if not exists youth_races_class_division_date_idx
on public.youth_races(season_number,competition_class,division_code,race_date);

create table if not exists public.youth_race_host_cities(
  id bigint generated by default as identity primary key,
  division_code text not null,
  country_code text not null,
  city_name text not null,
  sort_order smallint not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  unique(division_code,country_code,city_name)
);

create table if not exists public.youth_academy_competition_memberships(
  season_number integer not null,
  academy_id uuid not null references public.youth_academies(id) on delete cascade,
  competition_class text not null
    check(competition_class in ('world','continental','regional')),
  division_code text not null,
  seed_rank integer,
  assigned_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb,
  primary key(season_number,academy_id)
);

create index if not exists youth_academy_memberships_class_division_idx
on public.youth_academy_competition_memberships(
  season_number,competition_class,division_code
);

create table if not exists public.youth_race_invitations(
  race_id uuid not null references public.youth_races(id) on delete cascade,
  academy_id uuid not null references public.youth_academies(id) on delete cascade,
  invitation_type text not null
    check(invitation_type in (
      'world_class','wildcard','continental_pool','regional_local'
    )),
  status text not null default 'pending'
    check(status in ('pending','accepted','declined','expired','waitlist')),
  invited_on date not null,
  response_deadline date,
  responded_on date,
  priority_score numeric(10,3) not null default 0,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key(race_id,academy_id)
);

create index if not exists youth_race_invitations_academy_status_idx
on public.youth_race_invitations(academy_id,status,race_id);

create table if not exists public.youth_monthly_race_plans(
  academy_id uuid not null references public.youth_academies(id) on delete cascade,
  season_number integer not null,
  month_number smallint not null check(month_number between 1 and 12),
  world_race_limit smallint not null default 0 check(world_race_limit between 0 and 6),
  continental_race_limit smallint not null default 0 check(continental_race_limit between 0 and 10),
  regional_race_limit smallint not null default 0 check(regional_race_limit between 0 and 6),
  max_monthly_cost bigint not null default 0 check(max_monthly_cost>=0),
  approved boolean not null default false,
  approved_by_user_id uuid,
  approved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key(academy_id,season_number,month_number)
);

alter table public.youth_race_host_cities enable row level security;
alter table public.youth_academy_competition_memberships enable row level security;
alter table public.youth_race_invitations enable row level security;
alter table public.youth_monthly_race_plans enable row level security;

revoke all privileges on table public.youth_race_host_cities from anon,authenticated;
revoke all privileges on table public.youth_academy_competition_memberships from anon,authenticated;
revoke all privileges on table public.youth_race_invitations from anon,authenticated;
revoke all privileges on table public.youth_monthly_race_plans from anon,authenticated;

insert into public.youth_race_host_cities(
  division_code,country_code,city_name,sort_order
)
values
('NORTH_AMERICA','US','Boulder',1),
('NORTH_AMERICA','US','Asheville',2),
('NORTH_AMERICA','US','Madison',3),
('NORTH_AMERICA','CA','Victoria',4),
('NORTH_AMERICA','CA','Kelowna',5),
('NORTH_AMERICA','MX','Oaxaca',6),
('SOUTH_AMERICA','CO','Medellín',1),
('SOUTH_AMERICA','AR','Mendoza',2),
('SOUTH_AMERICA','BR','Curitiba',3),
('SOUTH_AMERICA','CL','Valdivia',4),
('SOUTH_AMERICA','PE','Arequipa',5),
('SOUTH_AMERICA','EC','Cuenca',6),
('WESTERN_EUROPE','BE','Ghent',1),
('WESTERN_EUROPE','FR','Roubaix',2),
('WESTERN_EUROPE','ES','Girona',3),
('WESTERN_EUROPE','PT','Braga',4),
('WESTERN_EUROPE','NL','Utrecht',5),
('WESTERN_EUROPE','IE','Cork',6),
('CENTRAL_EUROPE','DE','Freiburg',1),
('CENTRAL_EUROPE','AT','Innsbruck',2),
('CENTRAL_EUROPE','CH','Basel',3),
('CENTRAL_EUROPE','CZ','Brno',4),
('CENTRAL_EUROPE','PL','Kraków',5),
('CENTRAL_EUROPE','SK','Košice',6),
('SOUTHERN_BALKAN_EUROPE','HR','Split',1),
('SOUTHERN_BALKAN_EUROPE','IT','Modena',2),
('SOUTHERN_BALKAN_EUROPE','RS','Novi Sad',3),
('SOUTHERN_BALKAN_EUROPE','SI','Maribor',4),
('SOUTHERN_BALKAN_EUROPE','BA','Mostar',5),
('SOUTHERN_BALKAN_EUROPE','MK','Ohrid',6),
('NORTHERN_EASTERN_EUROPE','DK','Aarhus',1),
('NORTHERN_EASTERN_EUROPE','SE','Uppsala',2),
('NORTHERN_EASTERN_EUROPE','NO','Bergen',3),
('NORTHERN_EASTERN_EUROPE','FI','Tampere',4),
('NORTHERN_EASTERN_EUROPE','EE','Tartu',5),
('NORTHERN_EASTERN_EUROPE','UA','Lviv',6),
('WEST_NORTH_AFRICA','MA','Agadir',1),
('WEST_NORTH_AFRICA','DZ','Oran',2),
('WEST_NORTH_AFRICA','TN','Sfax',3),
('WEST_NORTH_AFRICA','EG','Alexandria',4),
('WEST_NORTH_AFRICA','SN','Dakar',5),
('WEST_NORTH_AFRICA','GH','Kumasi',6),
('CENTRAL_SOUTH_AFRICA','KE','Nairobi',1),
('CENTRAL_SOUTH_AFRICA','TZ','Arusha',2),
('CENTRAL_SOUTH_AFRICA','RW','Kigali',3),
('CENTRAL_SOUTH_AFRICA','ZA','Cape Town',4),
('CENTRAL_SOUTH_AFRICA','NA','Windhoek',5),
('CENTRAL_SOUTH_AFRICA','ZM','Lusaka',6),
('WEST_CENTRAL_ASIA','TR','Izmir',1),
('WEST_CENTRAL_ASIA','IR','Shiraz',2),
('WEST_CENTRAL_ASIA','KZ','Almaty',3),
('WEST_CENTRAL_ASIA','UZ','Samarkand',4),
('WEST_CENTRAL_ASIA','AE','Al Ain',5),
('WEST_CENTRAL_ASIA','OM','Salalah',6),
('SOUTH_ASIA','IN','Pune',1),
('SOUTH_ASIA','IN','Chandigarh',2),
('SOUTH_ASIA','PK','Lahore',3),
('SOUTH_ASIA','NP','Pokhara',4),
('SOUTH_ASIA','LK','Kandy',5),
('SOUTH_ASIA','BD','Chattogram',6),
('EAST_SOUTHEAST_ASIA','TH','Chiang Mai',1),
('EAST_SOUTHEAST_ASIA','VN','Da Nang',2),
('EAST_SOUTHEAST_ASIA','JP','Kyoto',3),
('EAST_SOUTHEAST_ASIA','KR','Busan',4),
('EAST_SOUTHEAST_ASIA','ID','Bandung',5),
('EAST_SOUTHEAST_ASIA','MY','Penang',6),
('OCEANIA','AU','Adelaide',1),
('OCEANIA','AU','Hobart',2),
('OCEANIA','AU','Geelong',3),
('OCEANIA','NZ','Christchurch',4),
('OCEANIA','NZ','Rotorua',5),
('OCEANIA','FJ','Suva',6)
on conflict(division_code,country_code,city_name) do update
set sort_order=excluded.sort_order,is_active=true;

create or replace function private.youth_continental_division_for_country_v1(
  p_country_code text
)
returns text
language sql
immutable
set search_path=public,pg_temp
as $function$
  select case public.get_expected_tier2_division_for_country(p_country_code)
    when 'PRO_WEST' then 'CONTINENTAL_WEST'
    when 'PRO_EAST' then 'CONTINENTAL_EAST'
    else 'CONTINENTAL_EAST'
  end;
$function$;

create or replace function private.youth_academy_strength_v1(
  p_academy_id uuid
)
returns numeric
language sql
stable
security definer
set search_path=public,pg_temp
as $function$
  select
    coalesce(a.reputation,0)::numeric*0.35
    +coalesce((
      select avg((
        r.sprint+r.climbing+r.time_trial+r.endurance+r.flat+r.recovery+
        r.resistance+r.race_iq+r.teamwork
      )::numeric/9.0)
      from public.youth_riders r
      where r.academy_id=a.id and r.status='academy'
    ),0)
  from public.youth_academies a
  where a.id=p_academy_id;
$function$;

create or replace function public.ensure_youth_competition_memberships_v1(
  p_season integer default null
)
returns jsonb
language plpgsql
security definer
set search_path=public,private,pg_temp
as $function$
declare
  v_season integer:=coalesce(p_season,public.get_current_season_number(),1);
begin
  if not exists(
    select 1 from public.youth_academy_competition_memberships
    where season_number=v_season
  ) then
    with ranked as (
      select a.id academy_id,
        row_number() over(
          order by private.youth_academy_strength_v1(a.id) desc,a.id
        )::integer rn
      from public.youth_academies a
      where a.is_active=true
    )
    insert into public.youth_academy_competition_memberships(
      season_number,academy_id,competition_class,division_code,seed_rank,metadata
    )
    select v_season,academy_id,'world','WORLD',rn,
      jsonb_build_object('assignment','initial_strength_top_16')
    from ranked
    where rn<=16;

    with remaining as (
      select a.id academy_id,
        private.youth_continental_division_for_country_v1(c.country_code) division_code,
        private.youth_academy_strength_v1(a.id) strength
      from public.youth_academies a
      join public.clubs c on c.id=a.club_id
      where a.is_active=true
        and not exists(
          select 1 from public.youth_academy_competition_memberships m
          where m.season_number=v_season and m.academy_id=a.id
        )
    ),
    ranked as (
      select r.*,
        row_number() over(
          partition by division_code order by strength desc,academy_id
        )::integer rn
      from remaining r
    )
    insert into public.youth_academy_competition_memberships(
      season_number,academy_id,competition_class,division_code,seed_rank,metadata
    )
    select v_season,academy_id,'continental',division_code,rn,
      jsonb_build_object('assignment','initial_continental_top_8')
    from ranked
    where rn<=8;

    insert into public.youth_academy_competition_memberships(
      season_number,academy_id,competition_class,division_code,seed_rank,metadata
    )
    select
      v_season,a.id,'regional',
      coalesce(public.get_amateur_division_for_country(c.country_code),'OTHER'),
      null,
      jsonb_build_object('assignment','initial_regional')
    from public.youth_academies a
    join public.clubs c on c.id=a.club_id
    where a.is_active=true
      and not exists(
        select 1 from public.youth_academy_competition_memberships m
        where m.season_number=v_season and m.academy_id=a.id
      );
  end if;

  insert into public.youth_academy_competition_memberships(
    season_number,academy_id,competition_class,division_code,metadata
  )
  select
    v_season,a.id,'regional',
    coalesce(public.get_amateur_division_for_country(c.country_code),'OTHER'),
    jsonb_build_object('assignment','midseason_new_academy')
  from public.youth_academies a
  join public.clubs c on c.id=a.club_id
  where a.is_active=true
    and not exists(
      select 1 from public.youth_academy_competition_memberships m
      where m.season_number=v_season and m.academy_id=a.id
    )
  on conflict(season_number,academy_id) do nothing;

  return jsonb_build_object(
    'season_number',v_season,
    'world',(
      select count(*) from public.youth_academy_competition_memberships
      where season_number=v_season and competition_class='world'
    ),
    'continental_west',(
      select count(*) from public.youth_academy_competition_memberships
      where season_number=v_season and division_code='CONTINENTAL_WEST'
    ),
    'continental_east',(
      select count(*) from public.youth_academy_competition_memberships
      where season_number=v_season and division_code='CONTINENTAL_EAST'
    ),
    'regional',(
      select count(*) from public.youth_academy_competition_memberships
      where season_number=v_season and competition_class='regional'
    )
  );
end;
$function$;

revoke all on function public.ensure_youth_competition_memberships_v1(integer)
from public,anon,authenticated;
grant execute on function public.ensure_youth_competition_memberships_v1(integer)
to service_role;

create or replace function private.ensure_youth_monthly_race_plan_v1(
  p_academy_id uuid,
  p_season integer,
  p_month integer
)
returns void
language plpgsql
security definer
set search_path=public,private,pg_temp
as $function$
declare
  v_class text;
  v_is_ai boolean:=false;
begin
  select m.competition_class,a.is_ai
  into v_class,v_is_ai
  from public.youth_academy_competition_memberships m
  join public.youth_academies a on a.id=m.academy_id
  where m.season_number=p_season and m.academy_id=p_academy_id;

  if v_class is null then return; end if;

  insert into public.youth_monthly_race_plans(
    academy_id,season_number,month_number,
    world_race_limit,continental_race_limit,regional_race_limit,
    max_monthly_cost,approved,approved_at
  )
  values(
    p_academy_id,p_season,p_month,
    case v_class when 'world' then 3 when 'continental' then 1 else 0 end,
    case v_class when 'world' then 2 when 'continental' then 4 else 2 end,
    case v_class when 'world' then 2 when 'continental' then 3 else 5 end,
    case v_class when 'world' then 10000 when 'continental' then 7000 else 5000 end,
    v_is_ai,
    case when v_is_ai then now() else null end
  )
  on conflict(academy_id,season_number,month_number) do nothing;
end;
$function$;

create or replace function private.pick_youth_race_host_city_v1(
  p_scope text,
  p_seed integer
)
returns table(city_name text,country_code text,division_code text)
language sql
stable
set search_path=public,private,pg_temp
as $function$
  select h.city_name,h.country_code,h.division_code
  from public.youth_race_host_cities h
  where h.is_active=true
    and (
      p_scope='WORLD'
      or (
        p_scope='CONTINENTAL_WEST'
        and private.youth_continental_division_for_country_v1(h.country_code)='CONTINENTAL_WEST'
      )
      or (
        p_scope='CONTINENTAL_EAST'
        and private.youth_continental_division_for_country_v1(h.country_code)='CONTINENTAL_EAST'
      )
      or h.division_code=p_scope
    )
  order by md5(p_seed::text||':'||h.id::text)
  limit 1;
$function$;

create or replace function private.youth_generated_race_name_v1(
  p_class text,
  p_city text,
  p_slot integer
)
returns text
language sql
immutable
as $function$
  select case p_class
    when 'world' then case mod(p_slot-1,5)
      when 0 then 'Youth World Cup – '||p_city
      when 1 then p_city||' U16 Grand Prix'
      when 2 then 'Youth World Classic – '||p_city
      when 3 then p_city||' International Youth Trophy'
      else 'World Youth Challenge – '||p_city end
    when 'continental' then case mod(p_slot-1,5)
      when 0 then p_city||' Continental Youth Cup'
      when 1 then p_city||' U16 Classic'
      when 2 then 'Continental Youth Trophy – '||p_city
      when 3 then 'Grand Prix '||p_city||' U16'
      else p_city||' Youth Challenge' end
    else case mod(p_slot-1,6)
      when 0 then p_city||' Youth Cup'
      when 1 then 'Grand Prix '||p_city||' U16'
      when 2 then p_city||' Junior Trophy'
      when 3 then p_city||' Youth Classic'
      when 4 then 'Prize of '||p_city||' U16'
      else p_city||' Regional Challenge' end
  end;
$function$;

create or replace function public.seed_youth_race_calendar_for_season_v1(
  p_season integer default null
)
returns jsonb
language plpgsql
security definer
set search_path=public,private,pg_temp
as $function$
declare
  v_season integer:=coalesce(p_season,public.get_current_season_number(),1);
  v_month integer;
  v_slot integer;
  v_day integer;
  v_division text;
  v_city text;
  v_country text;
  v_host_regional text;
  v_region text;
  v_date date;
  v_end_date date;
  v_days integer;
  v_terrain text;
  v_name text;
  v_race_id uuid;
  v_inserted integer:=0;
  v_regional_divisions text[]:=array[
    'NORTH_AMERICA','SOUTH_AMERICA','WESTERN_EUROPE','CENTRAL_EUROPE',
    'SOUTHERN_BALKAN_EUROPE','NORTHERN_EASTERN_EUROPE',
    'WEST_NORTH_AFRICA','CENTRAL_SOUTH_AFRICA','WEST_CENTRAL_ASIA',
    'SOUTH_ASIA','EAST_SOUTHEAST_ASIA','OCEANIA'
  ];
begin
  perform public.ensure_youth_competition_memberships_v1(v_season);

  for v_month in 1..12 loop
    for v_slot in 1..5 loop
      v_day:=case v_slot when 1 then 4 when 2 then 9 when 3 then 14 when 4 then 19 else 24 end;
      v_date:=public.game_date_from_parts(v_season,v_month,v_day);
      v_days:=case
        when v_slot=2 and v_month in (6,9) then 6
        when v_slot=3 and v_month in (3,12) then 3
        else 1
      end;
      v_end_date:=v_date+(v_days-1);
      select city_name,country_code,division_code
      into v_city,v_country,v_host_regional
      from private.pick_youth_race_host_city_v1(
        'WORLD',v_season*10000+v_month*100+v_slot
      );
      v_name:=private.youth_generated_race_name_v1('world',v_city,v_slot);
      v_terrain:=(array['flat','hilly','mountain','mixed','time_trial'])
        [1+mod(v_month+v_slot,5)];

      insert into public.youth_races(
        season_number,race_date,race_name,race_level,region_code,terrain_type,
        distance_km,entry_cost,lineup_size,qualification_rank_limit,status,
        competition_class,division_code,host_city,host_country_code,
        team_limit,race_days,race_end_date,invitation_response_deadline,metadata
      )
      values(
        v_season,v_date,v_name,
        case when v_month=12 and v_slot=5 then 'world_final' else 'world_series' end,
        'world',v_terrain,
        least(120,72+v_days*7+v_slot*2),600+v_days*140,5,null,'scheduled',
        'world','WORLD',v_city,v_country,20,v_days,v_end_date,v_date-14,
        jsonb_build_object(
          'calendar_source','youth_hierarchy_v1',
          'results_only',true,'replay_available',false,
          'host_regional_division',v_host_regional
        )
      )
      on conflict(season_number,race_date,race_name) do update
      set competition_class=excluded.competition_class,
          division_code=excluded.division_code,
          host_city=excluded.host_city,
          host_country_code=excluded.host_country_code,
          team_limit=excluded.team_limit,
          race_days=excluded.race_days,
          race_end_date=excluded.race_end_date,
          invitation_response_deadline=excluded.invitation_response_deadline,
          metadata=excluded.metadata,
          updated_at=now()
      returning id into v_race_id;

      insert into public.youth_race_invitations(
        race_id,academy_id,invitation_type,status,invited_on,response_deadline,
        priority_score,metadata
      )
      select
        v_race_id,m.academy_id,'world_class','pending',v_date-28,v_date-14,
        1000-coalesce(m.seed_rank,999),
        jsonb_build_object('source','all_world_class')
      from public.youth_academy_competition_memberships m
      where m.season_number=v_season and m.competition_class='world'
      on conflict(race_id,academy_id) do nothing;

      v_inserted:=v_inserted+1;
    end loop;

    foreach v_division in array array['CONTINENTAL_WEST','CONTINENTAL_EAST'] loop
      for v_slot in 1..5 loop
        v_day:=case v_slot when 1 then 3 when 2 then 8 when 3 then 13 when 4 then 18 else 23 end;
        v_date:=public.game_date_from_parts(v_season,v_month,v_day);
        v_days:=case when v_slot=3 and v_month in (4,8) then 2 else 1 end;
        v_end_date:=v_date+(v_days-1);
        select city_name,country_code,division_code
        into v_city,v_country,v_host_regional
        from private.pick_youth_race_host_city_v1(
          v_division,
          v_season*20000+v_month*200+v_slot+
            case when v_division='CONTINENTAL_EAST' then 50 else 0 end
        );
        v_region:=private.youth_region_for_country_v1(v_country);
        v_name:=private.youth_generated_race_name_v1(
          'continental',v_city,
          v_slot+case when v_division='CONTINENTAL_EAST' then 5 else 0 end
        );
        v_terrain:=(array['flat','hilly','mountain','mixed','time_trial'])
          [1+mod(v_month+v_slot+
            case when v_division='CONTINENTAL_EAST' then 2 else 0 end,5)];

        insert into public.youth_races(
          season_number,race_date,race_name,race_level,region_code,terrain_type,
          distance_km,entry_cost,lineup_size,qualification_rank_limit,status,
          competition_class,division_code,host_city,host_country_code,
          team_limit,race_days,race_end_date,invitation_response_deadline,metadata
        )
        values(
          v_season,v_date,v_name,'regional',v_region,v_terrain,
          least(105,58+v_days*6+v_slot*2),350+v_days*90,5,null,'scheduled',
          'continental',v_division,v_city,v_country,20,v_days,v_end_date,v_date-7,
          jsonb_build_object(
            'calendar_source','youth_hierarchy_v1',
            'results_only',true,'replay_available',false,
            'host_regional_division',v_host_regional
          )
        )
        on conflict(season_number,race_date,race_name) do update
        set competition_class=excluded.competition_class,
            division_code=excluded.division_code,
            host_city=excluded.host_city,
            host_country_code=excluded.host_country_code,
            team_limit=excluded.team_limit,
            race_days=excluded.race_days,
            race_end_date=excluded.race_end_date,
            invitation_response_deadline=excluded.invitation_response_deadline,
            metadata=excluded.metadata,
            updated_at=now()
        returning id into v_race_id;

        insert into public.youth_race_invitations(
          race_id,academy_id,invitation_type,status,invited_on,response_deadline,
          priority_score,metadata
        )
        select
          v_race_id,x.academy_id,'continental_pool','pending',v_date-21,v_date-7,
          x.priority_score,
          jsonb_build_object('source','continental_weighted_pool')
        from (
          select
            a.id academy_id,
            (
              case
                when public.get_amateur_division_for_country(c.country_code)=v_host_regional
                  then 30 else 0
              end
              +case m.competition_class
                when 'continental' then 20 when 'world' then 16 else 10 end
              +private.youth_academy_strength_v1(a.id)*0.05
              +private.youth_deterministic_fraction_v1(
                v_race_id::text||a.id::text||'continental_invite'
              )*8
            )::numeric priority_score
          from public.youth_academies a
          join public.clubs c on c.id=a.club_id
          join public.youth_academy_competition_memberships m
            on m.academy_id=a.id and m.season_number=v_season
          where a.is_active=true
            and private.youth_continental_division_for_country_v1(c.country_code)=v_division
          order by priority_score desc,a.id
          limit 20
        ) x
        on conflict(race_id,academy_id) do nothing;

        v_inserted:=v_inserted+1;
      end loop;
    end loop;

    foreach v_division in array v_regional_divisions loop
      for v_slot in 1..6 loop
        v_day:=case v_slot
          when 1 then 2 when 2 then 6 when 3 then 10
          when 4 then 14 when 5 then 18 else 22 end;
        v_date:=public.game_date_from_parts(v_season,v_month,v_day);
        v_days:=1;
        v_end_date:=v_date;
        select city_name,country_code,division_code
        into v_city,v_country,v_host_regional
        from private.pick_youth_race_host_city_v1(
          v_division,v_season*30000+v_month*300+v_slot+
          array_position(v_regional_divisions,v_division)*10
        );
        v_region:=private.youth_region_for_country_v1(v_country);
        v_name:=private.youth_generated_race_name_v1('regional',v_city,v_slot);
        v_terrain:=(array['flat','hilly','mountain','mixed','time_trial'])
          [1+mod(v_month+v_slot+array_position(v_regional_divisions,v_division),5)];

        insert into public.youth_races(
          season_number,race_date,race_name,race_level,region_code,terrain_type,
          distance_km,entry_cost,lineup_size,qualification_rank_limit,status,
          competition_class,division_code,host_city,host_country_code,
          team_limit,race_days,race_end_date,invitation_response_deadline,metadata
        )
        values(
          v_season,v_date,v_name,'regional',v_region,v_terrain,
          42+v_slot*4+mod(v_month,4)*2,150+v_slot*10,5,null,'scheduled',
          'regional',v_division,v_city,v_country,16,1,v_end_date,v_date-5,
          jsonb_build_object(
            'calendar_source','youth_hierarchy_v1',
            'results_only',true,'replay_available',false,
            'host_regional_division',v_division
          )
        )
        on conflict(season_number,race_date,race_name) do update
        set competition_class=excluded.competition_class,
            division_code=excluded.division_code,
            host_city=excluded.host_city,
            host_country_code=excluded.host_country_code,
            team_limit=excluded.team_limit,
            race_days=excluded.race_days,
            race_end_date=excluded.race_end_date,
            invitation_response_deadline=excluded.invitation_response_deadline,
            metadata=excluded.metadata,
            updated_at=now()
        returning id into v_race_id;

        insert into public.youth_race_invitations(
          race_id,academy_id,invitation_type,status,invited_on,response_deadline,
          priority_score,metadata
        )
        select
          v_race_id,a.id,'regional_local','pending',v_date-18,v_date-5,
          50+private.youth_deterministic_fraction_v1(
            v_race_id::text||a.id::text||'regional_invite'
          )*5,
          jsonb_build_object('source','home_regional_division')
        from public.youth_academies a
        join public.clubs c on c.id=a.club_id
        where a.is_active=true
          and public.get_amateur_division_for_country(c.country_code)=v_division
        on conflict(race_id,academy_id) do nothing;

        v_inserted:=v_inserted+1;
      end loop;
    end loop;
  end loop;

  return jsonb_build_object(
    'season_number',v_season,
    'races_processed',v_inserted,
    'world_per_month',5,
    'continental_per_month',10,
    'regional_per_division_per_month',6,
    'results_only',true,
    'replay_available',false
  );
end;
$function$;

revoke all on function public.seed_youth_race_calendar_for_season_v1(integer)
from public,anon,authenticated;
grant execute on function public.seed_youth_race_calendar_for_season_v1(integer)
to service_role;

create or replace function private.youth_race_rider_eligible_v1(
  p_rider_id uuid,
  p_race_date date
)
returns boolean
language plpgsql
stable
security definer
set search_path=public,private,pg_temp
as $function$
declare
  v_rider public.youth_riders%rowtype;
  v_age integer;
  v_recent_starts integer;
begin
  select * into v_rider from public.youth_riders where id=p_rider_id;
  if v_rider.id is null or v_rider.status<>'academy' then return false; end if;

  v_age:=extract(year from age(p_race_date,v_rider.birth_date))::integer;
  if v_age<12 or v_age>16 then return false; end if;

  select count(distinct x.race_id)::integer
  into v_recent_starts
  from (
    select rr.race_id
    from public.youth_race_results rr
    join public.youth_races r on r.id=rr.race_id
    where rr.youth_rider_id=p_rider_id
      and rr.result_status in ('finished','dnf')
      and r.race_date>=p_race_date-30
      and r.race_date<p_race_date
    union
    select e.race_id
    from public.youth_race_lineups l
    join public.youth_race_entries e on e.id=l.entry_id
    join public.youth_races r on r.id=e.race_id
    where l.youth_rider_id=p_rider_id
      and e.status='entered'
      and r.race_date>=p_race_date-30
      and r.race_date<p_race_date
  ) x;

  return coalesce(v_recent_starts,0)<private.youth_race_monthly_start_limit_v1(v_age)
    and v_rider.fatigue<78
    and v_rider.readiness>=45;
end;
$function$;

create or replace function private.youth_rider_available_for_race_v1(
  p_rider_id uuid,
  p_race_id uuid
)
returns boolean
language plpgsql
stable
security definer
set search_path=public,private,pg_temp
as $function$
declare
  v_race public.youth_races%rowtype;
begin
  select * into v_race from public.youth_races where id=p_race_id;
  if v_race.id is null then return false; end if;

  if not private.youth_race_rider_eligible_v1(p_rider_id,v_race.race_date) then
    return false;
  end if;

  return not exists(
    select 1
    from public.youth_race_lineups l
    join public.youth_race_entries e on e.id=l.entry_id
    join public.youth_races other on other.id=e.race_id
    where l.youth_rider_id=p_rider_id
      and e.status='entered'
      and other.id<>p_race_id
      and daterange(
        other.race_date,coalesce(other.race_end_date,other.race_date),'[]'
      ) && daterange(
        v_race.race_date,coalesce(v_race.race_end_date,v_race.race_date),'[]'
      )
  );
end;
$function$;

create or replace function private.youth_race_academy_qualified_v1(
  p_academy_id uuid,
  p_race_id uuid
)
returns boolean
language plpgsql
stable
security definer
set search_path=public,private,pg_temp
as $function$
declare
  v_invited boolean:=false;
begin
  select exists(
    select 1 from public.youth_race_invitations i
    where i.race_id=p_race_id and i.academy_id=p_academy_id
      and i.status in ('pending','accepted')
  ) into v_invited;

  if not v_invited then return false; end if;

  return (
    select count(*)>=3
    from public.youth_riders r
    where r.academy_id=p_academy_id
      and private.youth_rider_available_for_race_v1(r.id,p_race_id)
  );
end;
$function$;

create or replace function private.select_youth_race_lineup_v1(
  p_entry_id uuid,
  p_selected_by text default 'u16_head_coach'
)
returns integer
language plpgsql
security definer
set search_path=public,private,pg_temp
as $function$
declare
  v_entry public.youth_race_entries%rowtype;
  v_race public.youth_races%rowtype;
  v_rider record;
  v_slot integer:=0;
  v_coach_score numeric:=50;
begin
  select * into v_entry from public.youth_race_entries where id=p_entry_id;
  if v_entry.id is null then raise exception 'Youth race entry not found'; end if;
  select * into v_race from public.youth_races where id=v_entry.race_id;

  delete from public.youth_race_lineups where entry_id=p_entry_id;

  select coalesce(max(cs.expertise*0.55+cs.experience*0.20+cs.leadership*0.25),50)
  into v_coach_score
  from public.youth_academies a
  left join public.club_staff cs
    on cs.club_id=a.club_id and cs.role_type='u16_head_coach' and cs.is_active=true
  where a.id=v_entry.academy_id;

  for v_rider in
    select r.id,
      private.youth_race_capability_v1(r,v_race.terrain_type)
      +r.readiness*0.13-r.fatigue*0.16
      +v_coach_score*0.05 as selection_score
    from public.youth_riders r
    where r.academy_id=v_entry.academy_id
      and private.youth_rider_available_for_race_v1(r.id,v_race.id)
    order by selection_score desc,r.id
    limit v_race.lineup_size
  loop
    v_slot:=v_slot+1;
    insert into public.youth_race_lineups(
      entry_id,youth_rider_id,slot_no,selected_by
    )
    values(p_entry_id,v_rider.id,v_slot,p_selected_by);
  end loop;

  return v_slot;
end;
$function$;

create or replace function private.enter_youth_race_v1(
  p_academy_id uuid,
  p_race_id uuid,
  p_entered_by text,
  p_strategy text default 'balanced'
)
returns uuid
language plpgsql
security definer
set search_path=public,private,pg_temp
as $function$
declare
  v_race public.youth_races%rowtype;
  v_academy public.youth_academies%rowtype;
  v_budget public.youth_academy_season_budgets%rowtype;
  v_plan public.youth_monthly_race_plans%rowtype;
  v_invitation public.youth_race_invitations%rowtype;
  v_entry_id uuid;
  v_lineup integer;
  v_game_date date:=public.get_current_game_date_date();
  v_month integer;
  v_class_count integer:=0;
  v_class_limit integer:=0;
  v_month_cost bigint:=0;
  v_team_count integer:=0;
  v_squad_decider text;
begin
  select * into v_race from public.youth_races where id=p_race_id for update;
  select * into v_academy from public.youth_academies where id=p_academy_id;
  if v_race.id is null or v_academy.id is null then
    raise exception 'Race or Academy not found';
  end if;
  if v_race.status<>'scheduled' or v_race.race_date<=v_game_date then
    raise exception 'Youth race entry is closed';
  end if;

  select * into v_invitation
  from public.youth_race_invitations
  where race_id=p_race_id and academy_id=p_academy_id
  for update;
  if v_invitation.race_id is null
     or v_invitation.status not in ('pending','accepted') then
    raise exception 'This Academy does not have an active invitation to the Youth race';
  end if;

  if not private.youth_race_academy_qualified_v1(p_academy_id,p_race_id) then
    raise exception 'Academy does not currently have enough eligible Youth Riders';
  end if;

  v_month:=extract(month from v_race.race_date)::integer;
  perform private.ensure_youth_monthly_race_plan_v1(
    p_academy_id,v_race.season_number,v_month
  );
  select * into v_plan
  from public.youth_monthly_race_plans
  where academy_id=p_academy_id
    and season_number=v_race.season_number
    and month_number=v_month
  for update;

  if not v_academy.is_ai and not coalesce(v_plan.approved,false) then
    raise exception 'Approve the monthly Youth race plan before entering races';
  end if;

  v_class_limit:=case v_race.competition_class
    when 'world' then v_plan.world_race_limit
    when 'continental' then v_plan.continental_race_limit
    else v_plan.regional_race_limit
  end;

  select count(*)::integer into v_class_count
  from public.youth_race_entries e
  join public.youth_races r on r.id=e.race_id
  where e.academy_id=p_academy_id
    and e.status in ('entered','completed')
    and r.season_number=v_race.season_number
    and extract(month from r.race_date)::integer=v_month
    and r.competition_class=v_race.competition_class
    and r.id<>p_race_id;

  if v_class_count>=coalesce(v_class_limit,0) then
    raise exception 'Monthly % Youth race limit has been reached',
      v_race.competition_class;
  end if;

  select coalesce(sum(e.entry_cost),0)::bigint into v_month_cost
  from public.youth_race_entries e
  join public.youth_races r on r.id=e.race_id
  where e.academy_id=p_academy_id
    and r.season_number=v_race.season_number
    and extract(month from r.race_date)::integer=v_month
    and r.id<>p_race_id;

  if v_month_cost+v_race.entry_cost>coalesce(v_plan.max_monthly_cost,0) then
    raise exception 'Monthly Youth racing budget limit would be exceeded';
  end if;

  select count(*)::integer into v_team_count
  from public.youth_race_entries e
  where e.race_id=p_race_id and e.status in ('entered','completed');

  if v_team_count>=v_race.team_limit then
    raise exception 'Youth race team limit is already full';
  end if;

  select * into v_budget
  from public.youth_academy_season_budgets
  where academy_id=p_academy_id and season_number=v_race.season_number
  for update;
  if v_budget.academy_id is null then
    raise exception 'Youth Academy season budget not found';
  end if;
  if v_budget.season_budget-v_budget.spent_amount-v_budget.committed_amount<v_race.entry_cost then
    raise exception 'Youth Academy budget is insufficient for race travel/logistics';
  end if;

  insert into public.youth_race_entries(
    race_id,academy_id,entered_on,entered_by,strategy,entry_cost,status
  )
  values(
    p_race_id,p_academy_id,v_game_date,p_entered_by,
    case when p_strategy in ('conservative','balanced','aggressive')
      then p_strategy else 'balanced' end,
    v_race.entry_cost,'entered'
  )
  on conflict(race_id,academy_id) do update
  set status='entered',strategy=excluded.strategy,updated_at=now()
  returning id into v_entry_id;

  update public.youth_race_invitations
  set status='accepted',responded_on=coalesce(responded_on,v_game_date),updated_at=now()
  where race_id=p_race_id and academy_id=p_academy_id;

  if not exists(
    select 1 from public.youth_academy_ledger l
    where l.academy_id=p_academy_id
      and l.category='race_travel'
      and l.metadata->>'race_id'=p_race_id::text
  ) then
    update public.youth_academy_season_budgets
    set spent_amount=spent_amount+v_race.entry_cost,updated_at=now()
    where academy_id=p_academy_id and season_number=v_race.season_number;

    insert into public.youth_academy_ledger(
      academy_id,season_number,game_date,category,description,amount,metadata
    )
    values(
      p_academy_id,v_race.season_number,v_game_date,'race_travel',
      'Youth race travel/logistics: '||v_race.race_name,
      -v_race.entry_cost,
      jsonb_build_object(
        'race_id',p_race_id,
        'competition_class',v_race.competition_class,
        'host_city',v_race.host_city
      )
    );
  end if;

  select coalesce(s.race_squad_decider,'u16_head_coach')
  into v_squad_decider
  from public.youth_academy_settings s
  where s.academy_id=p_academy_id;

  if coalesce(v_squad_decider,'u16_head_coach')='u16_head_coach'
     or v_academy.is_ai then
    v_lineup:=private.select_youth_race_lineup_v1(
      v_entry_id,
      case when v_academy.is_ai then 'ai_head_coach' else 'u16_head_coach' end
    );
    if v_lineup<3 then
      raise exception 'Not enough eligible Youth Riders for this race';
    end if;
  end if;

  return v_entry_id;
end;
$function$;

create or replace function private.fill_youth_world_race_wildcards_v1(
  p_race_id uuid
)
returns integer
language plpgsql
security definer
set search_path=public,private,pg_temp
as $function$
declare
  v_race public.youth_races%rowtype;
  v_host_regional text;
  v_open integer:=0;
  v_added integer:=0;
  v_game_date date:=public.get_current_game_date_date();
begin
  select * into v_race from public.youth_races where id=p_race_id;
  if v_race.id is null or v_race.competition_class<>'world'
     or v_race.status<>'scheduled' then
    return 0;
  end if;

  v_host_regional:=coalesce(
    v_race.metadata->>'host_regional_division',
    public.get_amateur_division_for_country(v_race.host_country_code)
  );

  select greatest(
    v_race.team_limit-count(*),0
  )::integer into v_open
  from public.youth_race_invitations i
  where i.race_id=p_race_id and i.status in ('pending','accepted');

  if v_open<=0 then return 0; end if;

  with candidates as (
    select
      a.id academy_id,
      (
        case when public.get_amateur_division_for_country(c.country_code)=v_host_regional
          then 100 else 0 end
        +case m.competition_class when 'continental' then 35 else 20 end
        +private.youth_academy_strength_v1(a.id)*0.08
        +private.youth_deterministic_fraction_v1(
          p_race_id::text||a.id::text||'world_wildcard'
        )*12
      )::numeric priority_score
    from public.youth_academies a
    join public.clubs c on c.id=a.club_id
    join public.youth_academy_competition_memberships m
      on m.academy_id=a.id and m.season_number=v_race.season_number
    where a.is_active=true
      and m.competition_class<>'world'
      and not exists(
        select 1 from public.youth_race_invitations i
        where i.race_id=p_race_id and i.academy_id=a.id
      )
    order by priority_score desc,a.id
    limit v_open
  )
  insert into public.youth_race_invitations(
    race_id,academy_id,invitation_type,status,invited_on,response_deadline,
    priority_score,metadata
  )
  select
    p_race_id,c.academy_id,'wildcard','pending',v_game_date,v_race.race_date-7,
    c.priority_score,
    jsonb_build_object(
      'source','world_open_spot',
      'host_regional_division',v_host_regional
    )
  from candidates c;

  get diagnostics v_added=row_count;
  return v_added;
end;
$function$;

create or replace function private.process_youth_world_invitation_deadlines_v1(
  p_game_date date
)
returns jsonb
language plpgsql
security definer
set search_path=public,private,pg_temp
as $function$
declare
  v_race record;
  v_invite record;
  v_entered integer:=0;
  v_expired integer:=0;
  v_wildcards integer:=0;
begin
  for v_race in
    select r.id,r.season_number,r.race_date
    from public.youth_races r
    where r.status='scheduled'
      and r.competition_class='world'
      and r.invitation_response_deadline=p_game_date
  loop
    for v_invite in
      select i.academy_id,a.is_ai,
        coalesce(s.race_entry_decider,'u16_head_coach') race_entry_decider
      from public.youth_race_invitations i
      join public.youth_academies a on a.id=i.academy_id
      left join public.youth_academy_settings s on s.academy_id=a.id
      where i.race_id=v_race.id
        and i.invitation_type='world_class'
        and i.status='pending'
        and (
          a.is_ai
          or coalesce(s.race_entry_decider,'u16_head_coach')='u16_head_coach'
        )
    loop
      perform private.ensure_youth_monthly_race_plan_v1(
        v_invite.academy_id,v_race.season_number,
        extract(month from v_race.race_date)::integer
      );
      begin
        perform private.enter_youth_race_v1(
          v_invite.academy_id,v_race.id,
          case when v_invite.is_ai then 'ai_head_coach' else 'u16_head_coach' end,
          'balanced'
        );
        v_entered:=v_entered+1;
      exception when others then
        update public.youth_race_invitations
        set status='declined',responded_on=p_game_date,updated_at=now()
        where race_id=v_race.id and academy_id=v_invite.academy_id
          and status='pending';
      end;
    end loop;

    with expired as (
      update public.youth_race_invitations
      set status='expired',responded_on=p_game_date,updated_at=now()
      where race_id=v_race.id
        and invitation_type='world_class'
        and status='pending'
      returning 1
    )
    select count(*)::integer into v_expired from expired;

    v_wildcards:=v_wildcards+private.fill_youth_world_race_wildcards_v1(v_race.id);
  end loop;

  return jsonb_build_object(
    'game_date',p_game_date,
    'world_entries',v_entered,
    'world_expired',v_expired,
    'wildcards_added',v_wildcards
  );
end;
$function$;

create or replace function private.auto_enter_youth_races_v1(
  p_game_date date
)
returns integer
language plpgsql
security definer
set search_path=public,private,pg_temp
as $function$
declare
  v_pair record;
  v_count integer:=0;
  v_strategy text;
begin
  for v_pair in
    select
      r.id race_id,r.season_number,r.race_date,r.competition_class,
      a.id academy_id,a.is_ai,
      coalesce(s.race_entry_decider,'u16_head_coach') race_entry_decider
    from public.youth_races r
    join public.youth_race_invitations i on i.race_id=r.id
    join public.youth_academies a on a.id=i.academy_id
    left join public.youth_academy_settings s on s.academy_id=a.id
    where r.status='scheduled'
      and r.race_date=p_game_date+7
      and i.status='pending'
      and a.is_active=true
      and (
        a.is_ai
        or coalesce(s.race_entry_decider,'u16_head_coach')='u16_head_coach'
      )
      and not exists(
        select 1 from public.youth_race_entries e
        where e.race_id=r.id and e.academy_id=a.id
          and e.status in ('entered','completed')
      )
    order by
      case r.competition_class when 'world' then 1 when 'continental' then 2 else 3 end,
      r.race_date,r.id,a.id
  loop
    perform private.ensure_youth_monthly_race_plan_v1(
      v_pair.academy_id,v_pair.season_number,
      extract(month from v_pair.race_date)::integer
    );

    v_strategy:=case
      when private.youth_deterministic_fraction_v1(
        v_pair.race_id::text||v_pair.academy_id::text||'strategy'
      )<0.22 then 'conservative'
      when private.youth_deterministic_fraction_v1(
        v_pair.race_id::text||v_pair.academy_id::text||'strategy'
      )>0.78 then 'aggressive'
      else 'balanced'
    end;

    begin
      perform private.enter_youth_race_v1(
        v_pair.academy_id,v_pair.race_id,
        case when v_pair.is_ai then 'ai_head_coach' else 'u16_head_coach' end,
        v_strategy
      );
      v_count:=v_count+1;
    exception when others then
      null;
    end;
  end loop;
  return v_count;
end;
$function$;

create or replace function public.process_youth_race_day_v1(p_game_date date)
returns jsonb
language plpgsql
security definer
set search_path=public,private,pg_temp
as $function$
declare
  v_season integer:=coalesce(public.get_current_season_number(),1);
  v_race record;
  v_deadlines jsonb;
  v_auto_entries integer:=0;
  v_processed integer:=0;
begin
  perform public.ensure_youth_competition_memberships_v1(v_season);

  if not exists(
    select 1 from public.youth_races
    where season_number=v_season
      and metadata->>'calendar_source'='youth_hierarchy_v1'
  ) then
    perform public.seed_youth_race_calendar_for_season_v1(v_season);
  end if;

  insert into public.youth_academy_settings(
    academy_id,race_entry_decider,race_squad_decider
  )
  select a.id,'u16_head_coach','u16_head_coach'
  from public.youth_academies a
  where a.is_active=true
  on conflict(academy_id) do nothing;

  insert into public.youth_academy_season_budgets(
    academy_id,season_number,season_budget,spent_amount,committed_amount,
    scouting_range,scouting_budget,scouting_committed_amount
  )
  select a.id,v_season,100000,0,5000,'local',5000,5000
  from public.youth_academies a
  where a.is_active=true
  on conflict(academy_id,season_number) do nothing;

  v_deadlines:=private.process_youth_world_invitation_deadlines_v1(p_game_date);
  v_auto_entries:=private.auto_enter_youth_races_v1(p_game_date);

  for v_race in
    select id from public.youth_races
    where status='scheduled'
      and coalesce(race_end_date,race_date)<=p_game_date
    order by coalesce(race_end_date,race_date),id
  loop
    perform private.simulate_youth_race_v1(v_race.id);
    update public.youth_race_invitations
    set status='expired',responded_on=coalesce(responded_on,p_game_date),updated_at=now()
    where race_id=v_race.id and status='pending';
    v_processed:=v_processed+1;
  end loop;

  return jsonb_build_object(
    'game_date',p_game_date,
    'invitation_deadlines',v_deadlines,
    'auto_entries',v_auto_entries,
    'races_processed',v_processed,
    'results_only',true,
    'replay_available',false
  );
end;
$function$;

revoke all on function public.process_youth_race_day_v1(date)
from public,anon,authenticated;
grant execute on function public.process_youth_race_day_v1(date)
to service_role;

create or replace function public.save_my_youth_race_lineup_v1(
  p_race_id uuid,
  p_rider_ids uuid[],
  p_strategy text default 'balanced'
)
returns jsonb
language plpgsql
security definer
set search_path=public,private,auth,pg_temp
as $function$
declare
  v_user uuid:=auth.uid();
  v_academy_id uuid;
  v_entry public.youth_race_entries%rowtype;
  v_race public.youth_races%rowtype;
  v_squad_decider text;
  v_rider_id uuid;
  v_slot integer:=0;
begin
  if v_user is null then raise exception 'Not authenticated'; end if;
  if not public.user_has_premium_access_v1(v_user) then
    raise exception 'Premium membership is required to manage Youth Academy.';
  end if;

  select a.id,s.race_squad_decider
  into v_academy_id,v_squad_decider
  from public.youth_academies a
  join public.clubs c on c.id=a.club_id
  left join public.youth_academy_settings s on s.academy_id=a.id
  where c.owner_user_id=v_user and c.deleted_at is null and a.is_active=true
  limit 1;

  if coalesce(v_squad_decider,'u16_head_coach')<>'manager' then
    raise exception 'Race squad selection is delegated to the U16 Head Coach';
  end if;

  select * into v_entry from public.youth_race_entries
  where race_id=p_race_id and academy_id=v_academy_id and status='entered'
  for update;
  select * into v_race from public.youth_races where id=p_race_id;

  if v_entry.id is null then
    raise exception 'Enter the race before selecting a lineup';
  end if;
  if cardinality(p_rider_ids)<3 or cardinality(p_rider_ids)>v_race.lineup_size then
    raise exception 'Youth race lineup must contain between 3 and % riders',v_race.lineup_size;
  end if;

  delete from public.youth_race_lineups where entry_id=v_entry.id;

  foreach v_rider_id in array p_rider_ids loop
    if not exists(
      select 1 from public.youth_riders yr
      where yr.id=v_rider_id and yr.academy_id=v_academy_id
        and private.youth_rider_available_for_race_v1(yr.id,p_race_id)
    ) then
      raise exception 'One or more selected Youth Riders are not eligible or are booked in an overlapping race';
    end if;
    v_slot:=v_slot+1;
    insert into public.youth_race_lineups(
      entry_id,youth_rider_id,slot_no,selected_by
    )
    values(v_entry.id,v_rider_id,v_slot,'manager');
  end loop;

  update public.youth_race_entries
  set strategy=case when p_strategy in ('conservative','balanced','aggressive')
    then p_strategy else 'balanced' end,
      updated_at=now()
  where id=v_entry.id;

  return public.get_my_youth_race_calendar_v1();
end;
$function$;

revoke all on function public.save_my_youth_race_lineup_v1(uuid,uuid[],text)
from public,anon;
grant execute on function public.save_my_youth_race_lineup_v1(uuid,uuid[],text)
to authenticated;

create or replace function public.save_my_youth_monthly_race_plan_v1(
  p_month_number integer,
  p_world_race_limit integer,
  p_continental_race_limit integer,
  p_regional_race_limit integer,
  p_max_monthly_cost bigint
)
returns jsonb
language plpgsql
security definer
set search_path=public,private,auth,pg_temp
as $function$
declare
  v_user uuid:=auth.uid();
  v_academy_id uuid;
  v_season integer:=coalesce(public.get_current_season_number(),1);
begin
  if v_user is null then raise exception 'Not authenticated'; end if;
  if not public.user_has_premium_access_v1(v_user) then
    raise exception 'Premium membership is required to manage Youth Academy.';
  end if;
  if p_month_number not between 1 and 12 then
    raise exception 'Invalid Youth race plan month';
  end if;
  if p_world_race_limit not between 0 and 6
     or p_continental_race_limit not between 0 and 10
     or p_regional_race_limit not between 0 and 6
     or p_max_monthly_cost<0 then
    raise exception 'Invalid Youth monthly race plan limits';
  end if;

  select a.id into v_academy_id
  from public.youth_academies a
  join public.clubs c on c.id=a.club_id
  where c.owner_user_id=v_user and c.deleted_at is null and a.is_active=true
  limit 1;
  if v_academy_id is null then raise exception 'Youth Academy is not activated'; end if;

  perform public.ensure_youth_competition_memberships_v1(v_season);

  insert into public.youth_monthly_race_plans(
    academy_id,season_number,month_number,
    world_race_limit,continental_race_limit,regional_race_limit,
    max_monthly_cost,approved,approved_by_user_id,approved_at,updated_at
  )
  values(
    v_academy_id,v_season,p_month_number,
    p_world_race_limit,p_continental_race_limit,p_regional_race_limit,
    p_max_monthly_cost,true,v_user,now(),now()
  )
  on conflict(academy_id,season_number,month_number) do update
  set world_race_limit=excluded.world_race_limit,
      continental_race_limit=excluded.continental_race_limit,
      regional_race_limit=excluded.regional_race_limit,
      max_monthly_cost=excluded.max_monthly_cost,
      approved=true,
      approved_by_user_id=v_user,
      approved_at=now(),
      updated_at=now();

  return public.get_my_youth_race_calendar_v1();
end;
$function$;

revoke all on function public.save_my_youth_monthly_race_plan_v1(
  integer,integer,integer,integer,bigint
) from public,anon;
grant execute on function public.save_my_youth_monthly_race_plan_v1(
  integer,integer,integer,integer,bigint
) to authenticated;

create or replace function public.decline_my_youth_race_invitation_v1(
  p_race_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path=public,private,auth,pg_temp
as $function$
declare
  v_user uuid:=auth.uid();
  v_academy_id uuid;
  v_entry_decider text;
  v_class text;
  v_game_date date:=public.get_current_game_date_date();
begin
  if v_user is null then raise exception 'Not authenticated'; end if;
  if not public.user_has_premium_access_v1(v_user) then
    raise exception 'Premium membership is required to manage Youth Academy.';
  end if;

  select a.id,coalesce(s.race_entry_decider,'u16_head_coach')
  into v_academy_id,v_entry_decider
  from public.youth_academies a
  join public.clubs c on c.id=a.club_id
  left join public.youth_academy_settings s on s.academy_id=a.id
  where c.owner_user_id=v_user and c.deleted_at is null and a.is_active=true
  limit 1;

  if v_academy_id is null then raise exception 'Youth Academy is not activated'; end if;
  if v_entry_decider<>'manager' then
    raise exception 'Race participation is delegated to the U16 Head Coach';
  end if;

  select competition_class into v_class
  from public.youth_races where id=p_race_id;

  update public.youth_race_invitations
  set status='declined',responded_on=v_game_date,updated_at=now()
  where race_id=p_race_id and academy_id=v_academy_id and status='pending';

  if not found then raise exception 'No pending Youth race invitation found'; end if;

  if v_class='world' then
    perform private.fill_youth_world_race_wildcards_v1(p_race_id);
  end if;

  return public.get_my_youth_race_calendar_v1();
end;
$function$;

revoke all on function public.decline_my_youth_race_invitation_v1(uuid)
from public,anon;
grant execute on function public.decline_my_youth_race_invitation_v1(uuid)
to authenticated;

create or replace function public.get_my_youth_race_calendar_v1()
returns jsonb
language plpgsql
security definer
set search_path=public,private,auth,pg_temp
as $function$
declare
  v_user uuid:=auth.uid();
  v_academy_id uuid;
  v_broad_region text;
  v_regional_division text;
  v_game_date date:=public.get_current_game_date_date();
  v_season integer:=coalesce(public.get_current_season_number(),1);
  v_month integer:=extract(month from public.get_current_game_date_date())::integer;
  v_entry_decider text;
  v_squad_decider text;
  v_membership public.youth_academy_competition_memberships%rowtype;
  v_plan public.youth_monthly_race_plans%rowtype;
begin
  if v_user is null then raise exception 'Not authenticated'; end if;

  select
    a.id,
    private.youth_region_for_country_v1(c.country_code),
    coalesce(public.get_amateur_division_for_country(c.country_code),'OTHER'),
    s.race_entry_decider,s.race_squad_decider
  into
    v_academy_id,v_broad_region,v_regional_division,
    v_entry_decider,v_squad_decider
  from public.youth_academies a
  join public.clubs c on c.id=a.club_id
  left join public.youth_academy_settings s on s.academy_id=a.id
  where c.owner_user_id=v_user and c.deleted_at is null and a.is_active=true
  limit 1;

  if v_academy_id is null then
    return jsonb_build_object('activated',false,'races','[]'::jsonb);
  end if;

  perform public.ensure_youth_competition_memberships_v1(v_season);
  perform private.ensure_youth_monthly_race_plan_v1(v_academy_id,v_season,v_month);

  select * into v_membership
  from public.youth_academy_competition_memberships
  where season_number=v_season and academy_id=v_academy_id;

  select * into v_plan
  from public.youth_monthly_race_plans
  where academy_id=v_academy_id and season_number=v_season and month_number=v_month;

  return jsonb_build_object(
    'activated',true,
    'season_number',v_season,
    'game_date',v_game_date,
    'current_month',v_month,
    'academy_region',v_broad_region,
    'regional_division',v_regional_division,
    'race_entry_decider',coalesce(v_entry_decider,'u16_head_coach'),
    'race_squad_decider',coalesce(v_squad_decider,'u16_head_coach'),
    'competition_membership',jsonb_build_object(
      'competition_class',v_membership.competition_class,
      'division_code',v_membership.division_code,
      'seed_rank',v_membership.seed_rank
    ),
    'monthly_plan',jsonb_build_object(
      'month_number',v_plan.month_number,
      'world_race_limit',v_plan.world_race_limit,
      'continental_race_limit',v_plan.continental_race_limit,
      'regional_race_limit',v_plan.regional_race_limit,
      'max_monthly_cost',v_plan.max_monthly_cost,
      'approved',v_plan.approved,
      'available_world',(
        select count(*) from public.youth_races r
        left join public.youth_race_invitations i
          on i.race_id=r.id and i.academy_id=v_academy_id
        where r.season_number=v_season
          and extract(month from r.race_date)::integer=v_month
          and r.competition_class='world'
          and r.status='scheduled'
          and (i.status in ('pending','accepted') or i.status is null)
      ),
      'available_continental',(
        select count(*) from public.youth_races r
        left join public.youth_race_invitations i
          on i.race_id=r.id and i.academy_id=v_academy_id
        where r.season_number=v_season
          and extract(month from r.race_date)::integer=v_month
          and r.competition_class='continental'
          and r.status='scheduled'
          and (i.status in ('pending','accepted') or i.status is null)
      ),
      'available_regional',(
        select count(*) from public.youth_races r
        where r.season_number=v_season
          and extract(month from r.race_date)::integer=v_month
          and r.competition_class='regional'
          and r.division_code=v_regional_division
          and r.status='scheduled'
      ),
      'entered_cost',(
        select coalesce(sum(e.entry_cost),0)
        from public.youth_race_entries e
        join public.youth_races r on r.id=e.race_id
        where e.academy_id=v_academy_id
          and r.season_number=v_season
          and extract(month from r.race_date)::integer=v_month
      )
    ),
    'races',(
      select coalesce(jsonb_agg(jsonb_build_object(
        'id',r.id,
        'race_date',r.race_date,
        'race_end_date',coalesce(r.race_end_date,r.race_date),
        'race_days',r.race_days,
        'race_name',r.race_name,
        'race_level',r.race_level,
        'competition_class',r.competition_class,
        'division_code',r.division_code,
        'region_code',r.region_code,
        'host_city',r.host_city,
        'host_country_code',r.host_country_code,
        'terrain_type',r.terrain_type,
        'distance_km',r.distance_km,
        'entry_cost',r.entry_cost,
        'lineup_size',r.lineup_size,
        'team_limit',r.team_limit,
        'entries_count',(
          select count(*) from public.youth_race_entries xe
          where xe.race_id=r.id and xe.status in ('entered','completed')
        ),
        'status',r.status,
        'qualified',private.youth_race_academy_qualified_v1(v_academy_id,r.id),
        'invitation_status',i.status,
        'invitation_type',i.invitation_type,
        'invitation_response_deadline',i.response_deadline,
        'entry_id',e.id,
        'entry_status',e.status,
        'strategy',e.strategy,
        'entered_by',e.entered_by,
        'eligible_rider_ids',coalesce((
          select jsonb_agg(yr.id order by yr.display_name)
          from public.youth_riders yr
          where yr.academy_id=v_academy_id
            and private.youth_rider_available_for_race_v1(yr.id,r.id)
        ),'[]'::jsonb),
        'lineup',coalesce((
          select jsonb_agg(jsonb_build_object(
            'rider_id',yr.id,'name',yr.display_name,'age',
            extract(year from age(r.race_date,yr.birth_date))::integer,
            'role',yr.role,'readiness',yr.readiness,'fatigue',yr.fatigue,
            'eligible',private.youth_rider_available_for_race_v1(yr.id,r.id)
          ) order by l.slot_no)
          from public.youth_race_lineups l
          join public.youth_riders yr on yr.id=l.youth_rider_id
          where l.entry_id=e.id
        ),'[]'::jsonb),
        'my_results',coalesce((
          select jsonb_agg(jsonb_build_object(
            'rider_id',yr.id,'name',yr.display_name,
            'status',rr.result_status,'position',rr.finish_position,
            'gap_seconds',rr.gap_seconds,'regional_points',rr.regional_points,
            'world_points',rr.world_points
          ) order by rr.finish_position nulls last,yr.display_name)
          from public.youth_race_results rr
          join public.youth_riders yr on yr.id=rr.youth_rider_id
          where rr.race_id=r.id and rr.academy_id=v_academy_id
        ),'[]'::jsonb),
        'top_results',case when r.status='completed' then coalesce((
          select jsonb_agg(x.item order by x.position)
          from (
            select rr.finish_position position,jsonb_build_object(
              'position',rr.finish_position,'rider_name',yr.display_name,
              'country_code',yr.country_code,'academy_name',c.name,
              'gap_seconds',rr.gap_seconds
            ) item
            from public.youth_race_results rr
            join public.youth_riders yr on yr.id=rr.youth_rider_id
            join public.youth_academies a on a.id=rr.academy_id
            join public.clubs c on c.id=a.club_id
            where rr.race_id=r.id and rr.result_status='finished'
            order by rr.finish_position
            limit 10
          ) x
        ),'[]'::jsonb) else '[]'::jsonb end
      ) order by r.race_date,r.race_name),'[]'::jsonb)
      from public.youth_races r
      left join public.youth_race_invitations i
        on i.race_id=r.id and i.academy_id=v_academy_id
      left join public.youth_race_entries e
        on e.race_id=r.id and e.academy_id=v_academy_id
      where r.season_number=v_season
        and r.status<>'cancelled'
        and (
          r.competition_class in ('world','continental')
          or (
            r.competition_class='regional'
            and r.division_code=v_regional_division
          )
        )
    ),
    'riders',(
      select coalesce(jsonb_agg(jsonb_build_object(
        'id',yr.id,'name',yr.display_name,'age',
        extract(year from age(v_game_date,yr.birth_date))::integer,
        'role',yr.role,'readiness',yr.readiness,'fatigue',yr.fatigue
      ) order by yr.display_name),'[]'::jsonb)
      from public.youth_riders yr
      where yr.academy_id=v_academy_id and yr.status='academy'
    )
  );
end;
$function$;

revoke all on function public.get_my_youth_race_calendar_v1()
from public,anon;
grant execute on function public.get_my_youth_race_calendar_v1()
to authenticated;

create or replace function public.get_my_youth_rankings_v1()
returns jsonb
language plpgsql
security definer
set search_path=public,private,auth,pg_temp
as $function$
declare
  v_user uuid:=auth.uid();
  v_academy_id uuid;
  v_region text;
  v_season integer:=coalesce(public.get_current_season_number(),1);
  v_membership public.youth_academy_competition_memberships%rowtype;
begin
  if v_user is null then raise exception 'Not authenticated'; end if;

  select a.id,private.youth_region_for_country_v1(c.country_code)
  into v_academy_id,v_region
  from public.youth_academies a
  join public.clubs c on c.id=a.club_id
  where c.owner_user_id=v_user and c.deleted_at is null and a.is_active=true
  limit 1;

  if v_academy_id is null then
    return jsonb_build_object('activated',false);
  end if;

  perform public.ensure_youth_competition_memberships_v1(v_season);

  select * into v_membership
  from public.youth_academy_competition_memberships
  where season_number=v_season and academy_id=v_academy_id;

  return jsonb_build_object(
    'activated',true,
    'season_number',v_season,
    'region_code',v_region,
    'my_membership',jsonb_build_object(
      'competition_class',v_membership.competition_class,
      'division_code',v_membership.division_code
    ),
    'academy_divisions',(
      with rider_rows as (
        select
          rr.race_id,rr.academy_id,rr.finish_position,
          row_number() over(
            partition by rr.race_id,rr.academy_id
            order by rr.finish_position nulls last,rr.youth_rider_id
          ) rn
        from public.youth_race_results rr
        join public.youth_races r on r.id=rr.race_id
        where r.season_number=v_season and rr.result_status='finished'
      ),
      race_points as (
        select
          x.academy_id,
          sum(
            case r.competition_class
              when 'world' then private.youth_race_base_points_v1(x.finish_position)*2
              when 'continental' then round(
                private.youth_race_base_points_v1(x.finish_position)*1.25
              )::integer
              else private.youth_race_base_points_v1(x.finish_position)
            end
          )::bigint points,
          count(distinct x.race_id)::integer starts
        from rider_rows x
        join public.youth_races r on r.id=x.race_id
        where x.rn<=3
        group by x.academy_id
      ),
      standing_rows as (
        select
          m.competition_class,m.division_code,m.academy_id,c.name academy_name,
          c.country_code,
          coalesce(p.points,0)::bigint points,
          coalesce(p.starts,0)::integer starts,
          row_number() over(
            partition by m.competition_class,m.division_code
            order by coalesce(p.points,0) desc,
                     private.youth_academy_strength_v1(m.academy_id) desc,
                     lower(c.name),m.academy_id
          )::integer rank_no,
          count(*) over(
            partition by m.competition_class,m.division_code
          )::integer total_teams
        from public.youth_academy_competition_memberships m
        join public.youth_academies a on a.id=m.academy_id and a.is_active=true
        join public.clubs c on c.id=a.club_id
        left join race_points p on p.academy_id=m.academy_id
        where m.season_number=v_season
      ),
      divisions as (
        select
          s.competition_class,s.division_code,
          min(case
            when s.competition_class='world' then 1
            when s.competition_class='continental' and s.division_code='CONTINENTAL_WEST' then 2
            when s.competition_class='continental' then 3
            else 10
          end) sort_order,
          jsonb_agg(jsonb_build_object(
            'rank',s.rank_no,
            'academy_id',s.academy_id,
            'academy_name',s.academy_name,
            'country_code',s.country_code,
            'points',s.points,
            'starts',s.starts,
            'total_teams',s.total_teams,
            'is_mine',s.academy_id=v_academy_id,
            'promotion_zone',false,
            'relegation_zone',false
          ) order by s.rank_no) teams
        from standing_rows s
        group by s.competition_class,s.division_code
      )
      select coalesce(jsonb_agg(jsonb_build_object(
        'competition_class',d.competition_class,
        'division_code',d.division_code,
        'teams',d.teams
      ) order by d.sort_order,d.division_code),'[]'::jsonb)
      from divisions d
    ),
    'regional',(
      with totals as (
        select yr.id,yr.display_name,yr.country_code,yr.academy_id,
          sum(rr.regional_points)::bigint points,
          count(*) filter(where rr.result_status='finished')::integer starts
        from public.youth_riders yr
        join public.youth_race_results rr on rr.youth_rider_id=yr.id
        join public.youth_races r on r.id=rr.race_id
        join public.youth_academies ya on ya.id=yr.academy_id
        join public.clubs yc on yc.id=ya.club_id
        where r.season_number=v_season
          and private.youth_region_for_country_v1(yc.country_code)=v_region
        group by yr.id,yr.display_name,yr.country_code,yr.academy_id
      ),
      ranked as (
        select t.*,dense_rank() over(order by points desc,id)::integer rank_no
        from totals t
      )
      select coalesce(jsonb_agg(jsonb_build_object(
        'rank',x.rank_no,'rider_id',x.id,'rider_name',x.display_name,
        'country_code',x.country_code,'academy_id',x.academy_id,
        'academy_name',c.name,'points',x.points,'starts',x.starts,
        'is_mine',x.academy_id=v_academy_id
      ) order by x.rank_no),'[]'::jsonb)
      from (select * from ranked order by rank_no limit 100) x
      join public.youth_academies a on a.id=x.academy_id
      join public.clubs c on c.id=a.club_id
    ),
    'world',(
      with totals as (
        select yr.id,yr.display_name,yr.country_code,yr.academy_id,
          sum(rr.world_points)::bigint points,
          count(*) filter(where rr.result_status='finished')::integer starts
        from public.youth_riders yr
        join public.youth_race_results rr on rr.youth_rider_id=yr.id
        join public.youth_races r on r.id=rr.race_id
        where r.season_number=v_season
        group by yr.id,yr.display_name,yr.country_code,yr.academy_id
      ),
      ranked as (
        select t.*,dense_rank() over(order by points desc,id)::integer rank_no
        from totals t
      )
      select coalesce(jsonb_agg(jsonb_build_object(
        'rank',x.rank_no,'rider_id',x.id,'rider_name',x.display_name,
        'country_code',x.country_code,'academy_id',x.academy_id,
        'academy_name',c.name,'points',x.points,'starts',x.starts,
        'is_mine',x.academy_id=v_academy_id
      ) order by x.rank_no),'[]'::jsonb)
      from (select * from ranked order by rank_no limit 100) x
      join public.youth_academies a on a.id=x.academy_id
      join public.clubs c on c.id=a.club_id
    )
  );
end;
$function$;

revoke all on function public.get_my_youth_rankings_v1()
from public,anon;
grant execute on function public.get_my_youth_rankings_v1()
to authenticated;

delete from public.youth_races r
where r.metadata->>'calendar_source'='phase3'
  and r.status='scheduled'
  and not exists(
    select 1 from public.youth_race_entries e where e.race_id=r.id
  )
  and not exists(
    select 1 from public.youth_race_results rr where rr.race_id=r.id
  );

select public.ensure_youth_competition_memberships_v1(
  coalesce(public.get_current_season_number(),1)
);

select public.seed_youth_race_calendar_for_season_v1(
  coalesce(public.get_current_season_number(),1)
);

update public.youth_races
set status='cancelled',updated_at=now(),
    metadata=metadata||jsonb_build_object('prelaunch_cancelled',true)
where season_number=coalesce(public.get_current_season_number(),1)
  and metadata->>'calendar_source'='youth_hierarchy_v1'
  and race_date<=public.get_current_game_date_date()
  and status='scheduled';

update public.youth_race_invitations i
set status='expired',responded_on=public.get_current_game_date_date(),updated_at=now()
from public.youth_races r
where r.id=i.race_id and r.status='cancelled' and i.status='pending';
