CREATE INDEX entries_account_idx ON finance.entries USING btree (account_id);
CREATE INDEX entries_tx_idx ON finance.entries USING btree (transaction_id);
CREATE UNIQUE INDEX finance_account_balances_account_id_uidx ON finance.account_balances USING btree (account_id);
CREATE UNIQUE INDEX finance_accounts_club_currency_kind_uidx ON finance.accounts USING btree (club_id, currency, kind);
CREATE UNIQUE INDEX finance_accounts_system_unique ON finance.accounts USING btree (system_code, currency, kind) WHERE (system_code IS NOT NULL);
CREATE UNIQUE INDEX finance_transactions_created_by_idempotency_key_uidx ON finance.transactions USING btree (created_by, idempotency_key);
CREATE INDEX idx_finance_accounts_club_currency_kind_id_v1 ON finance.accounts USING btree (club_id, currency, kind, id);
CREATE INDEX idx_finance_entries_account_transaction_amount_v1 ON finance.entries USING btree (account_id, transaction_id, amount);
CREATE INDEX idx_finance_entries_transaction_account_amount_v1 ON finance.entries USING btree (transaction_id, account_id, amount);
CREATE INDEX idx_finance_transaction_types_code_taxable_v1 ON finance.transaction_types USING btree (code, is_taxable);
CREATE INDEX idx_finance_transaction_voids_correction_v1 ON finance.transaction_voids USING btree (correction_transaction_id);
CREATE INDEX idx_finance_transactions_tax_withholding_source_v1 ON finance.transactions USING btree (((metadata ->> 'source_transaction_id'::text))) WHERE (type = 'tax_withholding'::text);
CREATE INDEX idx_finance_transactions_type_id_v1 ON finance.transactions USING btree (type, id);
CREATE INDEX idx_finance_tx_id_text_game_date_v1 ON finance.transactions USING btree (((id)::text)) WHERE (jsonb_typeof((metadata -> 'game_date'::text)) = 'object'::text);
CREATE INDEX idx_finance_tx_payroll_game_date_lookup_v1 ON finance.transactions USING btree (type, COALESCE((metadata ->> 'charged_club_id'::text), (metadata ->> 'club_id'::text), ''::text), COALESCE((metadata ->> 'game_date'::text), (metadata ->> 'in_game_date'::text), ''::text), created_at DESC);
CREATE INDEX idx_finance_tx_rider_salary_lookup_v1 ON finance.transactions USING btree (type, COALESCE((metadata ->> 'charged_club_id'::text), (metadata ->> 'club_id'::text), ''::text), COALESCE((metadata ->> 'game_date'::text), (metadata ->> 'in_game_date'::text), ''::text), created_at DESC) WHERE (COALESCE((metadata ->> 'is_reversal'::text), 'false'::text) <> 'true'::text);
CREATE INDEX idx_finance_tx_source_game_date_parts_v1 ON finance.transactions USING btree ((((metadata -> 'game_date'::text) ->> 'season'::text)), (((metadata -> 'game_date'::text) ->> 'month'::text)), (((metadata -> 'game_date'::text) ->> 'day'::text))) WHERE (jsonb_typeof((metadata -> 'game_date'::text)) = 'object'::text);
CREATE INDEX monthly_tax_audits_club_period_idx ON finance.monthly_tax_audits USING btree (club_id, period_start DESC);
CREATE UNIQUE INDEX transactions_idem_uq ON finance.transactions USING btree (created_by, idempotency_key) WHERE (idempotency_key IS NOT NULL);
CREATE UNIQUE INDEX app_admins_user_id_uidx ON public.app_admins USING btree (user_id) WHERE (user_id IS NOT NULL);
CREATE INDEX birthday_gift_audit_email_idx ON public.birthday_gift_audit USING btree (email);
CREATE INDEX birthday_gift_audit_processed_date_idx ON public.birthday_gift_audit USING btree (processed_date);
CREATE INDEX birthday_gift_audit_user_id_idx ON public.birthday_gift_audit USING btree (user_id);
CREATE INDEX bug_report_admin_reads_admin_idx ON public.bug_report_admin_reads USING btree (admin_user_id, read_at DESC);
CREATE INDEX bug_report_notes_report_idx ON public.bug_report_notes USING btree (bug_report_id, created_at);
CREATE INDEX bug_reports_created_at_idx ON public.bug_reports USING btree (created_at DESC);
CREATE INDEX bug_reports_status_created_at_idx ON public.bug_reports USING btree (status, created_at DESC);
CREATE INDEX club_asset_repair_jobs_asset_idx ON public.club_infrastructure_asset_repair_jobs USING btree (asset_key, asset_id, status);
CREATE INDEX club_asset_repair_jobs_club_status_idx ON public.club_infrastructure_asset_repair_jobs USING btree (club_id, status, complete_game_date);
CREATE INDEX club_equipment_inventory_assigned_rider_idx ON public.club_equipment_inventory USING btree (assigned_rider_id);
CREATE INDEX club_equipment_inventory_brand_company_idx ON public.club_equipment_inventory USING btree (brand_company_id);
CREATE INDEX club_equipment_inventory_catalog_idx ON public.club_equipment_inventory USING btree (catalog_item_id);
CREATE INDEX club_equipment_inventory_club_category_idx ON public.club_equipment_inventory USING btree (club_id, equipment_category);
CREATE INDEX club_equipment_inventory_club_status_idx ON public.club_equipment_inventory USING btree (club_id, status);
CREATE INDEX club_equipment_maintenance_jobs_club_status_idx ON public.club_equipment_maintenance_jobs USING btree (club_id, status, complete_game_date);
CREATE INDEX club_equipment_maintenance_jobs_item_status_idx ON public.club_equipment_maintenance_jobs USING btree (inventory_item_id, status);
CREATE INDEX club_equipment_setup_presets_club_id_idx ON public.club_equipment_setup_presets USING btree (club_id);
CREATE UNIQUE INDEX club_equipment_vans_active_slot_uidx ON public.club_equipment_vans USING btree (club_id, garage_slot) WHERE (status <> 'sold'::text);
CREATE INDEX club_equipment_vans_club_status_idx ON public.club_equipment_vans USING btree (club_id, status);
CREATE INDEX club_infrastructure_jobs_asset_pending_idx ON public.club_infrastructure_jobs USING btree (club_id, target_key, asset_level, status) WHERE (job_type = 'asset_delivery'::text);
CREATE INDEX club_infrastructure_jobs_pending_complete_game_date_idx ON public.club_infrastructure_jobs USING btree (status, complete_game_date) WHERE (status = 'pending'::text);
CREATE INDEX club_memberships_club_id_idx ON public.club_memberships USING btree (club_id);
CREATE INDEX club_memberships_user_id_idx ON public.club_memberships USING btree (user_id);
CREATE UNIQUE INDEX club_mobile_workshops_active_slot_uidx ON public.club_mobile_workshops USING btree (club_id, garage_slot) WHERE (status <> 'sold'::text);
CREATE INDEX club_mobile_workshops_club_status_idx ON public.club_mobile_workshops USING btree (club_id, status);
CREATE INDEX club_race_supplies_club_idx ON public.club_race_supplies USING btree (club_id);
CREATE INDEX club_race_supplies_preferred_brand_idx ON public.club_race_supplies USING btree (preferred_brand_company_id);
CREATE INDEX club_race_supply_units_club_key_status_idx ON public.club_race_supply_units USING btree (club_id, supply_key, status);
CREATE INDEX club_race_supply_units_remaining_idx ON public.club_race_supply_units USING btree (club_id, supply_key, stage_uses_remaining) WHERE ((status = ANY (ARRAY['ready'::text, 'assigned'::text])) AND (stage_uses_remaining > 0));
CREATE INDEX club_referrals_referred_user_idx ON public.club_referrals USING btree (referred_user_id);
CREATE UNIQUE INDEX club_referrals_referred_user_unique ON public.club_referrals USING btree (referred_user_id);
CREATE INDEX club_referrals_referrer_idx ON public.club_referrals USING btree (referrer_club_id);
CREATE UNIQUE INDEX club_season_identities_active_naming_uq ON public.club_season_identities USING btree (club_id, season_number) WHERE ((is_active = true) AND (source_type = 'sponsor_naming_rights'::text));
CREATE INDEX club_season_identities_club_season_idx ON public.club_season_identities USING btree (club_id, season_number);
CREATE INDEX club_season_identities_source_sponsor_idx ON public.club_season_identities USING btree (source_sponsor_id);
CREATE INDEX club_sponsor_objectives_check_due_idx ON public.club_sponsor_objectives USING btree (status, check_state, target_check_game_date);
CREATE INDEX club_sponsor_objectives_eligible_window_idx ON public.club_sponsor_objectives USING btree (eligible_from_game_date, eligible_to_game_date);
CREATE INDEX club_sponsor_objectives_eval_mode_idx ON public.club_sponsor_objectives USING btree (club_sponsor_id, objective_target_mode, evaluation_mode, status);
CREATE INDEX club_sponsor_objectives_result_state_idx ON public.club_sponsor_objectives USING btree (club_sponsor_id, objective_result_state, check_state);
CREATE INDEX club_sponsor_objectives_sponsor_idx ON public.club_sponsor_objectives USING btree (club_sponsor_id, status);
CREATE INDEX club_sponsor_objectives_target_race_idx ON public.club_sponsor_objectives USING btree (target_race_id);
CREATE INDEX club_sponsor_objectives_target_stage_idx ON public.club_sponsor_objectives USING btree (target_stage_id);
CREATE INDEX club_sponsor_offers_club_season_idx ON public.club_sponsor_offers USING btree (club_id, season_number, status);
CREATE INDEX club_sponsor_offers_company_idx ON public.club_sponsor_offers USING btree (company_id);
CREATE INDEX club_sponsor_offers_refresh_idx ON public.club_sponsor_offers USING btree (club_id, season_number, sponsor_kind, status, refresh_mode);
CREATE INDEX club_sponsors_club_season_idx ON public.club_sponsors USING btree (club_id, season_number);
CREATE INDEX club_sponsors_club_status_idx ON public.club_sponsors USING btree (club_id, status);
CREATE INDEX club_sponsors_company_id_idx ON public.club_sponsors USING btree (company_id);
CREATE UNIQUE INDEX club_sponsors_one_active_main_per_club_season ON public.club_sponsors USING btree (club_id, season_number) WHERE ((sponsor_kind = 'main'::text) AND (status = 'active'::text));
CREATE UNIQUE INDEX club_sponsors_one_technical_per_club_season ON public.club_sponsors USING btree (club_id, season_number) WHERE (sponsor_kind = 'technical'::text);
CREATE UNIQUE INDEX club_sponsors_secondary_slot_per_club_season ON public.club_sponsors USING btree (club_id, season_number, slot_no) WHERE (sponsor_kind = 'secondary'::text);
CREATE INDEX club_sponsors_status_idx ON public.club_sponsors USING btree (status);
CREATE INDEX club_staff_active_role_lookup_idx ON public.club_staff USING btree (club_id, role_type) WHERE (is_active = true);
CREATE INDEX club_staff_club_id_idx ON public.club_staff USING btree (club_id);
CREATE INDEX club_staff_role_type_idx ON public.club_staff USING btree (role_type);
CREATE UNIQUE INDEX club_team_buses_active_slot_uidx ON public.club_team_buses USING btree (club_id, garage_slot) WHERE (status <> 'sold'::text);
CREATE INDEX club_team_buses_club_level_idx ON public.club_team_buses USING btree (club_id, asset_level);
CREATE INDEX club_team_buses_club_status_idx ON public.club_team_buses USING btree (club_id, status);
CREATE UNIQUE INDEX club_team_cars_active_slot_uidx ON public.club_team_cars USING btree (club_id, garage_slot) WHERE (status <> 'sold'::text);
CREATE INDEX club_team_cars_club_level_idx ON public.club_team_cars USING btree (club_id, asset_level);
CREATE INDEX club_team_cars_club_status_idx ON public.club_team_cars USING btree (club_id, status);
CREATE INDEX clubs_amateur_competition_lookup_v1 ON public.clubs USING btree (club_tier, amateur_division, name, id) WHERE (deleted_at IS NULL);
CREATE INDEX clubs_amateur_live_ranking_idx ON public.clubs USING btree (club_tier, amateur_division, name, id) WHERE (deleted_at IS NULL);
CREATE INDEX clubs_continental_competition_lookup_v1 ON public.clubs USING btree (club_tier, tier3_division, name, id) WHERE (deleted_at IS NULL);
CREATE INDEX clubs_country_code_idx ON public.clubs USING btree (country_code);
CREATE UNIQUE INDEX clubs_name_lower_key ON public.clubs USING btree (lower(name)) WHERE (deleted_at IS NULL);
CREATE UNIQUE INDEX clubs_one_developing_team_per_parent_uidx ON public.clubs USING btree (parent_club_id) WHERE (club_type = 'developing'::text);
CREATE INDEX clubs_owner_type_created_idx ON public.clubs USING btree (owner_user_id, club_type, created_at) WHERE (deleted_at IS NULL);
CREATE INDEX clubs_owner_user_id_idx ON public.clubs USING btree (owner_user_id);
CREATE UNIQUE INDEX clubs_owner_user_id_unique_real_only ON public.clubs USING btree (owner_user_id) WHERE ((owner_user_id IS NOT NULL) AND (is_ai = false) AND (COALESCE(club_type, 'main'::text) = 'main'::text));
CREATE INDEX clubs_parent_club_id_idx ON public.clubs USING btree (parent_club_id);
CREATE INDEX clubs_parent_type_created_idx ON public.clubs USING btree (parent_club_id, club_type, created_at) WHERE (deleted_at IS NULL);
CREATE INDEX clubs_proteam_competition_lookup_v1 ON public.clubs USING btree (club_tier, tier2_division, name, id) WHERE (deleted_at IS NULL);
CREATE UNIQUE INDEX clubs_referral_code_key ON public.clubs USING btree (referral_code);
CREATE INDEX clubs_tier2_live_ranking_idx ON public.clubs USING btree (club_tier, tier2_division, name, id) WHERE (deleted_at IS NULL);
CREATE INDEX clubs_tier3_live_ranking_idx ON public.clubs USING btree (club_tier, tier3_division, name, id) WHERE (deleted_at IS NULL);
CREATE INDEX competition_transition_movements_v1_club_idx ON public.competition_transition_movements_v1 USING btree (transition_run_id, club_id);
CREATE INDEX competition_transition_movements_v1_run_idx ON public.competition_transition_movements_v1 USING btree (transition_run_id, phase, movement_type);
CREATE INDEX contact_message_admin_reads_admin_idx ON public.contact_message_admin_reads USING btree (admin_user_id, read_at DESC);
CREATE INDEX contact_messages_admin_status_created_idx ON public.contact_messages USING btree (admin_status, created_at DESC);
CREATE INDEX contact_messages_email_status_created_idx ON public.contact_messages USING btree (email_status, created_at DESC);
CREATE INDEX country_market_group_members_group_idx ON public.country_market_group_members USING btree (group_code);
CREATE INDEX cross_game_referral_events_created_at_idx ON public.cross_game_referral_events USING btree (created_at DESC);
CREATE INDEX cross_game_referral_events_pair_idx ON public.cross_game_referral_events USING btree (source_game, destination_game, event_type, created_at DESC);
CREATE UNIQUE INDEX cycling_world_news_article_url_uidx ON public.cycling_world_news USING btree (article_url);
CREATE UNIQUE INDEX cycling_world_news_deduplication_hash_uidx ON public.cycling_world_news USING btree (deduplication_hash);
CREATE INDEX cycling_world_news_source_published_idx ON public.cycling_world_news USING btree (source_id, published_at DESC);
CREATE INDEX cycling_world_news_visible_published_idx ON public.cycling_world_news USING btree (is_visible, published_at DESC);
CREATE INDEX developing_team_season_access_status_idx ON public.developing_team_season_access USING btree (access_status, auto_renew, expires_after_season);
CREATE INDEX email_outbox_pending_idx ON public.email_outbox USING btree (status, created_at) WHERE (status = 'pending'::text);
CREATE INDEX equipment_catalog_brand_company_idx ON public.equipment_catalog USING btree (brand_company_id);
CREATE INDEX equipment_catalog_kind_category_idx ON public.equipment_catalog USING btree (equipment_kind, equipment_category);
CREATE INDEX game_world_reset_checkpoints_run_phase_idx ON public.game_world_reset_checkpoints USING btree (reset_run_id, phase, created_at);
CREATE INDEX game_world_reset_runs_created_at_idx ON public.game_world_reset_runs USING btree (created_at DESC);
CREATE INDEX game_world_reset_runs_status_idx ON public.game_world_reset_runs USING btree (status, created_at DESC);
CREATE INDEX homepage_player_reviews_status_created_at_idx ON public.homepage_player_reviews USING btree (status, created_at);
CREATE INDEX idx_ai_roster_transition_audit_run_v1 ON public.ai_roster_transition_audit_v1 USING btree (transition_run_id, action);
CREATE INDEX idx_club_infrastructure_jobs_club_status_complete ON public.club_infrastructure_jobs USING btree (club_id, status, complete_at);
CREATE INDEX idx_club_infrastructure_jobs_status_complete ON public.club_infrastructure_jobs USING btree (status, complete_at);
CREATE INDEX idx_club_medical_vans_club_status ON public.club_medical_vans USING btree (club_id, status);
CREATE INDEX idx_club_restart_released_riders_club_id ON public.club_restart_released_riders USING btree (club_id);
CREATE INDEX idx_club_restart_released_riders_restart_id ON public.club_restart_released_riders USING btree (restart_id);
CREATE INDEX idx_club_restart_released_riders_rider_id ON public.club_restart_released_riders USING btree (rider_id);
CREATE INDEX idx_club_riders_club ON public.club_riders USING btree (club_id);
CREATE INDEX idx_club_riders_rider ON public.club_riders USING btree (rider_id);
CREATE INDEX idx_club_riders_rider_lookup_v1 ON public.club_riders USING btree (rider_id, club_id);
CREATE INDEX idx_club_technical_sponsor_benefits_active ON public.club_technical_sponsor_benefits USING btree (club_id, sponsor_company_id, status);
CREATE INDEX idx_clubs_club_tier ON public.clubs USING btree (club_tier);
CREATE INDEX idx_clubs_tier2_division ON public.clubs USING btree (tier2_division);
CREATE INDEX idx_clubs_tier3_division ON public.clubs USING btree (tier3_division);
CREATE INDEX idx_competition_hourly_ai_fill_audit_club_v1 ON public.competition_hourly_ai_fill_audit_v1 USING btree (club_id, created_at DESC);
CREATE INDEX idx_competition_hourly_ai_fill_audit_run_v1 ON public.competition_hourly_ai_fill_audit_v1 USING btree (run_id, created_at);
CREATE INDEX idx_cron_guard_run_log_v1_job_created ON public.cron_guard_run_log_v1 USING btree (job_key, created_at DESC);
CREATE INDEX idx_first_names_master_country ON public.first_names_master USING btree (country_code);
CREATE INDEX idx_game_daily_tick_backlog_v1_status_date ON public.game_daily_tick_backlog_v1 USING btree (status, current_game_date);
CREATE INDEX idx_generated_rider_first_names_country_active ON public.generated_rider_first_names USING btree (country_code, is_active);
CREATE INDEX idx_generated_rider_last_names_country_active ON public.generated_rider_last_names USING btree (country_code, is_active);
CREATE INDEX idx_homepage_player_reviews_status_approved ON public.homepage_player_reviews USING btree (status, approved_at DESC NULLS LAST);
CREATE INDEX idx_homepage_player_reviews_status_created ON public.homepage_player_reviews USING btree (status, created_at DESC);
CREATE INDEX idx_inbox_conversation_participants_user ON public.inbox_conversation_participants USING btree (user_id, archived_at, conversation_id);
CREATE INDEX idx_inbox_conversations_last_message ON public.inbox_conversations USING btree (last_message_at DESC);
CREATE INDEX idx_inbox_messages_conversation_created ON public.inbox_messages USING btree (conversation_id, created_at DESC);
CREATE INDEX idx_last_names_master_country ON public.last_names_master USING btree (country_code);
CREATE INDEX idx_notifications_created ON public.notifications USING btree (created_at DESC);
CREATE INDEX idx_race_engine_stage_effect_history_v2_effect ON public.race_engine_stage_effect_history_v2 USING btree (effect_id, event_sequence);
CREATE INDEX idx_race_engine_stage_effect_history_v2_stage ON public.race_engine_stage_effect_history_v2 USING btree (stage_id, event_sequence);
CREATE INDEX idx_race_engine_stage_effect_ledger_v2_race ON public.race_engine_stage_effect_ledger_v2 USING btree (race_id, stage_id);
CREATE INDEX idx_race_engine_stage_effect_ledger_v2_status ON public.race_engine_stage_effect_ledger_v2 USING btree (effect_status, created_at DESC);
CREATE INDEX idx_race_engine_stage_effect_shadow_claim_v2_run ON public.race_engine_stage_effect_shadow_claim_v2 USING btree (shadow_run_id, claim_status);
CREATE INDEX idx_race_engine_stage_effect_shadow_claim_v2_stage ON public.race_engine_stage_effect_shadow_claim_v2 USING btree (stage_id, effect_key, created_at DESC);
CREATE INDEX idx_race_engine_stage_immutable_state_v2_race ON public.race_engine_stage_immutable_state_v2 USING btree (race_id, stage_id);
CREATE INDEX idx_race_engine_stage_immutable_state_v2_status ON public.race_engine_stage_immutable_state_v2 USING btree (immutable_status, created_at DESC);
CREATE INDEX idx_race_engine_stage_postprocessor_skip_logs_run ON public.race_engine_stage_postprocessor_skip_logs USING btree (simulation_run_id, main_club_id);
CREATE INDEX idx_race_engine_stage_postprocessor_skip_logs_stage_team ON public.race_engine_stage_postprocessor_skip_logs USING btree (stage_id, main_club_id, skip_reason);
CREATE INDEX idx_race_engine_stage_process_claim_history_v2_process_run ON public.race_engine_stage_process_claim_history_v2 USING btree (active_process_run_id, event_sequence);
CREATE INDEX idx_race_engine_stage_process_claim_history_v2_stage ON public.race_engine_stage_process_claim_history_v2 USING btree (stage_id, event_sequence);
CREATE INDEX idx_race_engine_stage_process_claim_history_v2_status ON public.race_engine_stage_process_claim_history_v2 USING btree (event_type, recorded_at DESC);
CREATE INDEX idx_race_engine_stage_process_claim_v2_race ON public.race_engine_stage_process_claim_v2 USING btree (race_id, stage_id);
CREATE INDEX idx_race_engine_stage_process_claim_v2_status ON public.race_engine_stage_process_claim_v2 USING btree (claim_status, heartbeat_at, expires_at);
CREATE INDEX idx_race_engine_stage_process_runs_v2_stage ON public.race_engine_stage_process_runs_v2 USING btree (stage_id, created_at DESC);
CREATE INDEX idx_race_engine_stage_process_runs_v2_status ON public.race_engine_stage_process_runs_v2 USING btree (status, created_at DESC);
CREATE INDEX idx_race_engine_stage_processing_attempts_stage_v1 ON public.race_engine_stage_processing_attempts_v1 USING btree (stage_id, created_at DESC);
CREATE INDEX idx_race_engine_stage_processing_attempts_status_v1 ON public.race_engine_stage_processing_attempts_v1 USING btree (status, created_at DESC);
CREATE INDEX idx_race_engine_stage_processor_shadow_case_v2_stage ON public.race_engine_stage_processor_shadow_case_v2 USING btree (stage_id, created_at DESC);
CREATE INDEX idx_race_engine_stage_runner_handoff_history_v2_stage ON public.race_engine_stage_runner_handoff_history_v2 USING btree (stage_id, recorded_at, event_sequence);
CREATE INDEX idx_race_engine_stage_runner_handoff_v2_status ON public.race_engine_stage_runner_handoff_v2 USING btree (handoff_status, updated_at DESC);
CREATE INDEX idx_race_plan_effect_rules_lookup ON public.race_plan_effect_rules USING btree (source_type, source_key, source_level, is_active, sort_order);
CREATE INDEX idx_race_preparation_assets_asset ON public.race_preparation_assets USING btree (asset_key, asset_id);
CREATE INDEX idx_race_preparation_riders_rider ON public.race_preparation_riders USING btree (rider_id);
CREATE INDEX idx_race_preparation_staff_staff ON public.race_preparation_staff USING btree (staff_id);
CREATE INDEX idx_race_preparations_club_status ON public.race_preparations USING btree (club_id, status);
CREATE INDEX idx_race_preparations_deadline ON public.race_preparations USING btree (rider_submission_deadline_on, status);
CREATE INDEX idx_race_preparations_race_status ON public.race_preparations USING btree (race_id, status);
CREATE INDEX idx_race_stage_incidents_rider ON public.race_stage_incidents USING btree (rider_id);
CREATE INDEX idx_race_stage_incidents_run ON public.race_stage_incidents USING btree (simulation_run_id);
CREATE INDEX idx_race_stage_incidents_stage ON public.race_stage_incidents USING btree (stage_id);
CREATE INDEX idx_race_stage_incidents_type ON public.race_stage_incidents USING btree (incident_type);
CREATE INDEX idx_race_stage_plan_assets_asset ON public.race_stage_plan_assets USING btree (asset_key, asset_id);
CREATE INDEX idx_race_stage_plan_automation_events_retry ON public.race_stage_plan_automation_stage_events USING btree (processing_status, updated_at, race_preparation_id);
CREATE INDEX idx_race_stage_plan_automation_events_source_run ON public.race_stage_plan_automation_stage_events USING btree (source_simulation_run_id);
CREATE INDEX idx_race_stage_plan_riders_rider ON public.race_stage_plan_riders USING btree (rider_id);
CREATE INDEX idx_race_stage_plans_open_lock ON public.race_stage_plans USING btree (opens_on_game_date, locks_on_game_date, status);
CREATE INDEX idx_race_stage_plans_race_status ON public.race_stage_plans USING btree (race_id, status);
CREATE INDEX idx_race_stage_rider_states_rider ON public.race_stage_rider_states USING btree (rider_id);
CREATE INDEX idx_race_stage_rider_states_run ON public.race_stage_rider_states USING btree (simulation_run_id);
CREATE INDEX idx_race_stage_rider_states_stage ON public.race_stage_rider_states USING btree (stage_id);
CREATE INDEX idx_race_stage_rider_states_team ON public.race_stage_rider_states USING btree (team_id);
CREATE INDEX idx_race_stage_simulation_runs_race_id ON public.race_stage_simulation_runs USING btree (race_id);
CREATE INDEX idx_race_stage_simulation_runs_stage_id ON public.race_stage_simulation_runs USING btree (stage_id);
CREATE INDEX idx_race_stage_simulation_runs_status ON public.race_stage_simulation_runs USING btree (status);
CREATE INDEX idx_race_stage_team_states_run ON public.race_stage_team_states USING btree (simulation_run_id);
CREATE INDEX idx_race_stage_team_states_stage ON public.race_stage_team_states USING btree (stage_id);
CREATE INDEX idx_race_stage_team_states_team ON public.race_stage_team_states USING btree (team_id);
CREATE INDEX idx_race_stage_weather_exposure_rider_date ON public.race_stage_weather_exposure_events USING btree (rider_id, stage_date DESC);
CREATE INDEX idx_race_team_stage_disqualifications_stage ON public.race_team_stage_disqualifications USING btree (race_id, from_stage_number, team_id);
CREATE INDEX idx_re_stage_cmd_delta_apps_rider ON public.race_engine_stage_command_outcome_delta_applications USING btree (rider_id);
CREATE INDEX idx_re_stage_cmd_delta_apps_stage_club ON public.race_engine_stage_command_outcome_delta_applications USING btree (stage_id, club_id);
CREATE INDEX idx_re_stage_cmd_delta_apps_status ON public.race_engine_stage_command_outcome_delta_applications USING btree (application_status);
CREATE INDEX idx_replay_frames_point_crossing_fast_v2 ON public.race_stage_replay_frames USING btree (simulation_run_id, stage_id, replay_mode, entity_type, km_marker, frame_number, race_seconds);
CREATE INDEX idx_replay_frames_point_crossing_v1 ON public.race_stage_replay_frames USING btree (simulation_run_id, stage_id, replay_mode, entity_type, km_marker, frame_number, race_seconds);
CREATE INDEX idx_replay_frames_point_frame_v1 ON public.race_stage_replay_frames USING btree (simulation_run_id, stage_id, replay_mode, entity_type, frame_number, group_order);
CREATE INDEX idx_replay_frames_point_writer_fast_v2 ON public.race_stage_replay_frames USING btree (simulation_run_id, stage_id, replay_mode, entity_type, frame_number, group_order);
CREATE INDEX idx_retirement_decisions_due_announcement ON public.retirement_decisions USING btree (announcement_game_date, status);
CREATE INDEX idx_retirement_decisions_owner ON public.retirement_decisions USING btree (owner_user_id, season_number);
CREATE INDEX idx_retirement_decisions_season_status ON public.retirement_decisions USING btree (season_number, status);
CREATE INDEX idx_rider_contract_negotiations_club ON public.rider_contract_negotiations USING btree (club_id);
CREATE INDEX idx_rider_contract_negotiations_rider ON public.rider_contract_negotiations USING btree (rider_id);
CREATE INDEX idx_rider_contract_negotiations_status ON public.rider_contract_negotiations USING btree (status);
CREATE INDEX idx_rider_contracts_active_rider_lookup_v1 ON public.rider_contracts USING btree (rider_id, club_id) WHERE (status = 'active'::rider_contract_status);
CREATE INDEX idx_rider_contracts_club ON public.rider_contracts USING btree (club_id);
CREATE INDEX idx_rider_contracts_end_season ON public.rider_contracts USING btree (end_season_number);
CREATE INDEX idx_rider_contracts_rider ON public.rider_contracts USING btree (rider_id);
CREATE INDEX idx_rider_contracts_start_season ON public.rider_contracts USING btree (start_season_number);
CREATE INDEX idx_rider_contracts_status ON public.rider_contracts USING btree (status);
CREATE INDEX idx_rider_free_agents_transition_available_v1 ON public.rider_free_agents USING btree (status, available_from_game_date, expires_on_game_date, id);
CREATE INDEX idx_rider_payroll_state_club ON public.rider_payroll_state USING btree (club_id);
CREATE INDEX idx_rider_payroll_state_rider ON public.rider_payroll_state USING btree (rider_id);
CREATE INDEX idx_rider_payroll_state_status ON public.rider_payroll_state USING btree (payroll_status);
CREATE INDEX idx_rider_skill_weekly_snapshots_rider_week ON public.rider_skill_weekly_snapshots USING btree (rider_id, week_start_date DESC);
CREATE INDEX idx_rider_states_point_writer_fast_v2 ON public.race_stage_rider_states USING btree (simulation_run_id, rider_id, finish_position);
CREATE INDEX idx_rider_states_point_writer_v1 ON public.race_stage_rider_states USING btree (simulation_run_id, rider_id);
CREATE INDEX idx_rider_weekly_dev_summaries_rider ON public.rider_weekly_development_summaries USING btree (rider_id, week_end_date DESC);
CREATE INDEX idx_rider_weekly_dev_summaries_week_end ON public.rider_weekly_development_summaries USING btree (week_end_date DESC);
CREATE INDEX idx_rider_weekly_development_summary_week ON public.rider_weekly_development_summary USING btree (week_end_date DESC);
CREATE INDEX idx_rider_weekly_skill_changes_latest ON public.rider_weekly_skill_changes USING btree (rider_id, week_end_date DESC, processed_at DESC);
CREATE INDEX idx_rider_weekly_skill_changes_rider ON public.rider_weekly_skill_changes USING btree (rider_id, week_end_date DESC);
CREATE INDEX idx_rider_weekly_skill_changes_rider_week ON public.rider_weekly_skill_changes USING btree (rider_id, week_end_date DESC);
CREATE INDEX idx_rider_weekly_skill_changes_week ON public.rider_weekly_skill_changes USING btree (week_end_date DESC);
CREATE INDEX idx_rider_weekly_skill_changes_week_attr ON public.rider_weekly_skill_changes USING btree (rider_id, week_start_date, week_end_date, attribute_code);
CREATE INDEX idx_riders_country ON public.riders USING btree (country_code);
CREATE INDEX idx_riders_role ON public.riders USING btree (role);
CREATE INDEX idx_staff_advisory_access_staff ON public.staff_advisory_access USING btree (staff_id);
CREATE INDEX idx_staff_advisory_access_user_club ON public.staff_advisory_access USING btree (user_id, club_id);
CREATE INDEX idx_staff_advisory_notification_mutes_user_muted ON public.staff_advisory_notification_mutes USING btree (user_id, is_muted, report_code);
CREATE INDEX idx_staff_advisory_purchases_user_club ON public.staff_advisory_purchases USING btree (user_id, club_id, created_at DESC);
CREATE INDEX idx_staff_advisory_reports_staff ON public.staff_advisory_reports USING btree (staff_id, generated_at DESC);
CREATE INDEX idx_staff_advisory_reports_user_club ON public.staff_advisory_reports USING btree (user_id, club_id, generated_at DESC);
CREATE INDEX idx_staff_candidates_available_expires_at ON public.staff_candidates USING btree (expires_at_game_ts) WHERE ((is_available = true) AND (expires_at_game_ts IS NOT NULL));
CREATE INDEX idx_staff_contract_transition_audit_run_v1 ON public.staff_contract_transition_audit_v1 USING btree (transition_run_id, action);
CREATE INDEX idx_staff_courses_club_status_staff ON public.staff_courses USING btree (club_id, status, staff_id, created_at DESC);
CREATE INDEX idx_staff_courses_staff_id ON public.staff_courses USING btree (staff_id);
CREATE INDEX idx_staff_courses_status_completes ON public.staff_courses USING btree (status, completes_on_game_date);
CREATE INDEX idx_stage_incident_equipment_damage_source ON public.race_engine_stage_incident_equipment_damage_applications USING btree (source_outcome_id);
CREATE INDEX idx_stage_incident_equipment_damage_stage ON public.race_engine_stage_incident_equipment_damage_applications USING btree (stage_id, club_id);
CREATE INDEX idx_stage_points_writer_v1 ON public.race_stage_points USING btree (stage_id, point_type, km_from_start);
CREATE INDEX idx_team_ranking_season_snapshots_season ON public.team_ranking_season_snapshots USING btree (season_number);
CREATE INDEX idx_team_ranking_season_snapshots_season_division ON public.team_ranking_season_snapshots USING btree (season_number, division);
CREATE INDEX idx_transfer_value_audit_created_at ON public.transfer_value_audit USING btree (created_at DESC);
CREATE INDEX idx_transfer_value_audit_offer_id ON public.transfer_value_audit USING btree (offer_id);
CREATE INDEX idx_transfer_value_audit_rider_id ON public.transfer_value_audit USING btree (rider_id);
CREATE INDEX idx_unsolicited_bids_buyer ON public.rider_unsolicited_transfer_bids USING btree (buyer_club_id, status);
CREATE INDEX idx_unsolicited_bids_rider ON public.rider_unsolicited_transfer_bids USING btree (rider_id);
CREATE INDEX idx_unsolicited_bids_seller ON public.rider_unsolicited_transfer_bids USING btree (seller_club_id, status);
CREATE INDEX idx_user_notifications_unread_only ON public.user_notifications USING btree (user_id, created_at DESC) WHERE (((status)::text = 'unread'::text) AND (deleted_at IS NULL));
CREATE INDEX idx_user_notifications_user_created ON public.user_notifications USING btree (user_id, created_at DESC);
CREATE INDEX idx_user_notifications_user_status_created ON public.user_notifications USING btree (user_id, status, created_at DESC);
CREATE INDEX idx_user_rewarded_ad_coin_grants_user_date ON public.user_rewarded_ad_coin_grants USING btree (user_id, reward_date DESC);
CREATE INDEX idx_user_rewarded_ad_daily_progress_user_date ON public.user_rewarded_ad_daily_progress USING btree (user_id, reward_date DESC);
CREATE INDEX idx_user_rewarded_ad_events_ip_date ON public.user_rewarded_ad_events USING btree (ip_hash, reward_date) WHERE (ip_hash IS NOT NULL);
CREATE INDEX idx_user_rewarded_ad_events_user_date ON public.user_rewarded_ad_events USING btree (user_id, reward_date, created_at DESC);
CREATE INDEX idx_user_team_inactivity_events_club_id ON public.user_team_inactivity_events USING btree (club_id);
CREATE INDEX idx_user_team_inactivity_events_created_at ON public.user_team_inactivity_events USING btree (created_at DESC);
CREATE INDEX idx_user_team_inactivity_events_user_id ON public.user_team_inactivity_events USING btree (user_id);
CREATE INDEX inbox_messages_game_season_number_idx ON public.inbox_messages USING btree (game_season_number) WHERE (game_season_number IS NOT NULL);
CREATE UNIQUE INDEX infrastructure_asset_config_asset_level_uidx ON public.infrastructure_asset_config USING btree (asset_key, asset_level);
CREATE INDEX national_association_maintenance_log_date_idx ON public.national_association_maintenance_log USING btree (game_date DESC, created_at DESC);
CREATE INDEX national_association_memberships_assoc_status_idx ON public.national_association_memberships USING btree (association_id, status);
CREATE UNIQUE INDEX national_association_memberships_one_active_per_user_idx ON public.national_association_memberships USING btree (user_id) WHERE (status = 'active'::text);
CREATE INDEX national_championship_bonus_rider_date_idx ON public.national_championship_ranking_bonus_awards USING btree (rider_id, award_date DESC);
CREATE INDEX national_championship_duties_heat_idx ON public.national_championship_duties USING btree (heat_id) WHERE (heat_id IS NOT NULL);
CREATE INDEX national_championship_duties_rider_date_idx ON public.national_championship_duties USING btree (rider_id, duty_date) WHERE (status = 'confirmed'::text);
CREATE INDEX national_championship_duties_window_idx ON public.national_championship_duties USING btree (rider_id, duty_start_date, duty_end_date, status);
CREATE INDEX national_championship_editions_champion_rider_idx ON public.national_championship_editions USING btree (champion_rider_id) WHERE (champion_rider_id IS NOT NULL);
CREATE INDEX national_championship_editions_country_idx ON public.national_championship_editions USING btree (country_code, season_number DESC);
CREATE INDEX national_championship_editions_due_idx ON public.national_championship_editions USING btree (status, ranking_snapshot_date, qualification_date, final_date);
CREATE INDEX national_championship_editions_final_race_idx ON public.national_championship_editions USING btree (final_race_id) WHERE (final_race_id IS NOT NULL);
CREATE INDEX national_championship_editions_final_source_stage_idx ON public.national_championship_editions USING btree (final_source_stage_id) WHERE (final_source_stage_id IS NOT NULL);
CREATE INDEX national_championship_editions_qualification_source_stage_idx ON public.national_championship_editions USING btree (qualification_source_stage_id) WHERE (qualification_source_stage_id IS NOT NULL);
CREATE INDEX national_championship_editions_schedule_idx ON public.national_championship_editions USING btree (season_number, climate_status, route_status, ranking_snapshot_date);
CREATE INDEX national_championship_entries_decision_idx ON public.national_championship_entries USING btree (edition_id, participation_decision, entry_status);
CREATE INDEX national_championship_entries_edition_status_idx ON public.national_championship_entries USING btree (edition_id, entry_status, national_rank);
CREATE INDEX national_championship_entries_heat_idx ON public.national_championship_entries USING btree (heat_id) WHERE (heat_id IS NOT NULL);
CREATE INDEX national_championship_entries_rider_idx ON public.national_championship_entries USING btree (rider_id, edition_id);
CREATE INDEX national_championship_heats_race_idx ON public.national_championship_heats USING btree (race_id) WHERE (race_id IS NOT NULL);
CREATE INDEX national_championship_ranking_club_idx ON public.national_championship_ranking_snapshots USING btree (club_id) WHERE (club_id IS NOT NULL);
CREATE INDEX national_championship_ranking_lookup_idx ON public.national_championship_ranking_snapshots USING btree (edition_id, national_rank);
CREATE INDEX national_championship_ranking_rider_idx ON public.national_championship_ranking_snapshots USING btree (rider_id, edition_id);
CREATE INDEX national_championship_result_history_heat_idx ON public.national_championship_result_history USING btree (heat_id) WHERE (heat_id IS NOT NULL);
CREATE INDEX national_championship_result_history_lookup_idx ON public.national_championship_result_history USING btree (edition_id, event_type, heat_id, rank);
CREATE INDEX national_championship_result_history_race_idx ON public.national_championship_result_history USING btree (race_id) WHERE (race_id IS NOT NULL);
CREATE INDEX national_championship_result_history_rider_idx ON public.national_championship_result_history USING btree (rider_id) WHERE (rider_id IS NOT NULL);
CREATE UNIQUE INDEX national_championship_result_history_unique_result_idx ON public.national_championship_result_history USING btree (edition_id, event_type, COALESCE(heat_id, '00000000-0000-0000-0000-000000000000'::uuid), rider_id) WHERE (rider_id IS NOT NULL);
CREATE INDEX national_championship_rider_plans_equipment_idx ON public.national_championship_rider_plans USING btree (equipment_setup_id) WHERE (equipment_setup_id IS NOT NULL);
CREATE INDEX national_championship_rider_plans_heat_idx ON public.national_championship_rider_plans USING btree (heat_id) WHERE (heat_id IS NOT NULL);
CREATE INDEX national_championship_rider_plans_rider_idx ON public.national_championship_rider_plans USING btree (rider_id, edition_id);
CREATE INDEX national_coach_elections_assoc_status_idx ON public.national_coach_elections USING btree (association_id, status);
CREATE INDEX national_coach_terms_assoc_season_idx ON public.national_coach_terms USING btree (association_id, season_number DESC);
CREATE UNIQUE INDEX national_coach_terms_one_active_per_association_idx ON public.national_coach_terms USING btree (association_id) WHERE (status = 'active'::text);
CREATE INDEX national_coach_votes_election_round_candidate_idx ON public.national_coach_votes USING btree (election_id, round_number, candidate_id);
CREATE INDEX national_team_callups_assoc_cycle_status_idx ON public.national_team_callups USING btree (association_id, season_number, cycle_key, status);
CREATE INDEX national_team_callups_owner_pending_idx ON public.national_team_callups USING btree (club_owner_user_id_snapshot, status, response_deadline);
CREATE INDEX national_team_duties_date_status_idx ON public.national_team_duties USING btree (status, start_date, end_date);
CREATE INDEX national_team_lineup_members_rider_idx ON public.national_team_lineup_members USING btree (rider_id, lineup_id);
CREATE INDEX national_team_squad_members_rider_idx ON public.national_team_squad_members USING btree (rider_id, squad_id);
CREATE INDEX nations_competition_entries_edition_status_idx ON public.nations_competition_entries USING btree (edition_id, status, seed_score DESC);
CREATE INDEX nations_group_events_race_idx ON public.nations_group_events USING btree (race_id) WHERE (race_id IS NOT NULL);
CREATE INDEX nations_group_events_stage_idx ON public.nations_group_events USING btree (stage_id) WHERE (stage_id IS NOT NULL);
CREATE UNIQUE INDEX player_reports_one_unreviewed_per_target ON public.player_reports USING btree (reported_user_id) WHERE (reviewed_at IS NULL);
CREATE INDEX premium_invoice_payments_subscription_idx ON public.premium_invoice_payments USING btree (stripe_subscription_id);
CREATE INDEX premium_invoice_payments_user_idx ON public.premium_invoice_payments USING btree (user_id, processed_at DESC);
CREATE INDEX premium_manager_automation_club_idx ON public.premium_manager_automation_rules_v1 USING btree (club_id, rule_type, is_enabled);
CREATE INDEX premium_manager_templates_club_type_idx ON public.premium_manager_templates_v1 USING btree (club_id, template_type, updated_at DESC);
CREATE INDEX premium_payment_failures_invoice_idx ON public.premium_payment_failures USING btree (stripe_invoice_id);
CREATE INDEX premium_payment_failures_user_idx ON public.premium_payment_failures USING btree (user_id, recorded_at DESC);
CREATE UNIQUE INDEX premium_plans_provider_price_id_uidx ON public.premium_plans USING btree (provider_price_id) WHERE (provider_price_id IS NOT NULL);
CREATE UNIQUE INDEX premium_plans_provider_product_id_uidx ON public.premium_plans USING btree (provider_product_id) WHERE (provider_product_id IS NOT NULL);
CREATE UNIQUE INDEX profiles_email_lower_unique_idx ON public.profiles USING btree (lower(btrim(email))) WHERE ((email IS NOT NULL) AND (btrim(email) <> ''::text));
CREATE INDEX profiles_has_created_club_idx ON public.profiles USING btree (has_created_club);
CREATE UNIQUE INDEX profiles_username_lower_key ON public.profiles USING btree (lower(username));
CREATE UNIQUE INDEX race_commitment_score_events_entry_event_unique_idx ON public.race_commitment_score_events USING btree (race_team_entry_id, event_type);
CREATE INDEX race_engine_calculation_survival_audit_stage_idx ON public.race_engine_calculation_survival_audit_v1 USING btree (stage_id, created_at DESC);
CREATE INDEX race_engine_phase3aa_base_result_correction_audit_v1_stage_idx ON public.race_engine_phase3aa_base_result_correction_audit_v1 USING btree (stage_id, created_at DESC);
CREATE UNIQUE INDEX race_engine_phase3aa_completed_prize_correction_plan_v1_idempot ON public.race_engine_phase3aa_completed_prize_correction_plan_v1 USING btree (planned_idempotency_key);
CREATE UNIQUE INDEX race_engine_phase3aa_completed_prize_correction_plan_v1_operati ON public.race_engine_phase3aa_completed_prize_correction_plan_v1 USING btree (stage_id, rank, operation_order);
CREATE UNIQUE INDEX race_engine_phase3aa_completed_prize_entitlement_v1_award_idx ON public.race_engine_phase3aa_completed_prize_entitlement_v1 USING btree (prize_award_id);
CREATE UNIQUE INDEX race_engine_phase3aa_completed_prize_entitlement_v1_rank_idx ON public.race_engine_phase3aa_completed_prize_entitlement_v1 USING btree (stage_id, rank);
CREATE INDEX race_engine_phase3aa_completed_prize_entry_v1_tx_idx ON public.race_engine_phase3aa_completed_prize_entry_v1 USING btree (transaction_id);
CREATE UNIQUE INDEX race_engine_phase3aa_completed_prize_event_lock_v1_idx ON public.race_engine_phase3aa_completed_prize_event_lock_v1 USING btree (event_type, club_id, ref_id);
CREATE UNIQUE INDEX race_engine_phase3aa_completed_prize_function_contract_v1_oid_i ON public.race_engine_phase3aa_completed_prize_function_contract_v1 USING btree (function_oid);
CREATE UNIQUE INDEX race_engine_phase3aa_completed_prize_transaction_v1_id_idx ON public.race_engine_phase3aa_completed_prize_transaction_v1 USING btree (transaction_id);
CREATE UNIQUE INDEX race_engine_phase3aa_downstream_function_audit_v1_oid_idx ON public.race_engine_phase3aa_downstream_function_audit_v1 USING btree (function_oid);
CREATE UNIQUE INDEX race_engine_phase3aa_downstream_function_relation_refs_v1_idx ON public.race_engine_phase3aa_downstream_function_relation_refs_v1 USING btree (function_oid, referenced_public_object);
CREATE UNIQUE INDEX race_engine_phase3aa_downstream_relation_contract_v1_name_idx ON public.race_engine_phase3aa_downstream_relation_contract_v1 USING btree (relation_name);
CREATE UNIQUE INDEX race_engine_phase3aa_finance_relation_columns_v1_name_idx ON public.race_engine_phase3aa_finance_relation_columns_v1 USING btree (table_schema, table_name);
CREATE UNIQUE INDEX race_engine_phase3aa_paid_prize_snapshot_v1_id_idx ON public.race_engine_phase3aa_paid_prize_snapshot_v1 USING btree (prize_award_id);
CREATE UNIQUE INDEX race_engine_phase3aa_point_gate_semantic_map_v1_official_idx ON public.race_engine_phase3aa_point_gate_semantic_map_v1 USING btree (official_point_id);
CREATE UNIQUE INDEX race_engine_phase3aa_point_gate_semantic_map_v1_preview_idx ON public.race_engine_phase3aa_point_gate_semantic_map_v1 USING btree (preview_point_id);
CREATE UNIQUE INDEX race_engine_phase3aa_point_result_preview_v1_point_rank_idx ON public.race_engine_phase3aa_point_result_preview_cache_v1 USING btree (point_id, rank);
CREATE UNIQUE INDEX race_engine_phase3aa_point_result_preview_v1_point_rider_idx ON public.race_engine_phase3aa_point_result_preview_cache_v1 USING btree (point_id, rider_id);
CREATE INDEX race_engine_phase3aa_point_result_preview_v1_rider_idx ON public.race_engine_phase3aa_point_result_preview_cache_v1 USING btree (stage_id, rider_id);
CREATE UNIQUE INDEX race_engine_phase3aa_point_result_semantic_map_v1_result_idx ON public.race_engine_phase3aa_point_result_semantic_map_v1 USING btree (official_result_id);
CREATE UNIQUE INDEX race_engine_phase3aa_point_result_semantic_map_v1_target_idx ON public.race_engine_phase3aa_point_result_semantic_map_v1 USING btree (preview_point_id, preview_rider_id);
CREATE UNIQUE INDEX race_engine_phase3aa_prize_function_relation_refs_v1_idx ON public.race_engine_phase3aa_prize_function_relation_refs_v1 USING btree (function_oid, referenced_public_object);
CREATE UNIQUE INDEX race_engine_phase3aa_prize_payment_function_v1_oid_idx ON public.race_engine_phase3aa_prize_payment_function_v1 USING btree (function_oid);
CREATE UNIQUE INDEX race_engine_phase3aa_prize_reversal_function_audit_v1_oid_idx ON public.race_engine_phase3aa_prize_reversal_function_audit_v1 USING btree (function_oid);
CREATE UNIQUE INDEX race_engine_phase3aa_prize_reversal_relation_audit_v1_name_idx ON public.race_engine_phase3aa_prize_reversal_relation_audit_v1 USING btree (relation_name);
CREATE UNIQUE INDEX race_engine_phase3aa_result_column_audit_v1_column_idx ON public.race_engine_phase3aa_result_column_audit_v1 USING btree (table_name, column_name);
CREATE UNIQUE INDEX race_engine_phase3aa_result_constraint_audit_v1_name_idx ON public.race_engine_phase3aa_result_constraint_audit_v1 USING btree (table_name, constraint_name);
CREATE UNIQUE INDEX race_engine_phase3aa_result_index_audit_v1_name_idx ON public.race_engine_phase3aa_result_index_audit_v1 USING btree (table_name, index_name);
CREATE UNIQUE INDEX race_engine_phase3aa_result_trigger_audit_v1_name_idx ON public.race_engine_phase3aa_result_trigger_audit_v1 USING btree (table_name, trigger_name);
CREATE UNIQUE INDEX race_engine_phase3aa_side_effect_snapshot_v1_stage_idx ON public.race_engine_phase3aa_side_effect_snapshot_v1 USING btree (stage_id);
CREATE INDEX race_engine_phase3aa_stage_result_preview_v1_group_idx ON public.race_engine_phase3aa_stage_result_preview_cache_v1 USING btree (stage_id, effective_live_group_rank, group_finish_rank);
CREATE UNIQUE INDEX race_engine_phase3aa_stage_result_preview_v1_rank_idx ON public.race_engine_phase3aa_stage_result_preview_cache_v1 USING btree (stage_id, rank);
CREATE UNIQUE INDEX race_engine_phase3aa_stage_result_preview_v1_rider_idx ON public.race_engine_phase3aa_stage_result_preview_cache_v1 USING btree (stage_id, rider_id);
CREATE UNIQUE INDEX race_engine_phase3aa_writer_function_audit_v1_oid_idx ON public.race_engine_phase3aa_writer_function_audit_v1 USING btree (function_oid);
CREATE INDEX race_engine_phase3q_launch_cache_v1_rider_step_idx ON public.race_engine_phase3q_launch_cache_v1 USING btree (rider_id, selected_step_order);
CREATE INDEX race_engine_phase3q_pace_cache_v1_rider_step_idx ON public.race_engine_phase3q_pace_cache_v1 USING btree (rider_id, step_order);
CREATE INDEX race_engine_phase3q_pace_cache_v1_step_group_idx ON public.race_engine_phase3q_pace_cache_v1 USING btree (step_order, live_group_code);
CREATE INDEX race_engine_phase3q_survival_cache_v1_launch_scenario_step_idx ON public.race_engine_phase3q_survival_cache_v1 USING btree (attack_launch_event_key, response_scenario_code, step_order);
CREATE INDEX race_engine_phase3q_survival_cache_v1_rider_scenario_step_idx ON public.race_engine_phase3q_survival_cache_v1 USING btree (rider_id, response_scenario_code, step_order);
CREATE UNIQUE INDEX race_engine_phase3r_pursuit_calibration_v1_key_idx ON public.race_engine_phase3r_pursuit_calibration_v1 USING btree (attack_launch_event_key, pursuit_multiplier);
CREATE UNIQUE INDEX race_engine_phase3s_dynamic_escape_cache_v1_key_idx ON public.race_engine_phase3s_dynamic_escape_cache_v1 USING btree (attack_launch_event_key, step_order);
CREATE INDEX race_engine_phase3s_dynamic_escape_cache_v1_rider_step_idx ON public.race_engine_phase3s_dynamic_escape_cache_v1 USING btree (rider_id, step_order);
CREATE UNIQUE INDEX race_engine_phase3s_dynamic_escape_hysteresis_cache_v1_key_idx ON public.race_engine_phase3s_dynamic_escape_hysteresis_cache_v1 USING btree (attack_launch_event_key, step_order);
CREATE INDEX race_engine_phase3s_dynamic_escape_hysteresis_cache_v1_rider_st ON public.race_engine_phase3s_dynamic_escape_hysteresis_cache_v1 USING btree (rider_id, step_order);
CREATE UNIQUE INDEX race_engine_phase3t_bridge_join_cache_v1_event_idx ON public.race_engine_phase3t_bridge_join_cache_v1 USING btree (attack_launch_event_key);
CREATE INDEX race_engine_phase3t_bridge_join_cache_v1_target_idx ON public.race_engine_phase3t_bridge_join_cache_v1 USING btree (selected_target_escape_event_key, join_step_order);
CREATE UNIQUE INDEX race_engine_phase3t_escape_overlap_cache_v1_event_idx ON public.race_engine_phase3t_escape_overlap_cache_v1 USING btree (attack_launch_event_key);
CREATE UNIQUE INDEX race_engine_phase3u_three_rider_breakaway_cache_v1_step_idx ON public.race_engine_phase3u_three_rider_breakaway_cache_v1 USING btree (group_event_key, step_order);
CREATE UNIQUE INDEX race_engine_phase3u_two_rider_chase_cache_v1_step_idx ON public.race_engine_phase3u_two_rider_chase_cache_v1 USING btree (group_event_key, step_order);
CREATE UNIQUE INDEX race_engine_phase3v_escape_rider_state_cache_v1_rider_step_idx ON public.race_engine_phase3v_escape_rider_state_cache_v1 USING btree (rider_id, step_order);
CREATE INDEX race_engine_phase3v_escape_rider_state_cache_v1_step_group_idx ON public.race_engine_phase3v_escape_rider_state_cache_v1 USING btree (step_order, canonical_group_code);
CREATE UNIQUE INDEX race_engine_phase3v_escape_topology_cache_v1_group_step_idx ON public.race_engine_phase3v_escape_topology_cache_v1 USING btree (physical_group_key, step_order);
CREATE INDEX race_engine_phase3v_escape_topology_cache_v1_step_rank_idx ON public.race_engine_phase3v_escape_topology_cache_v1 USING btree (step_order, group_rank);
CREATE UNIQUE INDEX race_engine_phase3w_escape_overlay_cache_v1_rider_step_idx ON public.race_engine_phase3w_escape_overlay_cache_v1 USING btree (rider_id, step_order);
CREATE INDEX race_engine_phase3w_escape_overlay_cache_v1_step_group_idx ON public.race_engine_phase3w_escape_overlay_cache_v1 USING btree (step_order, effective_live_group_rank, effective_physical_group_key);
CREATE INDEX race_engine_phase3x_effective_group_clock_cache_v1_continuity_i ON public.race_engine_phase3x_effective_group_clock_cache_v1 USING btree (race_id, stage_id, clock_continuity_key, step_order);
CREATE UNIQUE INDEX race_engine_phase3x_effective_group_clock_cache_v1_group_step_i ON public.race_engine_phase3x_effective_group_clock_cache_v1 USING btree (effective_physical_group_key, step_order);
CREATE INDEX race_engine_phase3x_effective_group_clock_cache_v1_step_rank_id ON public.race_engine_phase3x_effective_group_clock_cache_v1 USING btree (step_order, effective_live_group_rank);
CREATE INDEX race_engine_phase3y_canonical_live_state_cache_v1_continuity_id ON public.race_engine_phase3y_canonical_live_state_cache_v1 USING btree (race_id, stage_id, clock_continuity_key, step_order);
CREATE UNIQUE INDEX race_engine_phase3y_canonical_live_state_cache_v1_rider_step_id ON public.race_engine_phase3y_canonical_live_state_cache_v1 USING btree (rider_id, step_order);
CREATE INDEX race_engine_phase3y_canonical_live_state_cache_v1_step_group_id ON public.race_engine_phase3y_canonical_live_state_cache_v1 USING btree (step_order, effective_live_group_rank, effective_physical_group_key);
CREATE UNIQUE INDEX race_engine_phase3z_gate_approach_context_v1_rider_idx ON public.race_engine_phase3z_gate_approach_context_cache_v1 USING btree (point_id, rider_id);
CREATE UNIQUE INDEX race_engine_phase3z_gate_award_preview_v1_rank_idx ON public.race_engine_phase3z_gate_award_preview_cache_v1 USING btree (point_id, global_gate_rank);
CREATE INDEX race_engine_phase3z_gate_battle_preview_v1_global_rank_idx ON public.race_engine_phase3z_gate_battle_preview_cache_v1 USING btree (point_id, global_gate_rank);
CREATE INDEX race_engine_phase3z_gate_battle_preview_v1_group_rank_idx ON public.race_engine_phase3z_gate_battle_preview_cache_v1 USING btree (point_id, effective_physical_group_key, group_local_battle_rank);
CREATE UNIQUE INDEX race_engine_phase3z_gate_battle_preview_v1_rider_idx ON public.race_engine_phase3z_gate_battle_preview_cache_v1 USING btree (point_id, rider_id);
CREATE UNIQUE INDEX race_engine_phase3z_gate_definition_cache_v1_point_idx ON public.race_engine_phase3z_gate_definition_cache_v1 USING btree (point_id);
CREATE UNIQUE INDEX race_engine_phase3z_gate_definition_cache_v1_sort_idx ON public.race_engine_phase3z_gate_definition_cache_v1 USING btree (stage_id, sort_order);
CREATE INDEX race_engine_phase3z_gate_function_audit_v1_name_idx ON public.race_engine_phase3z_gate_function_audit_v1 USING btree (function_name);
CREATE UNIQUE INDEX race_engine_phase3z_gate_group_context_v1_group_idx ON public.race_engine_phase3z_gate_group_context_cache_v1 USING btree (point_id, effective_physical_group_key);
CREATE INDEX race_engine_phase3z_gate_group_context_v1_rank_idx ON public.race_engine_phase3z_gate_group_context_cache_v1 USING btree (point_id, calculated_group_arrival_rank);
CREATE INDEX race_engine_phase3z_gate_relation_audit_v1_name_idx ON public.race_engine_phase3z_gate_relation_audit_v1 USING btree (table_name);
CREATE INDEX race_engine_phase3z_gate_rider_context_v1_group_idx ON public.race_engine_phase3z_gate_rider_context_cache_v1 USING btree (point_id, calculated_group_arrival_rank, effective_physical_group_key);
CREATE UNIQUE INDEX race_engine_phase3z_gate_rider_context_v1_rider_idx ON public.race_engine_phase3z_gate_rider_context_cache_v1 USING btree (point_id, rider_id);
CREATE UNIQUE INDEX race_engine_phase3z_gate_team_support_v1_rider_idx ON public.race_engine_phase3z_gate_team_support_cache_v1 USING btree (point_id, rider_id);
CREATE UNIQUE INDEX race_engine_phase3z_refined_gate_award_v1_rank_idx ON public.race_engine_phase3z_refined_gate_award_preview_cache_v1 USING btree (point_id, refined_global_gate_rank);
CREATE INDEX race_engine_phase3z_refined_gate_battle_v1_rank_idx ON public.race_engine_phase3z_refined_gate_battle_preview_cache_v1 USING btree (point_id, refined_global_gate_rank);
CREATE UNIQUE INDEX race_engine_phase3z_refined_gate_battle_v1_rider_idx ON public.race_engine_phase3z_refined_gate_battle_preview_cache_v1 USING btree (point_id, rider_id);
CREATE UNIQUE INDEX race_engine_phase3z_team_captain_v1_team_idx ON public.race_engine_phase3z_team_captain_cache_v1 USING btree (race_id, stage_id, team_id);
CREATE INDEX race_engine_phase3z_team_gate_plan_v1_finisher_idx ON public.race_engine_phase3z_team_gate_plan_cache_v1 USING btree (point_id, designated_finisher_rider_id);
CREATE UNIQUE INDEX race_engine_phase3z_team_gate_plan_v1_team_group_idx ON public.race_engine_phase3z_team_gate_plan_cache_v1 USING btree (point_id, effective_physical_group_key, team_id);
CREATE INDEX race_engine_scenario_runs_date_template_idx ON public.race_engine_scenario_runs USING btree (game_date, template_id, selected_at);
CREATE INDEX race_engine_scenario_runs_race_date_idx ON public.race_engine_scenario_runs USING btree (race_id, game_date, selected_at);
CREATE INDEX race_engine_scenario_runs_race_template_idx ON public.race_engine_scenario_runs USING btree (race_id, template_id, selected_at);
CREATE INDEX race_engine_stage_command_outcomes_rider_idx ON public.race_engine_stage_command_outcomes USING btree (simulation_run_id, rider_id, source_event_order);
CREATE INDEX race_engine_stage_command_outcomes_stage_idx ON public.race_engine_stage_command_outcomes USING btree (stage_id, source_event_order);
CREATE UNIQUE INDEX race_engine_stage_command_outcomes_uq ON public.race_engine_stage_command_outcomes USING btree (simulation_run_id, source_interaction_event_id);
CREATE INDEX race_engine_stage_interaction_events_sim_idx ON public.race_engine_stage_interaction_events USING btree (simulation_run_id, event_order);
CREATE INDEX race_engine_stage_interaction_events_stage_idx ON public.race_engine_stage_interaction_events USING btree (stage_id, event_order);
CREATE UNIQUE INDEX race_engine_stage_interaction_events_uq ON public.race_engine_stage_interaction_events USING btree (simulation_run_id, COALESCE(club_id, '00000000-0000-0000-0000-000000000000'::uuid), event_order, interaction_type, COALESCE(rider_id, '00000000-0000-0000-0000-000000000000'::uuid));
CREATE UNIQUE INDEX race_engine_stage_supply_applications_run_resource_uidx ON public.race_engine_stage_supply_applications USING btree (simulation_run_id, resource_id);
CREATE INDEX race_engine_stage_supply_applications_stage_idx ON public.race_engine_stage_supply_applications USING btree (stage_id, club_id, supply_key);
CREATE UNIQUE INDEX race_engine_stage_wear_applications_once_uidx ON public.race_engine_stage_wear_applications USING btree (simulation_run_id, target_type, target_table, target_id);
CREATE INDEX race_engine_stage_wear_applications_stage_idx ON public.race_engine_stage_wear_applications USING btree (stage_id, target_type);
CREATE INDEX race_entry_rules_class_idx ON public.race_entry_rules USING btree (race_class_code);
CREATE INDEX race_entry_rules_status_close_idx ON public.race_entry_rules USING btree (applications_status, applications_close_game_date);
CREATE INDEX race_operations_incident_email_idx_v1 ON public.race_operations_incidents_v1 USING btree (email_sent_at, detected_at) WHERE (resolved_at IS NULL);
CREATE INDEX race_operations_incident_open_idx_v1 ON public.race_operations_incidents_v1 USING btree (resolved_at, detected_at DESC);
CREATE UNIQUE INDEX race_operations_one_open_issue_per_stage_key_v1 ON public.race_operations_incidents_v1 USING btree (stage_id, issue_key) WHERE (resolved_at IS NULL);
CREATE INDEX race_operations_status_problem_idx_v1 ON public.race_operations_stage_status_v1 USING btree (has_problem, stage_start_game_at DESC);
CREATE INDEX race_operations_status_start_idx_v1 ON public.race_operations_stage_status_v1 USING btree (stage_start_game_at DESC);
CREATE INDEX race_participant_riders_race_id_idx ON public.race_participant_riders USING btree (race_id);
CREATE INDEX race_participant_riders_race_team_start_idx ON public.race_participant_riders USING btree (race_id, team_id, start_number);
CREATE INDEX race_participant_riders_rider_id_idx ON public.race_participant_riders USING btree (rider_id);
CREATE INDEX race_participant_riders_team_id_idx ON public.race_participant_riders USING btree (team_id);
CREATE INDEX race_participant_teams_race_id_idx ON public.race_participant_teams USING btree (race_id);
CREATE INDEX race_preparation_stage_plan_automation_enabled_idx ON public.race_preparation_stage_plan_automation USING btree (is_enabled, participating_club_id);
CREATE INDEX race_preparations_participating_club_idx ON public.race_preparations USING btree (participating_club_id);
CREATE INDEX race_prize_awards_race_idx ON public.race_prize_awards USING btree (race_id, bucket_key, rank);
CREATE INDEX race_prize_awards_team_idx ON public.race_prize_awards USING btree (team_id);
CREATE INDEX race_ranking_point_awards_race_idx ON public.race_ranking_point_awards USING btree (race_id, source_type, rank);
CREATE INDEX race_ranking_point_awards_rider_idx ON public.race_ranking_point_awards USING btree (rider_id);
CREATE INDEX race_ranking_point_awards_team_idx ON public.race_ranking_point_awards USING btree (team_id);
CREATE INDEX race_stage_authoritative_runs_engine_idx ON public.race_stage_authoritative_runs USING btree (engine_version, simulation_mode);
CREATE INDEX race_stage_authoritative_runs_race_idx ON public.race_stage_authoritative_runs USING btree (race_id, stage_id);
CREATE INDEX race_stage_automation_state_race_idx ON public.race_stage_automation_state USING btree (race_id, scheduled_game_at);
CREATE INDEX race_stage_automation_state_status_idx ON public.race_stage_automation_state USING btree (last_status, last_checked_at);
CREATE INDEX race_stage_plan_generation_log_prep_created_idx ON public.race_stage_plan_generation_log USING btree (race_preparation_id, created_at DESC);
CREATE INDEX race_stage_plan_generation_log_stage_created_idx ON public.race_stage_plan_generation_log USING btree (stage_id, created_at DESC);
CREATE INDEX race_stage_plan_management_mode_idx ON public.race_stage_plan_management USING btree (management_mode, source_type);
CREATE INDEX race_stage_plan_management_prep_stage_idx ON public.race_stage_plan_management USING btree (race_preparation_id, stage_id);
CREATE UNIQUE INDEX race_stage_plans_unique_stage_id ON public.race_stage_plans USING btree (race_preparation_id, stage_id) WHERE (stage_id IS NOT NULL);
CREATE UNIQUE INDEX race_stage_points_one_finish_per_stage_idx ON public.race_stage_points USING btree (stage_id) WHERE (point_type = 'FINISH'::text);
CREATE UNIQUE INDEX race_stage_points_one_start_per_stage_idx ON public.race_stage_points USING btree (stage_id) WHERE (point_type = 'START'::text);
CREATE INDEX race_stage_points_point_type_idx ON public.race_stage_points USING btree (point_type);
CREATE INDEX race_stage_points_stage_id_idx ON public.race_stage_points USING btree (stage_id);
CREATE INDEX race_stage_points_stage_sort_idx ON public.race_stage_points USING btree (stage_id, sort_order, km_from_start);
CREATE INDEX race_stage_profile_details_race_idx ON public.race_stage_profile_details USING btree (race_id);
CREATE INDEX race_stage_replay_frames_entity_lookup_idx ON public.race_stage_replay_frames USING btree (simulation_run_id, entity_type, entity_id, frame_number) WHERE (entity_id IS NOT NULL);
CREATE UNIQUE INDEX race_stage_replay_frames_run_frame_entity_key_uidx ON public.race_stage_replay_frames USING btree (simulation_run_id, frame_number, entity_key);
CREATE INDEX race_stage_replay_frames_run_idx ON public.race_stage_replay_frames USING btree (simulation_run_id);
CREATE INDEX race_stage_replay_frames_run_mode_frame_idx ON public.race_stage_replay_frames USING btree (simulation_run_id, replay_mode, frame_number);
CREATE INDEX race_stage_replay_frames_stage_frame_idx ON public.race_stage_replay_frames USING btree (stage_id, frame_number);
CREATE INDEX race_stage_replay_frames_stage_idx ON public.race_stage_replay_frames USING btree (stage_id, frame_number);
CREATE INDEX race_stage_report_events_stage_idx ON public.race_stage_report_events USING btree (stage_id, event_order);
CREATE UNIQUE INDEX race_stage_results_pre_run_stage_rider_uidx ON public.race_stage_results USING btree (stage_id, rider_id) WHERE (simulation_run_id IS NULL);
CREATE INDEX race_stage_results_rider_stage_idx ON public.race_stage_results USING btree (rider_id, stage_id);
CREATE UNIQUE INDEX race_stage_results_run_rider_uidx ON public.race_stage_results USING btree (simulation_run_id, rider_id) WHERE (simulation_run_id IS NOT NULL);
CREATE INDEX race_stage_results_simulation_run_idx ON public.race_stage_results USING btree (simulation_run_id) WHERE (simulation_run_id IS NOT NULL);
CREATE UNIQUE INDEX race_stage_route_profile_jobs_active_stage_unique ON public.race_stage_route_profile_jobs USING btree (stage_id) WHERE (status = ANY (ARRAY['queued'::text, 'running'::text]));
CREATE INDEX race_stage_route_profile_jobs_stage_id_idx ON public.race_stage_route_profile_jobs USING btree (stage_id);
CREATE INDEX race_stage_route_profile_jobs_status_idx ON public.race_stage_route_profile_jobs USING btree (status, priority, created_at);
CREATE INDEX race_stage_route_profiles_stage_id_idx ON public.race_stage_route_profiles USING btree (stage_id);
CREATE INDEX race_stage_route_profiles_status_idx ON public.race_stage_route_profiles USING btree (status);
CREATE INDEX race_stage_safe_calculation_status_idx ON public.race_stage_safe_calculation_v1 USING btree (status, lease_expires_at, updated_at);
CREATE INDEX race_stage_simulation_events_run_time_idx ON public.race_stage_simulation_events USING btree (simulation_run_id, race_seconds, sequence_number);
CREATE INDEX race_stage_simulation_events_stage_idx ON public.race_stage_simulation_events USING btree (stage_id, sequence_number);
CREATE INDEX race_stage_simulation_runs_stage_engine_status_failed_idx ON public.race_stage_simulation_runs USING btree (stage_id, engine_version, simulation_mode, status, failed_at DESC);
CREATE INDEX race_stage_simulation_runs_stage_id_multi_idx ON public.race_stage_simulation_runs USING btree (stage_id, created_at, id);
CREATE UNIQUE INDEX race_stage_supply_usage_events_club_idempotency_uidx ON public.race_stage_supply_usage_events USING btree (club_id, idempotency_key) WHERE (idempotency_key IS NOT NULL);
CREATE INDEX race_stages_host_country_code_idx ON public.race_stages USING btree (host_country_code);
CREATE INDEX race_stages_planned_start_time_idx ON public.race_stages USING btree (race_id, stage_date, planned_start_hour_number, planned_start_minute);
CREATE INDEX race_stages_race_id_idx ON public.race_stages USING btree (race_id);
CREATE INDEX race_stages_stage_date_idx ON public.race_stages USING btree (stage_date);
CREATE INDEX race_stages_terrain_type_idx ON public.race_stages USING btree (terrain_type);
CREATE INDEX race_team_applications_race_status_idx ON public.race_team_applications USING btree (race_id, application_status);
CREATE INDEX race_team_applications_team_idx ON public.race_team_applications USING btree (team_id);
CREATE INDEX race_team_entries_club_status_idx ON public.race_team_entries USING btree (club_id, status);
CREATE INDEX race_team_entries_participating_club_idx ON public.race_team_entries USING btree (participating_club_id);
CREATE UNIQUE INDEX race_team_entries_race_club_uidx ON public.race_team_entries USING btree (race_id, club_id);
CREATE INDEX race_team_entries_race_status_idx ON public.race_team_entries USING btree (race_id, status);
CREATE INDEX races_category_idx ON public.races USING btree (category);
CREATE INDEX races_country_code_idx ON public.races USING btree (country_code);
CREATE INDEX races_end_date_idx ON public.races USING btree (end_date);
CREATE INDEX races_planned_start_time_idx ON public.races USING btree (start_date, planned_start_hour_number, planned_start_minute, status);
CREATE INDEX races_race_type_idx ON public.races USING btree (race_type);
CREATE INDEX races_start_date_idx ON public.races USING btree (start_date);
CREATE INDEX races_status_idx ON public.races USING btree (status);
CREATE INDEX referral_activity_days_user_date_idx ON public.referral_activity_days USING btree (referred_user_id, activity_date DESC);
CREATE INDEX rider_championship_honours_rider_season_idx ON public.rider_championship_honours USING btree (rider_id, season_number DESC);
CREATE UNIQUE INDEX rider_championship_honours_unique_v1 ON public.rider_championship_honours USING btree (rider_id, season_number, honor_type, COALESCE(country_code, ''::text), rank);
CREATE INDEX rider_contract_transition_audit_v1_rider_idx ON public.rider_contract_transition_audit_v1 USING btree (rider_id, created_at DESC);
CREATE INDEX rider_contract_transition_audit_v1_run_idx ON public.rider_contract_transition_audit_v1 USING btree (transition_run_id, action);
CREATE INDEX rider_daily_activity_date_rider_idx ON public.rider_daily_activity USING btree (activity_date, rider_id) INCLUDE (participated);
CREATE INDEX rider_daily_activity_rider_date_idx ON public.rider_daily_activity USING btree (rider_id, activity_date);
CREATE INDEX rider_free_agent_events_club_idx ON public.rider_free_agent_events USING btree (club_id, created_at DESC);
CREATE INDEX rider_free_agent_events_free_agent_idx ON public.rider_free_agent_events USING btree (free_agent_id, created_at DESC);
CREATE INDEX rider_free_agent_events_negotiation_idx ON public.rider_free_agent_events USING btree (negotiation_id, created_at DESC);
CREATE INDEX rider_free_agent_events_rider_idx ON public.rider_free_agent_events USING btree (rider_id, created_at DESC);
CREATE INDEX rider_free_agent_events_source_club_idx ON public.rider_free_agent_events USING btree (source_club_id, created_at DESC);
CREATE UNIQUE INDEX rider_free_agent_negotiations_open_uidx ON public.rider_free_agent_negotiations USING btree (free_agent_id, club_id) WHERE (status = 'open'::text);
CREATE INDEX rider_free_agent_negotiations_status_expiry_idx ON public.rider_free_agent_negotiations USING btree (status, expires_on_game_date);
CREATE INDEX rider_free_agents_status_idx ON public.rider_free_agents USING btree (status, expires_on_game_date);
CREATE UNIQUE INDEX rider_health_cases_one_open_case_per_rider_uidx ON public.rider_health_cases USING btree (rider_id) WHERE (status = ANY (ARRAY['active'::text, 'recovering'::text]));
CREATE INDEX rider_health_cases_rider_status_idx ON public.rider_health_cases USING btree (rider_id, status);
CREATE INDEX rider_health_cases_status_active_until_idx ON public.rider_health_cases USING btree (status, active_until);
CREATE INDEX rider_health_cases_status_recovery_until_idx ON public.rider_health_cases USING btree (status, recovery_until);
CREATE INDEX rider_health_condition_effect_runs_v1_case_idx ON public.rider_health_condition_effect_runs_v1 USING btree (health_case_id);
CREATE INDEX rider_health_condition_effect_runs_v1_rider_date_idx ON public.rider_health_condition_effect_runs_v1 USING btree (rider_id, effect_date DESC);
CREATE INDEX rider_race_development_events_progress_bank_idx ON public.rider_race_development_events USING btree (applied_to_progress_bank, stage_date, rider_id);
CREATE INDEX rider_race_development_events_rider_idx ON public.rider_race_development_events USING btree (rider_id, stage_date DESC);
CREATE INDEX rider_race_development_events_run_idx ON public.rider_race_development_events USING btree (simulation_run_id);
CREATE INDEX rider_race_development_events_stage_idx ON public.rider_race_development_events USING btree (stage_id);
CREATE INDEX rider_race_development_events_unapplied_idx ON public.rider_race_development_events USING btree (simulation_run_id, applied_to_condition);
CREATE INDEX rider_regular_training_daily_plans_club_date_idx ON public.rider_regular_training_daily_plans USING btree (club_id, plan_date);
CREATE INDEX rider_regular_training_daily_plans_rider_date_idx ON public.rider_regular_training_daily_plans USING btree (rider_id, plan_date);
CREATE INDEX rider_regular_training_daily_plans_source_status_idx ON public.rider_regular_training_daily_plans USING btree (source_type, status, plan_date);
CREATE INDEX rider_regular_training_management_mode_idx ON public.rider_regular_training_management USING btree (club_id, management_mode);
CREATE INDEX rider_scout_reports_club_created_at_game_ts_idx ON public.rider_scout_reports USING btree (club_id, created_at_game_ts);
CREATE INDEX rider_scout_reports_club_game_date_idx ON public.rider_scout_reports USING btree (club_id, scouted_on_game_date);
CREATE INDEX rider_scout_reports_club_rider_idx ON public.rider_scout_reports USING btree (club_id, rider_id, created_at DESC);
CREATE INDEX rider_scout_reports_rider_idx ON public.rider_scout_reports USING btree (rider_id);
CREATE UNIQUE INDEX rider_scout_reports_task_uidx ON public.rider_scout_reports USING btree (task_id) WHERE (task_id IS NOT NULL);
CREATE INDEX rider_scout_tasks_club_rider_idx ON public.rider_scout_tasks USING btree (club_id, rider_id, created_at DESC);
CREATE INDEX rider_scout_tasks_due_idx ON public.rider_scout_tasks USING btree (status, completes_at_game_ts);
CREATE UNIQUE INDEX rider_scout_tasks_one_active_per_scout_uidx ON public.rider_scout_tasks USING btree (scout_staff_id) WHERE ((scout_staff_id IS NOT NULL) AND (status <> ALL (ARRAY['completed'::text, 'cancelled'::text, 'failed'::text, 'expired'::text])));
CREATE UNIQUE INDEX rider_scout_tasks_one_open_per_club_rider_uidx ON public.rider_scout_tasks USING btree (club_id, rider_id) WHERE (status = ANY (ARRAY['queued'::text, 'in_progress'::text]));
CREATE INDEX rider_skill_weekly_snapshots_rider_week_idx ON public.rider_skill_weekly_snapshots USING btree (rider_id, week_start_date DESC);
CREATE INDEX rider_training_accident_decisions_v1_activity_date_idx ON public.rider_training_accident_decisions_v1 USING btree (activity_date);
CREATE INDEX rider_training_accident_decisions_v1_health_case_idx ON public.rider_training_accident_decisions_v1 USING btree (health_case_id) WHERE (health_case_id IS NOT NULL);
CREATE INDEX rider_transfer_events_buyer_idx ON public.rider_transfer_events USING btree (buyer_club_id, created_at DESC);
CREATE INDEX rider_transfer_events_listing_idx ON public.rider_transfer_events USING btree (listing_id, created_at DESC);
CREATE INDEX rider_transfer_events_negotiation_idx ON public.rider_transfer_events USING btree (negotiation_id, created_at DESC);
CREATE INDEX rider_transfer_events_offer_idx ON public.rider_transfer_events USING btree (offer_id, created_at DESC);
CREATE INDEX rider_transfer_events_rider_idx ON public.rider_transfer_events USING btree (rider_id, created_at DESC);
CREATE INDEX rider_transfer_events_seller_idx ON public.rider_transfer_events USING btree (seller_club_id, created_at DESC);
CREATE UNIQUE INDEX rider_transfer_listings_one_active_per_rider_idx ON public.rider_transfer_listings USING btree (rider_id) WHERE (status = ANY (ARRAY['listed'::text, 'club_accepted'::text]));
CREATE INDEX rider_transfer_listings_status_expiry_idx ON public.rider_transfer_listings USING btree (status, expires_on_game_date);
CREATE INDEX rider_transfer_listings_status_idx ON public.rider_transfer_listings USING btree (status, listed_on_game_date);
CREATE INDEX rider_transfer_negotiations_buyer_status_idx ON public.rider_transfer_negotiations USING btree (buyer_club_id, status, expires_on_game_date);
CREATE INDEX rider_transfer_negotiations_listing_status_idx ON public.rider_transfer_negotiations USING btree (listing_id, status, expires_on_game_date);
CREATE INDEX rider_transfer_negotiations_rider_idx ON public.rider_transfer_negotiations USING btree (rider_id, created_at DESC);
CREATE INDEX rider_transfer_negotiations_seller_status_idx ON public.rider_transfer_negotiations USING btree (seller_club_id, status, expires_on_game_date);
CREATE INDEX rider_transfer_offers_buyer_status_idx ON public.rider_transfer_offers USING btree (buyer_club_id, status, created_at DESC);
CREATE INDEX rider_transfer_offers_listing_idx ON public.rider_transfer_offers USING btree (listing_id, status);
CREATE INDEX rider_transfer_offers_listing_status_expiry_idx ON public.rider_transfer_offers USING btree (listing_id, status, expires_on_game_date);
CREATE UNIQUE INDEX rider_transfer_offers_one_open_offer_per_buyer_idx ON public.rider_transfer_offers USING btree (listing_id, buyer_club_id) WHERE (status = 'open'::text);
CREATE INDEX rider_transfer_offers_pair_idx ON public.rider_transfer_offers USING btree (seller_club_id, buyer_club_id, offered_on_game_date);
CREATE INDEX rider_transfer_offers_seller_status_idx ON public.rider_transfer_offers USING btree (seller_club_id, status, created_at DESC);
CREATE INDEX rider_transfer_offers_status_expiry_idx ON public.rider_transfer_offers USING btree (status, expires_on_game_date);
CREATE INDEX riders_availability_status_idx ON public.riders USING btree (availability_status);
CREATE INDEX riders_market_value_refresh_month_idx ON public.riders USING btree (market_value_refreshed_game_month, id);
CREATE INDEX riders_unavailable_until_idx ON public.riders USING btree (unavailable_until);
CREATE INDEX season_transition_engine_events_v2_run_idx ON public.season_transition_engine_events_v2 USING btree (run_id, id);
CREATE INDEX season_transition_engine_runs_v2_pair_idx ON public.season_transition_engine_runs_v2 USING btree (source_season, target_season, mode, created_at DESC);
CREATE UNIQUE INDEX season_transition_runs_v1_one_completed_pair_per_timeline ON public.season_transition_runs_v1 USING btree (timeline_id, source_season, target_season) WHERE (status = 'completed'::text);
CREATE INDEX season_transition_runs_v1_pair_status_idx ON public.season_transition_runs_v1 USING btree (timeline_id, source_season, target_season, status, started_at DESC);
CREATE INDEX site_analytics_pages_date_idx ON public.site_analytics_daily_pages USING btree (analytics_date);
CREATE INDEX site_analytics_pages_path_date_idx ON public.site_analytics_daily_pages USING btree (path, analytics_date);
CREATE INDEX site_analytics_sessions_country_date_idx ON public.site_analytics_daily_sessions USING btree (country_code, analytics_date);
CREATE INDEX site_analytics_sessions_date_idx ON public.site_analytics_daily_sessions USING btree (analytics_date);
CREATE INDEX site_analytics_sessions_referrer_date_idx ON public.site_analytics_daily_sessions USING btree (referrer_host, analytics_date);
CREATE INDEX site_analytics_sessions_user_date_idx ON public.site_analytics_daily_sessions USING btree (user_id, analytics_date) WHERE (user_id IS NOT NULL);
CREATE INDEX site_analytics_visitors_country_date_idx ON public.site_analytics_daily_visitors USING btree (country_code, analytics_date);
CREATE INDEX site_analytics_visitors_date_idx ON public.site_analytics_daily_visitors USING btree (analytics_date);
CREATE INDEX site_analytics_visitors_device_date_idx ON public.site_analytics_daily_visitors USING btree (device_type, analytics_date);
CREATE INDEX site_analytics_visitors_user_date_idx ON public.site_analytics_daily_visitors USING btree (user_id, analytics_date) WHERE (user_id IS NOT NULL);
CREATE INDEX sponsor_companies_home_group_idx ON public.sponsor_companies USING btree (home_group_code);
CREATE INDEX sponsor_companies_home_region_idx ON public.sponsor_companies USING btree (home_macro_region);
CREATE INDEX sponsor_company_eligibility_company_idx ON public.sponsor_company_eligibility USING btree (company_id, is_active);
CREATE INDEX sponsor_company_eligibility_match_idx ON public.sponsor_company_eligibility USING btree (scope_type, country_code, group_code, macro_region, is_active);
CREATE UNIQUE INDEX sponsor_company_eligibility_unique_rule ON public.sponsor_company_eligibility USING btree (company_id, scope_type, COALESCE(country_code, ''::text), COALESCE(group_code, ''::text), COALESCE(macro_region, ''::text), min_club_tier, max_club_tier, allow_worldteam_global);
CREATE UNIQUE INDEX sponsor_transition_audit_summary_uidx ON public.sponsor_transition_audit_v1 USING btree (transition_run_id, action) WHERE ((club_id IS NULL) AND (club_sponsor_id IS NULL));
CREATE INDEX staff_advisory_event_state_access_idx ON public.staff_advisory_event_state USING btree (access_id);
CREATE INDEX staff_advisory_medical_case_state_access_current_idx ON public.staff_advisory_medical_case_state USING btree (access_id, is_current);
CREATE UNIQUE INDEX staff_candidates_unique_profile_uidx ON public.staff_candidates USING btree (role_type, staff_name, specialization, salary_weekly);
CREATE INDEX staff_courses_staff_status_idx ON public.staff_courses USING btree (staff_id, status);
CREATE INDEX staff_scout_daily_usage_staff_date_idx ON public.staff_scout_daily_usage USING btree (staff_id, game_date);
CREATE UNIQUE INDEX system_incidents_active_dedupe_uidx ON public.system_incidents USING btree (dedupe_key) WHERE (status = ANY (ARRAY['open'::text, 'acknowledged'::text]));
CREATE INDEX system_monitor_runs_process_started_idx ON public.system_monitor_runs USING btree (process_key, started_at DESC);
CREATE UNIQUE INDEX system_monitor_runs_source_uidx ON public.system_monitor_runs USING btree (process_key, source_run_id) WHERE (source_run_id IS NOT NULL);
CREATE INDEX training_camp_bookings_club_idx ON public.training_camp_bookings USING btree (club_id);
CREATE INDEX training_camp_bookings_club_status_start_idx ON public.training_camp_bookings USING btree (club_id, status, start_date);
CREATE INDEX training_camp_bookings_dates_idx ON public.training_camp_bookings USING btree (start_date, end_date);
CREATE UNIQUE INDEX training_camp_bookings_finance_tx_uidx ON public.training_camp_bookings USING btree (finance_transaction_id) WHERE (finance_transaction_id IS NOT NULL);
CREATE INDEX training_camp_bookings_status_dates_idx ON public.training_camp_bookings USING btree (status, start_date, end_date);
CREATE INDEX training_camp_bookings_status_idx ON public.training_camp_bookings USING btree (status);
CREATE INDEX training_camp_catalog_active_idx ON public.training_camp_catalog USING btree (is_active);
CREATE INDEX training_camp_catalog_country_idx ON public.training_camp_catalog USING btree (country_code);
CREATE INDEX training_camp_catalog_type_idx ON public.training_camp_catalog USING btree (camp_type);
CREATE UNIQUE INDEX training_camp_catalog_unique_offer_idx ON public.training_camp_catalog USING btree (name, city_name, country_code, camp_type);
CREATE UNIQUE INDEX training_camp_daily_reports_booking_date_uidx ON public.training_camp_daily_reports USING btree (booking_id, report_date);
CREATE INDEX training_camp_daily_reports_booking_idx ON public.training_camp_daily_reports USING btree (booking_id);
CREATE UNIQUE INDEX training_camp_daily_reports_unique_idx ON public.training_camp_daily_reports USING btree (booking_id, report_date);
CREATE UNIQUE INDEX training_camp_notification_log_started_once_uidx ON public.training_camp_notification_log USING btree (booking_id) WHERE (notification_type = 'started'::text);
CREATE INDEX training_camp_participants_booking_rider_idx ON public.training_camp_participants USING btree (booking_id, rider_id);
CREATE INDEX training_camp_participants_rider_idx ON public.training_camp_participants USING btree (rider_id);
CREATE INDEX training_camp_staff_assignments_booking_idx ON public.training_camp_staff_assignments USING btree (booking_id);
CREATE INDEX training_camp_staff_assignments_club_idx ON public.training_camp_staff_assignments USING btree (club_id);
CREATE INDEX training_camp_staff_assignments_staff_idx ON public.training_camp_staff_assignments USING btree (staff_id);
CREATE INDEX universal_race_integration_test_runs_stage_status_idx ON public.universal_race_integration_test_runs USING btree (stage_id, status, calculated_at DESC);
CREATE UNIQUE INDEX uq_club_equipment_maintenance_one_pending_per_item ON public.club_equipment_maintenance_jobs USING btree (inventory_item_id) WHERE (status = 'pending'::text);
CREATE UNIQUE INDEX uq_club_infrastructure_facility_jobs_pending_target ON public.club_infrastructure_jobs USING btree (club_id, target_key) WHERE ((status = 'pending'::text) AND (job_type = 'facility_upgrade'::text));
CREATE UNIQUE INDEX uq_club_medical_vans_active_slot ON public.club_medical_vans USING btree (club_id, garage_slot) WHERE (status <> 'sold'::text);
CREATE UNIQUE INDEX uq_game_email_queue_once_per_club_type ON public.game_email_queue USING btree (club_id, email_type) WHERE (status <> 'cancelled'::text);
CREATE UNIQUE INDEX uq_race_engine_stage_effect_ledger_v2_idempotency_key ON public.race_engine_stage_effect_ledger_v2 USING btree (idempotency_key) WHERE (idempotency_key IS NOT NULL);
CREATE UNIQUE INDEX uq_rider_contract_negotiations_one_open_per_rider_club ON public.rider_contract_negotiations USING btree (rider_id, club_id) WHERE (status = 'open'::rider_negotiation_status);
CREATE UNIQUE INDEX uq_rider_contracts_one_active_per_rider ON public.rider_contracts USING btree (rider_id) WHERE (status = 'active'::rider_contract_status);
CREATE UNIQUE INDEX uq_staff_courses_one_active_per_staff ON public.staff_courses USING btree (staff_id) WHERE (status = 'active'::text);
CREATE UNIQUE INDEX uq_transfer_value_audit_stage_offer ON public.transfer_value_audit USING btree (stage, offer_id) WHERE (offer_id IS NOT NULL);
CREATE UNIQUE INDEX uq_unsolicited_active_bid_per_buyer_rider ON public.rider_unsolicited_transfer_bids USING btree (rider_id, buyer_club_id) WHERE (status = ANY (ARRAY['submitted'::text, 'countered'::text, 'accepted_pending_confirmation'::text]));
CREATE UNIQUE INDEX user_coin_ledger_scout_system_key_uidx ON public.user_coin_ledger USING btree (user_id, ((payload_json ->> 'system_key'::text))) WHERE ((reason = 'scout_report_extra'::text) AND (payload_json ? 'system_key'::text));
CREATE INDEX user_coin_ledger_user_id_created_at_idx ON public.user_coin_ledger USING btree (user_id, created_at DESC);
CREATE UNIQUE INDEX user_coin_ledger_user_system_key_uidx ON public.user_coin_ledger USING btree (user_id, ((payload_json ->> 'system_key'::text))) WHERE (payload_json ? 'system_key'::text);
CREATE UNIQUE INDEX user_coin_ledger_user_system_key_uq ON public.user_coin_ledger USING btree (user_id, ((payload_json ->> 'system_key'::text))) WHERE (payload_json ? 'system_key'::text);
CREATE UNIQUE INDEX user_notifications_source_event_user_uidx ON public.user_notifications USING btree (source_event_id, user_id) WHERE (source_event_id IS NOT NULL);
CREATE INDEX user_premium_subscriptions_access_idx ON public.user_premium_subscriptions USING btree (access_until);
CREATE UNIQUE INDEX user_premium_subscriptions_customer_uidx ON public.user_premium_subscriptions USING btree (stripe_customer_id) WHERE (stripe_customer_id IS NOT NULL);
CREATE INDEX user_premium_subscriptions_status_idx ON public.user_premium_subscriptions USING btree (stripe_status);
CREATE UNIQUE INDEX user_premium_subscriptions_subscription_uidx ON public.user_premium_subscriptions USING btree (stripe_subscription_id) WHERE (stripe_subscription_id IS NOT NULL);
CREATE UNIQUE INDEX ux_club_season_identities_one_active_per_club ON public.club_season_identities USING btree (club_id) WHERE (is_active = true);
CREATE UNIQUE INDEX ux_homepage_player_reviews_one_live_email ON public.homepage_player_reviews USING btree (lower(reviewer_email)) WHERE (status = ANY (ARRAY['pending'::text, 'approved'::text]));
CREATE UNIQUE INDEX ux_user_rewarded_ad_events_provider_event ON public.user_rewarded_ad_events USING btree (provider, provider_event_id) WHERE (provider_event_id IS NOT NULL);
CREATE INDEX world_road_championship_duties_rider_date_idx ON public.world_road_championship_duties USING btree (rider_id, duty_date) WHERE (status = 'confirmed'::text);
CREATE INDEX world_road_championship_entries_club_idx ON public.world_road_championship_entries USING btree (club_id_snapshot);
CREATE INDEX world_road_championship_entries_rider_idx ON public.world_road_championship_entries USING btree (rider_id);