create schema if not exists finance;
create schema if not exists control_center_private;
create schema if not exists private;

create sequence if not exists finance.entries_id_seq as bigint increment by 1 minvalue 1 maxvalue 9223372036854775807 start with 1 cache 1 no cycle;
create sequence if not exists finance.monthly_tax_audits_id_seq as bigint increment by 1 minvalue 1 maxvalue 9223372036854775807 start with 1 cache 1 no cycle;

create table if not exists control_center_private.admin_module_delivery_state (
  module_key text not null,
  last_event_at timestamp with time zone,
  last_sent_at timestamp with time zone,
  last_request_id bigint,
  updated_at timestamp with time zone default now() not null
);

create table if not exists control_center_private.telemetry_config (
  singleton boolean default true not null,
  endpoint text not null,
  source_project_ref text not null,
  bearer_token text not null,
  enabled boolean default true not null,
  last_request_id bigint,
  last_attempt_at timestamp with time zone,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);

create table if not exists finance.account_balances (
  account_id uuid not null,
  balance bigint default 0 not null,
  updated_at timestamp with time zone default now() not null
);

create table if not exists finance.accounts (
  id uuid default gen_random_uuid() not null,
  club_id uuid,
  user_id uuid,
  system_code text,
  currency text default 'CASH'::text not null,
  kind text default 'main'::text not null,
  created_at timestamp with time zone default now() not null
);

create table if not exists finance.club_insolvency_state (
  club_id uuid not null,
  emergency_rescue_count integer default 0 not null,
  status text default 'active'::text not null,
  last_rescue_game_date date,
  liquidated_at timestamp with time zone,
  liquidation_reason text,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);

create table if not exists finance.emergency_loan_repayment_runs (
  id uuid default gen_random_uuid() not null,
  loan_id uuid not null,
  club_id uuid not null,
  week_key text not null,
  due_game_date date not null,
  principal_due bigint default 0 not null,
  interest_due bigint default 0 not null,
  principal_transaction_id uuid,
  interest_transaction_id uuid,
  status text default 'charged'::text not null,
  metadata jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null
);

create table if not exists finance.emergency_loans (
  id uuid default gen_random_uuid() not null,
  club_id uuid not null,
  rescue_number integer not null,
  principal_amount bigint default 50000 not null,
  outstanding_principal bigint default 50000 not null,
  weekly_principal_due bigint default 10000 not null,
  weekly_interest_due bigint default 5000 not null,
  issued_game_date date not null,
  first_due_game_date date not null,
  final_due_game_date date not null,
  status text default 'active'::text not null,
  idempotency_key text not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  metadata jsonb default '{}'::jsonb not null
);

create table if not exists finance.entries (
  id bigint default nextval('finance.entries_id_seq'::regclass) not null,
  transaction_id uuid not null,
  account_id uuid not null,
  amount bigint not null,
  memo text,
  created_at timestamp with time zone default now() not null
);

create table if not exists finance.event_locks (
  event_type text not null,
  club_id uuid not null,
  ref_id uuid not null,
  transaction_id uuid not null,
  created_at timestamp with time zone default now() not null
);

create table if not exists finance.monthly_tax_audits (
  id bigint generated by default as identity not null,
  club_id uuid not null,
  period_start date not null,
  period_end date not null,
  tax_rate_bps integer not null,
  taxable_income_gross bigint default 0 not null,
  expected_tax bigint default 0 not null,
  already_withheld bigint default 0 not null,
  adjustment_amount bigint default 0 not null,
  audit_status text default 'ok'::text not null,
  details jsonb default '{}'::jsonb not null,
  notification_id bigint,
  created_at timestamp with time zone default now() not null
);

create table if not exists finance.system_state (
  key text not null,
  value_text text,
  updated_at timestamp with time zone default now() not null
);

create table if not exists finance.transaction_types (
  code text not null,
  name text not null,
  category text not null,
  description text default ''::text not null,
  is_user_visible boolean default true not null,
  affects_weekly boolean default true not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  is_taxable boolean default false not null,
  tax_rate_bps integer default 0 not null
);

create table if not exists finance.transaction_voids (
  source_transaction_id uuid not null,
  correction_transaction_id uuid,
  reason text not null,
  metadata jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null
);

create table if not exists finance.transactions (
  id uuid default gen_random_uuid() not null,
  type text not null,
  created_at timestamp with time zone default now() not null,
  created_by uuid default auth.uid(),
  idempotency_key text,
  metadata jsonb default '{}'::jsonb not null
);