create table if not exists public.race_engine_calculation_survival_audit_v1 (
  id bigint generated by default as identity primary key,
  stage_id uuid not null,
  race_id uuid not null,
  simulation_run_id uuid,
  action text not null,
  reason text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default clock_timestamp()
);

create index if not exists race_engine_calculation_survival_audit_stage_idx
  on public.race_engine_calculation_survival_audit_v1(stage_id, created_at desc);

create or replace function public.universal_race_stage_survival_mode_v1(p_stage_id uuid)
returns jsonb
language plpgsql
security definer
set search_path to 'public','pg_temp'
as $function$
declare
  v_stage record;
  v_current_game_at timestamp without time zone;
  v_stage_start_game_at timestamp without time zone;
  v_prior_failed_attempts integer := 0;
  v_authoritative_exists boolean := false;
  v_deadline_reached boolean := false;
begin
  select s.id as stage_id,
         s.race_id,
         s.stage_date,
         s.planned_start_hour_number,
         s.planned_start_minute
    into v_stage
  from public.race_stages s
  where s.id = p_stage_id;

  if not found then
    return jsonb_build_object('status','stage_not_found','stage_id',p_stage_id,'use_fallback',false);
  end if;

  select public.get_current_game_timestamp()::timestamp without time zone
    into v_current_game_at;

  v_stage_start_game_at := v_stage.stage_date::timestamp
    + make_interval(hours=>coalesce(v_stage.planned_start_hour_number,12),
                    mins=>coalesce(v_stage.planned_start_minute,0));

  select count(*)::integer
    into v_prior_failed_attempts
  from public.race_stage_simulation_runs sr
  where sr.stage_id = p_stage_id
    and sr.engine_version='race_engine_ts_v1'
    and sr.simulation_mode='deterministic_road_race_v1'
    and sr.status='failed';

  select exists(
    select 1 from public.race_stage_authoritative_runs a where a.stage_id=p_stage_id
  ) into v_authoritative_exists;

  v_deadline_reached := v_current_game_at >= v_stage_start_game_at - interval '15 minutes';

  return jsonb_build_object(
    'status','resolved',
    'stage_id',p_stage_id,
    'race_id',v_stage.race_id,
    'current_game_at',v_current_game_at,
    'stage_start_game_at',v_stage_start_game_at,
    'mandatory_ready_deadline_game_at',v_stage_start_game_at - interval '15 minutes',
    'deadline_reached',v_deadline_reached,
    'prior_failed_attempts',v_prior_failed_attempts,
    'authoritative_exists',v_authoritative_exists,
    'use_fallback',not v_authoritative_exists and (v_prior_failed_attempts > 0 or v_deadline_reached),
    'fallback_reason',case
      when v_authoritative_exists then 'authoritative_result_exists'
      when v_deadline_reached then 'mandatory_t_minus_15_deadline'
      when v_prior_failed_attempts > 0 then 'prior_failed_or_orphaned_attempt'
      else 'normal_engine_first_attempt'
    end,
    'model_version','race_calculation_survival_v1'
  );
end;
$function$;

create or replace function public.universal_race_stage_survival_recover_v1()
returns jsonb
language plpgsql
security definer
set search_path to 'public','pg_temp'
as $function$
declare
  v_current_game_at timestamp without time zone;
  v_run record;
  v_stage_start_game_at timestamp without time zone;
  v_deadline_reached boolean;
  v_stale_after interval;
  v_age interval;
  v_recovered integer := 0;
  v_checked integer := 0;
begin
  select public.get_current_game_timestamp()::timestamp without time zone
    into v_current_game_at;

  for v_run in
    select sr.id as simulation_run_id,
           sr.stage_id,
           sr.race_id,
           sr.started_at,
           sr.updated_at,
           sr.created_at,
           s.stage_date,
           s.planned_start_hour_number,
           s.planned_start_minute
    from public.race_stage_simulation_runs sr
    join public.race_stages s on s.id=sr.stage_id
    where sr.engine_version='race_engine_ts_v1'
      and sr.simulation_mode='deterministic_road_race_v1'
      and sr.status='running'
      and coalesce(sr.result_summary_json->>'calculation_contract','')='phase11b_claim_pending_v1'
      and not exists (
        select 1 from public.race_stage_authoritative_runs a where a.stage_id=sr.stage_id
      )
    order by coalesce(sr.updated_at,sr.started_at,sr.created_at)
    limit 200
  loop
    v_checked := v_checked + 1;
    v_stage_start_game_at := v_run.stage_date::timestamp
      + make_interval(hours=>coalesce(v_run.planned_start_hour_number,12),
                      mins=>coalesce(v_run.planned_start_minute,0));
    v_deadline_reached := v_current_game_at >= v_stage_start_game_at - interval '15 minutes';
    v_stale_after := case when v_deadline_reached then interval '45 seconds' else interval '2 minutes' end;
    v_age := clock_timestamp() - coalesce(v_run.updated_at,v_run.started_at,v_run.created_at);

    if v_age >= v_stale_after then
      perform public.universal_race_stage_fail_calculation_v1(
        v_run.stage_id,
        v_run.simulation_run_id,
        'Race calculation survival watchdog recovered an orphaned running claim.',
        jsonb_build_object(
          'recovery_model','race_calculation_survival_v1',
          'reason','stale_claim_pending_without_authoritative_result',
          'stale_age_seconds',extract(epoch from v_age),
          'stale_threshold_seconds',extract(epoch from v_stale_after),
          'deadline_reached',v_deadline_reached,
          'current_game_at',v_current_game_at,
          'stage_start_game_at',v_stage_start_game_at,
          'mandatory_ready_deadline_game_at',v_stage_start_game_at - interval '15 minutes'
        )
      );

      insert into public.race_engine_calculation_survival_audit_v1(
        stage_id,race_id,simulation_run_id,action,reason,details
      ) values (
        v_run.stage_id,
        v_run.race_id,
        v_run.simulation_run_id,
        'recover_stale_claim',
        'stale_claim_pending_without_authoritative_result',
        jsonb_build_object(
          'stale_age_seconds',extract(epoch from v_age),
          'stale_threshold_seconds',extract(epoch from v_stale_after),
          'deadline_reached',v_deadline_reached,
          'current_game_at',v_current_game_at,
          'stage_start_game_at',v_stage_start_game_at
        )
      );
      v_recovered := v_recovered + 1;
    end if;
  end loop;

  return jsonb_build_object(
    'status','completed',
    'current_game_at',v_current_game_at,
    'checked_running_claims',v_checked,
    'recovered_stale_claims',v_recovered,
    'normal_stale_after_seconds',120,
    'deadline_stale_after_seconds',45,
    'mandatory_ready_lead_minutes',15,
    'model_version','race_calculation_survival_v1'
  );
end;
$function$;

create or replace function public.universal_race_stage_claim_next_due_v1(p_worker_id text default 'netlify_phase11b_v1'::text)
returns jsonb
language plpgsql
security definer
set search_path to 'public','pg_temp'
as $function$
declare
  v_control public.race_engine_runtime_control_v1%rowtype;
  v_current_game_at timestamp without time zone;
  v_stage record;
  v_claim jsonb;
  v_readiness jsonb;
  v_repair jsonb;
  v_blocked jsonb := '[]'::jsonb;
  v_survival jsonb;
begin
  v_survival := public.universal_race_stage_survival_recover_v1();

  select * into v_control from public.race_engine_runtime_control_v1 where singleton_id=true;
  if not found or not coalesce(v_control.typescript_lifecycle_enabled,false) then
    return jsonb_build_object('status','disabled','survival',v_survival);
  end if;

  select public.get_current_game_timestamp()::timestamp without time zone into v_current_game_at;

  for v_stage in
    select stage.id as stage_id,
           stage.race_id,
           race.name as race_name,
           stage.stage_number,
           stage.stage_date,
           stage.planned_start_hour_number,
           stage.planned_start_minute,
           stage.stage_date::timestamp + make_interval(hours=>coalesce(stage.planned_start_hour_number,12),mins=>coalesce(stage.planned_start_minute,0)) as stage_start_game_at
    from public.race_stages stage
    join public.races race on race.id=stage.race_id
    where not coalesce(stage.weather_cancelled,false)
      and stage.planned_start_hour_number is not null
      and (stage.stage_date::timestamp + make_interval(hours=>coalesce(stage.planned_start_hour_number,12),mins=>coalesce(stage.planned_start_minute,0))) >= v_control.typescript_activation_game_at
      and (stage.stage_date::timestamp + make_interval(hours=>coalesce(stage.planned_start_hour_number,12),mins=>coalesce(stage.planned_start_minute,0)) - make_interval(hours=>coalesce(v_control.typescript_calculation_lead_hours,3))) <= v_current_game_at
      and not exists (select 1 from public.race_stage_authoritative_runs authority where authority.stage_id=stage.id)
      and not exists (
        select 1 from public.race_stage_simulation_runs run
        where run.stage_id=stage.id
          and run.engine_version='race_engine_ts_v1'
          and run.simulation_mode='deterministic_road_race_v1'
          and run.status in ('running','completed')
          and coalesce(run.result_summary_json->>'calculation_contract','') in ('phase11b_claim_pending_v1','universal_phase11b_calculated_hidden_v1')
      )
      and not exists (
        select 1 from public.race_stage_simulation_runs failed_run
        where failed_run.stage_id=stage.id
          and failed_run.engine_version='race_engine_ts_v1'
          and failed_run.simulation_mode='deterministic_road_race_v1'
          and failed_run.status='failed'
          and failed_run.failed_at is not null
          and failed_run.failed_at > clock_timestamp()-interval '2 minutes'
          and (stage.stage_date::timestamp + make_interval(hours=>coalesce(stage.planned_start_hour_number,12),mins=>coalesce(stage.planned_start_minute,0))) > v_current_game_at + interval '15 minutes'
      )
    order by
      case when (stage.stage_date::timestamp + make_interval(hours=>coalesce(stage.planned_start_hour_number,12),mins=>coalesce(stage.planned_start_minute,0))) <= v_current_game_at + interval '15 minutes' then 0 else 1 end,
      stage.stage_date,
      stage.planned_start_hour_number,
      stage.planned_start_minute,
      stage.race_id,
      stage.stage_number
    limit 100
  loop
    v_repair := public.race_startlist_engine_self_heal_v1(v_stage.race_id);
    v_readiness := coalesce(v_repair->'readiness_after', public.race_startlist_engine_readiness_v1(v_stage.race_id));

    if coalesce((v_readiness->>'ready')::boolean,false) is not true then
      v_blocked := v_blocked || jsonb_build_array(jsonb_build_object(
        'stage_id',v_stage.stage_id,'race_id',v_stage.race_id,'race_name',v_stage.race_name,'stage_number',v_stage.stage_number,
        'reason','startlist_engine_not_ready','readiness',v_readiness,'repair_result',v_repair));
      continue;
    end if;

    begin
      v_claim := public.universal_race_stage_claim_calculation_v1(v_stage.stage_id);
    exception when others then
      v_blocked := v_blocked || jsonb_build_array(jsonb_build_object(
        'stage_id',v_stage.stage_id,'race_id',v_stage.race_id,'race_name',v_stage.race_name,'stage_number',v_stage.stage_number,
        'reason','claim_exception','sqlstate',sqlstate,'message',sqlerrm,'repair_result',v_repair));
      continue;
    end;

    if coalesce(v_claim->>'status','')='claimed' then
      return v_claim || jsonb_build_object(
        'worker_id',coalesce(nullif(p_worker_id,''),'supabase_edge_phase11b_v1'),
        'scheduler_skipped_blocks',v_blocked,
        'startlist_self_heal_applied',coalesce((v_repair->>'team_list_repair_attempted')::boolean,false) or coalesce((v_repair->>'startlist_repair_attempted')::boolean,false),
        'startlist_self_heal_result',v_repair,
        'survival',v_survival,
        'survival_mode',public.universal_race_stage_survival_mode_v1(v_stage.stage_id));
    end if;
  end loop;

  return jsonb_build_object('status','no_due_stage','current_game_at',v_current_game_at,'scheduler_skipped_blocks',v_blocked,'survival',v_survival);
end;
$function$;

do $do$
declare v_job_id bigint;
begin
  select jobid into v_job_id from cron.job where jobname='universal-race-calculation-survival-v1' limit 1;
  if v_job_id is not null then
    perform cron.unschedule(v_job_id);
  end if;
end
$do$;

select cron.schedule(
  'universal-race-calculation-survival-v1',
  '* * * * *',
  'select public.universal_race_stage_survival_recover_v1();'
);
